server {
  listen      8089;
  server_name 0.0.0.0;
  resolver 127.0.0.11;

  location / {
    proxy_pass http://pfs.local.bitraft.io:8082/;
    proxy_redirect      off;
  }

  location ~* /v1/api/users/(.*)/messages(.*) {
    proxy_pass http://pfs.local.bitraft.io:8082/v1/api/$1/messages$2$is_args$args;
    proxy_redirect      off;
  }

  location /v2/api/users/me/messages {
    proxy_pass http://pfs.local.bitraft.io:8082/v2/api/me/messages;
    proxy_redirect off;
  }

  location /v1/api/users/me/info {
    proxy_pass http://pfs.local.bitraft.io:8082/v1/api/me/info;
    proxy_redirect off;
  }

  location /v1/api/users/info {
    proxy_pass http://pfs.local.bitraft.io:8082/v1/api/info;
    proxy_redirect      off;
  }

  location /v2/api/users/info {
    proxy_pass http://pfs.local.bitraft.io:8082/v2/api/info;
    proxy_redirect      off;
  }

  location /v1/api/users/senders {
    proxy_pass http://pfs.local.bitraft.io:8082/v1/api/users/senders;
    proxy_redirect      off;
  }

  location /v1/api/users {
    proxy_pass http://pfs.local.bitraft.io:8082/v1/api/users;
    proxy_redirect      off;
  }
}
