swagger: '2.0'

info:
  version: 0.0.1
  title: NHS App Clinical Decision Support API
  description: This is the API for NHS App Clinical Decision Support service

schemes:
  - https

paths:
  /question:
    get:
      tags:
        - clinical decision support
      summary: Get a question for the given type
      parameters:
        - name: questionType
          in: query
          description: Type of question to return.
          required: true
          type: string
      responses:
        200:
          description: Successfully retrieved question for questionType.
          schema:
            type: object
            properties:
              question:
                type: string
        400:
          description: No questionType provided.
        500:
          description: An unexpected error occurred processing the request.
