openapi: 3.0.1
info:
  title: NHS Online CDS API.
  description: NHS Online CDS API - clinical decision support api.
  version: 0.0.1
servers:
  - url: /
paths:
  /fhir/Questionnaire/{id}:
    get:
      summary: Gets the question for the specified id.
      description: Gets the question for the specified id.
      parameters:
        - name: id
          in: path
          description: id of the question.
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successful operation. Questionnaire returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Questionnaire'
  /fhir/QuestionnaireResponse:
    post:
      summary: Posts the question answer, for the specified questionnaire.
      description: Posts the question answer, for the specified questionnaire.
      requestBody:
        description: Body of answered question.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/QuestionnaireResponse"
      responses:
        200:
          description: Successful operation. Questionnaire answer returned.
components:
  schemas:
    Domain:
      type: object
      properties:
        resourceType:
          type: string
          description: This is the type of the requested resource.
        text:
          type: object
          description: Text summary of the resource, for human interpretation.
          properties:
            status:
              type: string
              description: one of generated | extensions | additional | empty
            div:
              type: string
              description: Limited xhtml content
        contained:
          type: object
          description: Contained, inline resources.
          properties:
            id:
              type: string
              description: Logical id of this artifact
            meta:
              type: object
              description: Metadata about the resource
              properties:
                versionId:
                  type: string
                  description: Version specific identifier
                lastUpdated:
                  type: string
                  description: When the resource version last changed
                source:
                  type: string
                  description: Identifies where the resource comes from
                profile:
                  type: string
                  description: Profiles this resource claims to conform to
                security:
                  $ref: "#/components/schemas/coding"
                  description: Security Labels applied to this resource
                tab:
                  $ref: "#/components/schemas/coding"
                  description: Tags applied to this resource
            implicitRules:
              type: string
              description: A set of rules under which this content was created
            language:
              $ref: "#/components/schemas/coding"
              description: Language of the resource content
        extension:
          type: object
          description: Additional content defined by implementations.
        modifierExtension:
          type: object
          description: Extensions that cannot be ignored.
    Questionnaire:
      allOf:
        - $ref: '#/components/schemas/Domain'
        - type: object
          required:
            - subjectType
          properties:
            id:
              type: string
              description: The id of the question.
            status:
              type: string
              description: Valid responses are draft | active | retired | unknown.
            code:
              type: string
              description: Concept that represents the overall questionnaire.
            subjectType:
              type: string
              description: Resource that can be subject of QuestionnaireResponse ResourceType (Required).
            item:
              $ref: "#/components/schemas/item"
    QuestionnaireResponse:
      allOf:
        - $ref: '#/components/schemas/Domain'
        - type: object
          properties:
            id:
              type: string
              description: The id of the question.
            questionnaire:
              type: string
              description: This MUST be populated with a reference to the Questionnaire to which this QuestionnaireResponse is responding.
            item:
              $ref: "#/components/schemas/itemResponse"
    coding:
      type: object
      description: A reference to a code defined by a terminology system
      properties:
        system:
          type: string
          description: Identity of the terminology system
        version:
          type: string
          description: Version of the system - if relevant
        code:
          type: string
          description: Symbol in syntax defined by the system
        display:
          type: string
          description: Representation defined by the system
        userSelected:
          type: boolean
          description: If this coding was chosen directly by the user
    extension:
      type: object
      description: Optional Extensions Element
      properties:
        url:
          type: string
          description: identifies the meaning of the extension
        valueInteger:
          type: integer
          description: Value of type integer.
        valueDate:
          type: string
          description: Value of type date.
        valueTime:
          type: string
          description: Value of type time.
        valueString:
          type: string
          description: Value of type string.
        valueCoding:
          $ref: "#/components/schemas/coding"
          description: Value of type coding.
        valueBoolean:
          type: boolean
          description: Value of type boolean.
        valueDecimal:
          type: integer
          description: Value of type decimal.
        valueDateTime:
          type: string
          description: Value of type dateTime.
        valueUri:
          type: string
          description: Value of type uri.
        valueAttachment:
          $ref: "#/components/schemas/attachment"
          description: Value of type attachment.
        valueQuantity:
          $ref: "#/components/schemas/quantity"
          description: Value of type quantity.
        valueReference:
          type: string
          description: Value of type reference.
        valueBase64Binary:
          type: string
          description: Value of type base 64 binary.
        valueCanonical: 
          type: string
          description: Value of type canonical.
        valueCode: 
          type: string
          description: Value of type code.
        valueId:
          type: string
          description: Value of type id.
        valueInstant:
          type: string
          description: Value of type instant.
        valueMarkdown:
          type: string
          description: Value of type markdown.
        valueOid:
          type: string
          description: Value of type oid.
        valuePositiveInt:
          type: integer
          description: Value of type positive int.
        valueUnsignedInt:
          type: integer
          description: Value of type unsigned int.
        valueUrl:
          type: string
          description: Value of type url.
        valueUuid:
          type: string
          description: Value of type uuid.
        valueAddress:
          $ref: "#/components/schemas/address"
          description: Value of type address. 
    address:
      type: object
      description: An address expressed using postal conventions
      properties:
        use:
          type: string
          description: one of home | work | temp | old | billing - purpose of this address
        type:
          type: string
          description: one of postal | physical | both
        text:
          type: string
          description: Text representation of the address
        line:
          type: string
          description: Street name, number, direction & P.O. Box etc.
        city:
          type: string
          description: Name of city, town etc.
        district: 
          type: string
          description: District name (aka county)
        state:
          type: string
          description: Sub-unit of country (abbreviations ok)
        postalCode:
          type: string
          description: Postal code for area
        country:
          type: string
          description: Country (e.g. can be ISO 3166 2 or 3 letter code)
        period:
          type: object
          description: Time period when address was/is in use
          properties:
            start:
              type: string
              description: Starting time with inclusive boundary
            end:
              type: string
              description: End time with inclusive boundary, if not ongoing
    attachment:
      type: object
      description: Content in a format defined elsewhere
      properties:
        contentType:
          type: string
          description: Mime type of the content, with charset etc.
        language:
          type: string
          description: Human language of the content (BCP-47)
        data:
          type: string
          description: Data inline, base64ed
        url:
          type: string
          description: Uri where the data can be found
        size:
          type: integer
          description: Number of bytes of content (if url provided)
        hash:
          type: string
          description: Hash of the data (sha-1, base64ed)
        title:
          type: string
          description: Label to display in place of the data
        creation:
          type: string
          description: Date attachment was first created
    quantity:
      type: object
      description: A measured or measurable amount
      properties:
        value:
          type: integer
          description: Numerical value (with implicit precision)
        comparator:
          type: string
          description: < | <= | >= | > - how to understand the value
        unit:
          type: string
          description: Unit representation
        system:
          type: string
          description: System that defines coded unit form
        code:
          type: string
          description: Coded form of the unit
    itemResponse:
      type: array
      items:
        type: object
        properties:
          linkId:
            type: string
            description: Unique id for item in questionnaire.
          answer:
            type: object
            properties:
              valueInteger:
                type: integer
                description: Value of type integer.
              valueDate:
                type: string
                description: Value of type date.
              valueTime:
                type: string
                description: Value of type time.
              valueString:
                type: string
                description: Value of type string.
              valueCoding:
                $ref: "#/components/schemas/coding"
                description: Value of type coding.
              valueBoolean:
                type: boolean
                description: Value of type boolean.
              valueDecimal:
                type: integer
                description: Value of type decimal.
              valueDateTime:
                type: string
                description: Value of type dateTime.
              valueUri:
                type: string
                description: Value of type uri.
              valueAttachment:
                $ref: "#/components/schemas/attachment"
                description: Value of type attachment.
              valueQuantity:
                $ref: "#/components/schemas/quantity"
                description: Value of type quantity.
              valueReference:
                type: string
                description: Value of type reference.
              item:
                type: object
                description: Nested groups and questions.
            description: Valueset containing permitted answers.
          text:
            type: string
            description: Primary text for the item.
          item:
            $ref: "#/components/schemas/itemResponse"
            description: Nested questionnaire response items.
    item:
      type: array
      items:
        type: object
        properties:
          repeats:
            type: boolean
            description: Whether the item may repeat.
          item:
            $ref: "#/components/schemas/item"
            properties: {}
            description: Nested questionnaire items.
          linkId:
            type: string
            description: Unique id for item in questionnaire.
          code:
            type: string
            description: Corresponding concept for this item in a terminology.
          options:
            type: string
            properties: {}
            description: Valueset containing permitted answers.
          text:
            type: string
            description: Primary text for the item.
          type:
            type: string
            description: The type of questionnaire item this is. If this is set
              to 'group', the EMS User interface MUST present all sub-items together
              to the user, with the group item description as the header.
          required:
            type: boolean
            description: Whether the item must be included in data results.
          option:
            type: array
            items:
              type: object
              properties:
                valueInteger:
                  type: integer
                  description: Value of type integer.
                valueDate:
                  type: string
                  description: Value of type date.
                valueTime:
                  type: string
                  description: Value of type time.
                valueString:
                  type: string
                  description: Value of type string.
                valueCoding:
                  $ref: "#/components/schemas/coding"
                  description: Value of type coding.
              description: Permitted answer