//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHSOnline.Backend.Worker.GpSystems.Suppliers.Emis {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmisApiErrorMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmisApiErrorMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("NHSOnline.Backend.Worker.GpSystems.Suppliers.Emis.EmisApiErrorMessages", typeof(EmisApiErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string MeApplicationsPost_AlreadyLinked {
            get {
                return ResourceManager.GetString("MeApplicationsPost_AlreadyLinked", resourceCulture);
            }
        }
        
        public static string MeApplicationsPost_AccountIdNotFound {
            get {
                return ResourceManager.GetString("MeApplicationsPost_AccountIdNotFound", resourceCulture);
            }
        }
        
        public static string MeApplicationsPost_LinkageKeyDoesNotMatch {
            get {
                return ResourceManager.GetString("MeApplicationsPost_LinkageKeyDoesNotMatch", resourceCulture);
            }
        }
        
        public static string MeApplicationsPost_SurnameOrDateOfBirthAreIncorrect {
            get {
                return ResourceManager.GetString("MeApplicationsPost_SurnameOrDateOfBirthAreIncorrect", resourceCulture);
            }
        }
        
        public static string AppointmentsPost_NotFound {
            get {
                return ResourceManager.GetString("AppointmentsPost_NotFound", resourceCulture);
            }
        }
        
        public static string AppointmentsPost_InThePast {
            get {
                return ResourceManager.GetString("AppointmentsPost_InThePast", resourceCulture);
            }
        }
        
        public static string EmisService_NotEnabledForUser {
            get {
                return ResourceManager.GetString("EmisService_NotEnabledForUser", resourceCulture);
            }
        }
        
        public static string Prescriptions_AlreadyOrderedLast30Days {
            get {
                return ResourceManager.GetString("Prescriptions_AlreadyOrderedLast30Days", resourceCulture);
            }
        }
        
        public static string Prescriptions_InvalidCourseId {
            get {
                return ResourceManager.GetString("Prescriptions_InvalidCourseId", resourceCulture);
            }
        }
        
        public static string AppointmentsDelete_InThePast {
            get {
                return ResourceManager.GetString("AppointmentsDelete_InThePast", resourceCulture);
            }
        }
        
        public static string AppointmentsDelete_NotFound {
            get {
                return ResourceManager.GetString("AppointmentsDelete_NotFound", resourceCulture);
            }
        }
    }
}
