//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHSOnline.Backend.Worker.GpSystems.Suppliers.Emis {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmisApiErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmisApiErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NHSOnline.Backend.Worker.GpSystems.Suppliers.Emis.EmisApiErrorMessages", typeof(EmisApiErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past appointments cannot be cancelled.
        /// </summary>
        public static string AppointmentsDelete_InThePast {
            get {
                return ResourceManager.GetString("AppointmentsDelete_InThePast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment not found.
        /// </summary>
        public static string AppointmentsDelete_NotFound {
            get {
                return ResourceManager.GetString("AppointmentsDelete_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment cannot be booked in the past.
        /// </summary>
        public static string AppointmentsPost_InThePast {
            get {
                return ResourceManager.GetString("AppointmentsPost_InThePast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment not found.
        /// </summary>
        public static string AppointmentsPost_NotFound {
            get {
                return ResourceManager.GetString("AppointmentsPost_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum booked appointments is limited.
        /// </summary>
        public static string EmisService_BookedAppointmentLimit {
            get {
                return ResourceManager.GetString("EmisService_BookedAppointmentLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services Access violation.
        /// </summary>
        public static string EmisService_NotEnabledForUser {
            get {
                return ResourceManager.GetString("EmisService_NotEnabledForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No registered online user found for given linkage details.
        /// </summary>
        public static string MeApplicationsPost_AccountIdNotFound {
            get {
                return ResourceManager.GetString("MeApplicationsPost_AccountIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered online user is already linked.
        /// </summary>
        public static string MeApplicationsPost_AlreadyLinked {
            get {
                return ResourceManager.GetString("MeApplicationsPost_AlreadyLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid linkage details.
        /// </summary>
        public static string MeApplicationsPost_LinkageKeyDoesNotMatch {
            get {
                return ResourceManager.GetString("MeApplicationsPost_LinkageKeyDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No match found for given demographics.
        /// </summary>
        public static string MeApplicationsPost_SurnameOrDateOfBirthAreIncorrect {
            get {
                return ResourceManager.GetString("MeApplicationsPost_SurnameOrDateOfBirthAreIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already a pending request in the past 30 days.
        /// </summary>
        public static string Prescriptions_AlreadyOrderedLast30Days {
            get {
                return ResourceManager.GetString("Prescriptions_AlreadyOrderedLast30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request is invalid.
        /// </summary>
        public static string Prescriptions_InvalidCourseId {
            get {
                return ResourceManager.GetString("Prescriptions_InvalidCourseId", resourceCulture);
            }
        }
    }
}
