package worker

object WorkerPaths {
    const val userPlaceholder = "<user>"
    const val patientIm1ConnectionV2 = "/v2/patient/im1connection"
    const val patientIm1ConnectionV1 = "/v1/patient/im1connection"
    const val sessionConnection = "/v1/session"
    const val refreshAccessToken = "/v1/patient/authorization/access-token/refresh"
    const val getPrescriptionsConnection = "/v1/patient/prescriptions"
    const val postPrescriptionsConnection = "/v1/patient/prescriptions"
    const val getCoursesConnection = "/v1/patient/courses"
    const val myAppointments = "/v1/patient/appointments"
    const val appointmentSlots = "/v1/patient/appointment-slots"
    const val getMyRecordConnection = "/v1/patient/my-record"
    const val getDemographicsConnection = "/v1/patient/demographics"
    const val sessionConnectionExtend = "/v1/session/extend"
    const val LinkageKey = "/v1/patient/linkage"
    const val ndopConnection = "/v1/patient/ndop"
    const val patientConfiguration = "/v1/patient/configuration"
    const val organDonationConnection = "/v1/patient/organdonation"
    const val serviceJourneyRules = "/v1/patient/journey-configuration"
    const val userDevices = "/v1/api/users/$userPlaceholder/devices"
    const val userMessages = "/v1/api/users/$userPlaceholder/messages"
    const val userMeInfo = "/v1/api/users/me/info"
    const val userMeUserResearch= "/v1/api/users/me/info/userResearch"
    const val userInfo = "/v1/api/users/info"
    const val configuration = "/v1/configuration"
    const val configurationV2 = "/v2/configuration"
    const val clientLogger = "/v1/api/log"
    const val healthReady = "/health/ready"
}
