version: "3.2"
services:
  web.local.bitraft.io:
    image: nhsapp.azurecr.io/nhsonline-web:${WEB_TAG}
    environment:
      - URI_FORMAT_API_CLIENT=http://api{host}:8082
      - API_HOST_SERVER=http://api.local.bitraft.io:8082
      - URI_FORMAT_CID_REDIRECT_WEB=http://web{host}:3000/auth-return
      - URI_FORMAT_CID_REDIRECT_NATIVE=nhsapp://10.0.2.2:3000/auth-return
      - CID_AUTH_ENDPOINT=http://stubs.local.bitraft.io:8080/citizenid/authorize
      - CID_REGISTER_ENDPOINT=http://stubs.local.bitraft.io:8080/citizenid/registrations
      - DATA_PREFERENCES_URL=http://stubs.local.bitraft.io:8080/ndop/createsession
      - VERSION_TAG=dev_bdd_docker_ops_main
      - BIOMETRICS_ENABLED=true
  api.local.bitraft.io:
    image: nhsapp.azurecr.io/nhsonline-backendworker:${BACKEND_TAG}
    environment:
      - BACKENDWORKER_RUNMODE=pfs
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8082
      - PORT=8082
      - NHS_WEB_APP_BASE_URL=http://web.local.bitraft.io:3000/
      - CORS_AUTHORITY=*
      - CITIZEN_ID_BASE_URL=http://stubs.local.bitraft.io:8080/citizenid/
      - EMIS_BASE_URL=http://stubs.local.bitraft.io:8080/emis/
      - TPP_BASE_URL=http://stubs.local.bitraft.io:8080/tpp/
      - VISION_SENDER_USERNAME=Username123123asdas
      - VISION_SENDER_USERFULLNAME=Name
      - VISION_SENDER_USERIDENTITY=65489761321654
      - VISION_SENDER_USERROLE=ROSU
      - ASPNETCORE_ENVIRONMENT=Development
      - GP_PROVIDER_ENABLED_EMIS=true
      - GP_PROVIDER_ENABLED_TPP=true
      - GP_PROVIDER_ENABLED_VISION=true
      - GP_PROVIDER_ENABLED_MICROTEST=true
      - EMIS_LINKAGE_USE_STUBBED_DATA=false
      - STUB_TERMS_AND_CONDITIONS=true
      - ConfigurationSettings__CookieDomain=.bitraft.io
    depends_on:
      - nhsonline.redis.sds
  cid.local.bitraft.io:
    image: nhsapp.azurecr.io/nhsonline-backendworker:${BACKEND_TAG}
    environment:
      - BACKENDWORKER_RUNMODE=cid
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8084
      - PORT=8084
      - NHS_WEB_APP_BASE_URL=http://web.local.bitraft.io:3000/
      - CORS_AUTHORITY=*
      - CITIZEN_ID_BASE_URL=http://stubs.local.bitraft.io:8080/citizenid/
      - EMIS_BASE_URL=http://stubs.local.bitraft.io:8080/emis/
      - TPP_BASE_URL=http://stubs.local.bitraft.io:8080/tpp/
      - ASPNETCORE_ENVIRONMENT=Development
      - GP_PROVIDER_ENABLED_EMIS=true
      - GP_PROVIDER_ENABLED_TPP=true
      - GP_PROVIDER_ENABLED_VISION=true
      - GP_PROVIDER_ENABLED_MICROTEST=true
      - EMIS_LINKAGE_USE_STUBBED_DATA=false
      - STUB_TERMS_AND_CONDITIONS=true
    depends_on:
      - nhsonline.redis.sds
  stubs.local.bitraft.io:
    image: nhsapp.azurecr.io/wiremock:${WIREMOCK_TAG}
    command: --local-response-templating
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    tty: true
  nhsonline.redis-data.sds:
    image: nhsapp.azurecr.io/nhsonline-redis-data:${REDIS_DATA_TAG}
    environment:
      - MODE=development
      - REDIS_HOST=nhsonline.redis.sds
    depends_on:
      - nhsonline.redis.sds
  nhsonline.redis.sds:
    image: nhsapp.azurecr.io/redis:${REDIS_TAG}
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - 'redis_data:/bitnami/redis'
  nhsonline.redis.session:
    image: nhsapp.azurecr.io/redis:${REDIS_TAG}
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
volumes:
  redis_data:
    driver: local
