version: "3.2"
services:
  nhsonline.mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  web.local.bitraft.io:
    image: nhsapp.azurecr.io/nhsonline-web:${WEB_TAG}
    environment:
      - URI_FORMAT_API_CLIENT=http://api{host}:8082
      - API_HOST_SERVER=http://api.local.bitraft.io:8082
      - URI_FORMAT_CID_REDIRECT_WEB=http://web{host}:3000/auth-return
      - URI_FORMAT_CID_REDIRECT_NATIVE=nhsapp://10.0.2.2:3000/auth-return
      - CID_AUTH_ENDPOINT=http://stubs.local.bitraft.io:8080/citizenid/authorize
      - CID_REGISTER_ENDPOINT=http://stubs.local.bitraft.io:8080/citizenid/register
      - DATA_PREFERENCES_URL=http://stubs.local.bitraft.io:8080/ndop/createsession
      - COOKIE_DOMAIN=.bitraft.io
      - VERSION_TAG=dev_bdd_docker_ops_main
      - BIOMETRICS_ENABLED=true
      - ORGAN_DONATION_INTEGRATION_ENABLED=true
  api.local.bitraft.io:
    image: nhsapp.azurecr.io/nhsonline-backendpfsapi:${BACKEND_TAG}
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8082
      - PORT=8082
      - NHS_WEB_APP_BASE_URL=http://web.local.bitraft.io:3000/
      - CORS_AUTHORITY=*
      - CITIZEN_ID_BASE_URL=http://stubs.local.bitraft.io:8080/citizenid/
      - ConfigurationSettings__EmisExtendedHttpTimeoutSeconds=10
      - EMIS_BASE_URL=http://stubs.local.bitraft.io:8080/emis/
      - TPP_BASE_URL=http://stubs.local.bitraft.io:8080/tpp/
      - VISION_SENDER_USERNAME=Username123123asdas
      - VISION_SENDER_USERFULLNAME=Name
      - VISION_SENDER_USERIDENTITY=65489761321654
      - VISION_SENDER_USERROLE=ROSU
      - ASPNETCORE_ENVIRONMENT=Development
      - GP_PROVIDER_ENABLED_EMIS=true
      - GP_PROVIDER_ENABLED_TPP=true
      - GP_PROVIDER_ENABLED_VISION=true
      - GP_PROVIDER_ENABLED_MICROTEST=true
      - EMIS_LINKAGE_USE_STUBBED_DATA=false
      - ConfigurationSettings__CookieDomain=.bitraft.io
      - SESSION_MONGO_DATABASE_HOST=nhsonline.mongodb
      - SESSION_MONGO_DATABASE_PORT=27017
      - SESSION_MONGO_DATABASE_USERNAME=
      - SESSION_MONGO_DATABASE_PASSWORD=
      - ORGAN_DONATION_BASE_URL=http://stubs.local.bitraft.io:8080/organdonation/
      - ORGAN_DONATION_CLIENT_ID=ODR-26-NHSAP
      - ORGAN_DONATION_OCP_APIM_SUBSCRIPTION_KEY=781859de3cce4bc48a715dfc8f36dc6f
      - ORGAN_DONATION_INTEGRATION_ENABLED=true
      - ORGAN_DONATION_REFERENCE_DATA_EXPIRY_SECONDS=86400
      - ConfigurationSettings__CurrentTermsConditionsEffectiveDate=2018-12-12T00:00:00+00:00
      - SPINE_URL=http://stubs.local.bitraft.io:8080/spine/
      - GP_PRACTICE_ODS_CODE_FOR_EPS_ENABLED_CHECK_OVERRIDE=
    depends_on:
      - nhsonline.redis.sds
      - nhsonline.mongodb
      - mongo_seed
    ports:
      - "8082:8082"
  cid.local.bitraft.io:
    image: nhsapp.azurecr.io/nhsonline-backendcidapi:${BACKEND_TAG}
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8084
      - PORT=8084
      - NHS_WEB_APP_BASE_URL=http://web.local.bitraft.io:3000/
      - CORS_AUTHORITY=*
      - CITIZEN_ID_BASE_URL=http://stubs.local.bitraft.io:8080/citizenid/
      - ConfigurationSettings__EmisExtendedHttpTimeoutSeconds=15
      - EMIS_BASE_URL=http://stubs.local.bitraft.io:8080/emis/
      - TPP_BASE_URL=http://stubs.local.bitraft.io:8080/tpp/
      - ASPNETCORE_ENVIRONMENT=Development
      - GP_PROVIDER_ENABLED_EMIS=true
      - GP_PROVIDER_ENABLED_TPP=true
      - GP_PROVIDER_ENABLED_VISION=true
      - GP_PROVIDER_ENABLED_MICROTEST=true
      - EMIS_LINKAGE_USE_STUBBED_DATA=false
      - SESSION_MONGO_DATABASE_HOST=nhsonline.mongodb
      - SESSION_MONGO_DATABASE_PORT=27017
      - SESSION_MONGO_DATABASE_USERNAME=
      - SESSION_MONGO_DATABASE_PASSWORD=
    depends_on:
      - nhsonline.redis.sds
      - nhsonline.mongodb
      - mongo_seed
  servicejourneyrulesapi.config:
    image: nhsapp.azurecr.io/nhsonline-service-journey-dev-config:${BACKEND_TAG}
    volumes:
      - 'servicejourneyrules_data:/output'
  servicejourneyrulesapi.local.bitraft.io:
    image: nhsapp.azurecr.io/nhsonline-backendservicejourneyrulesapi:${BACKEND_TAG}
    ports:
      - "8086:8086"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8086
      - PORT=8086
      - CORS_AUTHORITY=*
      - VERSION_TAG=servicejourneyrules_docker_main
      - SESSION_MONGO_DATABASE_HOST=nhsonline.mongodb
      - SESSION_MONGO_DATABASE_PORT=27017
      - SESSION_MONGO_DATABASE_USERNAME=
      - SESSION_MONGO_DATABASE_PASSWORD=
      - INPUT_FOLDER_PATH=/app/input
    depends_on:
      - nhsonline.redis.sds
      - nhsonline.mongodb
      - mongo_seed
      - servicejourneyrulesapi.config
    volumes:
      - 'servicejourneyrules_data:/app/input'
  users.local.bitraft.io:
    image: nhsapp.azurecr.io/nhsonline-backendusersapi:${BACKEND_TAG}
    ports:
      - "8083:8083"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8083
      - PORT=8088
      - CORS_AUTHORITY=*
      - VERSION_TAG=users_docker_main
      - SESSION_MONGO_DATABASE_HOST=nhsonline.mongodb
      - SESSION_MONGO_DATABASE_PORT=27017
      - SESSION_MONGO_DATABASE_USERNAME=
      - SESSION_MONGO_DATABASE_PASSWORD=
      - AZURE_NOTIFICATION_HUB_PATH=nhsapp-nonlive-bdd
      - AZURE_NOTIFICATION_HUB_CONNECTION_STRING=Endpoint=sb://nhsapp-nonlive-bdd.servicebus.windows.net/;SharedAccessKeyName=DefaultFullSharedAccessSignature;SharedAccessKey=
      - AZURE_NOTIFICATION_HUB_SHARED_ACCESS_KEY=
  log.local.bitraft.io:
    image: nhsapp.azurecr.io/nhsonline-clientloggerapi:${BACKEND_TAG}
    ports:
      - "8090:8090"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8090
      - PORT=8090
      - CORS_AUTHORITY=*
      - VERSION_TAG=log_docker_main
  stubs.local.bitraft.io:
    image: nhsapp.azurecr.io/wiremock:${WIREMOCK_TAG}
    command: --local-response-templating
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    tty: true
  nhsonline.redis-data.sds:
    image: nhsapp.azurecr.io/nhsonline-redis-data:${REDIS_DATA_TAG}
    environment:
      - MODE=development
      - REDIS_HOST=nhsonline.redis.sds
    depends_on:
      - nhsonline.redis.sds
  nhsonline.redis.sds:
    image: nhsapp.azurecr.io/redis:${REDIS_TAG}
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - 'redis_data:/bitnami/redis'
  nhsonline.redis.session:
    image: nhsapp.azurecr.io/redis:${REDIS_TAG}
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
  mongo_seed:
    image: mongo:latest
    links:
      - nhsonline.mongodb
    command: /bin/bash -c "sleep 5; mongo --host nhsonline.mongodb --eval 'db.session.createIndex({_ts:1},{expireAfterSeconds:60})' development"
    depends_on:
      - nhsonline.mongodb
volumes:
  redis_data:
    driver: local
  servicejourneyrules_data:
    driver: local
