version: "3.2"
services:
  web.local.bitraft.io:
    image: nhsapp.azurecr.io/nhsonline-web:${WEB_TAG}
    env_file:
      - vars_ci.env
    ports:
      - "3000:3000"
  api.local.bitraft.io:
    image: nhsapp.azurecr.io/nhsonline-backendworker:${BACKEND_TAG}
    depends_on:
      - nhsonline.redis.sds
      - nhsonline.redis.session
    env_file:
      - vars_ci.env
    ports:
      - "8082:8082"
    environment:
      - BACKENDWORKER_RUNMODE=pfs
      - ASPNETCORE_URLS=http://*:8082
      - PORT=8082
      - NDOP_CERTIFICATE_PASSWORD=GnewUt4z3y
      - NDOP_CERTIFICATE_PATH=/app/bddcerts/ndopJwtTest.pfx
      - STUB_TERMS_AND_CONDITIONS=true
      - ConfigurationSettings__CookieDomain=.bitraft.io
    volumes:
      - ../src/main/kotlin/mocking/ndop:/app/bddcerts
  cid.local.bitraft.io:
    image: nhsapp.azurecr.io/nhsonline-backendworker:${BACKEND_TAG}
    depends_on:
      - nhsonline.redis.sds
      - nhsonline.redis.session
    env_file:
      - vars_ci.env
    ports:
      - "8084:8084"
    environment:
      - BACKENDWORKER_RUNMODE=cid
      - ASPNETCORE_URLS=http://*:8084
      - PORT=8084
      - NDOP_CERTIFICATE_PASSWORD=GnewUt4z3y
      - NDOP_CERTIFICATE_PATH=/app/bddcerts/ndopJwtTest.pfx
      - STUB_TERMS_AND_CONDITIONS=true
    volumes:
      - ../src/main/kotlin/mocking/ndop:/app/bddcerts
  stubs.local.bitraft.io:
    image: nhsapp.azurecr.io/wiremock:${WIREMOCK_TAG}
    command: --local-response-templating
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    tty: true
    ports:
      - "8080:8080"
  nhsonline.redis-data.sds:
    image: nhsapp.azurecr.io/nhsonline-redis-data:${REDIS_DATA_TAG}
    environment:
      - REDIS_HOST=nhsonline.redis.sds
    depends_on:
      - nhsonline.redis.sds
  nhsonline.redis.sds:
    image: nhsapp.azurecr.io/redis:${REDIS_TAG}
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - 'redis_data:/bitnami/redis'
  nhsonline.redis.session:
    image: nhsapp.azurecr.io/redis:${REDIS_TAG}
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
volumes:
  redis_data:
    driver: local
