name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/APM-1162-readd-proxy-upload-error-logs
      endpoint: NHSDigital

  pipelines:
  - pipeline: build_pipeline
    source: "NHS-App-Build"
    trigger:
      branches:
        exclude:
          - master
          - refs/heads/master
          - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    product_display_name: ${{ variables.product_display_name }}
    product_description: ${{ variables.product_description }}
    spec_file: ${{ variables.spec_file }}
    portal_api_requires_callback_url: false
    config_ids:
     - /ptl/azure-devops/env-internal-dev/test-app/internal-testing-internal-dev/CLIENT_ID
    apigee_deployments:
      - environment: internal-dev
        post_deploy:
          - template: ./templates/run-integration-tests.yml
            parameters:
              working_directory: $(Pipeline.Workspace)/s
              test_folder_path: $(Pipeline.Workspace)/s/${{ variables.service_name }}/$(SERVICE_ARTIFACT_NAME)/tests
              target_url: https://$(APIGEE_ENVIRONMENT).api.service.nhs.uk/$(SERVICE_BASE_PATH)/
        make_spec_visible: true
      - environment: internal-dev-sandbox
        proxy_path: sandbox
        