name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital

  pipelines:
  - pipeline: build_pipeline
    source: "NHS-App-Build"
    trigger:
      branches:
        include:
          - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    prod_producer_approval: true
    enable_monitoring: true
    enable_status_monitoring: true
    apigee_deployments:
      - environment: internal-dev
      - environment: internal-qa
      - environment: dev
        service_name: "${{ variables.service_name }}-dep"
        short_service_name: "${{ variables.short_service_name }}-dep"
        service_base_path: "${{ variables.service_base_path }}-dep"
        depends_on:
          - internal_qa
      - environment: int
        depends_on:
          - internal_qa
      - environment: ref
        depends_on:
          - internal_qa
        enable_status_monitoring: false
      - environment: prod
        depends_on:
          - internal_qa
