name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "NHS-App-Build"
    trigger:
      branches:
        include:
          - refs/tags/v*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    product_display_name: ${{ variables.product_display_name }}
    product_description: ${{ variables.product_description }}
    spec_file: ${{ variables.spec_file }}
    apigee_deployments:
      - environment: internal-dev
        make_spec_visible: true  # Off by default. Turn on to allow expose API developers can subscribe their Apps to
      - environment: internal-qa
        make_spec_visible: true
      - environment: internal-qa-sandbox
        proxy_path: sandbox
        make_spec_visible: true
    # make_spec_visible is false for sandbox environment
    # (App subscription make sense for most sandbox implementations)
      - environment: sandbox
        proxy_path: sandbox
      - environment: int
        make_spec_visible: true
#        depends_on:
#          - internal_qa
#          - internal_qa_sandbox
