---
apiVersion: v1
data:
  password: {{ .Values.organdonationSubscription }}
kind: Secret
metadata:
  name: organdonation-subscription-{{ .Chart.AppVersion }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
type:
  Opaque
---
apiVersion: v1
data:
  password: {{ .Values.organdonation }}
kind: Secret
metadata:
  name: organdonation-{{ .Chart.AppVersion }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
type:
  Opaque
---
apiVersion: v1
data:
  organdonation.pfx: {{ .Values.organdonationCert }}
kind: Secret
metadata:
  name: organdonation-cert-{{ .Chart.AppVersion }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
type:
  Opaque
