---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: nhsapp-{{ $.Values.zone }}-{{ .Chart.AppVersion }}
spec:
  provider: azure
  secretObjects:
  {{- range $index, $notificationHub := .Values.secrets.notificationHubs }}
    - data:
        - key: password
          objectName: notificationHubSharedAccessKey-{{ $index }}
      secretName: notification-hub-shared-access-key-{{ $index }}-{{ $.Chart.AppVersion }}
      type: Opaque
    {{- end }}
    - data:
        - key: password
          objectName: authSigningPassword
      secretName: auth-signing-key-password-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: apikey
          objectName: gpLookupApiKey
      secretName: gp-lookup-api-key-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: apikey
          objectName: qualtricsApiKey
      secretName: qualtrics-api-key-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: apikey
          objectName: nhsAppApiKey
      secretName: nhsapp-api-key-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: password
          objectName: organdonationSubscription
      secretName: organdonation-subscription-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: session.key
          objectName: sessionKey
      secretName: session-key-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: secret
          objectName: spinePartyId
      secretName: spine-party-id-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: secret
          objectName: commsHubEventHubConnectionString
      secretName: comms-hub-event-hub-connection-string-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: secret
          objectName: commsHubEventHubPidConnectionString
      secretName: comms-hub-event-hub-pid-connection-string-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: secret
          objectName: auditEventHubConnectionStringSenderUKS
      secretName: audit-event-hub-connection-string-uks-{{ .Chart.AppVersion }}
      type: Opaque
  parameters:
    useVMManagedIdentity: "true"
  {{- if eq .Values.region "ukwest" }}
    keyvaultName: "nhsapp-{{ $.Values.zone }}-ukw"
  {{- else }}
    keyvaultName: "nhsapp-{{ $.Values.zone }}"
  {{- end }}
    objects: |
      array:
        - |
          objectName: gpLookupApiKey
          objectType: secret
        - |
          objectName: qualtricsApiKey
          objectType: secret
        - |
          objectName: nhsAppApiKey
          objectType: secret
        - |
          objectName: visionPfx
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
        - |
          objectName: sessionKey
          objectType: secret
        - |
          objectName: organdonationpfx
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
        - |
          objectName: organdonationSubscription
          objectType: secret
        {{- range $index, $notificationHub := .Values.secrets.notificationHubs }}
        - |
          objectName: {{ $notificationHub.name }}
          objectAlias: notificationHubSharedAccessKey-{{ $index }}
          {{- if eq $.Values.region "ukwest"}}
          objectVersion: {{ $notificationHub.versionukw }}
          {{- else }}
          objectVersion: {{ $notificationHub.versionuks }}
          {{- end }}
          objectType: secret
        {{- end }}
        - |
          objectName: ndopSigningKey
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
        - |
          objectName: authSigningPassword
          objectType: secret
        - |
          objectName: authSigningKey
          objectType: secret
        - |
          objectName: tppPfx
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
        - |
          objectName: spinePfx
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
        - |
          objectName: spineCrt
          objectType: secret
        - |
          objectName: spineKey
          objectType: secret
        - |
          objectName: spinePartyId
          objectType: secret
        - |
          objectName: emisPfx
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
        - |
          objectName: dockerRegistrySecret
          objectType: secret
        - |
          objectName: commsHubEventHubConnectionString
          objectType: secret
        - |
          objectName: commsHubEventHubPidConnectionString
          objectType: secret
        - |          
          objectName: auditEventHubConnectionStringSenderUKS
          objectType: secret 
    resourceGroup: "nhsapp-keyvault-{{ $.Values.AZURE_SUBSCRIPTION_NAME }}"
    subscriptionId: "{{ $.Values.keyvaultSubscriptionID }}"
    tenantId: "{{ $.Values.keyvaultTenantID }}"
