---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: nhsapp-{{ $.Values.zone }}-{{ .Chart.AppVersion }}
spec:
  provider: azure
  secretObjects:
    - data:
        - key: password
          objectName: nhsloginKey
      secretName: nhslogin-key-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: password
          objectName: emisPassword
      secretName: emiscert-password-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: password
          objectName: cosmosdbDevicesKey
      secretName: cosmosdb-devices-key-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: password
          objectName: cosmosdbKey
      secretName: cosmosdb-key-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: cert
          objectName: emiscert
      secretName: emiscert-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: cert
          objectName: visionClientCert
      secretName: vision-client-cert-pfx-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: cert
          objectName: spineCert
      secretName: spine-cert-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: secret
          objectName: spineCrt
      secretName: spine-crt-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: secret
          objectName: spineKey
      secretName: spine-key-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: cert
          objectName: microtestcert
      secretName: microtest-cert-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: password
          objectName: microtestKey
      secretName: microtest-crt-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: password
          objectName: microtestCrt
      secretName: microtest-key-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: password
          objectName: notificationHubSharedAccessKey
      secretName: notification-hub-shared-access-key-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: password
          objectName: microtestPfxPassword
      secretName: microtest-{{ .Chart.AppVersion }}
      type: Opaque    
    - data:
        - key: password
          objectName: nhsloginPassword
      secretName: nhslogin-key-password-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: apikey
          objectName: gpLookupApiKey
      secretName: gp-lookup-api-key-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: apikey
          objectName: qualtricsApiKey
      secretName: qualtrics-api-key-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: apikey
          objectName: nhsAppApiKey
      secretName: nhsapp-api-key-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: password
          objectName: organdonationSubscription
      secretName: organdonation-subscription-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: password
          objectName: tppCertificatePassword
      secretName: tpp-cert-password-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: password
          objectName: visionClientCertificatePfxPassword
      secretName: vision-client-cert-pfx-password-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: password
          objectName: visionClientCertPasswordStubbed
      secretName: vision-client-cert-pfx-stubbed-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: password
          objectName: ndopPassword
      secretName: ndop-cert-password-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: session.key
          objectName: sessionKey
      secretName: session-key-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: organdonation.pfx
          objectName: organdonationpfx
      secretName: organdonation-cert-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: password
          objectName: organdonationcertpass
      secretName: organdonation-{{ .Chart.AppVersion }}
      type: Opaque    
    - data:
        - key: tppPfx
          objectName: tppPfx
      secretName: tpp-cert-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: secret
          objectName: spinePartyId
      secretName: spine-party-id-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: secret
          objectName: cosmosDBConnectionStringUKS
      secretName: cosmosdb-mongodb-connection-string-uks-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: secret
          objectName: cosmosDBConnectionStringUKW
      secretName: cosmosdb-mongodb-connection-string-ukw-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: secret
          objectName: spineCertPassword
      secretName: spine-certificate-password-{{ .Chart.AppVersion }}
      type: Opaque
  parameters:
    useVMManagedIdentity: "true"
    keyvaultName: "nhsapp-{{ $.Values.zone }}"
    objects: |
      array:
        - |
          objectName: emisPassword
          objectType: secret
        - |
          objectName: cosmosdbDevicesKey
          objectType: secret
        - |
          objectName: cosmosdbKey
          objectType: secret
        - |
          objectName: cosmosdbMongoKey
          objectType: secret
        - |
          objectName: gpLookupApiKey
          objectType: secret
        - |
          objectName: qualtricsApiKey
          objectType: secret
        - |
          objectName: nhsAppApiKey
          objectType: secret
        - |
          objectName: tppCertificatePassword
          objectType: secret
        - |
          objectName: visionPfx
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
        - |
          objectName: visionClientCertPasswordStubbed
          objectType: secret
        - |
          objectName: visionClientCertificatePfxPassword
          objectType: secret
        - |
          objectName: sessionKey
          objectType: secret
        - |
          objectName: organdonationpfx
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
        - |
          objectName: organdonationSubscription
          objectType: secret
        - |
          objectName: notificationHubSharedAccessKey
          objectType: secret
        - |
          objectName: ndopPfx
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
        - |
          objectName: ndopPassword
          objectType: secret
        - |
          objectName: nhsloginPassword
          objectType: secret
        - |
          objectName: nhsloginKey
          objectType: secret
        - |
          objectName: tppPfx
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
        - |
          objectName: spineCert
          objectType: cert
        - |
          objectName: spineCrt
          objectType: secret
        - |          
          objectName: spineKey
          objectType: secret
        - |
          objectName: emiscert
          objectType: cert
        - |
          objectName: spinePartyId
          objectType: secret
        - |
          objectName: microtestcert
          objectType: cert
        - |
          objectName: microtestCrt
          objectType: secret
        - |
          objectName: microtestKey
          objectType: secret
        - |
          objectName: microtestPfxPassword
          objectType: secret
        - |
          objectName: dockerRegistrySecret
          objectType: secret
        - |
          objectName: cosmosDBConnectionStringUKS
          objectType: secret
        - |
          objectName: cosmosDBConnectionStringUKW
          objectType: secret
        - |
          objectName: spineCertPassword
          objectType: secret
    resourceGroup: "nhsapp-keyvault-{{ $.Values.AZURE_SUBSCRIPTION_NAME }}"
    subscriptionId: "{{ $.Values.keyvaultSubscriptionID }}"
    tenantId: "{{ $.Values.keyvaultTenantID }}"
