---
apiVersion: v1
data:
  apikey: {{ .Values.qualtricsApiKey }}
kind: Secret
metadata:
  name: qualtrics-api-key-{{ .Chart.AppVersion }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
type: Opaque