---
apiVersion: v1
data:
  session.key: {{ .Values.sessionKey }}
kind: Secret
metadata:
  name: session-key-{{ .Chart.AppVersion }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
type: Opaque