---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: nhsapp-{{ $.Values.zone }}-{{ .Chart.AppVersion }}
spec:
  provider: azure
  secretObjects:
    - data:
        - key: password
          objectName: cosmosdbDevicesKey
      secretName: cosmosdb-devices-key-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: password
          objectName: cosmosdbKey
      secretName: cosmosdb-key-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: password
          objectName: notificationHubSharedAccessKey
      secretName: notification-hub-shared-access-key-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: password
          objectName: authSigningPassword
      secretName: auth-signing-key-password-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: apikey
          objectName: gpLookupApiKey
      secretName: gp-lookup-api-key-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: apikey
          objectName: qualtricsApiKey
      secretName: qualtrics-api-key-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: apikey
          objectName: nhsAppApiKey
      secretName: nhsapp-api-key-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: password
          objectName: organdonationSubscription
      secretName: organdonation-subscription-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: session.key
          objectName: sessionKey
      secretName: session-key-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: secret
          objectName: spinePartyId
      secretName: spine-party-id-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: secret
          objectName: cosmosDBConnectionStringUKS
      secretName: cosmosdb-mongodb-connection-string-uks-{{ .Chart.AppVersion }}
      type: Opaque
    - data:
        - key: secret
          objectName: cosmosDBConnectionStringUKW
      secretName: cosmosdb-mongodb-connection-string-ukw-{{ .Chart.AppVersion }}
      type: Opaque
  parameters:
    useVMManagedIdentity: "true"
    keyvaultName: "nhsapp-{{ $.Values.zone }}"
    objects: |
      array:
        - |
          objectName: cosmosdbDevicesKey
          objectType: secret
        - |
          objectName: cosmosdbKey
          objectType: secret
        - |
          objectName: cosmosdbMongoKey
          objectType: secret
        - |
          objectName: gpLookupApiKey
          objectType: secret
        - |
          objectName: qualtricsApiKey
          objectType: secret
        - |
          objectName: nhsAppApiKey
          objectType: secret
        - |
          objectName: visionPfx
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
        - |
          objectName: sessionKey
          objectType: secret
        - |
          objectName: organdonationpfx
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
        - |
          objectName: organdonationSubscription
          objectType: secret
        - |
          objectName: {{ .Values.secrets.notificationHub.notificationHubSecretName }}
          objectAlias: notificationHubSharedAccessKey
          objectVersion: {{ .Values.secrets.notificationHub.notificationHubSecretVersion }}
          objectType: secret
        - |
          objectName: ndopPfx
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
        - |
          objectName: authSigningPassword
          objectType: secret
        - |
          objectName: authSigningKey
          objectType: secret
        - |
          objectName: tppPfx
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
        - |
          objectName: spinePfx
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
        - |
          objectName: spineCrt
          objectType: secret
        - |
          objectName: spineKey
          objectType: secret
        - |
          objectName: spinePartyId
          objectType: secret
        - |
          objectName: emisPfx
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
        - |
          objectName: microtestPfx
          objectAlias: microtestCrt
          objectType: cert
        - |
          objectName: microtestPfx
          objectAlias: microtestKey
          objectType: secret
        - |
          objectName: dockerRegistrySecret
          objectType: secret
        - |
          objectName: cosmosDBConnectionStringUKS
          objectType: secret
        - |
          objectName: cosmosDBConnectionStringUKW
          objectType: secret
    resourceGroup: "nhsapp-keyvault-{{ $.Values.AZURE_SUBSCRIPTION_NAME }}"
    subscriptionId: "{{ $.Values.keyvaultSubscriptionID }}"
    tenantId: "{{ $.Values.keyvaultTenantID }}"
