---
apiVersion: v1
data:
  spine.crt: {{ .Values.spineCrt }} 
  spine.key: {{ .Values.spineKey }}
kind: Secret
metadata:
  name: n3-cert-{{ .Chart.AppVersion }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
type: Opaque
