---
apiVersion: v1
data:
  key: {{ .Values.cosmosdbKey }}
kind: Secret
metadata:
  name: cosmosdbkey-{{ .Chart.AppVersion }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
type: Opaque
---
apiVersion: v1
data:
  password: {{ .Values.cosmosdbMongoKey }}
kind: Secret
metadata:
  name: cosmosdb-mongo-key-{{ .Chart.AppVersion }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
type: Opaque
---
apiVersion: v1
stringData:
{{- if eq .Values.zone "dev" }}
  key: "mongodb://nhsapp-{{ $.Values.zone }}-mongodb:{{ $.Values.cosmosdbMongoKey | b64dec }}@nhsapp-{{ $.Values.zone }}-mongodb-{{ $.Values.region }}.documents.azure.com:10255/?ssl=true&replicaSet=globaldb&appName=@UK {{ .Values.region | replace "uk" "" | title }}"
{{- else }}
  key: "mongodb://nhsapp-{{ $.Values.zone }}-mongo:{{ $.Values.cosmosdbMongoKey | b64dec }}@nhsapp-{{ $.Values.zone }}-mongo-{{ $.Values.region }}.documents.azure.com:10255/?ssl=true&replicaSet=globaldb&appName=@UK {{ .Values.region | replace "uk" "" | title }}"
{{- end }}
kind: Secret
metadata:
  name: cosmosdb-mongodb-connection-string-{{ .Chart.AppVersion }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
type: Opaque
