{{- if ($.Values.environmentStubbed.visionStubbed) }}
---
apiVersion: v1
data:
  visionclientcert.pfx: {{ .Values.visionClientCertPfxStubbed }}
kind: Secret
metadata:
  name: vision-client-cert-pfx-stubbed-{{ .Chart.AppVersion }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
type: Opaque
---
apiVersion: v1
data:
  password: {{ .Values.visionClientCertPfxPasswordStubbed }}
kind: Secret
metadata:
  name: vision-client-cert-pfx-password-stubbed-{{ .Chart.AppVersion }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
{{- else }}
---
apiVersion: v1
data:
  visionclientcert.pfx: {{ .Values.visionClientCertPfx }}
kind: Secret
metadata:
  name: vision-client-cert-pfx-{{ .Chart.AppVersion }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
type: Opaque
---
apiVersion: v1
data:
  password: {{ .Values.visionClientCertPfxPassword }}
kind: Secret
metadata:
  name: vision-client-cert-pfx-password-{{ .Chart.AppVersion }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
type: Opaque
{{- end }}