{{- if eq $.Values.nhsLoginKeyName "nhslogin-key" }}
---
apiVersion: v1
data:
  password: {{ .Values.nhsloginPassword }}
kind: Secret
metadata:
  name: nhslogin-key-password-{{ .Chart.AppVersion }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
type: Opaque
---
apiVersion: v1
data:
  nhslogin.pem: {{ .Values.nhsloginKey }}
kind: Secret
metadata:
  name: nhslogin-key-{{ .Chart.AppVersion }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
type: Opaque
{{- else if eq $.Values.nhsLoginKeyName "nhslogin-dev-key" }}
---
apiVersion: v1
data:
  password: {{ .Values.nhsloginDevPassword }}
kind: Secret
metadata:
  name: nhslogin-dev-key-password-{{ .Chart.AppVersion }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
type: Opaque
---
apiVersion: v1
data:
  nhslogin.pem: {{ .Values.nhsloginDevKey }}
kind: Secret
metadata:
  name: nhslogin-dev-key-{{ .Chart.AppVersion }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
type: Opaque
{{- else }}
{{- required "nhsLoginKeyName must be nhslogin-key or me nhslogin-key-dev" .Values.thisShouldNeverBeDefined }} 
{{- end }}