---
apiVersion: v1
data:
  apikey: {{ .Values.gpLookupApiKey }}
kind: Secret
metadata:
  name: gp-lookup-api-key-{{ .Chart.AppVersion }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
type: Opaque
