{{- if ($.Values.emisCertEnabled) }}
---
apiVersion: v1
data:
  emis.pfx:  {{ .Values.emisPfx }}
kind: Secret
metadata:
  name: emiscert-{{ .Chart.AppVersion }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
type:
  Opaque
---
apiVersion: v1
data:
  password: {{ .Values.emisPassword }}
kind: Secret
metadata:
  name: emiscert-password-{{ .Chart.AppVersion }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
type:
  Opaque
 {{- end }}
