---
apiVersion: v1
data:
  password: {{ .Values.nhsloginPassword }}
kind: Secret
metadata:
  name: nhslogin-key-password-{{ .Chart.AppVersion }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
type: Opaque
---
apiVersion: v1
data:
  nhslogin.pem: {{ .Values.nhsloginKey }}
kind: Secret
metadata:
  name: nhslogin-key-{{ .Chart.AppVersion }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
type: Opaque