---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nhsapp.name" . }}-{{ $.Values.users.role }}-{{ .Chart.AppVersion | replace "." "-" }}
  namespace: {{ $.Values.global.environment }}
  labels:
    app: {{ template "nhsapp.name" . }}-{{ $.Values.users.role }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  selector:
    matchLabels:
      app: {{ template "nhsapp.name" . }}-{{ $.Values.users.role }}
      version: {{ .Chart.AppVersion | quote }}
  template:
    metadata:
      labels:
        app: {{ template "nhsapp.name" . }}-{{ $.Values.users.role }}
        role: {{ $.Values.users.role }}
        version: {{ .Chart.AppVersion | quote }}
      annotations:
        chaos.alpha.kubernetes.io/enabled: "true"
    spec:
      volumes:
      - name: session-key
        secret:
          secretName: session-key-{{ .Chart.AppVersion }}
      - name: wildcard-namespace-cert
        secret:
          secretName: wildcard-{{ $.Values.global.environment }}-tls-{{ .Chart.AppVersion }}
      - name: internal-ca-public-key
        secret:
          secretName: internal-ca-public-key
      - name: sidecar-proxy-config
        configMap:
          name: users-sidecar-proxy-config-{{ .Chart.AppVersion }}
      containers:
      - name: users
        image: {{ $.Values.registry }}/{{ $.Values.users.image }}:{{ $.Values.users.image_tag }}
        imagePullPolicy: {{ $.Values.users.imagePullPolicy }}
        ports:
        - containerPort: {{ $.Values.users.containerPort }}
        resources:
          requests:
            memory: {{ $.Values.users.memoryRequest }}
            cpu: {{ $.Values.users.cpuRequest }}
          limits:
            memory: {{ $.Values.users.memoryLimit }}
            cpu: {{ $.Values.users.cpuLimit }}
        env:
{{- with $.Values.users.environmentVariables }}
{{ toYaml . | trim | indent 8 }}
{{- end }}
        - name: PORT
          value: "{{ $.Values.users.containerPort }}"
        - name: INPUT_FOLDER_PATH
          value: "{{ $.Values.users.inputPath }}"
        - name: ASPNETCORE_URLS
          value: "http://*:{{ $.Values.users.containerPort }}"
        - name: USERS_BASE_URL
          value: "https://nhsapp-users-{{ .Chart.AppVersion | replace "." "-" }}.{{ $.Values.global.environment }}.svc.cluster.local:{{ $.Values.sidecar_proxy.containerPort }}"
        - name: VERSION_TAG
          value: "{{ $.Values.users.image_tag }}"
        - name: SESSION_ENCRYPTION_KEY_FILE
          value: "/secrets/session-key/session.key"
        - name: CORS_AUTHORITY
          value: "https://*.{{ $.Values.domain }}"
        - name: DEVICES_MONGO_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: cosmosdb-mongodb-connection-string-{{ .Chart.AppVersion }}
              key: key
        - name: USERS_MONGO_DATABASE_NAME
          value: {{ $.Values.cosmosDBName }}-mongo
        - name: USERS_MONGO_DATABASE_USER_DEVICE_COLLECTION
          value: {{ $.Values.users.mongoDatabaseUserDeviceCollection }}
        - name: AZURE_NOTIFICATION_HUB_PATH
          value: {{ $.Values.users.notificationHubPath }}
        - name: AZURE_NOTIFICATION_HUB_CONNECTION_STRING
          value: {{ $.Values.users.notificationHubConnectionString }}
        - name: AZURE_NOTIFICATION_HUB_SHARED_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: notification-hub-shared-access-key-{{ .Chart.AppVersion }}
              key: password
        - name: CITIZEN_ID_AUTHENTICATION_TYPE
          value: "{{ $.Values.cidAuthenticationType }}"
        {{- if (and ($.Values.environmentStubbed) ($.Values.environmentStubbed.cidStubbed)) }}
        - name: CITIZEN_ID_JWT_ISSUER
          value: "https://nhsapp-wiremock-{{ .Chart.AppVersion | replace "." "-" }}.{{ $.Values.global.environment }}.svc.cluster.local:{{ $.Values.sidecar_proxy.containerPort }}/citizenid/"
        {{- else }}
        - name: CITIZEN_ID_JWT_ISSUER
          value: "{{ $.Values.cidProtocol }}://{{ $.Values.cidHostname }}"
        {{- end }}
        {{- if (and ($.Values.environmentStubbed) ($.Values.environmentStubbed.cidStubbed)) }}
        - name: CITIZEN_ID_BASE_URL
          value: "https://nhsapp-wiremock-{{ .Chart.AppVersion | replace "." "-" }}.{{ $.Values.global.environment }}.svc.cluster.local:{{ $.Values.sidecar_proxy.containerPort }}/citizenid/"
        {{- else }}
        - name: CITIZEN_ID_BASE_URL
          value: "https://iproxy-cid-{{ .Chart.AppVersion | replace "." "-" }}.{{ $.Values.global.environment }}.svc.cluster.local:{{ $.Values.iproxy.containerPort }}"
        {{- end }}
        - name: CITIZEN_ID_CLIENT_ID
          value: "{{ $.Values.cidClientID }}"
        volumeMounts:
        - name: session-key
          mountPath: "/secrets/session-key"
          readOnly: true
        - name: internal-ca-public-key
          mountPath: /usr/local/share/ca-certificates/internalca
          readOnly: true
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 2
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 2
      - name: proxy
        image: {{ $.Values.registry }}/{{ $.Values.sidecar_proxy.image }}:{{ $.Values.sidecar_proxy.image_tag }}
        imagePullPolicy: {{ $.Values.sidecar_proxy.imagePullPolicy }}
        ports:
        - containerPort: {{ $.Values.sidecar_proxy.containerPort }}
        resources:
          requests:
            memory: {{ $.Values.sidecar_proxy.memoryRequest }}
            cpu: {{ $.Values.sidecar_proxy.cpuRequest }}
          limits:
            memory: {{ $.Values.sidecar_proxy.memoryLimit }}
            cpu: {{ $.Values.sidecar_proxy.cpuLimit }}
        volumeMounts:
        - name: wildcard-namespace-cert
          mountPath: /etc/nginx/ssl
        - name: sidecar-proxy-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      hostAliases:
      - ip: "{{ trimSuffix "/32" $.Values.clusterIP }}"
        hostnames:
        - "api-{{ $.Values.global.environment }}.{{ $.Values.zone }}.{{ $.Values.domain }}"
        - "www-{{ $.Values.global.environment }}.{{ $.Values.zone }}.{{ $.Values.domain }}"
      imagePullSecrets:
      - name: azure-registry-{{ .Chart.AppVersion }}
      dnsConfig:
        options:
          - name: single-request-reopen
