---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nhsapp.name" . }}-{{ $.Values.logger.role }}-{{ .Chart.AppVersion | replace "." "-" }}
  namespace: {{ $.Values.global.environment }}
  labels:
    app: {{ template "nhsapp.name" . }}-{{ $.Values.logger.role }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  selector:
    matchLabels:
      app: {{ template "nhsapp.name" . }}-{{ $.Values.logger.role }}
      version: {{ .Chart.AppVersion | quote }}
  template:
    metadata:
      labels:
        app: {{ template "nhsapp.name" . }}-{{ $.Values.logger.role }}
        role: {{ $.Values.logger.role }}
        version: {{ .Chart.AppVersion | quote }}
      annotations:
        chaos.alpha.kubernetes.io/enabled: "true"
        rolleveryrelease: {{ randAlphaNum 5 | quote }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: role
                  operator: In
                  values:
                  - {{ $.Values.logger.role }}
              topologyKey: kubernetes.io/hostname
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "nhsapp-{{ $.Values.zone }}-{{ .Chart.AppVersion }}"
      - name: session-key
        secret:
          secretName: session-key-{{ .Chart.AppVersion }}
      - name: wildcard-namespace-cert
        secret:
          secretName: wildcard-{{ $.Values.global.environment }}-tls-{{ .Chart.AppVersion }}
      - name: internal-ca-public-key
        secret:
          secretName: internal-ca-public-key
      - name: sidecar-proxy-config
        configMap:
          name: logger-sidecar-proxy-config-{{ .Chart.AppVersion }}
      containers:
      - name: logger
        image: {{ $.Values.registry }}/{{ $.Values.logger.image }}:{{ $.Values.logger.image_tag }}
        imagePullPolicy: {{ $.Values.logger.imagePullPolicy }}
        lifecycle:
          {{- include "nhsapp.preStopHook" . | indent 12 }}
        ports:
        - containerPort: {{ $.Values.logger.containerPort }}
        resources:
          requests:
            memory: {{ $.Values.logger.memoryRequest }}
            cpu: {{ $.Values.logger.cpuRequest }}
          limits:
            memory: {{ $.Values.logger.memoryLimit }}
            cpu: {{ $.Values.logger.cpuLimit }}
        env:
{{- with $.Values.logger.environmentVariables }}
{{ toYaml . | trim | indent 8 }}
{{- end }}
        - name: PORT
          value: "{{ $.Values.logger.containerPort }}"
        - name: ASPNETCORE_URLS
          value: "http://*:{{ $.Values.logger.containerPort }}"
        - name: VERSION_TAG
          value: "{{ $.Values.logger.image_tag }}"
        - name: SESSION_ENCRYPTION_KEY_FILE
          value: "/mnt/secrets-store/sessionKey"
        - name: CORS_AUTHORITY
          {{- if $.Values.akamaiEnv }}
          value: "https://*.{{ $.Values.akamaiEnv }}"
          {{- else }}
          value: "https://*.{{ $.Values.domain }}"
          {{- end }}
        volumeMounts:
        - name: internal-ca-public-key
          mountPath: /usr/local/share/ca-certificates/internalca
          readOnly: true
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 2
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 2
      - name: proxy
        image: {{ $.Values.registry }}/{{ $.Values.sidecar_proxy.image }}:{{ $.Values.sidecar_proxy.image_tag }}
        imagePullPolicy: {{ $.Values.sidecar_proxy.imagePullPolicy }}
        lifecycle:
          {{- include "nhsapp.preStopHook" . | indent 12 }}
        ports:
        - containerPort: {{ $.Values.sidecar_proxy.containerPort }}
        resources:
          requests:
            memory: {{ $.Values.sidecar_proxy.memoryRequest }}
            cpu: {{ $.Values.sidecar_proxy.cpuRequest }}
          limits:
            memory: {{ $.Values.sidecar_proxy.memoryLimit }}
            cpu: {{ $.Values.sidecar_proxy.cpuLimit }}
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        - name: wildcard-namespace-cert
          mountPath: /etc/nginx/ssl
        - name: sidecar-proxy-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      hostAliases:
      - ip: "{{ trimSuffix "/32" $.Values.clusterIP }}"
        hostnames:
        - "api-{{ $.Values.global.environment }}.{{ $.Values.zone }}.{{ $.Values.domain }}"
        - "www-{{ $.Values.global.environment }}.{{ $.Values.zone }}.{{ $.Values.domain }}"
      imagePullSecrets:
      - name: azure-registry-{{ .Chart.AppVersion }}
      dnsConfig:
        options:
        - name: single-request-reopen
