---
apiVersion: v1
kind: Service
metadata:
  name: iproxy-nhssearch-{{ .Chart.AppVersion | replace "." "-" }}
  namespace: {{ $.Values.global.environment }}
  labels:
    app: {{ $.Values.iproxy.role }}-nhssearch
    role: {{ $.Values.iproxy.role }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  selector:
    role: {{ $.Values.iproxy.role }}
    version: {{ .Chart.AppVersion | quote }}
  ports:
  - port: {{ $.Values.iproxy.containerPort }}
    targetPort: {{ $.Values.iproxy.containerPort }}
