{{- if (and ($.Values.messagesEnabled) ($.Values.messages.createService)) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "nhsapp.name" . }}-{{ $.Values.messages.role }}-{{ .Chart.AppVersion | replace "." "-" }}
  namespace: {{ $.Values.global.environment }}
  labels:
    app: {{ template "nhsapp.name" . }}-{{ $.Values.messages.role }}
    role: {{ $.Values.messages.role }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  selector:
    role: {{ $.Values.messages.role }}
    version: {{ .Chart.AppVersion | quote }}
  ports:
  - port: {{ $.Values.sidecar_proxy.containerPort }}
    targetPort: {{ $.Values.sidecar_proxy.containerPort }}
{{- end }}