---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'false'
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-body-size: "3m"
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: {{ template "nhsapp.name" . }}-api-{{ .Chart.AppVersion | replace "." "-" }}
  namespace: {{ $.Values.global.environment }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
spec:
  rules:
    {{- if .Values.createDefaultIngress }}
    - host: api-{{ $.Values.global.environment | replace "." "-" }}.{{ $.Values.zone }}.{{ $.Values.domain }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ template "nhsapp.name" . }}-api-{{ .Chart.AppVersion | replace "." "-" }}
                port:
                  number: {{ $.Values.sidecar_proxy.containerPort }}
          {{- if $.Values.sjrExternalIngressEnabled }}
          - path: /api/odscodes
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ template "nhsapp.name" . }}-sjr-{{ .Chart.AppVersion | replace "." "-"}}
                port:
                  number: {{ $.Values.sidecar_proxy.containerPort }}
          - path: /api/servicejourneyrules
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ template "nhsapp.name" . }}-sjr-{{ .Chart.AppVersion | replace "." "-"}}
                port:
                  number: {{ $.Values.sidecar_proxy.containerPort }}
          {{- end }}
    {{- end }}
    - host: api-{{ $.Values.global.environment | replace "." "-" }}-{{ .Chart.AppVersion | replace "." "-" }}.{{ $.Values.zone }}.{{ $.Values.domain }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
             service:
              name: {{ template "nhsapp.name" . }}-api-{{ .Chart.AppVersion | replace "." "-" }}
              port:
                number: {{ $.Values.sidecar_proxy.containerPort }}
          {{- if $.Values.sjrExternalIngressEnabled }}
          - path: /api/odscodes
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ template "nhsapp.name" . }}-sjr-{{ .Chart.AppVersion | replace "." "-"}}
                port:
                  number: {{ $.Values.sidecar_proxy.containerPort }}
          - path: /api/servicejourneyrules
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ template "nhsapp.name" . }}-sjr-{{ .Chart.AppVersion | replace "." "-"}}
                port:
                  number: {{ $.Values.sidecar_proxy.containerPort }}
          {{- end }}

  tls:
    - hosts:
        - api-{{ $.Values.global.environment | replace "." "-" }}.{{ $.Values.zone }}.{{ $.Values.domain }}
        - api-{{ $.Values.global.environment | replace "." "-" }}-{{ .Chart.AppVersion | replace "." "-" }}.{{ $.Values.zone }}.{{ $.Values.domain }}
      secretName: {{ $.Values.zone }}-{{ $.Values.domain | replace "." "-" }}
