{{- if ($.Values.environmentStubbed.cdssStubbed) }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'false'
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-body-size: "3m"
  name: {{ template "nhsapp.name" . }}-cdsswiremock-{{ .Chart.AppVersion | replace "." "-" }}
  namespace: {{ $.Values.global.environment }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
spec:
  rules:
    - host: cdsswiremock-{{ $.Values.global.environment | replace "." "-" }}.{{ $.Values.zone }}.{{ $.Values.domain }}
      http:
        paths:
          - backend:
              serviceName: {{ template "nhsapp.name" . }}-cdsswiremock-{{ .Chart.AppVersion | replace "." "-" }}
              servicePort: {{ $.Values.sidecar_proxy.containerPort }}
            path: /
  tls:
    - hosts:
      - cdsswiremock-{{ $.Values.global.environment | replace "." "-" }}.{{ $.Values.zone }}.{{ $.Values.domain }}
      secretName: {{ $.Values.zone }}-{{ $.Values.domain | replace "." "-" }}
{{- end }}
