---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx-ingress-internal
    kubernetes.io/tls-acme: 'false'
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/use-regex: "true"
    externalDns: "true"
  name: {{ template "nhsapp.name" . }}-messages-{{ .Chart.AppVersion | replace "." "-" }}
  namespace: {{ .Values.global.environment }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
spec:
  rules:
    - host: messages-{{ .Values.global.environment | replace "." "-" }}.private.{{ .Values.zone }}.{{ .Values.domain }}
      http:
        paths:
          - backend:
              serviceName: {{ template "nhsapp.name" . }}-messages-{{ .Chart.AppVersion | replace "." "-" }}
              servicePort: {{ .Values.sidecar_proxy.containerPort }}
            path: "/([a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12})/messages"
  tls:
    - hosts:
        - messages-{{ .Values.global.environment | replace "." "-" }}.private.{{ .Values.zone }}.{{ .Values.domain }}
      secretName: private-{{ .Values.zone }}-{{ .Values.domain | replace "." "-" }}
