{{- if $.Values.web.createIngress -}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'false'
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers 'X-Xss-Protection: 1; mode=block';
      more_set_headers 'X-Frame-Options: DENY';
      more_set_headers 'X-Content-Type-Options: nosniff';
      more_set_headers 'Referrer-Policy: no-referrer';
      more_set_headers 'Content-Security-Policy: frame-src \'self\' https://nhs.demdex.net/ https://assets.adobedtm.com *.112.2o7.net https://*.hotjar.com; frame-ancestors \'self\'; object-src \'none\'';
      more_clear_headers 'server';
  name: {{ template "nhsapp.name" . }}-{{ $.Values.web.role }}-{{ .Chart.AppVersion | replace "." "-" }}
  namespace: {{ $.Values.global.environment }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
spec:
  rules:
    - host: www-{{ $.Values.global.environment | replace "." "-" }}.{{ $.Values.zone }}.{{ $.Values.domain }}
      http:
        paths:
          - backend:
              serviceName: {{ template "nhsapp.name" . }}-{{ $.Values.web.role }}-{{ .Chart.AppVersion | replace "." "-" }}
              servicePort: {{ $.Values.sidecar_proxy.containerPort }}
            path: /
    - host: www-{{ $.Values.global.environment | replace "." "-" }}-{{ .Chart.AppVersion | replace "." "-" }}.{{ $.Values.zone }}.{{ $.Values.domain }}
      http:
        paths:
          - backend:
              serviceName: {{ template "nhsapp.name" . }}-{{ $.Values.web.role }}-{{ .Chart.AppVersion | replace "." "-" }}
              servicePort: {{ $.Values.sidecar_proxy.containerPort }}
            path: /
    - host: www.{{ $.Values.zone }}.{{ $.Values.domain }}
      http:
        paths:
          - backend:
              serviceName: {{ template "nhsapp.name" . }}-{{ $.Values.web.role }}-{{ .Chart.AppVersion | replace "." "-" }}
              servicePort: {{ $.Values.sidecar_proxy.containerPort }}
            path: /_nuxt/{{ $.Values.appImageTag | toString | replace "." "-" }}
  tls:
    - hosts:
        - www-{{ $.Values.global.environment | replace "." "-" }}.{{ $.Values.zone }}.{{ $.Values.domain }}
        - www-{{ $.Values.global.environment | replace "." "-" }}-{{ .Chart.AppVersion | replace "." "-" }}.{{ $.Values.zone }}.{{ $.Values.domain }}
        - www.{{ $.Values.zone }}.{{ $.Values.domain }}
      secretName: {{ $.Values.zone }}-{{ $.Values.domain | replace "." "-" }}
{{- end }}
