{{- if ($.Values.networkPolicyEnabled) }}
{{- if ($.Values.messagesEnabled) }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-https-ingress-to-messages-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    role: {{ $.Values.messages.role }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.messages.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: app-publishing
    ports:
    - protocol: TCP
      port: {{ $.Values.sidecar_proxy.containerPort }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-messages-egress-to-iproxy-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    role: {{ $.Values.messages.role }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.messages.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          role: iproxy
          version: {{ .Chart.AppVersion | quote }}
    ports:
    - protocol: TCP
      port: {{ $.Values.sidecar_proxy.containerPort }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-internal-dns-ingress-to-{{ $.Values.messages.role }}-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    role: {{ $.Values.messages.role }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.messages.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: nginx-ingress-internal
    ports:
    - protocol: TCP
      port: {{ $.Values.sidecar_proxy.containerPort }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-messages-ingress-from-api-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    role: {{ $.Values.messages.role }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.messages.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          role: api
    ports:
    - protocol: TCP
      port: {{ $.Values.sidecar_proxy.containerPort }}
{{- end }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-metaservice-egress-from-messages-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.messages.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: {{ $.Values.metaServiceCIDR }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-cosmosdb-egress-from-messages-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.cid.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 10.0.0.0/8
    ports:
      - protocol: TCP
        port: 10255
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-eventhub-egress-from-messages-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    role: {{ $.Values.users.role }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.users.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 10.0.0.0/8
    ports:
{{- range $.Values.eventHubPorts }}
      - protocol: TCP
        port: {{ . }}
{{- end }}
{{- end }}