{{- if $.Values.networkPolicyEnabled -}}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-app-publishing-https-ingress-to-www-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.web.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: app-publishing
    ports:
    - protocol: TCP
      port: {{ $.Values.sidecar_proxy.containerPort }}
{{- end }}
