{{- if $.Values.networkPolicyEnabled -}}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-https-ingress-to-api-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.api.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: app-publishing
    ports:
    - protocol: TCP
      port: {{ $.Values.sidecar_proxy.containerPort }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-api-ingress-from-www-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.api.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          role: www
          version: {{ .Chart.AppVersion | quote }}
    ports:
    - protocol: TCP
      port: {{ $.Values.sidecar_proxy.containerPort }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-api-egress-to-iproxy-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.api.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          role: iproxy
          version: {{ .Chart.AppVersion | quote }}
    ports:
    - protocol: TCP
      port: {{ $.Values.sidecar_proxy.containerPort }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-emis-egress-from-api-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.api.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: {{ $.Values.emisIPTrust }}
    ports:
      - protocol: TCP
        port: {{ $.Values.emisPort }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-organdonation-egress-from-api-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.api.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: {{ $.Values.organDonationIPTrust }}
    ports:
      - protocol: TCP
        port: {{ $.Values.organDonationPort }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-vision-egress-from-api-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.api.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: {{ $.Values.visionIPTrust }}
    ports:
      - protocol: TCP
        port: {{ $.Values.visionPort }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-tpp-egress-from-api-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.api.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: {{ $.Values.tppIPTrust }}
    ports:
      - protocol: TCP
        port: {{ $.Values.tppPort }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-cosmosdb-egress-from-api-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.api.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Egress
  egress:
  - to:
{{- range $.Values.cosmosDBIPTrust }}
    - ipBlock:
        cidr: {{ . }}
{{- end }}
    ports:
{{- range $.Values.cosmosDBPortRange }}
      - protocol: TCP
        port: {{ . }}
{{- end }}
---
{{- if $.Values.spineLdapLookupEnabled -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-spine-ldap-egress-from-api-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.api.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: {{ $.Values.spineLdapCIDR }}
    ports:
      - protocol: TCP
        port: {{ $.Values.spineLdapPort }}
---
{{- end }}
{{- if $.Values.spinePdsEnabled -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-spine-pds-egress-from-api-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.api.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: {{ $.Values.spinePdsCIDR }}
    ports:
      - protocol: TCP
        port: {{ $.Values.spinePdsPort }}
{{- end }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-api-egress-to-userinfo-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.api.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          role: info
          version: {{ .Chart.AppVersion | quote }}
    ports:
    - protocol: TCP
      port: {{ $.Values.sidecar_proxy.containerPort }}
{{- end }}
