{{- if and ($.Values.environmentStubbed.deployWiremock) ($.Values.networkPolicyEnabled) }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-https-ingress-to-wiremock-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.wiremock.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: app-publishing
    - podSelector:
        matchLabels:
          role: {{ $.Values.cid.role }}
          version: {{ .Chart.AppVersion | quote }}
    - podSelector:
        matchLabels:
          role: {{ $.Values.api.role }}
          version: {{ .Chart.AppVersion | quote }}
    - podSelector:
        matchLabels:
          role: {{ $.Values.users.role }}
          version: {{ .Chart.AppVersion | quote }}
    - podSelector:
        matchLabels:
          role: {{ $.Values.messages.role }}
          version: {{ .Chart.AppVersion | quote }}
    - podSelector:
        matchLabels:
          role: {{ $.Values.info.role }}
          version: {{ .Chart.AppVersion | quote }}
    ports:
    - protocol: TCP
      port: {{ $.Values.sidecar_proxy.containerPort }}
{{- end }}
