{{- if $.Values.networkPolicyEnabled -}}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-https-ingress-to-cid-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    role: {{ $.Values.cid.role }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.cid.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: app-publishing
    ports:
    - protocol: TCP
      port: {{ $.Values.sidecar_proxy.containerPort }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-cid-egress-to-sjr-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    role: {{ $.Values.cid.role }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.cid.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          role: sjr
          version: {{ .Chart.AppVersion | quote }}
    ports:
    - protocol: TCP
      port: {{ $.Values.sidecar_proxy.containerPort }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-emis-egress-from-cid-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    role: {{ $.Values.cid.role }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.cid.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: {{ $.Values.emisIPTrust }}
    ports:
    - protocol: TCP
      port: {{ $.Values.emisPort }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-vision-egress-from-cid-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    role: {{ $.Values.cid.role }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.cid.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: {{ $.Values.visionIPTrust }}
    ports:
    - protocol: TCP
      port: {{ $.Values.visionPort }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-tpp-egress-from-cid-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    role: {{ $.Values.cid.role }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.cid.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: {{ $.Values.tppIPTrust }}
    ports:
    - protocol: TCP
      port: {{ $.Values.tppPort }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-metaservice-egress-from-cid-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.cid.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: {{ $.Values.metaServiceCIDR }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-cosmosdb-egress-from-cid-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.cid.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 10.0.0.0/8
    ports:
      - protocol: TCP
        port: 10255
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-cid-egress-to-iproxy-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    role: {{ $.Values.cid.role }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.cid.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          role: iproxy
          version: {{ .Chart.AppVersion | quote }}
    ports:
    - protocol: TCP
      port: {{ $.Values.sidecar_proxy.containerPort }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-eventhub-egress-from-cid-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    role: {{ $.Values.cid.role }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.cid.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 10.0.0.0/8
    ports:
{{- range $.Values.eventHubPorts }}
      - protocol: TCP
        port: {{ . }}
{{- end }}
{{- end }}