{{- if $.Values.networkPolicyEnabled -}}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-https-ingress-to-api-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    role: {{ $.Values.api.role }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.api.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: app-publishing
    ports:
    - protocol: TCP
      port: {{ $.Values.sidecar_proxy.containerPort }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-mongodb-egress-from-api-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    role: {{ $.Values.api.role }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.api.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 10.0.0.0/8
    ports:
    - protocol: TCP
      port: 10255
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-api-ingress-from-www-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    role: {{ $.Values.api.role }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.api.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          role: www
          version: {{ .Chart.AppVersion | quote }}
    ports:
    - protocol: TCP
      port: {{ $.Values.sidecar_proxy.containerPort }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-api-egress-to-iproxy-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    role: {{ $.Values.api.role }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.api.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          role: iproxy
          version: {{ .Chart.AppVersion | quote }}
    ports:
    - protocol: TCP
      port: {{ $.Values.sidecar_proxy.containerPort }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-api-egress-to-sjr-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    role: {{ $.Values.api.role }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.api.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          role: sjr
          version: {{ .Chart.AppVersion | quote }}
    ports:
    - protocol: TCP
      port: {{ $.Values.sidecar_proxy.containerPort }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-emis-egress-from-api-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    role: {{ $.Values.api.role }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.api.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: {{ $.Values.emisIPTrust }}
    ports:
    - protocol: TCP
      port: {{ $.Values.emisPort }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-organdonation-egress-from-api-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    role: {{ $.Values.api.role }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.api.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: {{ $.Values.organDonationIPTrust }}
    ports:
    - protocol: TCP
      port: {{ $.Values.organDonationPort }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-vision-egress-from-api-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    role: {{ $.Values.api.role }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.api.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: {{ $.Values.visionIPTrust }}
    ports:
    - protocol: TCP
      port: {{ $.Values.visionPort }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-tpp-egress-from-api-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    role: {{ $.Values.api.role }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.api.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: {{ $.Values.tppIPTrust }}
    ports:
    - protocol: TCP
      port: {{ $.Values.tppPort }}
---
{{- if $.Values.spineLdapLookupEnabled -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-spine-ldap-egress-from-api-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    role: {{ $.Values.api.role }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.api.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: {{ $.Values.spineLdapCIDR }}
    ports:
      - protocol: TCP
        port: {{ $.Values.spineLdapPort }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-internet-egress-from-api-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    role: {{ $.Values.api.role }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.api.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
---
{{- end }}
{{- if $.Values.spinePdsEnabled -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-spine-pds-egress-from-api-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    role: {{ $.Values.api.role }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.api.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: {{ $.Values.spinePdsCIDR }}
    ports:
      - protocol: TCP
        port: {{ $.Values.spinePdsPort }}
{{- end }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-notificationhubs-egress-from-api-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    role: {{ $.Values.api.role }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.api.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 443
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-internal-dns-ingress-to-{{ $.Values.api.role }}-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    role: {{ $.Values.api.role }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.api.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: nginx-ingress-internal
    ports:
    - protocol: TCP
      port: {{ $.Values.sidecar_proxy.containerPort }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-cosmosdb-egress-from-api-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    role: {{ $.Values.api.role }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.api.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 10.0.0.0/8
    ports:
      - protocol: TCP
        port: 10255
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-api-egress-to-cid-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    role: {{ $.Values.api.role }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.api.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Egress
  egress:
  - to:
  {{- range $.Values.cidIPTrust }}
    - ipBlock:
        cidr: {{ . }}
  {{- end }}
    ports:
    - protocol: TCP
      port: 443
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-api-ingress-from-iproxy-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    role: {{ $.Values.api.role }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.api.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          role: iproxy
          version: {{ .Chart.AppVersion | quote }}
    ports:
    - protocol: TCP
      port: {{ $.Values.sidecar_proxy.containerPort }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-https-egress-from-{{ $.Values.api.role }}-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    role: {{ $.Values.api.role }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.api.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 443
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-api-egress-to-messages-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    role: {{ $.Values.api.role }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.api.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          role: messages
          version: {{ .Chart.AppVersion | quote }}
    ports:
    - protocol: TCP
      port: {{ $.Values.sidecar_proxy.containerPort }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-metaservice-egress-from-api-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    role: {{ $.Values.api.role }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.api.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: {{ $.Values.metaServiceCIDR }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-eventhub-egress-from-api-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    role: {{ $.Values.api.role }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.api.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 10.0.0.0/8
    ports:
{{- range $.Values.eventHubPorts }}
      - protocol: TCP
        port: {{ . }}
{{- end }}
{{- end }}