---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-knownservices-config-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
data:
  KnownServices.json: {{ $.Values.knownservices_config | toJson | quote }}