{{- if $.Values.usersEnabled }}
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: {{ template "nhsapp.name" . }}-{{ $.Values.users.role }}
    role: {{ $.Values.users.role }}
    version: {{ .Chart.AppVersion | quote }}
  name: {{ template "nhsapp.name" . }}-{{ $.Values.users.role }}-{{ .Chart.AppVersion }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: {{ template "nhsapp.name" . }}-{{ $.Values.users.role }}-{{ .Chart.AppVersion }}
  minReplicas: {{ $.Values.users.minReplicas }}
  maxReplicas: {{ $.Values.users.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ $.Values.users.targetCPUUtilizationPercentage }}
{{- end }}