server {
  listen      8089;
  server_name 0.0.0.0;
  resolver 127.0.0.11;

  location / {
    proxy_pass http://pfs.local.bitraft.io:8082/;
    proxy_redirect      off;
  }

  location ~* /v1/api/users/(.*)/messages(.*) {
    proxy_pass http://messages.local.bitraft.io:8085/v1/api/$1/messages$2$is_args$args;
    proxy_redirect      off;
  }

  location /v1/api/users/me/info {
    proxy_pass http://userinfo.local.bitraft.io:8091/v1/api/me/info;
    proxy_redirect      off;
  }

  location /v1/api/users/info {
    proxy_pass http://userinfo.local.bitraft.io:8091/v1/api/info;
    proxy_redirect      off;
  }

  location /v1/api/users {
    proxy_pass http://users.local.bitraft.io:8083/v1/api/users;
    proxy_redirect      off;
  }

  location /v1/api/log {
    proxy_pass http://log.local.bitraft.io:8090/v1/api/log;
    proxy_redirect off;
  }
}
