version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    commit-message:
      prefix: "DPDB: "
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/sandbox"
    commit-message:
      prefix: "DPDB: "
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/"
    commit-message:
      prefix: "DPDB: "
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"
