parameters:
  - name: sharepointFolderPath
    type: string
    default: ''

jobs:
  - job: upload_native_apps_to_sharepoint
    displayName: Upload Native Apps to SharePoint Archive
    steps:
      - task: DownloadBuildArtifacts@0
        displayName: Download Android Native Apps
        inputs:
          artifactName: Xamarin Android Clients
          downloadPath: $(Build.SourcesDirectory)

      - task: DownloadBuildArtifacts@0
        displayName: Download iOS Native Apps
        inputs:
          artifactName: Xamarin iOS Clients
          downloadPath: $(Build.SourcesDirectory)

      - task: DownloadSecureFile@1
        name: nhsapp_sharepoint_cert
        inputs:
          secureFile: 'nhsapp_sharepoint_cert.pfx'

      - task: PowerShell@2
        inputs:
          targetType: 'filePath'
          filePath: buildscripts/archive_nativeapps_sharepoint.ps1
          arguments: >
            -CertificateFilePath "$(nhsapp_sharepoint_cert.secureFilePath)"
            -FileToUploadRootFolder "$(Build.SourcesDirectory)/Xamarin Android Clients"
            -SharePointFolderPath "${{ parameters.sharepointFolderPath }}"
        displayName: 'Archive Android Native Apps'

      - task: PowerShell@2
        inputs:
          targetType: 'filePath'
          filePath: buildscripts/archive_nativeapps_sharepoint.ps1
          arguments: >
            -CertificateFilePath "$(nhsapp_sharepoint_cert.secureFilePath)"
            -FileToUploadRootFolder "$(Build.SourcesDirectory)/Xamarin iOS Clients"
            -SharePointFolderPath "${{ parameters.sharepointFolderPath }}"
        displayName: 'Archive iOS Native Apps'