---
name: ${{ parameters.environmentRefOverride }}-$(Build.SourceBranchName)-$(Date:yyyyMMdd)_$(Rev:r)
trigger: none
parameters:
  - name: reapply_config
    displayName: Reapply bootstrap
    type: string
    default: false
    values:
      - false
      - true
  - name: loginEnv
    displayName: Login environment
    type: string
    default: ext
    values:
      - ext
      - aos
      - sandpit
      - dev10
      - dev18
      - nhsapp
  - name: imageVersionOverride
    displayName: "Optional image version override (develop or tag)"
    type: string
    default: "None"
  - name: environmentRefOverride
    displayName: "Pipeline will automatically extract the jira reference from the branch, you can override by providing a value other than jiraref to this parameter"
    type: string
    default: "jiraref"
    values:
      - jiraref
      - scratch1
      - scratch2
      - scratch3
      - scratch4
      - scratch5
      - scratch6
      - scratch7
      - scratch8
      - scratch9
      - scratch10
      - scratch11
      - scratch12
      - scratch13
      - scratch14
      - scratch15
      - scratch16
      - scratch17
      - scratch18
      - scratch19
      - scratch20
      - scratch21
      - onboardingsandpit
      - onboardingaos
      - logindevelopment
      - preview
      - demo
      - ops1
      - ops2
      - ops3
resources:
  repositories:
    - repository: nhsapp-ops-terraform
      type: git
      name: nhsapp-ops-terraform
      ref: develop
    - repository: nhsapp_ops_vault
      type: git
      name: nhsapp-ops-vault
      ref: develop
    - repository: nhsapp_ops_infra
      type: git
      name: nhsapp-ops-infra
      ref: develop
variables:
  - group: Ops
  - name: terraformVersion
    value: 0.14.8
  - name: REAPPLY_CONFIG
    value: ${{ parameters.reapply_config }}
  - name: PROJECT_PATH
    value: nhsapp-ops-infra
  - name: SCRIPTS_PATH
    value: ../nhsapp-ops-vault/scripts
  - name: TARGET_ZONE
    value: dev
  - name: backendAzureRmResourceGroupName
    value: nhsonline
  - name: backendAzureRmStorageAccountName
    value: nhsappterraformnlv
  - name: tfVarFileName
    value: ../zone/devscratch.tfvars
  - name: backendAzureRmContainerName
    value: terraform
  - name: region
    value: uksouth
  - name: environment
    value: dev
  - name: DECODE_PERCENTS
    value: false
  - name: cosmosDBName
    value: scratch
  - name: helmVersion
    value: 3.2.3
pool:
  vmImage: 'ubuntu-latest'
stages:
  - stage: stage_plan_apply_scratch_cluster
    displayName: Scratch Cluster Plan And Apply
    jobs:
      - deployment: terraform
        displayName: Run Terraform Plan And Apply
        timeoutInMinutes: 20
        pool:
          vmImage: 'ubuntu-latest'
        environment: scratch-dev
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: nhsapp-ops-terraform
                - template: /pipelines/templates/steps/get_environment_ref.yml@nhsapp-ops-terraform
                  parameters:
                    environmentRefOverride: ${{ parameters.environmentRefOverride }}
                    ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
                      branchName: $(System.PullRequest.SourceBranch)
                    ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
                      branchName: $(Build.SourceBranch)
                - template: /pipelines/templates/terraform_with_reference.yml@nhsapp-ops-terraform
                  parameters:
                    serviceConnectionName: nhsapp-nonlive-terraform-sp
                    backendAzureRmResourceGroupName: $(backendAzureRmResourceGroupName)
                    backendAzureRmStorageAccountName: $(backendAzureRmStorageAccountName)
                    backendAzureRmContainerName: $(backendAzureRmContainerName)
                    tfExecutionDir: src/cluster-only-environment
                    tfVarFileName: $(tfVarFileName)
                    deployReason: $(Build.Reason)
                    queuedBy: $(Build.QueuedBy)
                    environmentRef: $(ENVIRONMENT_REF)
  - stage: stage_bootstrap_cluster
    displayName: Bootstrap Cluster
    jobs:
      - job: bootstrap_k8s_job
        timeoutInMinutes: 5
        displayName: "[k8s] Bootstrap"
        variables:
          TARGET_ZONE: 'dev'
          CONFIG_ZONE: 'scratch'
        steps:
          - checkout: nhsapp_ops_vault
          - checkout: nhsapp_ops_infra
          - checkout: nhsapp-ops-terraform
          - template: /pipelines/templates/steps/get_environment_ref.yml@nhsapp-ops-terraform
            parameters:
              environmentRefOverride: ${{ parameters.environmentRefOverride }}
              ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
                branchName: $(System.PullRequest.SourceBranch)
              ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
                branchName: $(Build.SourceBranch)
          - bash: |
              echo "##vso[task.setvariable variable=NAMESPACE]$(ENVIRONMENT_REF)"
              echo "##vso[task.setvariable variable=AKSCLUSTERNAME]nhsapp-dev-$(ENVIRONMENT_REF)uks1"
          - template: .azuredevops/templates/steps/init_ci.yaml@nhsapp_ops_vault
          - bash: |
              cd $(PROJECT_PATH) \
              && $(SCRIPTS_PATH)/k8s/k8s_bootstrap_in_docker.sh
            displayName: "[k8s] Bootstrap"
          - bash: |
              cd $(PROJECT_PATH) \
              && $(SCRIPTS_PATH)/k8s/validate_k8s_cluster_in_docker.sh
            displayName: "[k8s] Smoke Test"
  - stage: stage_deploy_app
    displayName: Deploy app to the cluster
    jobs:
      - job: deploy_app
        displayName: 'Deploy NHS App to the cluster'
        timeoutInMinutes: 5
        steps:
        - checkout: nhsapp-ops-terraform
        - checkout: self
        - template: /pipelines/templates/steps/get_environment_ref.yml@nhsapp-ops-terraform
          parameters:
            environmentRefOverride: ${{ parameters.environmentRefOverride }}
            ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
              branchName: $(System.PullRequest.SourceBranch)
            ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
              branchName: $(Build.SourceBranch)
        - task: Bash@3
          displayName: Set version
          inputs:
            targetType: 'inline'
            script: |
              if [[ "${{ parameters.imageVersionOverride }}" != "None" ]]; then
                echo "Using version override ${{ parameters.imageVersionOverride }}"
                version=${{ parameters.imageVersionOverride }}
                echo "##vso[task.setvariable variable=version]${{ parameters.imageVersionOverride }}"
                echo "$version"
              elif [ "$(Build.SourceBranchName)" == "develop" ]; then
                echo "Versioning for develop"
                version=$(echo "develop")
                echo "##vso[task.setvariable variable=version]$version"
                echo "$version"
              elif [[ "$(Build.SourceBranchName)" =~ ^v[0-9]+\.[0-9]+ ]]; then
                echo "Versioning for tag $(Build.SourceBranchName)"
                version=$(Build.SourceBranchName)
                echo "##vso[task.setvariable variable=version]$version"
              else
                echo "Versioning for pull request (latest git hash) $(Build.SourceBranch)"
                version=$(az repos pr list --source-branch $(Build.SourceBranch) | jq -r '.[].lastMergeCommit.commitId')
                echo "##vso[task.setvariable variable=version]$version"
                echo "$version"
                echo "##vso[task.logissue type=warning]If you have recently pushed a new change to your pull request branch, your pods may be in a failed state while the NHS App CI pipeline builds the images."
              fi
          env:
            AZURE_DEVOPS_EXT_PAT: $(AZURE_DEVOPS_EXT_PAT)
        - task: Bash@3
          displayName: 'Update chart version'
          inputs:
            workingDirectory: $(System.DefaultWorkingDirectory)/nhsapp/nhsapp-chart/nhsapp/
            targetType: 'inline'
            script: sed -i -e "s|APPVERSION|$appImageTag|g" Chart.yaml
          env:
            chartVersion: $(Build.SourceBranchName)
            appImageTag: $(version)
        - task: Bash@3
          displayName: 'Set release name'
          inputs:
            targetType: 'inline'
            script: |
              releaseName=$(ENVIRONMENT_REF)-$(Build.SourceBranchName)

              if [ ${#releaseName} -gt 50 ]; then
                truncatedReleaseName="${releaseName:0:50}-t"
                lowercaseReleaseName=$(echo "$truncatedReleaseName" | tr '[:upper:]' '[:lower:]')
              else
                lowercaseReleaseName=$(echo "$releaseName" | tr '[:upper:]' '[:lower:]')
              fi
              echo $lowercaseReleaseName
              echo "##vso[task.setvariable variable=lowercaseReleaseName]$lowercaseReleaseName"
        - task: AzureCLI@2
          displayName: Get cluster IP
          inputs:
            azureSubscription: nhsapp-nonlive-terraform-sp
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              PUBLIC_IP_ADDRESS=`az network public-ip show --name nhsapp-dev-$(ENVIRONMENT_REF)uks1_PIP_ingress --resource-group nhsapp-dev-$(ENVIRONMENT_REF)uks1 | jq '.ipAddress' | tr -d '"'`/32
              echo $PUBLIC_IP_ADDRESS
              echo "##vso[task.setvariable variable=clusterIP;]$PUBLIC_IP_ADDRESS"
        - task: HelmInstaller@1
          displayName: 'Install Helm'
          inputs:
            helmVersionToInstall: $(helmVersion)
        - task: AzureCLI@2
          displayName: Login K8s
          inputs:
            azureSubscription: nhsapp-nonlive-terraform-sp
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              az aks get-credentials -n nhsapp-dev-$(ENVIRONMENT_REF)uks1 -g nhsapp-dev-$(ENVIRONMENT_REF)uks1 --admin
        - task: Bash@3
          displayName: 'Uninstall old releases'
          inputs:
            targetType: 'inline'
            script: |
              if [[ $(helm ls -n $(ENVIRONMENT_REF) --short) ]]; then
                helm ls -n $(ENVIRONMENT_REF) --short | xargs helm delete $old_releases -n $(ENVIRONMENT_REF) && sleep 10
              else
                echo "No releases to uninstall."
              fi
        - task: Bash@3
          displayName: 'Install Environment with Helm'
          inputs:
            targetType: 'inline'
            script: |
              if [ -f "$(System.DefaultWorkingDirectory)/nhsapp/nhsapp-chart/vars/zone/$(environment)/namespace/vars-$(environment)-${{ parameters.environmentRefOverride }}.yaml" ]; then
                echo "Installing with namespace override file"
                helm upgrade $(lowercaseReleaseName) $(System.DefaultWorkingDirectory)/nhsapp/nhsapp-chart/nhsapp/ \
                  --namespace $(ENVIRONMENT_REF) \
                  --install \
                  --set global.environment="$(ENVIRONMENT_REF)" \
                  -f $(System.DefaultWorkingDirectory)/nhsapp/nhsapp-chart/vars/zone/$(environment)/vars-$(environment).yaml \
                  -f $(System.DefaultWorkingDirectory)/nhsapp/nhsapp-chart/vars/zone/$(environment)/namespace/vars-$(environment)-${{ parameters.environmentRefOverride }}.yaml \
                  -f $(System.DefaultWorkingDirectory)/nhsapp/nhsapp-chart/vars/zone/$(environment)/environment_overrides/vars-nhslogin-${{ parameters.loginEnv }}.yaml \
                  --set appImageTag=$(version) \
                  --set cid.image_tag=$(version) \
                  --set api.image_tag=$(version) \
                  --set web.image_tag=$(version) \
                  --set cdsswiremock.image_tag=$(version) \
                  --set logger.image_tag=$(version) \
                  --set sjr.image_tag=$(version) \
                  --set sjrconfig.image_tag=$(version) \
                  --set stub_loader.image_tag=$(version) \
                  --set wiremock.image_tag=latest \
                  --set users.image_tag=$(version) \
                  --set messages.image_tag=$(version) \
                  --set info.image_tag=$(version) \
                  --reset-values \
                  --set cosmosDBName=$(cosmosDBName) \
                  --set region=$(region) \
                  --set zone=$(environment) \
                  --set clusterIP=$(clusterIP) \
                  --set networkPolicyEnabled=false 
              else
                echo "Installing without namespace override file"
                helm upgrade $(lowercaseReleaseName) $(System.DefaultWorkingDirectory)/nhsapp/nhsapp-chart/nhsapp/ \
                  --namespace $(ENVIRONMENT_REF) \
                  --install \
                  --set global.environment="$(ENVIRONMENT_REF)" \
                  -f $(System.DefaultWorkingDirectory)/nhsapp/nhsapp-chart/vars/zone/$(environment)/vars-$(environment).yaml \
                  -f $(System.DefaultWorkingDirectory)/nhsapp/nhsapp-chart/vars/zone/$(environment)/environment_overrides/vars-nhslogin-${{ parameters.loginEnv }}.yaml \
                  --set appImageTag=$(version) \
                  --set cid.image_tag=$(version) \
                  --set api.image_tag=$(version) \
                  --set web.image_tag=$(version) \
                  --set cdsswiremock.image_tag=$(version) \
                  --set logger.image_tag=$(version) \
                  --set sjr.image_tag=$(version) \
                  --set sjrconfig.image_tag=$(version) \
                  --set stub_loader.image_tag=$(version) \
                  --set wiremock.image_tag=latest \
                  --set users.image_tag=$(version) \
                  --set messages.image_tag=$(version) \
                  --set info.image_tag=$(version) \
                  --reset-values \
                  --set cosmosDBName=$(cosmosDBName) \
                  --set region=$(region) \
                  --set zone=$(environment) \
                  --set clusterIP=$(clusterIP) \
                  --set networkPolicyEnabled=false 
              fi