jobs:
  - job: build_and_unit_test_backend
    displayName: Build and Unit Test
    steps:
      - template: set-branch-tag-steps.yml
      - template: docker-login-steps.yml
      - template: nuget-authenticate.yml

      - task: ShellScript@2
        displayName: Restore backend packages
        inputs:
          scriptPath: backendworker/buildscripts/01_restore_packages.sh

      - task: ShellScript@2
        displayName: Build backend
        inputs:
          scriptPath: backendworker/buildscripts/02_build.sh

      - task: ShellScript@2
        displayName: Run backend unit tests
        inputs:
          scriptPath: backendworker/buildscripts/03_run_unit_tests.sh

      - task: Bash@3
        displayName: Check for test container
        condition: succeededOrFailed()
        inputs:
          targetType: 'inline'
          script: |
            if [ "$(docker ps -a -q --filter=name=nhsonline-backend-test-run)" ]; then
              echo "##vso[task.setvariable variable=unit.tests.container.exists]True"
            fi

      - task: ShellScript@2
        displayName: Retrieve backend unit tests results and coverage
        condition: and(succeededOrFailed(), eq(variables['unit.tests.container.exists'], 'True'))
        inputs:
          scriptPath: backendworker/buildscripts/04_extract_test_results.sh

      - template: check-for-output-steps.yml
        parameters:
          description: unit tests results
          test.path: "backendworker/TestResults"
          test.path.exists.variable.name: unit.tests.results.exists

      - task: Bash@3
        displayName: Fix unit tests results paths
        condition: and(succeededOrFailed(), eq(variables['unit.tests.results.exists'], 'True'))
        inputs:
          targetType: 'inline'
          script: |
            find backendworker/TestResults -name '*.trx' -exec \
              sed \
                -ir \
                -e 's#storage="/src/#storage="backendworker/#' \
                -e 's#codeBase="/src/#codeBase="backendworker/#' \
                -e 's# in /src/# in backendworker/#' \
                 \{\} \;

      - task: PublishTestResults@2
        displayName: Publish backend unit tests results
        condition: and(succeededOrFailed(), eq(variables['unit.tests.results.exists'], 'True'))
        inputs:
          testRunTitle: Unit Tests Backend
          testResultsFormat: VSTest
          testResultsFiles: backendworker/TestResults/*.trx
          failTaskOnFailedTests: false
          mergeTestResults: true

      - template: check-for-output-steps.yml
        parameters:
          description: unit tests coverage
          test.path: "backendworker/coverage"
          test.path.exists.variable.name: unit.tests.coverage.exists

      - task: PublishBuildArtifacts@1
        displayName: Publish unit test coverage
        condition: and(succeededOrFailed(), eq(variables['unit.tests.coverage.exists'], 'True'))
        inputs:
          pathToPublish: 'backendworker/coverage'
          artifactName: 'coverage'

      - task: Bash@3
        name: output_vars
        displayName: Output results directories
        condition: succeededOrFailed()
        inputs:
          targetType: 'inline'
          script: |
            echo "unit.tests.coverage.exists=$UNIT_TESTS_COVERAGE_EXISTS"
            echo "##vso[task.setvariable variable=unit.tests.coverage.exists;isOutput=true]$UNIT_TESTS_COVERAGE_EXISTS"

      - task: ShellScript@2
        displayName: Package PFS API
        inputs:
          scriptPath: backendworker/buildscripts/05_package_pfs_api.sh

      - task: ShellScript@2
        displayName: Package CID API
        inputs:
          scriptPath: backendworker/buildscripts/06_package_cid_api.sh

      - task: ShellScript@2
        displayName: Package SJR API
        inputs:
          scriptPath: backendworker/buildscripts/07_package_sjr_api.sh

      - task: ShellScript@2
        displayName: Package CDSS Wiremock
        inputs:
          scriptPath: backendworker/buildscripts/08_package_cdss_wiremock.sh

      - task: ShellScript@2
        displayName: Validate non-live SJR config
        inputs:
          scriptPath: backendworker/buildscripts/09_validate_non_live_sjr_config.sh

      - task: ShellScript@2
        displayName: Package non-live SJR config
        inputs:
          scriptPath: backendworker/buildscripts/10_package_non_live_sjr_config.sh

      - task: ShellScript@2
        displayName: Package Logger API
        inputs:
          scriptPath: backendworker/buildscripts/11_package_logger_api.sh

      - task: ShellScript@2
        displayName: Package Users API
        inputs:
          scriptPath: backendworker/buildscripts/12_package_users_api.sh

      - task: ShellScript@2
        displayName: Package User Info API
        inputs:
          scriptPath: backendworker/buildscripts/13_package_userinfo_api.sh

      - task: ShellScript@2
        displayName: Package Messages API
        inputs:
          scriptPath: backendworker/buildscripts/14_package_messages_api.sh
