jobs:
  - job: build_and_unit_test_web
    displayName: Build and Unit Test
    steps:
      - template: set-branch-tag-steps.yml
      - template: docker-login-steps.yml
      - template: npm-authenticate.yml

      - task: ShellScript@2
        displayName: Run web security audit
        inputs:
          scriptPath: web/buildscripts/01_run_security_audit.sh

      - task: ShellScript@2
        displayName: Run web security tests
        inputs:
          scriptPath: web/buildscripts/02_run_security_tests.sh

      - task: ShellScript@2
        displayName: Restore web packages
        inputs:
          scriptPath: web/buildscripts/03_restore_dependencies.sh

      - task: ShellScript@2
        displayName: Run web linting
        inputs:
          scriptPath: web/buildscripts/04_run_lint.sh

      - task: ShellScript@2
        displayName: Build web
        inputs:
          scriptPath: web/buildscripts/05_build.sh

      - task: ShellScript@2
        displayName: Run web unit tests
        inputs:
          scriptPath: web/buildscripts/06_run_unit_tests.sh

      - task: Bash@3
        displayName: Check for test container
        condition: succeededOrFailed()
        inputs:
          targetType: 'inline'
          script: |
            if [ "$(docker ps -a -q --filter=name=nhsonline-web-test-run)" ]; then
              echo "##vso[task.setvariable variable=unit.tests.container.exists]True"
            fi

      - task: ShellScript@2
        displayName: Retrieve web unit test results and coverage
        condition: and(succeededOrFailed(), eq(variables['unit.tests.container.exists'], 'True'))
        inputs:
          scriptPath: web/buildscripts/07_extract_test_results.sh

      - template: check-for-output-steps.yml
        parameters:
          description: unit tests results
          test.path: "web/web-unit-test-results.xml"
          test.path.exists.variable.name: unit.tests.results.exists

      - task: PublishTestResults@2
        displayName: Publish web unit tests results
        condition: and(succeededOrFailed(), eq(variables['unit.tests.results.exists'], 'True'))
        inputs:
          testRunTitle: Unit Tests Web
          testResultsFormat: JUnit
          testResultsFiles: web/web-unit-test-results.xml
          failTaskOnFailedTests: false
          mergeTestResults: true

      - template: check-for-output-steps.yml
        parameters:
          description: unit tests coverage
          test.path: "web/web-unit-test-coverage.xml"
          test.path.exists.variable.name: unit.tests.coverage.exists

      - task: PublishBuildArtifacts@1
        displayName: Publish unit tests coverage
        condition: and(succeededOrFailed(), eq(variables['unit.tests.coverage.exists'], 'True'))
        inputs:
          pathToPublish: 'web/web-unit-test-coverage.xml'
          artifactName: 'coverage'

      - task: Bash@3
        name: output_vars
        displayName: Output results directories
        condition: succeededOrFailed()
        inputs:
          targetType: 'inline'
          script: |
            echo "unit.tests.coverage.exists=$UNIT_TESTS_COVERAGE_EXISTS"
            echo "##vso[task.setvariable variable=unit.tests.coverage.exists;isOutput=true]$UNIT_TESTS_COVERAGE_EXISTS"

      - task: ShellScript@2
        displayName: Build web docker image
        inputs:
          scriptPath: web/buildscripts/08_build_docker_image.sh
