jobs:
  - job: coverage
    displayName: Generate Unit Test Coverage Report
    steps:
      - task: DownloadBuildArtifacts@0
        displayName: Download coverage
        inputs:
          artifactName: 'coverage'
          downloadPath: $(Build.SourcesDirectory)

      - task: Bash@3
        displayName: Fix Coverage Sources
        inputs:
          targetType: 'inline'
          script: |
            set -e
            find coverage -name 'backend-*.xml' -exec sed -ir -e 's#<source>.*</source>#<source>backendworker</source>#' \{\} \;
            find coverage -name 'ios-*.xml' -exec sed -ir -e 's#<source>.*</source>#<source>ios/NHSOnline</source>#' \{\} \;
            find coverage -name 'web-*.xml' -exec sed -ir -e 's#<source>.*</source>#<source>web</source>#' \{\} \;

      - task: PublishCodeCoverageResults@1
        displayName: Publish coverage report
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: coverage/*.xml
          pathToSources: $(Build.SourcesDirectory)