jobs:
  - job: package_helm_charts
    displayName: Package helm charts
    steps: 
      - template: set-branch-tag-steps.yml

      - task: HelmInstaller@1
        displayName: Helm installer
        inputs: 
          helmVersionToInstall: 3.2.3

      - task: HelmDeploy@0
        displayName: Helm package app chart
        inputs:
          command: package
          chartPath: nhsapp-chart/nhsapp/
          destination: $(System.ArtifactsDirectory)
          version: v1.0.0
          arguments: --app-version=$(branch.tag)
      - task: Bash@3
        displayName: Helm lint app chart
        inputs:
          workingDirectory: $(System.ArtifactsDirectory)
          targetType: 'inline'
          script: helm lint nhsapp-v1.0.0.tgz

      - task: HelmDeploy@0
        displayName: Helm package redirector chart
        inputs:
          command: package
          chartPath: nhsapp-chart/redirector/
          destination: $(System.ArtifactsDirectory)
          version: v1.0.0
          arguments: --app-version=$(branch.tag)
      - task: Bash@3
        displayName: Helm lint app chart
        inputs:
          workingDirectory: $(System.ArtifactsDirectory)
          targetType: 'inline'
          script: helm lint defaultingress-v1.0.0.tgz

      - task: HelmDeploy@0
        displayName: Helm package internal ingress chart
        inputs:
          command: package
          chartPath: nhsapp-chart/internalingress/
          destination: $(System.ArtifactsDirectory)
          version: v1.0.0
          arguments: --app-version=$(branch.tag)
      - task: Bash@3
        displayName: Helm lint app chart
        inputs:
          workingDirectory: $(System.ArtifactsDirectory)
          targetType: 'inline'
          script: helm lint internalingress-v1.0.0.tgz

      - task: PublishBuildArtifacts@1
        displayName: Publish packaged helm charts
        inputs:
          pathToPublish: $(System.ArtifactsDirectory)
          artifactName: 'charts'
      - task: PublishBuildArtifacts@1
        displayName: Publish packaged chart values
        inputs:
          pathToPublish: nhsapp-chart/vars/
          artifactName: 'charts/vars'
      - task: PublishBuildArtifacts@1
        displayName: Publish cleanup utils directory
        inputs:
          pathToPublish: nhsapp-chart/utils/release_management
          artifactName: 'charts/utils/release_management'
  