jobs:
  - job:
    displayName: Generate Xamarin integration test flipbook
    steps:
      - template: docker-login-steps.yml

      - task: DownloadPipelineArtifact@2
        inputs:
          artifact: $(native.xamarin.flipbookInterimFolderName)
          path: xamarinintegrationtests/flipbookgeneration/flipbook

      - task: ShellScript@2
        displayName: Build
        inputs:
          scriptPath: xamarinintegrationtests/buildscripts/09_run_build_flipbook.sh

      - task: Bash@3
        displayName: Set Flipbook Artefact Name Variable
        condition: succeededOrFailed()
        inputs:
          targetType: 'inline'
          script: |
            formattedDate=$(date '+%Y-%m-%d')
            echo "##vso[task.setvariable variable=native.xamarin.flipbookPdfName]flipbook_${formattedDate}_$(System.JobAttempt)"

      - task: ShellScript@2
        displayName: Generate Xamarin integration test flipbook
        env:
          FLIPBOOK_NAME: $(native.xamarin.flipbookPdfName)
        inputs:
          scriptPath: xamarinintegrationtests/buildscripts/10_run_flipbook_generate.sh

      - task: PublishPipelineArtifact@1
        displayName: Publish Xamarin tests flipbook
        inputs:
          artifactName: Flipbook
          targetPath: 'xamarinintegrationtests/flipbookgeneration/flipbook/$(native.xamarin.flipbookPdfName).pdf'

      - task: Bash@3
        displayName: 'Upload flipbook PDF to Slack'
        inputs:
          targetType: 'inline'
          workingDirectory: xamarinintegrationtests/flipbookgeneration/flipbook
          script: |
            tag=$(git describe --abbrev=0 --tags)
            filename=$(native.xamarin.flipbookPdfName).pdf
            substitutedFilename=Flipbook_${tag}.pdf
            curl -F file=@${filename} -F "initial_comment=${tag}" -F "title=${substitutedFilename}" -F "filename=${substitutedFilename}" -F channels=$(SLACK_GENERATE_FLIPBOOK_CHANNEL) -H "Authorization: Bearer $(SLACK_API_TOKEN)" https://slack.com/api/files.upload