jobs:
  - job: unit_test_ios
    displayName: Unit Test
    pool:
      vmImage: 'macos-latest'
    steps:
      - template: set-branch-tag-steps.yml
      - template: ios-install-cocoapods-steps.yml

      - task: Xcode@5
        displayName: 'Build and Run Unit Tests'
        inputs:
          xcodeDeveloperDir: /Applications/Xcode_10.1.app
          xcWorkspacePath: ios/NHSOnline/NHSOnline.xcworkspace
          sdk: iphonesimulator
          scheme: NHSOnline
          configuration: Development
          actions: test
          signingOption: auto
          destinationPlatformOption: iOS
          destinationSimulators: 'iPhone 8'
          publishJUnitResults: false

      - template: check-for-output-steps.yml
        parameters:
          description: unit tests results
          test.path: "./build/reports/junit.xml"
          test.path.exists.variable.name: unit.tests.results.exists

      - task: PublishTestResults@2
        displayName: Publish unit tests results
        condition: and(succeededOrFailed(), eq(variables['unit.tests.results.exists'], 'True'))
        inputs:
          testRunTitle: Unit Tests iOS
          testResultsFormat: JUnit
          testResultsFiles: './build/reports/junit.xml'
          failTaskOnFailedTests: false
          mergeTestResults: true

      - task: Bash@3
        displayName: Generate coverage report
        inputs:
          targetType: 'inline'
          script: |
            set -e
            gem install slather
            cd ios/NHSOnline/
            slather coverage --workspace NHSOnline.xcworkspace --scheme NHSOnline --cobertura-xml --output-directory reports/coverage NHSOnline.xcodeproj
            mv reports/coverage/cobertura.xml reports/coverage/ios-cobertura.xml

      - template: check-for-output-steps.yml
        parameters:
          description: coverage report
          test.path: "ios/NHSOnline/reports/coverage/ios-cobertura.xml"
          test.path.exists.variable.name: unit.tests.coverage.exists

      - task: PublishBuildArtifacts@1
        displayName: Publish unit test coverage
        condition: and(succeededOrFailed(), eq(variables['unit.tests.coverage.exists'], 'True'))
        inputs:
          pathToPublish: 'ios/NHSOnline/reports/coverage'
          artifactName: 'coverage'
