jobs:
  - job: securityscan
    displayName: Twistlock Vulnerabilities and Compliance Scan
    steps:
      - template: set-branch-tag-steps.yml
      - template: docker-login-steps.yml

      - task: ShellScript@2
        displayName: Run
        env:
          TWISTLOCK_CLI_PASS: $(tw.pass)
        inputs:
          scriptPath: build/run_twistlock_security_scan.sh
