parameters:
  - name: branchName
    type: string 

jobs:
    - job: secret_scanning
      displayName: Scan commit history for secrets
      steps: 
        - task: Bash@3
          displayName: Scan commit history for secrets - GitLeaks
          inputs:
            targetType: 'inline'
            script: git checkout ${{ parameters.branchName }} && docker run -v ${PWD}:/repo zricethezav/gitleaks:v7.6.1 --path="/repo" --branch=${{ parameters.branchName }} --verbose --redact --config-path="/repo/gitleaks.config" --leaks-exit-code=1