parameters:
  - name: configuration
    type: string
    default: 'BrowserStack - Release'
  - name: apkFilename
    type: string
    default: 'com.nhs.online.nhsonline.browserstack.apk'
  - name: keyStoreFile
    type: string
    default: 'AndroidDebugSigningKeyStore'
  - name: apksignerKeystorePassword
    type: string
    default: '$(android.debug.key.store.password)'
  - name: keystoreAlias
    type: string
    default: 'debug'

jobs:
  - job:
    displayName: Build Xamarin Android - ${{ parameters.configuration }}
    pool:
      vmImage: 'windows-latest'

    variables:
      output.directory: '$(build.binariesDirectory)/xamarin-android'

    steps:
      - task: NuGetAuthenticate@0
        displayName: NuGet Authenticate

      - task: DownloadSecureFile@1
        name: android_key_store
        inputs:
          secureFile: '${{ parameters.keyStoreFile }}'

      - task: ShellScript@2
        displayName: Build Android '${{ parameters.configuration }}'
        env:
          ANDROID_KEY_STORE_LOCATION: '$(android_key_store.secureFilePath)'
          ANDROID_KEY_STORE_PASSWORD: '${{ parameters.apksignerKeystorePassword }}'
          ANDROID_KEY_STORE_KEY_ALIAS: '${{ parameters.keystoreAlias }}'
          CONFIGURATION: '${{ parameters.configuration }}'
        inputs:
          scriptPath: xamarin/buildscripts/03_build_android.sh

      - task: Bash@3
        displayName: Copy APK
        inputs:
          targetType: 'inline'
          script: |
            mkdir -p "$OUTPUT_DIRECTORY"
            for apk in $(find xamarin/NHSOnline.App.Android/bin -name '*-Signed.apk'); do
              echo "$apk" => "$OUTPUT_DIRECTORY/$(basename $apk | sed -r -e 's/-Signed//')"
              cp "$apk" "$OUTPUT_DIRECTORY/$(basename $apk | sed -r -e 's/-Signed//')"
            done

      - task: PublishBuildArtifacts@1
        displayName: Publish build outputs
        inputs:
          pathtoPublish: '$(output.directory)'
          artifactName: Xamarin Android Clients
