jobs:
- job:
  displayName: Build
  pool:
    vmImage: 'macos-latest'

  variables:
    build.configuration: 'Release'
    output.directory: '$(build.binariesDirectory)/$(build.configuration)'

  steps:
    - task: MSBuild@1
      displayName: Restore packages
      inputs:
        solution: 'xamarin/NhsOnline.App.sln'
        msbuildArguments: '-m /t:Restore'
        configuration: '$(build.configuration)'

    - task: XamarinAndroid@1
      displayName: Build Android
      inputs:
        projectFile: 'xamarin/NhsOnline.App.Android/NhsOnline.App.Android.csproj'
        outputDirectory: '$(output.directory)'
        configuration: '$(build.configuration)'

    - task: AndroidSigning@3
      displayName: Sign Android
      inputs:
        apkFiles: '$(output.directory)/com.nhs.online.nhsonline.apk'
        apksign: true
        apksignerKeystoreFile: AndroidDebugSigningKeyStore
        apksignerKeystorePassword: $(android.debug.key.store.password)
        apksignerKeyPassword: $(android.debug.key.store.password)
        keystoreAlias: debug

    - task: InstallAppleCertificate@2
      displayName: 'Install Apple certificate'
      inputs:
        certSecureFile: iOSDevelopmentCertificate.p12
        certPwd: $(ios.development.certificate.password)

    - task: InstallAppleProvisioningProfile@1
      displayName: 'Install provisioning profile'
      inputs:
        provProfileSecureFile: iOSDevelopmentBrowserStack.mobileprovision
        removeProfile: true

    - task: XamariniOS@2
      displayName: Build iOS
      inputs:
        solutionFile: 'xamarin/NhsOnline.App.sln'
        configuration: '$(build.configuration)'
        buildForSimulator: false
        packageApp: true
        signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
        signingProvisioningProfileID: '$(APPLE_PROV_PROFILE_UUID)'
        args: /p:IpaPackageDir="$(output.directory)"

    - template: check-for-output-steps.yml
      parameters:
        description: build outputs
        test.path: '$(output.directory)'
        test.path.exists.variable.name: output.directory.exists

    - task: PublishBuildArtifacts@1
      displayName: Publish build outputs
      condition: and(succeededOrFailed(), eq(variables['output.directory.exists'], 'True'))
      inputs:
        pathtoPublish: '$(output.directory)'
        artifactName: Xamarin Clients
