image: docker:latest

stages:
  - build
  - analyse
  - package

variables:
  PROJECT_VERSION: "0.1"

cache:
  key: "${CI_COMMIT_SHA}"

build_branch:
  stage: build
  script:
    - apk add --update nodejs
    - npm install
    - npm run test-unit


sonarqube_analyse:
  stage: analyse
  image: java:8-jre-alpine
  script:
    - apk update && apk add --no-cache curl git python3
    - pip3 install --upgrade pip pylint setuptools
    - curl -OL https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.0.3.778.zip
    - mkdir sonar_scanner_unzip && unzip -d sonar_scanner_unzip sonar-scanner-cli-3.0.3.778.zip && mv sonar_scanner_unzip/* sonar_scanner && rm -rf sonar_scanner_unzip sonar-scanner-cli-3.0.3.778.zip
    - ./sonar_scanner/bin/sonar-scanner -Dsonar.projectKey=${CI_PROJECT_NAME} -Dsonar.sources=. -X -Dsonar.login=${SONAR_TOKEN} -Dsonar.projectName=${CI_PROJECT_NAME} -Dsonar.projectVersion=${PROJECT_VERSION} -Dsonar.branch=${CI_COMMIT_REF_SLUG} -Dsonar.host.url=${SONAR_URL} -Dsonar.exclusions=node_modules/**


.job_template: &push_docker
  stage: package
  script:
    - docker login -u ${DOCKER_REGISTRY_USERNAME} -p ${DOCKER_REGISTRY_PASSWORD} ${DOCKER_REGISTRY}
    - docker build . -t "${DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${DOCKER_TAG}"
    - docker push "${DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${DOCKER_TAG}"

package_docker_branches:
  variables:
    DOCKER_TAG: ${CI_COMMIT_REF_SLUG}
  only:
    - branches
  except:
    - master
    - develop
  <<: *push_docker

package_docker_develop:
  variables:
    DOCKER_TAG: latest
  only:
    - develop
  <<: *push_docker
