name: $[format('{0}-{1}', variables['Build.SourceBranchName'], counter(variables['Build.SourceBranchName']))]

trigger:
  branches:
    include:
      - develop
  tags:
    include:
      - v*

pool:
  vmImage: 'ubuntu-latest'

variables:
  docker.registry: nhsapp.azurecr.io
  docker.tag: $[variables['Build.SourceVersion']]
  source.develop: $[eq(variables['Build.SourceBranchName'], 'develop')]
  source.tag: $[startsWith(variables['Build.SourceBranch'], 'refs/tags/')]

stages:
  - stage: backend
    displayName: Backend
    dependsOn:
    jobs:
      - template: .azuredevops/templates/build-and-test-backend-job.yml

  - stage: web
    displayName: Web
    dependsOn:
    jobs:
      - template: .azuredevops/templates/build-and-test-web-job.yml

  - stage: android
    displayName: Android Client
    dependsOn:
    jobs:
      - template: .azuredevops/templates/build-and-test-android-client-job.yml

  - stage: ios
    displayName: iOS Client
    dependsOn:
    jobs:
      - template: .azuredevops/templates/ios-client-test-job.yml

      - template: .azuredevops/templates/ios-client-build-job.yml
        parameters:
          name: Client

      - ${{ if or(startsWith(variables['Build.SourceBranch'], 'refs/tags/'), eq(variables['Build.SourceBranchName'], 'develop')) }}:
        - template: .azuredevops/templates/ios-client-build-job.yml
          parameters:
            name: Preview
            target: Preview
            condition: and(succeeded(), ne(variables['ios.target'], 'Preview'))
            provProfileSecureFile: iOSDevelopmentPreview.mobileprovision
            provisioningProfileName: 'NHS App Dev Preview'

      - ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}:
        - template: .azuredevops/templates/ios-client-build-job.yml
          parameters:
            name: Demo
            target: Demo
            certSecureFile: iOSProductionCertificate.p12
            certPwd: '$(ios.production.certificate.password)'
            scheme: 'NHSOnline Demo'
            provProfileSecureFile: iOSDemo.mobileprovision
            provisioningProfileName: 'NHS App Demo Distribution'

        - template: .azuredevops/templates/ios-client-build-job.yml
          parameters:
            name: Release
            target: Production
            certSecureFile: iOSProductionCertificate.p12
            certPwd: '$(ios.production.certificate.password)'
            scheme: 'NHSOnline'
            provProfileSecureFile: iOSProduction.mobileprovision
            provisioningProfileName: 'NHS App Distribution'

  - stage: generate_code_coverage
    displayName: Generate Code Coverage
    condition: succeededOrFailed()
    dependsOn:
      - web
      - backend
      - ios
    jobs:
      - template: .azuredevops/templates/generate-coverage-report-job.yml

  - stage: security
    displayName: Security Scans
    dependsOn:
      - web
      - backend
    condition: and(succeeded(), or(variables['security.run.scans'], eq(variables['source.develop'], 'True'), eq(variables['source.tag'], 'True')))
    jobs:
      - template: .azuredevops/templates/run-security-scan-job.yml

  - stage: integration_tests
    displayName: Integration Tests
    dependsOn:
      - web
      - backend
    jobs:
      - template: .azuredevops/templates/integration-tests-initialise-job.yml

      - job: tranche
        displayName: Tranche
        dependsOn:
          - init
        condition: and(succeeded(), dependencies.init.outputs['matrix.tranches'])
        timeoutInMinutes: 180
        strategy:
          matrix: $[ dependencies.init.outputs['matrix.tranches'] ]
        variables:
          - template: .azuredevops/templates/integration-tests-variables.yml
        steps:
          - template: .azuredevops/templates/integration-tests-steps.yml

  - stage: android_integration_tests
    displayName: Android Integration Tests
    dependsOn:
      - web
      - backend
      - android
    condition: and(succeeded(), eq(variables['android.target'], 'browserstack'), or(eq(variables['source.tag'], 'True'), eq(variables['source.develop'], 'True'), eq(variables['int.tests.run.native.android'], 'True')))
    jobs:
      - template: .azuredevops/templates/integration-tests-android-job.yml

  - stage: ios_integration_tests
    displayName: iOS Integration Tests
    condition: and(succeeded(), eq(variables['ios.target'], 'BrowserStack'), or(eq(variables['source.tag'], 'True'), eq(variables['source.develop'], 'True'), eq(variables['int.tests.run.native.ios'], 'True')))
    dependsOn:
      - web
      - backend
      - ios
    jobs:
      - template: .azuredevops/templates/integration-tests-ios-job.yml
