name: $[format('{0}-{1}', variables['Build.SourceBranchName'], counter(variables['Build.SourceBranchName']))]

trigger:
  branches:
    include:
      - develop
  tags:
    include:
      - v*

variables:
  docker.registry: nhsappdev.azurecr.io
  docker.tag: $[variables['Build.SourceVersion']]

stages:
  - stage: init
    displayName: Initialise
    jobs:
      - job: init
        displayName: Initialise
        steps:
          - task: PowerShell@2
            displayName: Determine branch tag
            inputs:
              pwsh: true
              targetType: inline
              script: |
                $buildNumber = $env:BUILD_BUILDNUMBER
                $branchTag = $env:BUILD_SOURCEBRANCHNAME
                if ($env:BUILD_REASON -eq 'PullRequest') {
                  $buildNumber = "PR $env:SYSTEM_PULLREQUEST_PULLREQUESTID ($env:SYSTEM_PULLREQUEST_PULLREQUESTITERATION)"
                  $branchTag = "PR$env:SYSTEM_PULLREQUEST_PULLREQUESTID"
                }
                Write-Host "##vso[build.updatebuildnumber]$buildNumber"
                Write-Host "##vso[task.setvariable variable=branch.tag]$branchTag"
                Write-Host "buildNumber: $buildNumber"
                Write-Host "docker.tag: $env:DOCKER_TAG"
                Write-Host "branch.tag: $branchTag"
                New-Item -ItemType Directory -Force -Path (Join-Path $(System.ArtifactsDirectory) 'variables') | Out-Null
                $branchTag | Set-Content (Join-Path $(System.ArtifactsDirectory) 'variables' 'branchTag')

          # Use an artifact to pass the branch tag between stages
          # https://medium.com/microsoftazure/how-to-pass-variables-in-azure-pipelines-yaml-tasks-5c81c5d31763
          - task: PublishBuildArtifacts@1
            displayName: Publish variables
            inputs:
              pathtoPublish: $(System.ArtifactsDirectory)/variables
              artifactName: variables

  - stage: build_and_unit_test
    displayName: Build and Unit Test
    dependsOn: init
    jobs:
      - job: web
        #condition: false
        displayName: Web
        steps:
          - task: DownloadBuildArtifacts@0
            displayName: Download variables
            inputs:
              buildType: current
              artifactName: variables

          - task: PowerShell@2
            displayName: Set branch.tag variable
            inputs:
              pwsh: true
              targetType: inline
              script: |
                $branchTag = Get-Content -Path (Join-Path $(System.ArtifactsDirectory) 'variables' 'branchTag')
                Write-Host "##vso[task.setvariable variable=branch.tag]$branchTag"

          - task: Docker@2
            displayName: Login to docker registry
            inputs:
              command: login
              containerRegistry: nhsappcontainers

          - task: Docker@2
            displayName: Login to temp docker registry
            inputs:
              command: login
              containerRegistry: nhsappdevacr

          - task: ShellScript@2
            displayName: Restore web packages
            inputs:
              scriptPath: web/buildscripts/01_restore_dependencies.sh
              
          - task: ShellScript@2
            displayName: Build web
            inputs:
              scriptPath: web/buildscripts/02_build.sh

          - task: ShellScript@2
            displayName: Run web linting
            inputs:
              scriptPath: web/buildscripts/03_run_lint.sh

          - task: Bash@3
            displayName: Set web unit tests run flag
            inputs:
              targetType: 'inline'
              script: echo "##vso[task.setvariable variable=unitTestsRun]Yes"

          - task: ShellScript@2
            displayName: Run web unit tests
            inputs:
              scriptPath: web/buildscripts/04_run_unit_tests.sh

          - task: ShellScript@2
            displayName: Retrieve web unit test results and coverage
            condition: and(succeededOrFailed(), eq(variables['unitTestsRun'], 'Yes'))
            inputs:
              scriptPath: web/buildscripts/05_extract_test_results.sh

          - task: PublishTestResults@2
            displayName: Publish web unit test results
            condition: and(succeededOrFailed(), eq(variables['unitTestsRun'], 'Yes'))
            inputs:
              testResultsFormat: JUnit
              testResultsFiles: web/web-unit-test-results.xml

          - task: PublishPipelineArtifact@1
            displayName: Publish unit test coverage
            condition: and(succeededOrFailed(), eq(variables['unitTestsRun'], 'Yes'))
            inputs:
              targetPath: 'web/web-unit-test-coverage.xml' 
              artifactName: 'web-coverage'

          - task: ShellScript@2
            displayName: Build web docker image
            inputs:
              scriptPath: web/buildscripts/06_build_docker_image.sh

      - job: backend
        #condition: false
        displayName: Backend
        steps:
          - task: DownloadBuildArtifacts@0
            displayName: Download variables
            inputs:
              buildType: current
              artifactName: variables

          - task: PowerShell@2
            displayName: Set branch.tag variable
            inputs:
              pwsh: true
              targetType: inline
              script: |
                $branchTag = Get-Content -Path (Join-Path $(System.ArtifactsDirectory) 'variables' 'branchTag')
                Write-Host "##vso[task.setvariable variable=branch.tag]$branchTag"

          - task: Docker@2
            displayName: Login to docker registry
            inputs:
              command: login
              containerRegistry: nhsappcontainers

          - task: Docker@2
            displayName: Login to temp docker registry
            inputs:
              command: login
              containerRegistry: nhsappdevacr

          - task: ShellScript@2
            displayName: Restore backend packages
            inputs:
              scriptPath: backendworker/buildscripts/01_restore_packages.sh
          
          - task: ShellScript@2
            displayName: Build backend
            inputs:
              scriptPath: backendworker/buildscripts/02_build.sh

          - task: Bash@3
            displayName: Set backend unit tests run flag
            inputs:
              targetType: 'inline'
              script: echo "##vso[task.setvariable variable=unitTestsRun]Yes"

          - task: ShellScript@2
            displayName: Run backend unit tests
            inputs:
              scriptPath: backendworker/buildscripts/03_run_unit_tests.sh
          
          - task: ShellScript@2
            displayName: Retrieve backend unit tests results and coverage
            condition: and(succeededOrFailed(), eq(variables['unitTestsRun'], 'Yes'))
            inputs:
              scriptPath: backendworker/buildscripts/04_extract_test_results.sh

          - task: PublishTestResults@2
            displayName: Publish backend unit test results
            condition: and(succeededOrFailed(), eq(variables['unitTestsRun'], 'Yes'))
            inputs:
              testResultsFormat: VSTest
              testResultsFiles: backendworker/TestResults/*.trx

          - task: PublishPipelineArtifact@1
            displayName: Publish unit test coverage
            condition: and(succeededOrFailed(), eq(variables['unitTestsRun'], 'Yes'))
            inputs:
              targetPath: 'backendworker/coverage' 
              artifactName: 'backend-coverage'

          - task: ShellScript@2
            displayName: Package PFS API
            inputs:
              scriptPath: backendworker/buildscripts/05_package_pfs_api.sh

          - task: ShellScript@2
            displayName: Package CID API
            inputs:
              scriptPath: backendworker/buildscripts/06_package_cid_api.sh

          - task: ShellScript@2
            displayName: Package SJR API
            inputs:
              scriptPath: backendworker/buildscripts/07_package_sjr_api.sh

          - task: ShellScript@2
            displayName: Package CDSS Wiremock
            inputs:
              scriptPath: backendworker/buildscripts/08_package_cdss_wiremock.sh

          - task: ShellScript@2
            displayName: Validate non-live SJR config
            inputs:
              scriptPath: backendworker/buildscripts/09_validate_non_live_sjr_config.sh

          - task: ShellScript@2
            displayName: Package non-live SJR config
            inputs:
              scriptPath: backendworker/buildscripts/10_package_non_live_sjr_config.sh

          - task: ShellScript@2
            displayName: Package Logger API
            inputs:
              scriptPath: backendworker/buildscripts/11_package_logger_api.sh

          - task: ShellScript@2
            displayName: Package Users API
            inputs:
              scriptPath: backendworker/buildscripts/12_package_users_api.sh

          - task: ShellScript@2
            displayName: Package User Info API
            inputs:
              scriptPath: backendworker/buildscripts/13_package_userinfo_api.sh

          - task: ShellScript@2
            displayName: Package Messages API
            inputs:
              scriptPath: backendworker/buildscripts/14_package_messages_api.sh

      - job: coverage
        displayName: Generate Unit Test Coverage Report
        dependsOn:
          - web
          - backend
        condition: succeededOrFailed()
        steps:
          - task: DownloadPipelineArtifact@2
            displayName: Download web coverage
            inputs:
              artifact: 'web-coverage'
              path: $(Build.SourcesDirectory)/web-coverage

          - task: DownloadPipelineArtifact@2
            displayName: Download backend coverage
            inputs:
              artifact: 'backend-coverage'
              path: $(Build.SourcesDirectory)/backend-coverage

          - task: Bash@3
            displayName: Aggregate coverage files
            inputs:
              targetType: 'inline'
              script: |
                mkdir -p $(Build.SourcesDirectory)/coverage/src
                find $(Build.SourcesDirectory)/web-coverage -name \*.xml -exec ln -s \{\} $(Build.SourcesDirectory)/coverage/ \;
                find $(Build.SourcesDirectory)/backend-coverage -name \*.xml -exec ln -s \{\} $(Build.SourcesDirectory)/coverage/ \;
                find $(Build.SourcesDirectory)/backendworker -maxdepth 1 -type d -name NHSOnline.\* -exec ln -s \{\} $(Build.SourcesDirectory)/coverage/src/ \;
                ln -s $(Build.SourcesDirectory)/web/src $(Build.SourcesDirectory)/coverage/src/
                ls -lR $(Build.SourcesDirectory)/coverage

          - task: PublishCodeCoverageResults@1
            displayName: Publish coverage report
            inputs:
              codeCoverageTool: Cobertura
              summaryFileLocation: coverage/*.xml
              pathToSources: $(Build.SourcesDirectory)/coverage/src

  - stage: bdd_test
    displayName: Run BDD
    jobs:
      - job: smoketest
        displayName: Smoketest
        #condition: false
        steps:
          - task: DownloadBuildArtifacts@0
            displayName: Download variables
            inputs:
              buildType: current
              artifactName: variables

          - task: PowerShell@2
            displayName: Set branch.tag variable
            inputs:
              pwsh: true
              targetType: inline
              script: |
                $branchTag = Get-Content -Path (Join-Path $(System.ArtifactsDirectory) 'variables' 'branchTag')
                Write-Host "##vso[task.setvariable variable=branch.tag]$branchTag"

          - task: Docker@2
            displayName: Login to docker registry
            inputs:
              command: login
              containerRegistry: nhsappcontainers

          - task: Docker@2
            displayName: Login to temp docker registry
            inputs:
              command: login
              containerRegistry: nhsappdevacr

          - task: Bash@3
            displayName: Set BDD tests run flag
            inputs:
              targetType: 'inline'
              script: echo "##vso[task.setvariable variable=bddTestsRun]Yes"

          - task: ShellScript@2
            displayName: Run BDD smoketest
            env:
              AZURE_NOTIFICATION_HUB_SHARED_ACCESS_KEY: $(azure.notification.hub.shared.access.key)
            inputs:
              scriptPath: bddtests/buildscripts/01_spin_up_environment.sh

          - task: ArchiveFiles@2
            displayName: Zip serenity report
            condition: and(succeededOrFailed(), eq(variables['bddTestsRun'], 'Yes'))
            inputs:
              rootFolderOrFile: bddtests/target/site/serenity
              includeRootFolder: false
              archiveType: zip
              archiveFile: '$(Build.ArtifactStagingDirectory)/SmokeTests/serenity_report.zip'
              
          - task: ArchiveFiles@2
            displayName: Zip detekt report
            condition: and(succeededOrFailed(), eq(variables['bddTestsRun'], 'Yes'))
            inputs:
              rootFolderOrFile: bddtests/target/site/detekt
              includeRootFolder: false
              archiveType: zip
              archiveFile: '$(Build.ArtifactStagingDirectory)/SmokeTests/detekt_report.zip'
              
          - task: ArchiveFiles@2
            displayName: Zip docker logs
            condition: and(succeededOrFailed(), eq(variables['bddTestsRun'], 'Yes'))
            inputs:
              rootFolderOrFile: bddtests/ops/logs
              includeRootFolder: false
              archiveType: zip
              archiveFile: '$(Build.ArtifactStagingDirectory)/SmokeTests/docker_logs.zip'
              
          - task: ArchiveFiles@2
            displayName: Zip junit logs
            condition: and(succeededOrFailed(), eq(variables['bddTestsRun'], 'Yes'))
            inputs:
              rootFolderOrFile: bddtests/build/test-results
              includeRootFolder: false
              archiveType: zip
              archiveFile: '$(Build.ArtifactStagingDirectory)/SmokeTests/junit_logs.zip'
              
          - task: PublishPipelineArtifact@1
            displayName: Publish smoke test artifacts
            condition: and(succeededOrFailed(), eq(variables['bddTestsRun'], 'Yes'))
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)/SmokeTests'
              artifactName: 'smoke-tests'

          - task: PublishTestResults@2
            displayName: Publish smoke test results
            condition: and(succeededOrFailed(), eq(variables['bddTestsRun'], 'Yes'))
            inputs:
              testResultsFormat: JUnit
              testResultsFiles: '**/TEST-*.xml'
              searchFolder: '$(Build.SourcesDirectory)/bddtests/build/test-results'
              testRunTitle: Smoke Tests
