name: $[format('{0}-{1}', variables['Build.SourceBranchName'], counter(variables['Build.SourceBranchName']))]

trigger:
  branches:
    include:
      - develop
  tags:
    include:
      - v*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: .azuredevops/templates/docker-variables.yml

stages:
  - template: .azuredevops/templates/initialise-stage.yml

  - stage: build_and_unit_test
    displayName: Build and Unit Test
    dependsOn: init
    jobs:
      - job: web
        displayName: Web
        steps:
          - template: .azuredevops/templates/build-and-test-web-steps.yml

      - job: backend
        displayName: Backend
        steps:
          - template: .azuredevops/templates/build-and-test-backend-steps.yml

      - template: .azuredevops/templates/generate-coverage-report-job.yml

  - stage: integration_tests
    displayName: Integration Tests
    jobs:
      - template: .azuredevops/templates/integration-tests-initialise-job.yml

      - job: tranche
        displayName: Tranche
        dependsOn:
          - init
        condition: and(succeeded(), dependencies.init.outputs['matrix.tranches'])
        strategy:
          matrix: $[ dependencies.init.outputs['matrix.tranches'] ]
        variables:
          - template: .azuredevops/templates/integration-tests-variables.yml
        steps:
          - template: .azuredevops/templates/integration-tests-steps.yml
