# This docker compose file is for local development only.  It spins up the backend proxy, worker
# and stubs but not the web container.  This is because web served by webpack-dev-server on the
# local machine.
version: '3'
services:
  nhsonline.backend.proxy:
    image: nhsonline.backend.proxy
    ports:
      - "8800:80"
  nhsonline.backend.worker:
    image: nhsonline.backend.worker
  nhsonline.stubs.emis.im1:
    image: nhsonline.stubs.emis.im1
