version: "3.4"

secrets:
  azure_notification_hub_key:
    file: "~/.nhsonline/secrets/azure_notification_hub_key"
  microtest_cert:
    file: "~/.nhsonline/secrets/microtest_client_cert.pfx"
  microtest_cert_passphrase:
    file: "~/.nhsonline/secrets/microtest_client_cert.password"
  gp_lookup_api_key:
    file: "~/.nhsonline/secrets/gp_lookup_api_key"
  nhsapp_api_key:
    file: "~/.nhsonline/secrets/nhsapp_api_key"
  nhslogin_private_key:
    file: "~/.nhsonline/secrets/nhslogin_ext_private_key.pem"
  nhslogin_rsapass:
    file: "~/.nhsonline/secrets/nhslogin_ext_rsapass.password"
  organ_donation_cert:
    file: "~/.nhsonline/secrets/organ_donation_cert.pfx"
  organ_donation_cert_passphrase:
    file: "~/.nhsonline/secrets/organ_donation_cert.password"
  session_encryption_key:
    file: "~/.nhsonline/secrets/session_encryption_key"
  spine_cert:
    file: "~/.nhsonline/secrets/spine_client_cert.pfx"
  spine_cert_passphrase:
    file: "~/.nhsonline/secrets/spine_client_cert.password"
  tpp_cert:
    file: "~/.nhsonline/secrets/tpp_client_cert.pfx"
  tpp_cert_passphrase:
    file: "~/.nhsonline/secrets/tpp_client_cert.password"
  vision_cert:
    file: "~/.nhsonline/secrets/vision_client_cert.pfx"
  vision_cert_passphrase:
    file: "~/.nhsonline/secrets/vision_client_cert.password"
  qualtrics_api_key:
    file: "~/.nhsonline/secrets/qualtrics_api_key"


services:

  mongodb.bitraft.io:
    image: mongo:latest

  api.local.bitraft.io:
    restart: always
    image: nginx:alpine
    volumes:
      - ./docker/nginx/api:/etc/nginx/conf.d
    depends_on:
      - log.local.bitraft.io
      - messages.local.bitraft.io
      - pfs.local.bitraft.io
      - userinfo.local.bitraft.io
      - users.local.bitraft.io

  silver.integrations.bitraft.io:
    image: nginx:alpine
    volumes:
      - type: bind
        source: ./silver-integration-api-test-site
        target: /etc/nginx/html
      - ./docker/nginx/silver:/etc/nginx/conf.d

  web.local.bitraft.io:
    image: ${WEB_DOCKER_REGISTRY:-local}/nhsonline-web:${WEB_DOCKER_TAG:-latest}
    env_file:
      - ./docker/web.env
      - ./docker/gplookup_connectivity.env
      - ./docker/nhslogin_connectivity_ext.env

  pfs.local.bitraft.io:
    image: ${PFSAPI_DOCKER_REGISTRY:-local}/nhsonline-backendpfsapi:${PFSAPI_DOCKER_TAG:-latest}
    entrypoint:
      - /bin/bash # The service currently expects secrets as env vars but docker-compose only supports files
      - -c        # Therefore we run a script before starting the service to read the file into an env var
      - |
          if [ -f "$$TPP_CERT_PASSPHRASE" ]; then
            export TPP_CERT_PASSPHRASE=$$(<$$TPP_CERT_PASSPHRASE)
          fi
          if [ -f "$$MICROTEST_CERT_PASSPHRASE" ]; then
            export MICROTEST_CERT_PASSPHRASE=$$(<$$MICROTEST_CERT_PASSPHRASE)
          fi
          if [ -f "$$ORGAN_DONATION_CERT_PASSPHRASE" ]; then
            export ORGAN_DONATION_CERT_PASSPHRASE=$$(<$$ORGAN_DONATION_CERT_PASSPHRASE)
          fi
          if [ -f "$$SPINE_CERT_PASSPHRASE" ]; then
            export SPINE_CERT_PASSPHRASE=$$(<$$SPINE_CERT_PASSPHRASE)
          fi
          if [ -f "$$GP_LOOKUP_API_KEY" ]; then
            export GP_LOOKUP_API_KEY=$$(<$$GP_LOOKUP_API_KEY)
          fi
          if [ -f "$$NHSLOGIN_KEY_PASSWORD" ]; then
            export NHSLOGIN_KEY_PASSWORD=$$(<$$NHSLOGIN_KEY_PASSWORD)
          fi
          if [ -f "$$NDOP_CERT_PASSPHRASE" ]; then
            export NDOP_CERT_PASSPHRASE=$$(<$$NDOP_CERT_PASSPHRASE)
          fi
          if [ -f "$$VISION_CERT_PASSPHRASE" ]; then
            export VISION_CERT_PASSPHRASE=$$(<$$VISION_CERT_PASSPHRASE)
          fi
          exec $$*
      - "--"
    command: dotnet NHSOnline.Backend.PfsApi.dll
    env_file:
      - ./docker/emis_connectivity.env
      - ./docker/fakegp_connectivity.env
      - ./docker/gplookup_connectivity.env
      - ./docker/im1cache_database.env
      - ./docker/microtest_connectivity.env
      - ./docker/organdonation_connectivity.env
      - ./docker/session_database.env
      - ./docker/sjr_connectivity.env
      - ./docker/spine_connectivity.env
      - ./docker/tpp_connectivity.env
      - ./docker/userinfo_connectivity.env
      - ./docker/vision_connectivity.env
      - ./docker/proxy_access.env
      - ./docker/pfs.env
    depends_on:
      - servicejourneyrulesapi.local.bitraft.io
    secrets:
      - gp_lookup_api_key
      - microtest_cert
      - microtest_cert_passphrase
      - nhslogin_private_key
      - nhslogin_rsapass
      - organ_donation_cert
      - organ_donation_cert_passphrase
      - session_encryption_key
      - spine_cert
      - spine_cert_passphrase
      - tpp_cert
      - tpp_cert_passphrase
      - vision_cert
      - vision_cert_passphrase

  cid.local.bitraft.io:
    image: ${CIDAPI_DOCKER_REGISTRY:-local}/nhsonline-backendcidapi:${CIDAPI_DOCKER_TAG:-latest}
    entrypoint:
      - /bin/bash # The service currently expects secrets as env vars but docker-compose only supports files
      - -c        # Therefore we run a script before starting the service to read the file into an env var
      - |
          if [ -f "$$TPP_CERT_PASSPHRASE" ]; then
            export TPP_CERT_PASSPHRASE=$$(<$$TPP_CERT_PASSPHRASE)
          fi
          if [ -f "$$MICROTEST_CERT_PASSPHRASE" ]; then
            export MICROTEST_CERT_PASSPHRASE=$$(<$$MICROTEST_CERT_PASSPHRASE)
          fi
          if [ -f "$$VISION_CERT_PASSPHRASE" ]; then
            export VISION_CERT_PASSPHRASE=$$(<$$VISION_CERT_PASSPHRASE)
          fi
          exec $$*
      - "--"
    command: dotnet NHSOnline.Backend.CidApi.dll
    env_file:
      - ./docker/emis_connectivity.env
      - ./docker/fakegp_connectivity.env
      - ./docker/im1cache_database.env
      - ./docker/microtest_connectivity.env
      - ./docker/session_database.env
      - ./docker/sjr_connectivity.env
      - ./docker/tpp_connectivity.env
      - ./docker/vision_connectivity.env
      - ./docker/proxy_access.env
      - ./docker/cid.env
    depends_on:
      - servicejourneyrulesapi.local.bitraft.io
    secrets:
      - microtest_cert
      - microtest_cert_passphrase
      - session_encryption_key
      - tpp_cert
      - tpp_cert_passphrase
      - vision_cert
      - vision_cert_passphrase

  servicejourneyrulesapi.config:
    image: ${SJRCONFIG_DOCKER_REGISTRY:-local}/nhsonline-service-journey-dev-config:${SJRCONFIG_DOCKER_TAG:-latest}
    volumes:
      - 'servicejourneyrules_data:/output'

  servicejourneyrulesapi.local.bitraft.io:
    image: ${SJRAPI_DOCKER_REGISTRY:-local}/nhsonline-backendservicejourneyrulesapi:${SJRAPI_DOCKER_TAG:-latest}
    command: dotnet NHSOnline.Backend.ServiceJourneyRulesApi.dll
    env_file:
      - ./docker/sjr.env
    depends_on:
      - servicejourneyrulesapi.config
    volumes:
      - 'servicejourneyrules_data:/app/input'

  users.local.bitraft.io:
    image: ${USERSAPI_DOCKER_REGISTRY:-local}/nhsonline-backendusersapi:${USERSAPI_DOCKER_TAG:-latest}
    entrypoint:
      - /bin/bash # The service currently expects secrets as env vars but docker-compose only supports files
      - -c        # Therefore we run a script before starting the service to read the file into an env var
      - |
          if [ -f "$$AZURE_NOTIFICATION_HUB_SHARED_ACCESS_KEY" ]; then
            export AZURE_NOTIFICATION_HUB_SHARED_ACCESS_KEY=$$(<$$AZURE_NOTIFICATION_HUB_SHARED_ACCESS_KEY)
          fi
          if [ -f "$$NHSLOGIN_KEY_PASSWORD" ]; then
            export NHSLOGIN_KEY_PASSWORD=$$(<$$NHSLOGIN_KEY_PASSWORD)
          fi
          exec $$*
      - "--"
    command: dotnet NHSOnline.Backend.UsersApi.dll
    env_file:
      - ./docker/notificationhub_connectivity.env
      - ./docker/users.env
    secrets:
      - nhslogin_private_key
      - nhslogin_rsapass
      - azure_notification_hub_key

  userinfo.local.bitraft.io:
    image: ${USERINFOAPI_DOCKER_REGISTRY:-local}/nhsonline-backenduserinfoapi:${USERINFOAPI_DOCKER_TAG:-latest}
    entrypoint:
      - /bin/bash # The service currently expects secrets as env vars but docker-compose only supports files
      - -c        # Therefore we run a script before starting the service to read the file into an env var
      - |
          if [ -f "$$NHSAPP_API_KEY" ]; then
            export NHSAPP_API_KEY=$$(<$$NHSAPP_API_KEY)
          fi
          if [ -f "$$NHSLOGIN_KEY_PASSWORD" ]; then
            export NHSLOGIN_KEY_PASSWORD=$$(<$$NHSLOGIN_KEY_PASSWORD)
          fi
          if [ -f "$$QUALTRICS_API_KEY" ]; then
            export QUALTRICS_API_KEY=$$(<$$QUALTRICS_API_KEY)
          fi
          exec $$*
      - "--"
    command: dotnet NHSOnline.Backend.UserInfoApi.dll
    env_file:
      - ./docker/nhslogin_connectivity_ext.env
      - ./docker/qualtrics_connectivity.env
      - ./docker/userinfo.env
    secrets:
      - nhsapp_api_key
      - nhslogin_private_key
      - nhslogin_rsapass
      - qualtrics_api_key

  messages.local.bitraft.io:
    image: ${MESSAGESAPI_DOCKER_REGISTRY:-local}/nhsonline-backendmessagesapi:${MESSAGESAPI_DOCKER_TAG:-latest}
    entrypoint:
      - /bin/bash # The service currently expects secrets as env vars but docker-compose only supports files
      - -c        # Therefore we run a script before starting the service to read the file into an env var
      - |
          if [ -f "$$NHSAPP_API_KEY" ]; then
            export NHSAPP_API_KEY=$$(<$$NHSAPP_API_KEY)
          fi
          if [ -f "$$NHSLOGIN_KEY_PASSWORD" ]; then
            export NHSLOGIN_KEY_PASSWORD=$$(<$$NHSLOGIN_KEY_PASSWORD)
          fi
          exec $$*
      - "--"
    command: dotnet NHSOnline.Backend.MessagesApi.dll
    env_file:
      - ./docker/messages.env
    secrets:
      - nhsapp_api_key
      - nhslogin_private_key
      - nhslogin_rsapass

  log.local.bitraft.io:
    image: ${LOGAPI_DOCKER_REGISTRY:-local}/nhsonline-clientloggerapi:${LOGAPI_DOCKER_TAG:-latest}
    env_file:
      - ./docker/logger.env
    secrets:
      - nhsapp_api_key

  mongo_seed:
    image: mongo:latest
    links:
      - mongodb.bitraft.io
    entrypoint:
      - /bin/bash
      - -c
      - |
          sleep 5
          EVAL="db.session.createIndex({_ts:1},{expireAfterSeconds:$${EXPIRE_AFTER_SECONDS:-600}})"
          mongo --host mongodb.bitraft.io --eval "$$EVAL" development
      - "--"
    depends_on:
      - mongodb.bitraft.io

volumes:
  servicejourneyrules_data:
    driver: local
