version: '3'

services:
  nhsonline.web:
    ports:
      - "8080:8080"
    environment:
      - API_HOST=http://localhost:8800
  nhsonline.backend.proxy:
    image: nhsonline.backend.proxy
    ports:
      - "8800:80"
  nhsonline.backend.worker:
    image: nhsonline.backend.worker
  nhsonline.stubs.emis.im1:
    image: nhsonline.stubs.emis.im1

