version: '3'

services:
  nhsonline.backend.worker:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:80"
  nhsonline.stubs.emis.im1:
    image: nhsonline.stubs.emis.im1
