FROM alpine:3.7

ENV HOST 0.0.0.0
ENV API_HOST http://localhost:8800
ENV ORGAN_DONATION_URL https://www.organdonation.nhs.uk/
ENV SYMPTOM_CHECKER_URL https://111.nhs.uk

RUN apk upgrade --no-cache && \
    apk add --no-cache \
      nodejs \
      nodejs-npm \
      tini \
    && \
    adduser -D nodejs && \
    npm install webpack webpack-dev-server -g

VOLUME ["/opt/app"]
WORKDIR /opt/app
RUN chown nodejs:nodejs -R /opt/app

USER nodejs
ENTRYPOINT ["/sbin/tini", "--"]

EXPOSE 8080
CMD ["sh", "-c", "npm set progress=false && npm config set depth 0 && npm install && npm run start"]
