version: "3.4"

secrets:
  auth_signing_private_key:
    file: "~/.nhsonline/secrets/auth_signing_private_key.pem"
  auth_signing_rsapass:
    file: "~/.nhsonline/secrets/auth_signing_rsapass.password"
  azure_notification_hub_key:
    file: "~/.nhsonline/secrets/azure_notification_hub_key"
  gp_lookup_api_key:
    file: "~/.nhsonline/secrets/gp_lookup_api_key"
  nhsapp_api_key:
    file: "~/.nhsonline/secrets/nhsapp_api_key"
  nhsapp_apim_pfx:
    file: "~/.nhsonline/secrets/nhs_app_apim.pfx"
  nhsapp_apim_pfx_passphrase:
    file: "~/.nhsonline/secrets/nhs_app_apim.password"
  nhsapp_apim_key:
    file: "~/.nhsonline/secrets/nhs_app_apim_key"
  organ_donation_cert:
    file: "~/.nhsonline/secrets/organ_donation_cert.pfx"
  organ_donation_cert_passphrase:
    file: "~/.nhsonline/secrets/organ_donation_cert.password"
  session_encryption_key:
    file: "~/.nhsonline/secrets/session_encryption_key"
  spine_cert:
    file: "~/.nhsonline/secrets/spine_client_cert.pfx"
  spine_cert_passphrase:
    file: "~/.nhsonline/secrets/spine_client_cert.password"
  tpp_cert:
    file: "~/.nhsonline/secrets/tpp_client_cert.pfx"
  tpp_cert_passphrase:
    file: "~/.nhsonline/secrets/tpp_client_cert.password"
  vision_cert:
    file: "~/.nhsonline/secrets/vision_client_cert.pfx"
  vision_cert_passphrase:
    file: "~/.nhsonline/secrets/vision_client_cert.password"
  qualtrics_api_key:
    file: "~/.nhsonline/secrets/qualtrics_api_key"
  comms_hub_event_hub_pid_connection_string:
    file: "~/.nhsonline/secrets/comms_hub_event_hub_pid_connection_string"
  comms_hub_event_hub_connection_string:
    file: "~/.nhsonline/secrets/comms_hub_event_hub_connection_string"
  audit_event_hub_connection_string:
    file: "~/.nhsonline/secrets/audit_event_hub_connection_string"
  cosmos_sql_api_connection_string:
    file: "~/.nhsonline/secrets/cosmos_sql_api_connection_string"


services:

  mongodb.bitraft.io:
    image: mongo:latest

  api.local.bitraft.io:
    restart: always
    image: nginx:alpine
    volumes:
      - ./docker/nginx/api:/etc/nginx/conf.d
    depends_on:
      - pfs.local.bitraft.io
      - userinfo.local.bitraft.io
      - users.local.bitraft.io

  silver.local.bitraft.io:
    image: nginx:alpine
    volumes:
      - type: bind
        source: ./silver-integration-api-test-site/dist
        target: /etc/nginx/html
      - ./docker/nginx/silver:/etc/nginx/conf.d

  web.local.bitraft.io:
    image: ${WEB_DOCKER_REGISTRY:-local}/nhsonline-web:${WEB_DOCKER_TAG:-latest}
    env_file:
      - ./docker/web.env
      - ./docker/gplookup_connectivity.env
      - ./docker/nhslogin_connectivity_ext.env
      - ./docker/appointments.env
      - ./docker/well-known.env
      - ./docker/gp_session_connectivity.env
      - ./docker/health_checks_enabled.env
      - ./docker/organ_donation_desktop_enabled.env
      - ./docker/tpp_test_results.env

  pfs.local.bitraft.io:
    image: ${PFSAPI_DOCKER_REGISTRY:-local}/nhsonline-backendpfsapi:${PFSAPI_DOCKER_TAG:-latest}
    entrypoint:
      - /bin/bash # The service currently expects secrets as env vars but docker-compose only supports files
      - -c        # Therefore we run a script before starting the service to read the file into an env var
      - |
          if [ -f "$$AUTH_SIGNING_PASSWORD" ]; then
            export AUTH_SIGNING_PASSWORD=$$(<$$AUTH_SIGNING_PASSWORD)
          fi
          if [ -f "$$TPP_CERT_PASSPHRASE" ]; then
            export TPP_CERT_PASSPHRASE=$$(<$$TPP_CERT_PASSPHRASE)
          fi
          if [ -f "$$NHSAPP_API_KEY" ]; then
            export NHSAPP_API_KEY=$$(<$$NHSAPP_API_KEY)
          fi
          if [ -f "$$ORGAN_DONATION_CERT_PASSPHRASE" ]; then
            export ORGAN_DONATION_CERT_PASSPHRASE=$$(<$$ORGAN_DONATION_CERT_PASSPHRASE)
          fi
          if [ -f "$$SPINE_CERT_PASSPHRASE" ]; then
            export SPINE_CERT_PASSPHRASE=$$(<$$SPINE_CERT_PASSPHRASE)
          fi
          if [ -f "$$GP_LOOKUP_API_KEY" ]; then
            export GP_LOOKUP_API_KEY=$$(<$$GP_LOOKUP_API_KEY)
          fi
          if [ -f "$$NDOP_SIGNING_KEY_PASSPHRASE" ]; then
            export NDOP_SIGNING_KEY_PASSPHRASE=$$(<$$NDOP_SIGNING_KEY_PASSPHRASE)
          fi
          if [ -f "$$VISION_CERT_PASSPHRASE" ]; then
            export VISION_CERT_PASSPHRASE=$$(<$$VISION_CERT_PASSPHRASE)
          fi
          if [ -f "$$COMMS_HUB_EVENT_HUB_PID_CONNECTION_STRING" ]; then
            export COMMS_HUB_EVENT_HUB_PID_CONNECTION_STRING=$$(<$$COMMS_HUB_EVENT_HUB_PID_CONNECTION_STRING)
          fi
          if [ -f "$$COMMS_HUB_EVENT_HUB_CONNECTION_STRING" ]; then
            export COMMS_HUB_EVENT_HUB_CONNECTION_STRING=$$(<$$COMMS_HUB_EVENT_HUB_CONNECTION_STRING)
          fi
          if [ -f "$$NHSAPP_APIM_PFX_PASSPHRASE" ]; then
            export NHSAPP_APIM_PFX_PASSPHRASE=$$(<$$NHSAPP_APIM_PFX_PASSPHRASE)
          fi
          if [ -f "$$NHSAPP_APIM_KEY" ]; then
            export NHSAPP_APIM_KEY=$$(<$$NHSAPP_APIM_KEY)
          fi
          if [ -f "$$AUDIT_EVENT_HUB_CONNECTION_STRING" ]; then
            export AUDIT_EVENT_HUB_CONNECTION_STRING=$$(<$$AUDIT_EVENT_HUB_CONNECTION_STRING)
          fi
          if [ -f "$$COSMOS_SQL_API_CONNECTION_STRING" ]; then
            export COSMOS_SQL_API_CONNECTION_STRING=$$(<$$COSMOS_SQL_API_CONNECTION_STRING)
          fi
          exec $$*
      - "--"
    command: dotnet NHSOnline.Backend.PfsApi.dll
    env_file:
      - ./docker/emis_connectivity.env
      - ./docker/fakegp_connectivity.env
      - ./docker/gplookup_connectivity.env
      - ./docker/im1cache_database.env
      - ./docker/messages_connectivity.env
      - ./docker/organdonation_connectivity.env
      - ./docker/session_database.env
      - ./docker/sjr_connectivity.env
      - ./docker/spine_connectivity.env
      - ./docker/tpp_connectivity.env
      - ./docker/userinfo_connectivity.env
      - ./docker/vision_connectivity.env
      - ./docker/eventhub_connectivity.env
      - ./docker/proxy_access.env
      - ./docker/appointments.env
      - ./docker/pfs.env
      - ./docker/knownservices.env
      - ./docker/knownservicesV3.env
      - ./docker/health_checks_enabled.env
      - ./docker/tpp_test_results.env
      - ./docker/secondarycare_connectivity.env
      - ./docker/apim_connectivity.env
    depends_on:
      - servicejourneyrulesapi.local.bitraft.io
    secrets:
      - auth_signing_private_key
      - auth_signing_rsapass
      - gp_lookup_api_key
      - nhsapp_api_key
      - organ_donation_cert
      - organ_donation_cert_passphrase
      - session_encryption_key
      - spine_cert
      - spine_cert_passphrase
      - tpp_cert
      - tpp_cert_passphrase
      - vision_cert
      - vision_cert_passphrase
      - comms_hub_event_hub_pid_connection_string
      - comms_hub_event_hub_connection_string
      - audit_event_hub_connection_string
      - nhsapp_apim_pfx
      - nhsapp_apim_pfx_passphrase
      - nhsapp_apim_key
      - cosmos_sql_api_connection_string

  cid.local.bitraft.io:
    image: ${CIDAPI_DOCKER_REGISTRY:-local}/nhsonline-backendcidapi:${CIDAPI_DOCKER_TAG:-latest}
    entrypoint:
      - /bin/bash # The service currently expects secrets as env vars but docker-compose only supports files
      - -c        # Therefore we run a script before starting the service to read the file into an env var
      - |
          if [ -f "$$TPP_CERT_PASSPHRASE" ]; then
            export TPP_CERT_PASSPHRASE=$$(<$$TPP_CERT_PASSPHRASE)
          fi
          if [ -f "$$VISION_CERT_PASSPHRASE" ]; then
            export VISION_CERT_PASSPHRASE=$$(<$$VISION_CERT_PASSPHRASE)
          fi
          exec $$*
      - "--"
    command: dotnet NHSOnline.Backend.CidApi.dll
    env_file:
      - ./docker/emis_connectivity.env
      - ./docker/fakegp_connectivity.env
      - ./docker/im1cache_database.env
      - ./docker/session_database.env
      - ./docker/sjr_connectivity.env
      - ./docker/tpp_connectivity.env
      - ./docker/vision_connectivity.env
      - ./docker/proxy_access.env
      - ./docker/cid.env
      - ./docker/health_checks_enabled.env
    depends_on:
      - servicejourneyrulesapi.local.bitraft.io
    secrets:
      - session_encryption_key
      - tpp_cert
      - tpp_cert_passphrase
      - vision_cert
      - vision_cert_passphrase

  servicejourneyrulesapi.config:
    image: ${SJRCONFIG_DOCKER_REGISTRY:-local}/nhsonline-service-journey-dev-config:${SJRCONFIG_DOCKER_TAG:-latest}
    volumes:
      - 'servicejourneyrules_data:/output'

  servicejourneyrulesapi.local.bitraft.io:
    image: ${SJRAPI_DOCKER_REGISTRY:-local}/nhsonline-backendservicejourneyrulesapi:${SJRAPI_DOCKER_TAG:-latest}
    command: dotnet NHSOnline.Backend.ServiceJourneyRulesApi.dll
    env_file:
      - ./docker/sjr.env
      - ./docker/health_checks_enabled.env
    depends_on:
      - servicejourneyrulesapi.config
    volumes:
      - 'servicejourneyrules_data:/app/input'

  users.local.bitraft.io:
    image: ${USERSAPI_DOCKER_REGISTRY:-local}/nhsonline-backendusersapi:${USERSAPI_DOCKER_TAG:-latest}
    entrypoint:
      - /bin/bash # The service currently expects secrets as env vars but docker-compose only supports files
      - -c        # Therefore we run a script before starting the service to read the file into an env var
      - |
          if [ -f "$$AUTH_SIGNING_PASSWORD" ]; then
            export AUTH_SIGNING_PASSWORD=$$(<$$AUTH_SIGNING_PASSWORD)
          fi
          if [ -f "$$NHSAPP_API_KEY" ]; then
            export NHSAPP_API_KEY=$$(<$$NHSAPP_API_KEY)
          fi
          if [ -f "$$AZURE_NOTIFICATION_HUBS__0__AZURE_NOTIFICATION_HUB_SHARED_ACCESS_KEY" ]; then
            export AZURE_NOTIFICATION_HUBS__0__AZURE_NOTIFICATION_HUB_SHARED_ACCESS_KEY=$$(<$$AZURE_NOTIFICATION_HUBS__0__AZURE_NOTIFICATION_HUB_SHARED_ACCESS_KEY)
          fi
          if [ -f "$$COMMS_HUB_EVENT_HUB_PID_CONNECTION_STRING" ]; then
            export COMMS_HUB_EVENT_HUB_PID_CONNECTION_STRING=$$(<$$COMMS_HUB_EVENT_HUB_PID_CONNECTION_STRING)
          fi
          if [ -f "$$COMMS_HUB_EVENT_HUB_CONNECTION_STRING" ]; then
            export COMMS_HUB_EVENT_HUB_CONNECTION_STRING=$$(<$$COMMS_HUB_EVENT_HUB_CONNECTION_STRING)
          fi
          exec $$*
      - "--"
    command: dotnet NHSOnline.Backend.UsersApi.dll
    env_file:
      - ./docker/notificationhub_connectivity.env
      - ./docker/eventhub_connectivity.env
      - ./docker/users.env
      - ./docker/health_checks_enabled.env
    secrets:
      - auth_signing_private_key
      - auth_signing_rsapass
      - azure_notification_hub_key
      - nhsapp_api_key
      - comms_hub_event_hub_pid_connection_string
      - comms_hub_event_hub_connection_string

  userinfo.local.bitraft.io:
    image: ${USERINFOAPI_DOCKER_REGISTRY:-local}/nhsonline-backenduserinfoapi:${USERINFOAPI_DOCKER_TAG:-latest}
    entrypoint:
      - /bin/bash # The service currently expects secrets as env vars but docker-compose only supports files
      - -c        # Therefore we run a script before starting the service to read the file into an env var
      - |
          if [ -f "$$AUTH_SIGNING_PASSWORD" ]; then
            export AUTH_SIGNING_PASSWORD=$$(<$$AUTH_SIGNING_PASSWORD)
          fi
          if [ -f "$$NHSAPP_API_KEY" ]; then
            export NHSAPP_API_KEY=$$(<$$NHSAPP_API_KEY)
          fi
          if [ -f "$$QUALTRICS_API_KEY" ]; then
            export QUALTRICS_API_KEY=$$(<$$QUALTRICS_API_KEY)
          fi
          if [ -f "$$COMMS_HUB_EVENT_HUB_PID_CONNECTION_STRING" ]; then
            export COMMS_HUB_EVENT_HUB_PID_CONNECTION_STRING=$$(<$$COMMS_HUB_EVENT_HUB_PID_CONNECTION_STRING)
          fi
          if [ -f "$$COMMS_HUB_EVENT_HUB_CONNECTION_STRING" ]; then
            export COMMS_HUB_EVENT_HUB_CONNECTION_STRING=$$(<$$COMMS_HUB_EVENT_HUB_CONNECTION_STRING)
          fi
          if [ -f "$$COSMOS_SQL_API_CONNECTION_STRING" ]; then
            export COSMOS_SQL_API_CONNECTION_STRING=$$(<$$COSMOS_SQL_API_CONNECTION_STRING)
          fi
          exec $$*
      - "--"
    command: dotnet NHSOnline.Backend.UserInfoApi.dll
    env_file:
      - ./docker/nhslogin_connectivity_ext.env
      - ./docker/qualtrics_connectivity.env
      - ./docker/eventhub_connectivity.env
      - ./docker/userinfo.env
      - ./docker/health_checks_enabled.env
    secrets:
      - auth_signing_private_key
      - auth_signing_rsapass
      - nhsapp_api_key
      - qualtrics_api_key
      - comms_hub_event_hub_pid_connection_string
      - comms_hub_event_hub_connection_string
      - cosmos_sql_api_connection_string

  mongo_seed:
    image: mongo:latest
    links:
      - mongodb.bitraft.io
    entrypoint:
      - /bin/bash
      - -c
      - |
          sleep 5
          EVAL="db.session.createIndex({_ts:1},{expireAfterSeconds:$${EXPIRE_AFTER_SECONDS:-600}})"
          mongo --host mongodb.bitraft.io --eval "$$EVAL" development
      - "--"
    depends_on:
      - mongodb.bitraft.io

volumes:
  servicejourneyrules_data:
    driver: local
