//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHSOnline.Backend.Worker.GpSystems.Suppliers.Tpp {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TppApiErrorMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TppApiErrorMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("NHSOnline.Backend.Worker.GpSystems.Suppliers.Tpp.TppApiErrorMessages", typeof(TppApiErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Prescriptions_CourseAlreadyOrdered_IsUnavailable {
            get {
                return ResourceManager.GetString("Prescriptions_CourseAlreadyOrdered_IsUnavailable", resourceCulture);
            }
        }
        
        public static string Prescriptions_InvalidCourseIds {
            get {
                return ResourceManager.GetString("Prescriptions_InvalidCourseIds", resourceCulture);
            }
        }
        
        public static string Prescriptions_MustViewMedicationsListFirst {
            get {
                return ResourceManager.GetString("Prescriptions_MustViewMedicationsListFirst", resourceCulture);
            }
        }
        
        public static string Prescriptions_RequestNoteTooLarge {
            get {
                return ResourceManager.GetString("Prescriptions_RequestNoteTooLarge", resourceCulture);
            }
        }
    }
}
