#! /usr/bin/bash

export DOCKER_COMPOSE_FILES_TRANCHE=()

export DOCKER_PROJECT_NAME="${DOCKER_PROJECT_NAME:-int_test}"
export DOCKER_NETWORK="${DOCKER_PROJECT_NAME}_default"

export DOCKER_REGISTRY=${DOCKER_REGISTRY:-local}
export DOCKER_TAG=${DOCKER_TAG:-latest}

export DOCKER_IMAGE_DOTNET_BUILD=${DOCKER_IMAGE_DOTNET_BUILD:-nhsapp.azurecr.io/nhsonline-dotnetcore-build:3.1}
export DOCKER_IMAGE_BROWSERSTACK_LOCAL=${DOCKER_IMAGE_BROWSERSTACK_LOCAL:-nhsapp.azurecr.io/nhsonline-browserstack-local:latest}

export NATIVE_APP_PATH_ANDROID=${NATIVE_APP_PATH_ANDROID:-com.nhs.online.nhsonline.browserstack.apk}
export NATIVE_APP_PATH_IOS=${NATIVE_APP_PATH_IOS:-NHSOnline.App.BrowserStack.ipa}

export WEB_DOCKER_TAG=${WEB_DOCKER_TAG:-$DOCKER_TAG}
export WEB_DOCKER_REGISTRY=${WEB_DOCKER_REGISTRY:-$DOCKER_REGISTRY}
export PFSAPI_DOCKER_TAG=${PFSAPI_DOCKER_TAG:-$DOCKER_TAG}
export PFSAPI_DOCKER_REGISTRY=${PFSAPI_DOCKER_REGISTRY:-$DOCKER_REGISTRY}
export CIDAPI_DOCKER_TAG=${CIDAPI_DOCKER_TAG:-$DOCKER_TAG}
export CIDAPI_DOCKER_REGISTRY=${CIDAPI_DOCKER_REGISTRY:-$DOCKER_REGISTRY}
export SJRCONFIG_DOCKER_TAG=${SJRCONFIG_DOCKER_TAG:-$DOCKER_TAG}
export SJRCONFIG_DOCKER_REGISTRY=${SJRCONFIG_DOCKER_REGISTRY:-$DOCKER_REGISTRY}
export SJRAPI_DOCKER_TAG=${SJRAPI_DOCKER_TAG:-$DOCKER_TAG}
export SJRAPI_DOCKER_REGISTRY=${SJRAPI_DOCKER_REGISTRY:-$DOCKER_REGISTRY}
export USERSAPI_DOCKER_TAG=${USERSAPI_DOCKER_TAG:-$DOCKER_TAG}
export USERSAPI_DOCKER_REGISTRY=${USERSAPI_DOCKER_REGISTRY:-$DOCKER_REGISTRY}
export USERINFOAPI_DOCKER_TAG=${USERINFOAPI_DOCKER_TAG:-$DOCKER_TAG}
export USERINFOAPI_DOCKER_REGISTRY=${USERINFOAPI_DOCKER_REGISTRY:-$DOCKER_REGISTRY}
export LOGAPI_DOCKER_TAG=${LOGAPI_DOCKER_TAG:-$DOCKER_TAG}
export LOGAPI_DOCKER_REGISTRY=${LOGAPI_DOCKER_REGISTRY:-$DOCKER_REGISTRY}
export MESSAGESAPI_DOCKER_TAG=${MESSAGESAPI_DOCKER_TAG:-$DOCKER_TAG}
export MESSAGESAPI_DOCKER_REGISTRY=${MESSAGESAPI_DOCKER_REGISTRY:-$DOCKER_REGISTRY}
