export const ANSWERING_DEMOGRAPHICS_NAME = 'ANSWERING_CONSENT_QUESTION';
export const DEMOGRAPHICS_QUESTION_NAME = 'NHSAPP_DEMOGRAPHICS_CONSENT';
export const DEMOGRAPHICS_QUESTION_OPTION = 'NHSAPP_DEMOGRAPHICS_CONSENT_GIVEN';
