# This is an OpenAPI Specification (https://swagger.io/specification/)
# describing a realtime receipt callback endpoint that suppliers integrating with the NHS App API's Realtime Receipts functionality should create.
# This example spec is owned by NHS Digital (https://digital.nhs.uk/).

openapi: "3.0.0"
info:
  version: "1.0.0"
  title: NHS App API
  description: |
    NHS app has a range of APIs that allows you to syndicate content from various partners. To implement the API will take some technical knowledge.
paths:
  /FHIR/R4/CommunicationRequest:
    post:
      summary: |
        Keyword reply is a messaging option in NHS App that allows a sender to send messages to their patients and include a fixed set of reply option(s). Patients can only reply to the messages by selecting only one option as a response.
      operationId: This is a unique string used to identify an operation. These IDs must be unique among all operations described in NHS API.
      description: |
        In this pattern, you authenticate your application by sending a signed JSON Web Token (JWT) to our OAuth 2.0 authorisation server. You provide us with your public key and sign the JWT with your private key. In return, we give you an access token, which you then include with each API request.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: components/schemas/requests/communicationrequest.yaml
            examples:
              completed:
                summary: A request to send a message reply communication was completed.
                value:
                  $ref: components/examples/responses/completed.json
      responses:
        "202":
          description: The receipt has been successfully accepted.
        "400":
          description: There is an error in the structure of the request.
        "401":
          description: Authorisation issue, for example the client certificate cannot be verified.