import {
  APPOINTMENTS_PATH,
  INDEX_PATH,
  HEALTH_RECORDS_PATH,
  MESSAGES_PATH,
  GP_MESSAGES_PATH,
  PRESCRIPTIONS_PATH,
  MORE_PATH,
  MORE_ACCOUNTANDSETTINGS_LEGALANDCOOKIES_PATH,
  MORE_ACCOUNTANDSETTINGS_PATH,
  PRESCRIPTION_TYPE_PATH,
  CHOOSE_TEST_RESULT_YEAR_PATH,
  GP_MEDICAL_RECORD_PATH,
  TESTRESULTS_V2_PATH,
} from '@/router/paths';
import {
  GP_APPOINTMENTS_NAME,
  APPOINTMENT_BOOKING_SUCCESS_NAME,
  APPOINTMENT_CANCELLING_SUCCESS_NAME,
  LINKED_PROFILES_SHUTTER_APPOINTMENTS_NAME,
  LINKED_PROFILES_SHUTTER_PRESCRIPTIONS_NAME,
  ORGAN_DONATION_NAME,
  ORGAN_DONATION_VIEW_DECISION_NAME,
  PRESCRIPTION_REPEAT_COURSES_NAME,
  PRESCRIPTION_TYPE_NAME,
  PRESCRIPTIONS_VIEW_ORDERS_NAME,
  GP_MESSAGES_NAME,
  GP_MESSAGES_URGENCY_NAME,
  GP_MESSAGES_VIEW_MESSAGE_NAME,
  SWITCH_PROFILE_NAME,
  LINKED_PROFILES_NAME,
  MORE_ACCOUNTANDSETTINGS_LEGALANDCOOKIES_MANAGECOOKIES_NAME,
  MORE_ACCOUNTANDSETTINGS_LEGALANDCOOKIES_NAME,
  MORE_ACCOUNTANDSETTINGS_NAME,
  NOMINATED_PHARMACY_CHECK_NAME,
  CHOOSE_TEST_RESULT_YEAR_NAME,
  TEST_RESULTS_FOR_YEAR_NAME,
  TESTRESULTS_V2_NAME,
  GP_MEDICAL_RECORD_NAME,
} from '@/router/names';

/**
 * Overrides for the back link on native
 *
 * For these routes, when clicking the back nav on native, the defaultPath will be used if
 * there is no state.navigation.backLinkOverride path set in the store. If this value is
 * to be ignored and the default path is to always be used, be sure to set ignoreStore: true
 */
export default {
  [MORE_ACCOUNTANDSETTINGS_LEGALANDCOOKIES_MANAGECOOKIES_NAME]: {
    ignoreStore: true,
    defaultPath: MORE_ACCOUNTANDSETTINGS_LEGALANDCOOKIES_PATH,
  },
  [MORE_ACCOUNTANDSETTINGS_LEGALANDCOOKIES_NAME]: {
    ignoreStore: true,
    defaultPath: MORE_ACCOUNTANDSETTINGS_PATH,
  },
  [MORE_ACCOUNTANDSETTINGS_NAME]: {
    ignoreStore: true,
    defaultPath: MORE_PATH,
  },
  [APPOINTMENT_BOOKING_SUCCESS_NAME]: {
    ignoreStore: true,
    defaultPath: APPOINTMENTS_PATH,
  },
  [GP_APPOINTMENTS_NAME]: {
    ignoreStore: true,
    defaultPath: APPOINTMENTS_PATH,
  },
  [APPOINTMENT_CANCELLING_SUCCESS_NAME]: {
    ignoreStore: true,
    defaultPath: APPOINTMENTS_PATH,
  },
  [LINKED_PROFILES_NAME]: {
    defaultPath: MORE_PATH,
  },
  [LINKED_PROFILES_SHUTTER_APPOINTMENTS_NAME]: {
    ignoreStore: true,
    defaultPath: APPOINTMENTS_PATH,
  },
  [LINKED_PROFILES_SHUTTER_PRESCRIPTIONS_NAME]: {
    ignoreStore: true,
    defaultPath: INDEX_PATH,
  },
  [NOMINATED_PHARMACY_CHECK_NAME]: {
    ignoreStore: true,
    defaultPath: PRESCRIPTION_TYPE_PATH,
  },
  [ORGAN_DONATION_NAME]: {
    defaultPath: HEALTH_RECORDS_PATH,
  },
  [ORGAN_DONATION_VIEW_DECISION_NAME]: {
    defaultPath: HEALTH_RECORDS_PATH,
  },
  [PRESCRIPTION_REPEAT_COURSES_NAME]: {
    defaultPath: PRESCRIPTION_TYPE_PATH,
  },
  [PRESCRIPTION_TYPE_NAME]: {
    ignoreStore: true,
    defaultPath: PRESCRIPTIONS_PATH,
  },
  [PRESCRIPTIONS_VIEW_ORDERS_NAME]: {
    ignoreStore: true,
    defaultPath: PRESCRIPTIONS_PATH,
  },
  [GP_MESSAGES_NAME]: {
    ignoreStore: true,
    defaultPath: MESSAGES_PATH,
  },
  [GP_MESSAGES_URGENCY_NAME]: {
    defaultPath: GP_MESSAGES_PATH,
  },
  [GP_MESSAGES_VIEW_MESSAGE_NAME]: {
    ignoreStore: true,
    defaultPath: GP_MESSAGES_PATH,
  },
  [SWITCH_PROFILE_NAME]: {
    ignoreStore: true,
    defaultPath: INDEX_PATH,
  },
  [CHOOSE_TEST_RESULT_YEAR_NAME]: {
    ignoreStore: true,
    defaultPath: TESTRESULTS_V2_PATH,
  },
  [TEST_RESULTS_FOR_YEAR_NAME]: {
    ignoreStore: true,
    defaultPath: CHOOSE_TEST_RESULT_YEAR_PATH,
  },
  [TESTRESULTS_V2_NAME]: {
    ignoreStore: true,
    defaultPath: GP_MEDICAL_RECORD_PATH,
  },
  [GP_MEDICAL_RECORD_NAME]: {
    ignoreStore: false,
    defaultPath: INDEX_PATH,
  },
};
