version: "3.2"
services:
  stubs.local.bitraft.io:
    image: rodolpheche/wiremock
    command: --local-response-templating
    ports:
      - "8080:8080"
  data.stubs.local.bitraft.io:
    image: nhsonline.stubs.data
    depends_on:
      - stubs.local.bitraft.io
    environment:
      - wiremockUrl=http://stubs.local.bitraft.io:8080
  nhsonline.redis-data.sds:
    image: nhsapp.azurecr.io/nhsonline-redis-data:latest
    environment:
      - MODE=development
      - REDIS_HOST=nhsonline.redis.sds
    depends_on:
      - nhsonline.redis.sds
  nhsonline.redis.sds:
    image: bitnami/redis:4.0.8-r7
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
    volumes:
      - 'redis_data:/bitnami/redis'
  nhsonline.redis.session:
    image: bitnami/redis:4.0.8-r7
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6380:6379"
volumes:
  redis_data:
    driver: local
