version: "3.2"
services:
  servicejourneyrulesapi.config:
    image: nhsonline-service-journey-dev-config
    build:
      context: .
      dockerfile: configurations/Dockerfile
    volumes:
      - 'servicejourneyrules_data:/output'
  servicejourneyrulesapi.local.bitraft.io:
    image: nhsonline.backend.servicejourneyrulesapi
    build:
      context: .
      dockerfile: NHSOnline.Backend.ServiceJourneyRulesApi/Dockerfile
    environment:
      - INPUT_FOLDER_PATH=/app/input
    ports:
      - "8086:8086"
    depends_on:
      - servicejourneyrulesapi.config
    volumes:
      - 'servicejourneyrules_data:/app/input'
  nhsonline.mongodb:
    image: mongo:latest
    ports:
    - "27017:27017"
  stubs.local.bitraft.io:
    image: rodolpheche/wiremock
    command: --local-response-templating
    ports:
      - "8080:8080"
  mongo_seed:
    image: mongo:latest
    links:
      - nhsonline.mongodb
    command: /bin/bash -c "sleep 5; mongo --host nhsonline.mongodb --eval 'db.session.createIndex({_ts:1},{expireAfterSeconds:600})' development"
    depends_on:
      - nhsonline.mongodb
volumes:
  servicejourneyrules_data:
    driver: local