version: "3.2"
services:
  nhsonline.mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  userinfo.local.bitraft.io:
    image: nhsonline.backend.userinfoapi
    build:
      context: .
      dockerfile: NHSOnline.Backend.UserInfoApi/Dockerfile
    ports:
      - "8091:8091"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8091
      - PORT=8091
      - CORS_AUTHORITY=*
      - VERSION_TAG=userinfo_docker_main
      - USERINFO_MONGO_DATABASE_HOST=nhsonline.mongodb
      - USERINFO_MONGO_DATABASE_PORT=27017
      - USERINFO_MONGO_DATABASE_USERNAME=
      - USERINFO_MONGO_DATABASE_PASSWORD=
