version: "3.2"
services:
  nhsonline.mongodb:
    image: mongo:latest
    ports:
    - "27017:27017"
  stubs.local.bitraft.io:
    image: rodolpheche/wiremock
    command: --local-response-templating
    ports:
      - "8080:8080"
  nhsonline.redis-data.sds:
    image: nhsapp.azurecr.io/nhsonline-redis-data:latest
    environment:
      - MODE=development
      - REDIS_HOST=nhsonline.redis.sds
    depends_on:
      - nhsonline.redis.sds
  nhsonline.redis.sds:
    image: bitnami/redis:4.0.8-r7
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
    volumes:
      - 'redis_data:/bitnami/redis'
  mongo_seed:
    image: mongo:latest
    links:
      - nhsonline.mongodb
    command: /bin/bash -c "sleep 5; mongo --host nhsonline.mongodb --eval 'db.session.createIndex({_ts:1},{expireAfterSeconds:600})' development"
    depends_on:
      - nhsonline.mongodb
volumes:
  redis_data:
    driver: local
