export const CLEAR = 'CLEAR';
export const HIDE_EXPIRY_MESSAGE = 'HIDE_EXPIRY_MESSAGE';
export const SET_DURATION_SECONDS = 'SET_DURATION_SECONDS';
export const SET_LAST_CALLED_AT = 'SET_LAST_CALLED_AT';
export const SHOW_EXPIRY_MESSAGE = 'SHOW_EXPIRY_MESSAGE';
