CREATE TABLE IF NOT EXISTS "compute"."DailyUsage"(
"Date" date NOT NULL UNIQUE,
"P5NewAppUsers" int,
"AcceptedTermsAndConditions" int,
"P9VerifiedNHSAppUsers" int,
"Logins" int,
"UsersLogin" int,
"RecordViews" int,
"UsersRecordViews" int,
"Prescriptions" int,
"UsersPrescriptions" int,
"ODRegistrations" int,
"UsersODRegistrations" int,
"NomPharmacy" int,
"UsersNomPharmacy" int,
"AppointmentsBooked" int,
"UsersAppointmentsBooked" int,
"ODWithdrawals" int,
"UsersODWithdrawals" int,
"ODUpdates" int,
"UsersODUpdates" int,
"ODLookups" int,
"UsersODLookups" int,
"AppointmentsCancelled" int DEFAULT 0,
"UsersAppointmentsCancelled" int DEFAULT 0,
"RecordViewsDCR" INT DEFAULT 0,
"UsersRecordViewsDCR" INT DEFAULT 0,
"RecordViewsSCR" INT DEFAULT 0,
"UsersRecordViewsSCR" INT DEFAULT 0);

CALL perms.apply_compute_table_permissions('compute', 'DailyUsage');