name: ${{ parameters.namespace }}-$(Build.SourceBranchName)-$(Date:yyyyMMdd)_$(Rev:r)

trigger: none

pool:
  vmImage: 'ubuntu-18.04'

parameters:
- name: namespace
  displayName: Namespace
  type: string
  default: loadtest
  values:
    - loadtest
- name: imageVersionOverride
  displayName: "Optional image version override (develop or tag)"
  type: string
  default: "develop"
- name: ukSouthClusters
  displayName: UK South Clusters
  type: object
  default:
    - loadtestuks1

variables:
- name: environment
  value: loadtest
- name: cosmosDBName
  value: stubbed
- name: helmVersion
  value: 3.2.3
- group: Ops

stages:
- stage: deployNhsAppUKSouth
  displayName: 'UK South - Deploy NHS App'
  dependsOn:
  jobs:
  - ${{ each AKS_SHORTNAME in parameters.ukSouthClusters }}:
    - job:
      displayName: 'Deploy NHS App to ${{ parameters.namespace }}'
      steps:
      - task: Bash@3
        displayName: Set version
        inputs:
          targetType: 'inline'
          script: |
            if [[ "${{ parameters.imageVersionOverride }}" != "None" ]]; then
              echo "Using version override ${{ parameters.imageVersionOverride }}"
              version=${{ parameters.imageVersionOverride }}
              echo "##vso[task.setvariable variable=version]${{ parameters.imageVersionOverride }}"
              echo "$version"
            elif [ "$(Build.SourceBranchName)" == "develop" ]; then
              echo "Versioning for develop"
              version=$(echo "develop")
              echo "##vso[task.setvariable variable=version]$version"
              echo "$version"
            elif [[ "$(Build.SourceBranchName)" =~ ^v[0-9]+\.[0-9]+ ]]; then
              echo "Versioning for tag $(Build.SourceBranchName)"
              version=$(Build.SourceBranchName)
              echo "##vso[task.setvariable variable=version]$version"
            else
              echo "Versioning for pull request (latest git hash) $(Build.SourceBranch)"
              version=$(az repos pr list --source-branch $(Build.SourceBranch) | jq -r '.[].lastMergeCommit.commitId')
              echo "##vso[task.setvariable variable=version]$version"
              echo "$version"
              echo "##vso[task.logissue type=warning]If you have recently pushed a new change to your pull request branch, your pods may be in a failed state while the NHS App CI pipeline builds the images."
            fi
        env:
          AZURE_DEVOPS_EXT_PAT: $(AZURE_DEVOPS_EXT_PAT)
      - task: Bash@3
        displayName: 'Update chart version'
        inputs:
          workingDirectory: $(System.DefaultWorkingDirectory)/nhsapp-chart/nhsapp/
          targetType: 'inline'
          script: sed -i -e "s|APPVERSION|$appImageTag|g" Chart.yaml
        env:
          chartVersion: $(Build.SourceBranchName)
          appImageTag: ${{ parameters.imageVersionOverride }}
      - task: Bash@3
        displayName: 'Set release name'
        inputs:
          targetType: 'inline'
          script: |
            releaseName=${{ parameters.namespace }}-$(Build.SourceBranchName)

            if [ ${#releaseName} -gt 50 ]; then
              truncatedReleaseName="${releaseName:0:50}-t"
              lowercaseReleaseName=$(echo "$truncatedReleaseName" | tr '[:upper:]' '[:lower:]')
            else
              lowercaseReleaseName=$(echo "$releaseName" | tr '[:upper:]' '[:lower:]')
            fi
            echo $lowercaseReleaseName
            echo "##vso[task.setvariable variable=lowercaseReleaseName]$lowercaseReleaseName"
      - task: AzureCLI@2
        displayName: Get cluster IP
        inputs:
          azureSubscription: nhsapp-nonlive-terraform-sp
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            PUBLIC_IP_ADDRESS=`az network public-ip show --name nhsapp-${{ AKS_SHORTNAME }}_PIP --resource-group nhsapp-${{ AKS_SHORTNAME }}_PIP | jq '.ipAddress' | tr -d '"'`/32
            echo $PUBLIC_IP_ADDRESS
            echo "##vso[task.setvariable variable=clusterIP;]$PUBLIC_IP_ADDRESS"
      - task: AzureCLI@2
        displayName: Get managed identity
        inputs:
          azureSubscription: nhsapp-nonlive-terraform-sp
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            ManagedIdentity=$(az aks show -n nhsapp-${{ AKS_SHORTNAME }} -g nhsapp-${{ AKS_SHORTNAME }} --query identityProfile.kubeletidentity.clientId -o tsv)
            echo $ManagedIdentity
            echo "##vso[task.setvariable variable=managedIdentity;]$ManagedIdentity"
      - task: HelmInstaller@1
        displayName: 'Install Helm'
        inputs:
          helmVersionToInstall: $(helmVersion)
      - task: Kubernetes@1
        displayName: 'Kubernetes Login'
        inputs:
          connectionType: Kubernetes Service Connection
          kubernetesServiceEndpoint: nhsapp-${{ AKS_SHORTNAME }}-${{ parameters.namespace }}
          command: login
      - task: Bash@3
        displayName: 'Uninstall old releases'
        inputs:
          targetType: 'inline'
          script: |
            if [[ $(helm ls -n ${{ parameters.namespace }} --short) ]]; then
              helm ls -n ${{ parameters.namespace }} --short | grep ${{ parameters.namespace }} | xargs -I {} helm delete -n ${{ parameters.namespace }} {} && sleep 10
            else
              echo "No releases to uninstall."
            fi
      - task: HelmDeploy@0
        displayName: Helm Upgrade
        inputs:
          connectionType: Kubernetes Service Connection
          kubernetesServiceEndpoint: nhsapp-${{ AKS_SHORTNAME }}-${{ parameters.namespace }}
          namespace: ${{ parameters.namespace }}
          command: upgrade
          chartType: filepath
          chartPath: $(System.DefaultWorkingDirectory)/nhsapp-chart/nhsapp/
          releaseName: $(lowercaseReleaseName)
          valueFile: $(System.DefaultWorkingDirectory)/nhsapp-chart/vars/cluster/vars-${{ AKS_SHORTNAME }}.yaml
          arguments: --set global.environment="${{ parameters.namespace }}"
                    -f $(System.DefaultWorkingDirectory)/nhsapp-chart/vars/zone/$(environment)/vars-$(environment).yaml
                    -f $(System.DefaultWorkingDirectory)/nhsapp-chart/vars/zone/$(environment)/namespace/vars-$(environment)-${{ parameters.namespace }}.yaml
                    --set appImageTag=${{ parameters.imageVersionOverride }}
                    --set cid.image_tag=${{ parameters.imageVersionOverride }}
                    --set api.image_tag=${{ parameters.imageVersionOverride }}
                    --set web.image_tag=${{ parameters.imageVersionOverride }}
                    --set cdsswiremock.image_tag=${{ parameters.imageVersionOverride }}
                    --set logger.image_tag=${{ parameters.imageVersionOverride }}
                    --set sjr.image_tag=${{ parameters.imageVersionOverride }}
                    --set sjrconfig.image_tag=${{ parameters.imageVersionOverride }}
                    --set stub_loader.image_tag=${{ parameters.imageVersionOverride }}
                    --set wiremock.image_tag=${{ parameters.imageVersionOverride }}
                    --set users.image_tag=${{ parameters.imageVersionOverride }}
                    --set messages.image_tag=${{ parameters.imageVersionOverride }}
                    --set info.image_tag=${{ parameters.imageVersionOverride }}
                    --reset-values
                    --install
                    --set cosmosDBName=$(cosmosDBName)
                    --set region=uksouth
                    --set zone=$(environment)
                    --set clusterIP=$(clusterIP)
                    --set clusterManagedId=$(managedIdentity)
          install: true
          waitForExecution: false
      - task: HelmDeploy@0
        displayName: Deploy/Update Redirector
        inputs:
          connectionType: Kubernetes Service Connection
          kubernetesServiceEndpoint: nhsapp-${{ AKS_SHORTNAME }}-${{ parameters.namespace }}
          namespace: ${{ parameters.namespace }}
          command: upgrade
          chartType: filepath
          chartPath: $(System.DefaultWorkingDirectory)/nhsapp-chart/redirector/
          releaseName: defaultingress
          valueFile: $(System.DefaultWorkingDirectory)/nhsapp-chart/vars/cluster/vars-${{ AKS_SHORTNAME }}.yaml
          arguments: -f $(System.DefaultWorkingDirectory)/nhsapp-chart/vars/zone/$(environment)/vars-$(environment).yaml
                    --set global.environment=$(environment) 
                    --set zone=$(environment) 
                    --set cid.version=${{ parameters.imageVersionOverride }} 
                    --set api.version=${{ parameters.imageVersionOverride }} 
                    --set www.version=${{ parameters.imageVersionOverride }} 
                    --set messages.version=${{ parameters.imageVersionOverride }} 
                    --set users.version=${{ parameters.imageVersionOverride }} 
                    --set info.version=${{ parameters.imageVersionOverride }} 
                    --set logger.version=${{ parameters.imageVersionOverride }} 
                    --namespace $(environment)
                    --reset-values
                    --install
          install: true
          waitForExecution: false
