platform :ios, '9.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://git.nhschoices.net/nhsonline/nhsonline-fido-client-ios-cocoapod.git'

target 'NHSOnline' do
  pod 'FidoClientIOS'
  pod 'SwiftyJSON', '~> 4.0'

  target 'NHSOnlineTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
            config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
        end
    end
end