package mocking.onlineConsultations.configurations

import utils.SerenityHelpers

class DOBQuestionConfiguration: IQuestionConfiguration {
    private val patientDateOfBirth = SerenityHelpers.getPatient().dateOfBirth
    override val request: String = """{
       "resourceType":"Parameters",
       "parameter":[
          {
             "name":"sessionId",
             "valueString":"f8f2c2a2-acd9-425a-b93e-cf9c21bbd512"
          },
          {
             "name":"inputData",
             "resource":{
                "resourceType":"QuestionnaireResponse",
                "questionnaire":{
                   "reference":"Questionnaire/Q_BRP_BRP_AD_1"
                },
                "status":"completed",
                "item":[
                   {
                      "linkId":"Q_BRP_BRP_AD_1",
                      "answer":[
                         {
                            "valueString":"I need medication for my sore throat"
                         }
                      ]
                   }
                ]
             }
          }
       ]
    }"""

    override val response: String = """{
       "resourceType":"GuidanceResponse",
       "contained":[
          {
             "resourceType":"Parameters",
             "id":"outputParams",
             "parameter":[
                {
                   "name":"sessionId",
                   "valueString":"4ea9390f-f6f2-410b-8d46-39b37a6a1753"
                }
             ]
          },
          {
             "resourceType":"Questionnaire",
             "id":"PRE_STD_AD_DOB",
             "status":"active",
             "item":[
                {
                   "linkId":"PRE_STD_AD_DOB_GROUP",
                   "text":"",
                   "type":"group",
                   "item":[
                      {
                         "extension":[
                            {
                               "url":"http://hl7.org/fhir/StructureDefinition/questionnaire-itemControl",
                               "valueCodeableConcept":{
                                  "id":"backButton",
                                  "coding":[
                                     {
                                        "system":"http://hl7.org/fhir/ValueSet/questionnaire-item-control",
                                        "code":"button",
                                        "display":"back"
                                     }
                                  ],
                                  "text":"back"
                               }
                            }
                         ],
                         "linkId":"PRE_STD_AD_DOB_PREV",
                         "text":"",
                         "type":"boolean",
                         "required":false
                      },
                      {
                         "extension":[
                            {
                               "url":"http://hl7.org/fhir/StructureDefinition/minValue",
                               "valueDate":"1894-02-26"
                            },
                            {
                               "url":"http://hl7.org/fhir/StructureDefinition/maxValue",
                               "valueDate":"2002-02-25"
                            },
                            {
                               "url":"http://hl7.org/fhir/StructureDefinition/entryFormat",
                               "valueString":"You must be between 18 and 125 years old in order to 
                                    complete this request"
                            }
                         ],
                         "linkId":"PRE_STD_AD_DOB",
                         "text":"Tell us your date of birth",
                         "type":"date",
                         "required":true
                      }
                   ]
                }
             ]
          },
          {
             "resourceType":"QuestionnaireResponse",
             "questionnaire":{
                "reference":"Questionnaire/PRE_STD_AD_DOB"
             },
             "status":"completed",
             "item":[
                {
                   "linkId":"PRE_STD_AD_DOB",
                   "answer":[
                      {
                         "valueDate":"$patientDateOfBirth"
                      }
                   ]
                }
             ]
          }
       ],
       "module":{
          "reference":"https://stubs.onlineconsultations/fhir/ServiceDefinition/BRP_BRP"
       },
       "status":"data-required",
       "occurrenceDateTime":"2020-02-25T12:38:00.885",
       "outputParameters":{
          "reference":"#outputParams"
       },
       "dataRequirement":[
          {
             "id":"PRE_STD_AD_DOB",
             "extension":[
                {
                   "url":"https://www.hl7.org/fhir/questionnaire.html",
                   "valueReference":{
                      "reference":"#PRE_STD_AD_DOB"
                   }
                }
             ],
             "type":"QuestionnaireResponse",
             "profile":[
                "https://www.hl7.org/fhir/questionnaireresponse.html"
             ]
          }
       ]
    }"""
}