package mocking.onlineConsultations.configurations

class PainOriginQuestionConfiguration:IQuestionConfiguration {
    override val request = """{
       "resourceType":"Parameters",
       "parameter":[
          {
             "name":"sessionId",
             "valueString":"0d7036ed-3c5a-48a8-9927-81dbcf50e6a6"
          },
          {
             "name":"inputData",
             "resource":{
                "resourceType":"QuestionnaireResponse",
                "status":"completed",
                "item":[
                   {
                      "linkId":"Q_GEC_ADM_AD_80",
                      "answer":[
                         {
                            "valueCoding":{
                               "code":"A_GEC_ADM_AD_140"
                            }
                         }
                      ]
                   }
                ],
                "questionnaire":{
                   "reference":"Questionnaire/Q_GEC_ADM_AD_80"
                }
             }
          }
       ]
    }"""

 override val response = """{
       "resourceType":"GuidanceResponse",
       "contained":[
          {
             "resourceType":"Parameters",
             "id":"outputParams",
             "parameter":[
                {
                   "name":"sessionId",
                   "valueString":"1"
                }
             ]
          },
          {
             "resourceType":"Questionnaire",
             "id":"NHS_ADMIN_AD_REFERRALPAINORIGIN",
             "status":"active",
             "item":[
                {
                   "linkId":"NHS_ADMIN_AD_REFERRALPAINORIGIN_GROUP",
                   "type":"group",
                   "item":[
                      {
                         "extension":[
                            {
                               "url":"http://hl7.org/fhir/StructureDefinition/questionnaire-itemControl",
                               "valueCodeableConcept":{
                                  "id":"codeableConcept",
                                  "coding":[
                                     {
                                        "system":"http://hl7.org/fhir/ValueSet/questionnaire-item-control",
                                        "code":"button",
                                        "display":"back"
                                     }
                                  ],
                                  "text":"back"
                               }
                            }
                         ],
                         "linkId":"NHS_ADMIN_AD_REFERRALPAINORIGIN_PREV",
                         "type":"boolean",
                         "required":false
                      },
                      {
                         "linkId":"NHS_ADMIN_AD_REFERRALPAINORIGIN",
                         "text":"Where is the origin of the pain?",
                         "type":"string",
                         "required":false,
                         "repeats":false,
                         "initialAttachment":{
                            "url": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAATYAAACjCAMAAAA3vsLfAAAAjVB
                            MVEUaXrb///8AWLT3+v12l80ATrEAUbHV3+/v9PoAUrIAVrMAVLMVXLUATLAPWrUdYLfP2u3H0uje5vPm7Pa8y+
                            WUrNeit9xSfsO4yORwksvy
                            9vtdhcaDoNF8m89Gd8AvaruvweBnjMmasdkzbLxLecGKpdMAQq0ASK+Urdepvd6ftNtgh8Ywa7s/cb1pjsm
                            Nk35kAAAJZ0lEQVR4nO2dbV/iOh
                            DFedgG2oSCoKKIAq74sF78/h/vAk2gc2Zau7y4qb87/3cLKdJDkpk5SbqdjqIoiqIoiqIoiqIoiqIoiqIoiqI
                            oiqIoiqIoiqIoiqIoiqIoyn+
                            O+/FEUS3v/XDyCLrl993+D6d7n//nsvV+dX88v3oq2wWobBehsl2EynYRKptEfzidXB2ZDKbDPm/QEtn6Awn
                            5nuRW0yYXs0Zckdnd9mFlE5N
                            6jEnS8e5zu562ULa7V8N5W0i3PqNNR/Pi5V5CXk5S6doxbWTe4P3JcpXYjCezed6zxj7cDlsm2zYTGtpr6
                            davLGmU/Tm+OjT02nwuXNqHRu6
                            FvPveMb2a9N/ldrRpl2wv0tfdlxMCN1RhMynETOm12Y1w6QRky7Yl0baJ9NPBBct2yWakhq4nyTandU1Sj
                            OR3uGd7JVx6a6HR3emt6973ou3
                            /WJgx2yHbQJStY6R5vUM6pvtdvPoARWIyFC7FSjKZhXd+JU2+uRuf2rdCtg8rtxRG2syIH4bT+JhfuY8It
                            JHLwhtz+e+z7/PYLtl+yYaC+4ff
                            +jW9Q/shidnJPwXVFiNoFMLGrskA7Zzm0dbI9rsigJ1H0Ykb+oX9OAYxO9mzINsEwkbozJuGqjl3/p3bIF
                            u/amaxa3bvEBF8eraF20iliPAHw
                            0aR4Hw0mtfoF2+FbNgNTuQP7N7pJOaevJjQXRMpU96IEWGRNrVqzfm3aIVs2A3OJNgUJrGQSGEeuxJU646
                            hUZHfLAUFXGZTkxwwxtpe7l88f
                            1QrZPustJjZYMOIUGReU4wIX4JqQxiMRdgQOltmdtv1ZDpbDIfD2eDq9nFn0n35UM6+WyHbuLrtEprCJOZ
                            jxh3msbeCbKyQOIYNlvs4s2SBq
                            H/16NKkVOu1QbZZzZyM+RedxEIdgQMtnXQ5zzAVFD0ZQkzH2Qrj5XpX+kcbZMPsoUwypW3pkAoh4wkG2ki
                            wyNhUYA6FRN/CpaWCq4Y2yCba
                            Hx5vcAQwIrwXL0N3lSNCRyoksKwr5WZtl020PzzU28FJzBfsLCJI1glOBUUjnBWFlKetstWZXJCBQcf0B
                            TtO677iouBUUIQNnPDyzU+RDfqK
                            o1MQnWsgIjj5JkTn5AYbTYTfoWJ8t1G2NekGbkftHTrg6EAL6dkOI4J0pxgy02M3ZsmuWJa1UbZH8hXye+
                            p6kzl6SmXz6RmWtHKPgW1CvhGT
                            zeXcPmilbNT+yG77dBIypRzsTnwLve6zLVYCI4L/Fjh097ql4hJG22RbUCn2mSodTmXDH2YiU6RnzOvmv
                            okQEYqwseY5o0vmFRlvm2SDvpL0I
                            TAG2/sATVWCi4let5GGGc79PmwMpAolT56+6XHxZaP2x2HKgfFU8irBEPeDcYUJjBlxMGJmvpCQd0a6N
                            NvWzXHxZdvwwElnu3MWBqmKH4yLpj
                            Yj+TuhwlxWlCiul8yrg2p82ejPfQyO1OY4J+4YEYp6FZ2NZl8iWCs1PkJuxtIs2QrZoMo8BkdaKDobCn
                            PaM4JtiIl+I85Z9LLGSHB2LFf20W
                            WDCFd4F7QHnjLQF9EQrzY5ayg5K7/rrnfmSZrjostGEyefhNIFwFMeRl2jkJmML9i2XU6iF+Na3fNE6HD
                            RZZtLpRTtgq5TNMWIUCQJ6HU3wp
                            V31ixWtcPcjfgqd3TZQAqxXPI5FqSmPj27KCKUc+g990ltj03e2yYb9KDgZtMtHX6xmNaPoQ/y8qgBuAd
                            ssqpd9ksw+40tG/Sg4K7RQsEnW
                            U+iIY7ORiP4cv96ZaqFcxmsu8aWjdofpxUXLBSOtn9GI4Lfr4Bet3iiC5t0ULU91/Mkq1IO3YHYslGr7
                            Gyu0YLpmGXheC7SEtw003FjAZCj
                            wvqeLnNckQkfmtLuFlm2vmigdXHP5NGPxIhQ3AjbNCMukWIjNscH7l6MOOjBZ48s20CoEcQ3ujiegxfJ
                            nA1piRT3WtZZuNOvRBAO9gJHlg2
                            sstJQoOsyBzF2olmOS6SptETaaK/lidmcb+4sbwCJL9sXuZ+ym0371j7PgogQRg0se5XduTMwYzlxr2W
                            JW55CUxMvsmyrioiAWexeUBy2R
                            QqMS6TiERu213LzjWzdNetvdDUsrmzDqojAdhkkM4gI3hZBU7vREiks9Uuwc7Z0OowrGxRGZDqn85Fd
                            Q43gbUbI++QlUgwb4s4aCtu7bls
                            kG0Q4khzB8ukDnfuDzYhLpGJEaLTXkoIHZiBCx5XtoTIisAkJMn1vM8Li4MmDozRaRwXQvDQtOqqWV0
                            aELiYcgLcZcSyxbYQHGu2sAZgdlZ
                            KcJaps8iJ7oM7sDmkU2zQjmf9sr6UUNgAMNXCQKaps8iJ7haiEkLSz40Cwi/AIblgQwwaAi4hQxUaVDe
                            7Hwkxd43aHkxhwd85KElTstZxI1a
                            uHnfCAkRBVNhoG2UyNyUUJnw6wTTPSKVK2+94XEsvR+FleQp4+sfkBVvpjygblEpupr+Rzfwd8UYnnQM
                            DrLmBhw3tnY+cys7u5gj7ev9pwwx
                            I2dUaVbSCuI5SodA073mZkm2akrRsVYaOYOvNemqw+t7fXk8FgMLm7Xb7YVIjgBj44pmwftRGhW7MCGo
                            rKL/E4EMD2WhZh4xyoXZ5ZmxpjU
                            mt74p4Qlg7GlA3CoGG5u7CLqiAUlXgcSIwIrJDwL//FGgQL0DFlo2FQsHwql0B9UcmOA0leNwsbRc+pO
                            0OCGFb6R5RtSOdzKXfH1CHgU4iL
                            nivgC4mKA9MSln+ziLLBTUu5e8XRv5CqYB3xN88VaL5OmG74h0aU7Vl8MgWholAIn4AhQ/S6MWwUGdi
                            iaWdziVTmRpQNDH4jWT5yoRAqT9z
                            8LT4AAwuJ/Pgq1qlVZJm4HTWibO67iNCt2uvoi0p2HEh8roD8OBo8ySyTJ/eyNRdPNvDTZDdHLhRM8W
                            YjrxvDRu9YSPTf7LeP5XTZ6EtyBu
                            LKhqfOZDdHki0kn7hpRlz9ZGHDb+9af2WmWrp9BpysnquXBePJ9viWlHmV/f1P2urIWzDER/T1V+k25
                            /ABr+dCYvpxv0qMzfLSgHXO5T2bZ
                            PM/VR0tsmyHk+hl5O/XHwr44MFelz7gm0b9wfrmcze2h4cJHB4q0Fs9fd3c1UoWV7ZW0V/MptPBTHow
                            oIjKdhEq20WobBehsl2EynYREWTTJ
                            9hfhv5/CRfq9uOJoZqiKIqiKIqiKIqiKIqiKIqiKIqiKIqiKIqiKIqiKIqiKIqiKP93/gXhqKkPx/M
                            DxQAAAABJRU5ErkJggg=="
                         }
                      }
                   ]
                }
             ]
          }
       ],
       "requestId":"1",
       "module":{
          "reference":"https://stubs.onlineconsultations/fhir/ServiceDefinition/BRP_BRP"
       },
       "status":"data-required",
       "occurrenceDateTime":"2019-05-23T11:18:04.864",
       "outputParameters":{
          "reference":"#outputParams"
       },
       "dataRequirement":[
          {
             "id":"NHS_ADMIN_AD_REFERRALPAINORIGIN",
             "extension":[
                {
                   "url":"https://www.hl7.org/fhir/questionnaire.html",
                   "valueReference":{
                      "reference":"#NHS_ADMIN_AD_REFERRALPAINORIGIN"
                   }
                }
             ],
             "type":"QuestionnaireResponse",
             "profile":[
                "https://www.hl7.org/fhir/questionnaireresponse.html"
             ]
          }
       ]
    }"""
}