package mocking.onlineConsultations.configurations

class QuantityQuestionConfiguration: IQuestionConfiguration {
    override val request: String = """{
       "resourceType":"Parameters",
       "parameter":[
          {
             "name":"sessionId",
             "valueString":"1"
          },
          {
             "name":"inputData",
             "resource":{
                "resourceType":"QuestionnaireResponse",
                "questionnaire":{
                   "reference":"Questionnaire/NHS_ADMIN_AD_REFERRALPAINORIGIN"
                },
                "status":"completed",
                "item":[
                   {
                      "linkId":"NHS_ADMIN_AD_REFERRALPAINORIGIN",
                      "answer":[
                         {
                            "valueString":"Point:155,80"
                         }
                      ]
                   }
                ]
             }
          }
       ]
    }"""

    override val response: String = """{
       "resourceType":"GuidanceResponse",
       "contained":[
          {
             "resourceType":"Parameters",
             "id":"outputParams",
             "parameter":[
                {
                   "name":"sessionId",
                   "valueString":"1"
                }
             ]
          },
          {
             "resourceType":"Questionnaire",
             "id":"NHS_ADMIN_AD_REFERRALPAINDURATION",
             "status":"active",
             "item":[
                {
                   "linkId":"NHS_ADMIN_AD_REFERRALPAINDURATION_GROUP",
                   "type":"group",
                   "item":[
                      {
                         "extension":[
                            {
                               "url":"http://hl7.org/fhir/StructureDefinition/questionnaire-itemControl",
                               "valueCodeableConcept":{
                                  "id":"codeableConcept",
                                  "coding":[
                                     {
                                        "system":"http://hl7.org/fhir/ValueSet/questionnaire-item-control",
                                        "code":"button",
                                        "display":"back"
                                     }
                                  ],
                                  "text":"back"
                               }
                            }
                         ],
                         "linkId":"NHS_ADMIN_AD_REFERRALPAINDURATION_PREV",
                         "type":"boolean",
                         "required":false
                      },
                      {
                         "linkId":"NHS_ADMIN_AD_REFERRALPAINDURATION",
                         "text":"How long does the pain persist for once felt?",
                         "type":"quantity",
                         "required":false,
                         "repeats":false,
                         "extension":[
                            {
                               "url":"http://hl7.org/fhir/StructureDefinition/questionnaire-unit",
                               "valueCoding":{
                                  "system":"http://unitsofmeasure.org",
                                  "code":"m",
                                  "display":"mins"
                               }
                            }
                         ]
                      }
                   ]
                }
             ]
          }
       ],
       "requestId":"1",
       "module":{
          "reference":"https://stubs.onlineconsultations/fhir/ServiceDefinition/BRP_BRP"
       },
       "status":"data-required",
       "occurrenceDateTime":"2019-05-23T11:18:04.864",
       "outputParameters":{
          "reference":"#outputParams"
       },
       "dataRequirement":[
          {
             "id":"NHS_ADMIN_AD_REFERRALPAINDURATION",
             "extension":[
                {
                   "url":"https://www.hl7.org/fhir/questionnaire.html",
                   "valueReference":{
                      "reference":"#NHS_ADMIN_AD_REFERRALPAINDURATION"
                   }
                }
             ],
             "type":"QuestionnaireResponse",
             "profile":[
                "https://www.hl7.org/fhir/questionnaireresponse.html"
             ]
          }
       ]
    }"""
}