#! /usr/bin/env bash

function generate_host_settings() {
  local IMAGE
  local DOCKER_TAG
  local LAUNCH_SETTINGS_VAR_NAME
  local LAUNCH_SETTINGS

  for IMAGE in "${IMAGE_SETTING_NAMES[@]}"; do
    DOCKER_TAG=${!IMAGE}

    if [ "$DOCKER_TAG" == "host" ]; then
      LAUNCH_SETTINGS_VAR_NAME="${IMAGE}_LAUNCH_SETTINGS"
      LAUNCH_SETTINGS=${!LAUNCH_SETTINGS_VAR_NAME}

      if [ -n "$LAUNCH_SETTINGS" ]; then
        generate_launch_settings "$IMAGE" "$LAUNCH_SETTINGS"
      fi
    fi
  done
}

function generate_launch_settings() {
  local IMAGE=$1
  local LAUNCH_SETTINGS="$REPO_ROOT/$2"

  echo "Generating $IMAGE launch settings ($LAUNCH_SETTINGS)"

  if [ -z "$DOCKER_COMPOSE_FILES_ARGS" ]; then
    echo "DOCKER_COMPOSE_FILES_ARGS array must be set in order to generate launch settings"
    exit 1
  fi

  local SERVICE_NAME_VAR_NAME="${IMAGE}_SERVICE_NAME"
  local SERVICE_NAME_DECLARATION="  ${!SERVICE_NAME_VAR_NAME}:"

  local IN_SERVICE=0
  local IN_ENVIRONMENT=0
  local ENVIRONMENT_INDENT=0

  local SECRET_NAME_REGEX='^  (.*):$'
  local SECRET_FILE_REGEX='^    file: (.*)$'

  local SED_SCRIPT
  SED_SCRIPT=$(mktemp)
  {
    # Remove quotes from values
    echo "s/: '\(.*\)'$/: \1/";
    echo 's/: "\(.*\)"$/: \1/'

    # Add quotes around key and value
    echo 's/^[[:space:]]*\(.*\): \(.*\)$/        "\1": "\2"/'

    # Use localhost for mongo connections
    echo 's/nhsonline\.mongodb/127.0.0.1/'

    echo "s#/app/bddcerts#$REPO_ROOT/bddtests/src/main/kotlin/mocking/dummycerts#"
  } >> "$SED_SCRIPT"

  local IFS=$'\n'
  LINES=()
  for LINE in $(docker-compose "${DOCKER_COMPOSE_FILES_ARGS[@]}" config | tr -d '\r'); do

    # Parse secrets from config yaml.
    # Expected format:
    # secrets:
    #   secret-name:
    #     file: /absolute/host/path/to/secret/file
    #
    # Secrets are mounted in docker under /run/secrets/secret-name so setup a sed replacement
    # command for each secret to replace this path with the absolute host system path.
    if [[ "$LINE" =~ ^secrets: ]]; then
      IN_SECRETS=1
    elif [ "$IN_SECRETS" == "1" ] && [[ "$LINE" =~ $SECRET_NAME_REGEX ]]; then
      SECRET_NAME=${BASH_REMATCH[1]}
    elif [ "$IN_SECRETS" == "1" ] && [[ "$LINE" =~ $SECRET_FILE_REGEX ]]; then
      SECRET_VALUE=${BASH_REMATCH[1]}
      if [[ "$SECRET_VALUE" =~ password$ ]] || [[ "$SECRET_VALUE" =~ azure_notification_hub_key$ ]]; then
        SECRET_VALUE=$(<"$SECRET_VALUE")
      fi
      echo "s#\"/run/secrets/$SECRET_NAME\"\$#\"${SECRET_VALUE//\\//}\"#" >> "$SED_SCRIPT"
    elif [ "$IN_SECRETS" == "1" ]; then
      IN_SECRETS=0
    fi

    # Parse environment section for target service.
    # Expected format:
    #   service-name:
    #     ...
    #     environment:
    #       KEY1: VALUE1
    #       KEY2: "VALUE2"
    #       KEY3: 'VALUE3'
    #
    # Detect the end of the environment section by indentation change.
    if [ "$LINE" == "$SERVICE_NAME_DECLARATION" ]; then
      IN_SERVICE=1
    elif [ "$IN_SERVICE" == "1" ] && [[ $LINE =~ environment: ]]; then
      IN_ENVIRONMENT=1
    elif [ "$IN_SERVICE" == "1" ] && [ "$IN_ENVIRONMENT" == "1" ]; then
      INDENT=$(echo "$LINE" | sed -e 's/^\([[:space:]]*\).*$/\1/' | wc -c)
      if [ $ENVIRONMENT_INDENT == 0 ]; then
        ENVIRONMENT_INDENT=$INDENT
      fi

      if [ "$ENVIRONMENT_INDENT" == "$INDENT" ]; then
        LAST_LINE=$(echo "$LINE" | sed -f "$SED_SCRIPT")
        LINES+=("$LAST_LINE")
      else
        IN_ENVIRONMENT=0
        IN_SERVICE=0
      fi
    fi
  done

  rm "$SED_SCRIPT"

  echo '/*
 *               *************
 *               ** WARNING **
 *               *************
 *
 * This file was automatically generated by '"${BASH_SOURCE[0]}"'
 * Any changes will be lost when it is regenerated
 *
 */
{
  "profiles": {
    "'"$IMAGE"'": {
      "commandName": "Project",
      "launchBrowser": false,
      "environmentVariables": {' > "$LAUNCH_SETTINGS"
  for LINE in "${LINES[@]}"; do
    if [ "$LINE" == "$LAST_LINE" ]; then
      echo "$LINE" >> "$LAUNCH_SETTINGS"
    else
      echo "$LINE," >> "$LAUNCH_SETTINGS"
    fi
  done
  echo '      }
    }
  }
}' >> "$LAUNCH_SETTINGS"
}
