export const ADD_API_ERROR = 'ADD_API_ERROR';
export const SET_API_ERROR_BUTTON_PATH = 'SET_API_ERROR_BUTTON_PATH';
export const DISABLE_API_ERROR = 'DISABLE_API_ERROR';
export const CLEAR_ALL_API_ERRORS = 'CLEAR_ALL_API_ERRORS';
export const SET_CONNECTION_PROBLEM = 'SET_CONNECTION_PROBLEM';
