---
apiVersion: v1
kind: Service
metadata:
  name: cold-messages
  namespace: {{ .Values.global.environment }}
  labels:
    role: cold-messages
    releaseVersion: {{ default "develop" .Values.messages.targetAppVersion }}
spec:
  type: ExternalName
  externalName: {{ template "nhsapp.name" . }}-messages-{{ $.Values.messages.targetAppVersion | replace "." "-" }}.{{ .Values.zone }}.svc.cluster.local
  ports:
    - port: {{ .Values.defaultServicePort }}
      targetPort: {{ .Values.sidecar_proxy.containerPort }}
