---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'false'
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  name: cold-users
  namespace: {{ $.Values.global.environment }}
  labels:
    role: cold-users
    releaseVersion: {{ default "develop" .Values.users.targetAppVersion }}
spec:
  rules:
    - host: api-cold.{{ .Values.zone }}.{{ .Values.domain }}
      http:
        paths:
          - backend:
              serviceName: cold-users
              servicePort: {{ $.Values.defaultServicePort }}
            path: /v[1,2]/api/users
  tls:
    - hosts:
        - api-cold.{{ .Values.zone }}.{{ .Values.domain }}
      secretName: {{ $.Values.zone }}-{{ $.Values.domain | replace "." "-" }}
