server {
  listen      444 http2 ssl;
  server_name 0.0.0.0;

  ssl_certificate     /etc/ssl/local-development-https.crt;
  ssl_certificate_key /etc/ssl/key.pem;

  location / {
    proxy_pass          http://api.local.bitraft.io:8082/;
    proxy_redirect      off;
  }

  location /v1/api/users {
    proxy_pass http://users.local.bitraft.io:8083/api/users;
    proxy_redirect      off;
  }

  location /v1/api/log {
    proxy_pass http://log.local.bitraft.io:8090/v1/api/log;
    proxy_redirect off;
  }
}
