version: "3.4"

services:

  pfs.local.bitraft.io:
    env_file:
      - ./docker/bddtests/env/pfs_browserstack.env

  mongo_seed:
    env_file:
      - ./docker/bddtests/env/mongo_seed_browserstack.env

  browserstack.local:
    image: ${DOCKER_IMAGE_BROWSERSTACK_LOCAL}
    restart: always
    entrypoint:
      - /bin/bash
      - -c
      - |
        BrowserStackLocal --key "$$BROWSERSTACK_ACCESS_KEY" --force-local --local-identifier "$$BROWSERSTACK_LOCAL_IDENTIFIER" --verbose 2
    environment:
      BROWSERSTACK_ACCESS_KEY: "${BROWSERSTACK_ACCESS_KEY}"
      BROWSERSTACK_LOCAL_IDENTIFIER: "${BROWSERSTACK_LOCAL_IDENTIFIER}"
