version: "3.4"

secrets:
  tpp_cert:
    file: "./bddtests/dummysecrets/tpp_client_cert.pfx"
  tpp_cert_password:
    file: "./bddtests/dummysecrets/tpp_client_cert.password"
  session_encryption_key:
    file: "./bddtests/dummysecrets/session_encryption_key"
  microtest_cert:
    file: "./bddtests/dummysecrets/microtest_client_cert.pfx"
  microtest_cert_password:
    file: "./bddtests/dummysecrets/microtest_client_cert.password"
  nhslogin_ext_private_key:
    file: "./bddtests/dummysecrets/nhslogin_ext_private_key.pem"
  nhslogin_ext_rsapass:
    file: "./bddtests/dummysecrets/nhslogin_ext_rsapass.password"
  organ_donation_cert:
    file: "./bddtests/dummysecrets/organ_donation_cert.pfx"
  organ_donation_cert_password:
    file: "./bddtests/dummysecrets/organ_donation_cert.password"
  spine_cert:
    file: "./bddtests/dummysecrets/spine_client_cert.pfx"
  spine_cert_password:
    file: "./bddtests/dummysecrets/spine_client_cert.password"
  azure_notification_hub_key:
    file: "~/.nhsonline/secrets/azure_notification_hub_key_bdd"
  gp_lookup_api_key:
    file: "./bddtests/dummysecrets/gp_lookup_api_key"

services:

  web.local.bitraft.io:
    env_file:
     - ./docker/bddtests/env/web.env

  pfs.local.bitraft.io:
    env_file:
      - ./docker/bddtests/env/emis_connectivity.env
      - ./docker/bddtests/env/gplookup_connectivity.env
      - ./docker/bddtests/env/microtest_connectivity.env
      - ./docker/bddtests/env/nhslogin_connectivity.env
      - ./docker/bddtests/env/onlineconsultationsproviders_connectivity.env
      - ./docker/bddtests/env/organdonation_connectivity.env
      - ./docker/bddtests/env/session_database.env
      - ./docker/bddtests/env/spine_connectivity.env
      - ./docker/bddtests/env/tpp_connectivity.env
      - ./docker/bddtests/env/vision_connectivity.env
      - ./docker/bddtests/env/proxy_access.env
      - ./docker/bddtests/env/pfs.env
    volumes:
      - ./bddtests/src/main/kotlin/mocking/dummycerts:/app/bddcerts

  cid.local.bitraft.io:
    env_file:
      - ./docker/bddtests/env/emis_connectivity.env
      - ./docker/bddtests/env/microtest_connectivity.env
      - ./docker/bddtests/env/nhslogin_connectivity.env
      - ./docker/bddtests/env/session_database.env
      - ./docker/bddtests/env/tpp_connectivity.env
      - ./docker/bddtests/env/vision_connectivity.env
      - ./docker/bddtests/env/proxy_access.env
    volumes:
      - ./bddtests/src/main/kotlin/mocking/dummycerts:/app/bddcerts

  users.local.bitraft.io:
    env_file:
      - ./docker/bddtests/env/nhslogin_connectivity.env
      - ./docker/bddtests/env/notificationhub_connectivity.env

  userinfo.local.bitraft.io:
    env_file:
      - ./docker/bddtests/env/nhslogin_connectivity.env
    volumes:
      - ./bddtests/src/main/kotlin/mocking/dummycerts:/app/bddcerts

  messages.local.bitraft.io:
    env_file:
      - ./docker/bddtests/env/nhslogin_connectivity.env

  mongo_seed:
    env_file:
      - ./docker/bddtests/env/mongo_seed.env

  stubs.local.bitraft.io:
    image: ${WIREMOCK_DOCKER_REGISTRY:-nhsapp.azurecr.io}/wiremock:${WIREMOCK_DOCKER_TAG:-2.22.0-alpine}
    command: --local-response-templating
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    tty: true

volumes:
  servicejourneyrules_data:
    driver: local
