version: "3.4"

secrets:
  session_encryption_key:
    file: "./docker/bddtests/secrets/session_encryption_key"
  nhsapp_api_key:
    file: "./docker/bddtests/secrets/nhsapp_api_key"
  organ_donation_cert:
    file: "./docker/stubbed/certs/TestCert.pfx"
  organ_donation_cert_password:
    file: "./docker/stubbed/certs/TestCert.password"
  spine_cert:
    file: "./docker/stubbed/certs/TestCert.pfx"
  spine_cert_password:
    file: "./docker/stubbed/certs/TestCert.password"
  azure_notification_hub_key:
    file: "~/.nhsonline/secrets/azure_notification_hub_key_bdd"
  gp_lookup_api_key:
    file: "./docker/bddtests/secrets/gp_lookup_api_key"
  ndop_cert:
    file: "./docker/stubbed/certs/TestCert.pfx"
  ndop_cert_password:
    file: "./docker/stubbed/certs/TestCert.password"

services:

  web.local.bitraft.io:
    env_file:
     - ./docker/bddtests/env/web.env

  pfs.local.bitraft.io:
    env_file:
      - ./docker/bddtests/env/emis_connectivity.env
      - ./docker/bddtests/env/ndop_connectivity.env
      - ./docker/bddtests/env/proxy_access.env
      - ./docker/bddtests/env/pfs.env
    secrets:
      - ndop_cert
      - ndop_cert_password

  cid.local.bitraft.io:
    env_file:
      - ./docker/bddtests/env/emis_connectivity.env
      - ./docker/bddtests/env/proxy_access.env

  users.local.bitraft.io:
    env_file:
      - ./docker/bddtests/env/notificationhub_connectivity.env

  mongo_seed:
    env_file:
      - ./docker/bddtests/env/mongo_seed.env

  stubs.local.bitraft.io:
    image: ${WIREMOCK_DOCKER_REGISTRY:-nhsapp.azurecr.io}/wiremock:${WIREMOCK_DOCKER_TAG:-2.22.0-alpine}
    command: --local-response-templating
    tty: true

volumes:
  servicejourneyrules_data:
    driver: local
