version: "3.4"

services:

  web.local.bitraft.io:
    environment:
      EXPIRE_AFTER_SECONDS: 300

  pfs.local.bitraft.io:
    environment:
      ConfigurationSettings__DefaultSessionExpiryMinutes: 5

  browserstack.local:
    image: ${DOCKER_IMAGE_BROWSERSTACK_LOCAL}
    entrypoint:
      - /bin/bash
      - -c
      - |
        BrowserStackLocal --key "$$BROWSERSTACK_ACCESS_KEY" --force-local --local-identifier "$$BROWSERSTACK_LOCAL_IDENTIFIER" --verbose 2
    environment:
      BROWSERSTACK_ACCESS_KEY: "${BROWSERSTACK_ACCESS_KEY}"
      BROWSERSTACK_LOCAL_IDENTIFIER: "${BROWSERSTACK_LOCAL_IDENTIFIER}"
