//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHSOnline.Backend.Support {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("NHSOnline.Backend.Support.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ConfigurationValueNotFound {
            get {
                return ResourceManager.GetString("ConfigurationValueNotFound", resourceCulture);
            }
        }
        
        public static string ConnectionMultiplexerFactoryUnknownMultiplexerName {
            get {
                return ResourceManager.GetString("ConnectionMultiplexerFactoryUnknownMultiplexerName", resourceCulture);
            }
        }
        
        public static string HttpClientFactoryUnknownClientName {
            get {
                return ResourceManager.GetString("HttpClientFactoryUnknownClientName", resourceCulture);
            }
        }
        
        public static string InvalidLogLevel {
            get {
                return ResourceManager.GetString("InvalidLogLevel", resourceCulture);
            }
        }
        
        public static string NoNhsNumberAvailable {
            get {
                return ResourceManager.GetString("NoNhsNumberAvailable", resourceCulture);
            }
        }
        
        public static string SupplierNotSpecified {
            get {
                return ResourceManager.GetString("SupplierNotSpecified", resourceCulture);
            }
        }
        
        public static string AccessTokenInvalid {
            get {
                return ResourceManager.GetString("AccessTokenInvalid", resourceCulture);
            }
        }
        
        public static string OdsCodeLookupUnknownOdsCode {
            get {
                return ResourceManager.GetString("OdsCodeLookupUnknownOdsCode", resourceCulture);
            }
        }
        
        public static string OdsCodeLookupUnknownSupplierCode {
            get {
                return ResourceManager.GetString("OdsCodeLookupUnknownSupplierCode", resourceCulture);
            }
        }
        
        public static string ConfigurationValueNotValid {
            get {
                return ResourceManager.GetString("ConfigurationValueNotValid", resourceCulture);
            }
        }
        
        public static string ConfigurationValueNotValidWithDetail {
            get {
                return ResourceManager.GetString("ConfigurationValueNotValidWithDetail", resourceCulture);
            }
        }
    }
}
