package mocking.patientPracticeMessaging

import utils.ISerenityHelperEnums

enum class PatientPracticeMessagingSerenityHelpers: ISerenityHelperEnums {
    EXPECTED_MESSAGES,
    EXPECTED_INBOX_MESSAGE_DATES,
    EXPECTED_MESSAGE_SENT_DATE,
    EXPECTED_UNREAD_MESSAGE_REPLY_DATES,
    EXPECTED_READ_MESSAGE_REPLY_DATES,
    SELECTED_MESSAGE,
    AVAILABLE_MESSAGE,
    AVAILABLE_RECIPIENTS,
    SENT_MESSAGE,
    INITIAL_FROM_GP,
    INITIAL_MESSAGE_ID,
    EXPECTED_REPLY_MESSAGE_DATES,
}