//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHSOnline.Backend.GpSystems.Suppliers.Tpp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TppApiErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TppApiErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NHSOnline.Backend.GpSystems.Suppliers.Tpp.TppApiErrorMessages", typeof(TppApiErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the medications requested is no longer available.
        /// </summary>
        public static string Prescriptions_CourseAlreadyOrdered_IsUnavailable {
            get {
                return ResourceManager.GetString("Prescriptions_CourseAlreadyOrdered_IsUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error processing your request.
        /// </summary>
        public static string Prescriptions_InvalidCourseIds {
            get {
                return ResourceManager.GetString("Prescriptions_InvalidCourseIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot request repeat medication until you have seen an up to date medication list.
        /// </summary>
        public static string Prescriptions_MustViewMedicationsListFirst {
            get {
                return ResourceManager.GetString("Prescriptions_MustViewMedicationsListFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The textual request is too long.
        /// </summary>
        public static string Prescriptions_RequestNoteTooLarge {
            get {
                return ResourceManager.GetString("Prescriptions_RequestNoteTooLarge", resourceCulture);
            }
        }
    }
}
