openapi: 3.0.0

info:
  version: 2.0.1
  title: NHS App Middleware for NHS Login.
  description: NHS App Middleware endpoints to allow NHS Login to retrieve and validate linkage details and IM1 Connection Tokens.

paths:
  /v2/patient/im1connection:
    get:
      tags:
        - im1-connection
      summary: Gets an IM1 connection token.
      description: This call returns an IM1 connection token and an array of NHS Numbers,
        given an IM1 Connection Token and ODS Code.
      parameters:
        - in: header
          name: NHSO-Connection-Token
          required: true
          description: IM1 Connection token
          schema:
            type: string
        - in: header
          name: NHSO-ODS-Code
          required: true
          description: ODS code for the Patient's GP.
          schema:
            type: string
      responses:
        "200":
          description: Successful operation. IM1 Connection Token and NHS Numbers returned.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PatientIm1ConnectionResponse"
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiErrorResponse'
          description: |
            Bad Request - Possible errorCodes and errorMessages:
            * 100 - Unknown Error 
            * 106 - Invalid details
            * 108 - Invalid Nhs Number
            * 109 - Invalid Provider Id
            * 110 - Invalid Account Id
            * 111 - Invalid Linkage Key
            * 112 - Problem Logging In
            * 113 - User Record Unavailable
            * 114 - Invalid Security
            * 115 - Invalid Request
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiErrorResponse'
          description: |
            Forbidden - Possible errorCodes and errorMessages:
            * 100 - Unknown Error 
            * 101 - Practice not enabled
            * 102 - Patient Archived or Disabled
            * 104 - Patient under minimum age or non competent
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiErrorResponse'
          description: |
            Not Found - Possible errorCodes and errorMessages:
            * 100 - Unknown Error 
            * 103 - Patient not found
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiErrorResponse'
          description: |
            Conflict - Possible errorCodes and errorMessages:
            * 100 - Unknown Error 
            * 105 - User account conflict
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiErrorResponse'
          description: |
            Unexpected Internal server error - Possible errorCodes and errorMessages:
            * 100 - Unknown Error
        "501":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiErrorResponse'
          description: |
            No GP System found for supplied ODS Code. This could mean either they don't exist, or they're not yet onboarded. - Possible errorCodes and errorMessages:
            * 106 - Invalid details
        "502":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiErrorResponse'
          description: |
            Bad response received from GP System. An example would be that a session could not be established
            * 100 - Unknown Error
            * 107 - Upstream Error
        "504":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiErrorResponse'
          description: |
            Timeout when calling GP System
            * 100 - Unknown Error
    post:
      tags:
        - im1-connection
      summary: Given either linkage details or an NHS Number, creates an IM1 Connection Token
      description: |
        Retrieve a set of linkage keys from the GP System. If none exist then they will be created.

        This will also cause the user to be linked with the NHS App, creating an IM1 Connection Token. This is only available on the first invocation.

        Once a user has been created their IM1 Connection Token cannot be subsequently retrieved.
      parameters:
        - in: header
          name: NHSO-Request-ID
          required: false
          description: A request identifier, NHS Login should provide something unique on each separate request to allow NHS App to easily retrieve relevant log entries for debugging purposes.
          schema:
            type: string
        - in: header
          name: NHSO-NHS-Login-Client
          required: false
          description: An optional identifier for the client of NHS Login that resulted in this request to NHS App.
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/CreateIm1ConnectionWithLinkageDetailsRequest'
                - $ref: '#/components/schemas/CreateIm1ConnectionWithNhsNumberRequest'
        required: true
      responses:
        "201":
          description: IM1 Connection Token successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateIm1ConnectionResponse'
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiErrorResponse'
          description: |            
            Bad Request - Possible errorCodes and errorMessages:
            * 100 - Unknown Error 
            * 106 - Invalid details
            * 108 - Invalid Nhs Number
            * 109 - Invalid Provider Id
            * 110 - Invalid Account Id
            * 111 - Invalid Linkage Key
            * 112 - Problem Logging In
            * 113 - User Record Unavailable
            * 114 - Invalid Security
            * 115 - Invalid Request
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiErrorResponse'
          description: |
            Forbidden - Possible errorCodes and errorMessages:
            * 100 - Unknown Error 
            * 101 - Practice not enabled
            * 102 - Patient Archived or Disabled
            * 104 - Patient under minimum age or non competent
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiErrorResponse'
          description: |
            Not Found - Possible errorCodes and errorMessages:
            * 100 - Unknown Error 
            * 103 - Patient not found
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiErrorResponse'
          description: |
            Conflict - Possible errorCodes and errorMessages:
            * 100 - Unknown Error 
            * 105 - User account conflict
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiErrorResponse'
          description: |
            Unexpected Internal server error - Possible errorCodes and errorMessages:
            * 100 - Unknown Error
        "501":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiErrorResponse'
          description: |
            No GP System found for supplied ODS Code. This could mean either they don't exist, or they're not yet onboarded. - Possible errorCodes and errorMessages:
            * 106 - Invalid details
        "502":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiErrorResponse'
          description: |
            Bad response received from GP System. An example would be that a session could not be established
            * 100 - Unknown Error
            * 107 - Upstream Error
        "504":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiErrorResponse'
          description: |
            Timeout when calling GP System
            * 100 - Unknown Error

components:
  schemas:
    CreateIm1ConnectionRequest:
      type: object
      required:
        - odsCode
        - surname
        - dateOfBirth
      properties:
        odsCode:
          type: string
          description: ODS code for the Patient's GP.
        surname:
          type: string
          description: Patient's Surname.
        dateOfBirth:
          type: string
          format: date
          description: Patient's Date of Birth.

    CreateIm1ConnectionWithLinkageDetailsRequest:
      allOf:
        - $ref: '#/components/schemas/CreateIm1ConnectionRequest'
        - type: object
          required:
            - accountId
            - linkageKey
          properties:
            accountId:
              type: string
              description: Patient's GP IM1 Account ID.
            linkageKey:
              type: string
              description: Patient's GP IM1 Linkage Key.

    CreateIm1ConnectionWithNhsNumberRequest:
      allOf:
        - $ref: '#/components/schemas/CreateIm1ConnectionRequest'
        - type: object
          required:
            - nhsNumber
            - emailAddress
            - identityToken
          properties:
            nhsNumber:
              type: string
              description: Patient's NHS Number.
            identityToken:
              type: string
              description: Token to uniquely identify the patient at their current practice within the Citizen ID platform.
            emailAddress:
              type: string
              description: Patient's email address, this will be used if a new online user is to be created in the GP System.

    PatientIm1ConnectionResponse:
      type: object
      properties:
        connectionToken:
          type: string
          description: IM1 Connection Token.
        nhsNumbers:
          type: array
          description: The NHS Numbers associated with the patient in the GP System.
          items:
            type: object
            properties:
              nhsNumber:
                type: string
                description: An NHS Number associated with the patient in the GP System.
        odsCode:
          type: string
          description: ODS code for the Patient's GP.

    CreateIm1ConnectionResponse:
      allOf:
        - $ref: '#/components/schemas/PatientIm1ConnectionResponse'
        - type: object
          required:
            - accountId
          properties:
            accountId:
              type: string
              description: Patient's GP IM1 Account ID.
            linkageKey:
              type: string
              description: Patient's GP IM1 Linkage Key.

    apiErrorResponse:
      type: object
      description: error response from backend api.
      properties:
        errorCode:
          type: integer
          description: error code.
        errorMessage:
          type: string
          description: error message.
        gpSystem:
          type: string
          description: Patient's GP System
