swagger: "2.0"

info:
  version: 0.0.5
  title: NHS App Sub-API - Demographics
  description: NHS App Sub-API - endpoints pertaining to demographics. All require an NHSO-Session-Id cookie (obtained from Session endpoint).

paths:
  /demographics:
    get:
      tags:
        - demographics
      summary: Gets demographic information for the logged on user.
      description: Returns users personal details and address details for the logged in user. Requires NHSO-Session-Id cookie (obtained from session endpoint).
      produces:
        - application/json
      responses:
        200:
          description: Returns demographic data for the logged in user.
          schema:
            $ref: "#/definitions/DemographicResponse"
        401:
          description: User session has expired.
        403:
          description: The patient does not have the necessary permissions within the GP system.
        500:
          description: An unexpected error occurred processing the request.
        502:
          description: The GP system is currently unavailable.
        504:
          description: The GP system did not respond in a timely fashion.
 
definitions:
  DemographicResponse:
    type: object
    properties:
      nhsNumber:
        type: string
        description: The persons NHS number.
      patientName:
        type: string
        description: The patients name.
      dateOfBirth:
        type: string
        format: date-time
        description: The persons date of birth.
      sex:
        type: string
        description: The persons sex.
      address:
        type: string
        description: The patients address.
