openapi: 3.0.2
info:
  version: 0.0.1
  title: NHS App Sub-API - Secondary Care
  description: NHS App Sub-API - endpoints pertaining to Secondary-Care integration.
paths:
  /secondary-care/summary:
    get:
      tags:
        - secondary-care
      summary: Gets a summary of secondary care appointments and referrals for the user.
      description: Gets a summary of secondary care appointments and referrals for the user. Requires NHSO-Session-Id and NHSO-Session-Expiry cookies (obtained from session endpoint).
      responses:
        "200":
          description: Successfully retrieved secondary care summary.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SecondaryCareSummaryResponse"
        "400":
          description: Bad request. Supplied request is incomplete or invalid.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
        "401":
          description: User session has expired.
        "500":
          description: An unexpected error occurred during the processing of the request.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
        "502":
          description: Bad response received from upstream system.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
        "504":
          description: Timeout when calling upstream system.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"

components:
  schemas:
    SecondaryCareSummaryResponse:
      type: object
      required:
        - referralsNotInReview
        - referralsInReview
        - confirmedAppointments
        - unconfirmedAppointments
      properties:
        referralsNotInReview:
          type: array
          description: An array of referrals (Not in review) for the authorized user.
          items:
            $ref: "#/components/schemas/ReferralNotInReview"
        referralsInReview:
          type: array
          description: An array of referrals (In review) for the authorized user.
          items:
            $ref: "#/components/schemas/ReferralInReview"
        confirmedAppointments:
          type: array
          description: An array of confirmed (with appointment date) appointments for the authorized user.
          items:
            $ref: "#/components/schemas/ConfirmedAppointment"
        unconfirmedAppointments:
          type: array
          description: An array of unconfirmed (without appointment date) appointments for the authorized user.
          items:
            $ref: "#/components/schemas/UnconfirmedAppointment"
    ReferralNotInReview:
      type: object
      required:
        - referralId
        - referredDatetime
        - referrerOrganisation
        - status
        - provider
        - deepLinkUrl
      properties:
        referralId:
          type: string
          description: Supplier specific reference - booking reference.
        referredDatetime:
          type: string
          format: date-time
          description: The date-time the referral was initiated.
        serviceSpecialty:
          type: string
          description: The specialty of the department the patient is being referred to.
        referrerOrganisation:
          type: string
          description: Patient friendly name of the referrer organisation.
        status:
          type: string
          description: Possible referral states.
          enum:
            - bookable
            - bookableWasCancelled
        reviewDueDate:
          type: string
          format: date-time
          description: Optional - Date when referral is due if applicable. Only will be returned if status is InReview.
        provider:
          type: string
          description: The linked referral or portal system.
          enum:
            - pkb
            - ers
            - drdoctor
        deepLinkUrl:
          type: string
          description: Deep link url for the user to get more details on the referral.
    ReferralInReview:
      type: object
      required:
        - referralId
        - referredDatetime
        - referrerOrganisation
        - status
        - provider
        - deepLinkUrl
      properties:
        referralId:
          type: string
          description: Supplier specific reference - booking reference.
        referredDatetime:
          type: string
          format: date-time
          description: The date-time the referral was initiated.
        serviceSpecialty:
          type: string
          description: The specialty of the department the patient is being referred to.
        referrerOrganisation:
          type: string
          description: Patient friendly name of the referrer organisation.
        status:
          type: string
          description: Possible referral states.
          enum:
            - inReview
        reviewDueDate:
          type: string
          format: date-time
          description: Optional - Date when referral is due if applicable. Only will be returned if status is InReview.
        provider:
          type: string
          description: The linked referral or portal system.
          enum:
            - pkb
            - ers
            - drdoctor
        deepLinkUrl:
          type: string
          description: Deep link url for the user to get more details on the referral.
    ConfirmedAppointment:
      type: object
      required:
        - appointmentDatetime
        - appointmentStatus
        - locationDescription
        - deepLinkUrl
        - provider
      properties:
        appointmentDatetime:
          type: string
          format: date-time
          description: The date-time of the upcoming appointment.
        appointmentStatus:
          type: string
          description: State of the appointment. Initially only booked appointments will be returned.
          enum:
            - booked
        locationDescription:
          type: string
          description: A patient friendly term for where the appointment will be.
        provider:
          type: string
          description: The linked referral or portal system.
          enum:
            - pkb
            - ers
            - drdoctor
        deepLinkUrl:
          type: string
          description: Deep link url for the user to get more details on the appointment.
    UnconfirmedAppointment:
      type: object
      required:
        - appointmentStatus
        - locationDescription
        - deepLinkUrl
        - provider
      properties:
        appointmentStatus:
          type: string
          description: State of the appointment. Initially only booked appointments will be returned.
          enum:
            - booked
        locationDescription:
          type: string
          description: A patient friendly term for where the appointment will be.
        provider:
          type: string
          description: The linked referral or portal system.
          enum:
            - pkb
            - ers
            - drdoctor
        deepLinkUrl:
          type: string
          description: Deep link url for the user to get more details on the appointment.