openapi: 3.0.2
info:
  version: 0.0.2
  title: NHS App Sub-API - Secondary Care
  description: NHS App Sub-API - endpoints pertaining to Secondary-Care integration.
paths:
  /secondary-care/summary:
    get:
      tags:
        - secondary-care
      summary: Gets a summary of secondary care appointments and referrals for the user.
      description: Gets a summary of secondary care appointments and referrals for the user. Requires NHSO-Session-Id and NHSO-Session-Expiry cookies (obtained from session endpoint).
      responses:
        "200":
          description: Successfully retrieved secondary care summary.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SecondaryCareSummaryResponse"
        "400":
          description: Bad request. Supplied request is incomplete or invalid.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
        "401":
          description: User session has expired.
        "470":
          description: Custom error response to indicate user failed minimum age validation check.
        "500":
          description: An unexpected error occurred during the processing of the request.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
        "502":
          description: Bad response received from upstream system.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
        "504":
          description: Timeout when calling upstream system.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"

  /secondary-care/waittimes:
    get:
      tags:
        - secondary-care
      summary: Gets a list of secondary care wait times.
      description: Gets a list of secondary care wait times. Requires NHSO-Session-Id and NHSO-Session-Expiry cookies (obtained from session endpoint).
      responses:
        "200":
          description: Successfully retrieved secondary care wait times.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SecondaryCareWaitTimesResponse"
        "400":
          description: Bad request. Supplied request is incomplete or invalid.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
        "401":
          description: User session has expired.
        "404":
          description: Wait times not enabled.
        "500":
          description: An unexpected error occurred during the processing of the request.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
        "502":
          description: Bad response received from upstream system.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
        "504":
          description: Timeout when calling upstream system.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
components:
  schemas:
    SecondaryCareSummaryResponse:
      type: object
      required:
        - actionableReferralsAndAppointments
        - referralsInReviewNotOverdue
        - confirmedAppointments
      properties:
        confirmedAppointments:
          type: array
          description: An array of confirmed (with appointment date) appointments for the authorized user.
          items:
            $ref: "#/components/schemas/ConfirmedAppointment"
        referralsInReviewNotOverdue:
          type: array
          description: |
            An array of in-review referrals that are not overdue (a ReviewDueDate before today). Items are sorted
            by ReferredDateTime in chronological order.
          items:
            $ref: "#/components/schemas/ReferralInReview"
        actionableReferralsAndAppointments:
          type: array
          description: |
            An array of appointments (cancelled) and referrals (not in review, or overdue) that may require
            attention for the authorized user. Items are sorted by appointments then referrals, and subsequently
            referrals are then sorted by ReferredDateTime in chronological order.
          items:
            anyOf:
              - $ref: "#/components/schemas/UnconfirmedAppointment"
              - $ref: "#/components/schemas/ReferralNotInReview"
              - $ref: "#/components/schemas/ReferralInReview"
    ReferralNotInReview:
      type: object
      required:
        - itemType
        - referralId
        - referredDatetime
        - status
        - provider
        - deepLinkUrl
      properties:
        itemType:
          type: string
          description: A string representation of the type of this summary item
          enum:
            - Referral
        referralId:
          type: string
          description: Supplier specific reference - booking reference.
        referredDatetime:
          type: string
          format: date-time
          description: The date-time the referral was initiated.
        serviceSpecialty:
          type: string
          description: The specialty of the department the patient is being referred to.
        status:
          type: string
          description: Possible referral states.
          enum:
            - bookable
            - bookableWasCancelled
        reviewDueDate:
          type: string
          format: date-time
          description: Optional - Date when referral is due if applicable. Only will be returned if status is InReview.
        provider:
          type: string
          description: The linked referral or portal system.
          enum:
            - accurx
            - drdoctor
            - ers
            - healthcarecomms
            - netcall
            - pkb
            - zesty
        deepLinkUrl:
          type: string
          description: Deep link url for the user to get more details on the referral.
    ReferralInReview:
      type: object
      required:
        - itemType
        - referralId
        - referredDatetime
        - status
        - provider
        - deepLinkUrl
      properties:
        itemType:
          type: string
          description: A string representation of the type of this summary item
          enum:
            - Referral
        referralId:
          type: string
          description: Supplier specific reference - booking reference.
        referredDatetime:
          type: string
          format: date-time
          description: The date-time the referral was initiated.
        serviceSpecialty:
          type: string
          description: The specialty of the department the patient is being referred to.
        status:
          type: string
          description: Possible referral states.
          enum:
            - inReview
        reviewDueDate:
          type: string
          format: date-time
          description: Optional - Date when referral is due if applicable
        provider:
          type: string
          description: The linked referral or portal system.
          enum:
            - accurx
            - drdoctor
            - ers
            - healthcarecomms
            - netcall
            - pkb
            - zesty
        deepLinkUrl:
          type: string
          description: Deep link url for the user to get more details on the referral.
    ConfirmedAppointment:
      type: object
      required:
        - itemType
        - appointmentDatetime
        - appointmentStatus
        - locationDescription
        - deepLinkUrl
        - provider
      properties:
        itemType:
          type: string
          description: A string representation of the type of this summary item
          enum:
            - UpcomingAppointment
        appointmentDatetime:
          type: string
          format: date-time
          description: The date-time of the upcoming appointment.
        appointmentStatus:
          type: string
          description: State of the appointment. Initially only booked appointments will be returned.
          enum:
            - booked
        locationDescription:
          type: string
          description: A patient friendly term for where the appointment will be.
        provider:
          type: string
          description: The linked referral or portal system.
          enum:
            - accurx
            - drdoctor
            - ers
            - healthcarecomms
            - netcall
            - pkb
            - zesty
        deepLinkUrl:
          type: string
          description: Deep link url for the user to get more details on the appointment.
    UnconfirmedAppointment:
      type: object
      required:
        - itemType
        - appointmentStatus
        - locationDescription
        - deepLinkUrl
        - provider
      properties:
        itemType:
          type: string
          description: A string representation of the type of this summary item
          enum:
            - UpcomingAppointment
        appointmentStatus:
          type: string
          description: State of the appointment. Initially only booked appointments will be returned.
          enum:
            - booked
        locationDescription:
          type: string
          description: A patient friendly term for where the appointment will be.
        provider:
          type: string
          description: The linked referral or portal system.
          enum:
            - accurx
            - drdoctor
            - ers
            - healthcarecomms
            - netcall
            - pkb
            - zesty
        deepLinkUrl:
          type: string
          description: Deep link url for the user to get more details on the appointment.
    SecondaryCareWaitTimesResponse:
      type: object
      required:
        - waitTimes
      properties:
        waitTimes:
          type: array
          description: An array of wait times for the authorized user.
          items:
            $ref: "#/components/schemas/WaitTimes"

    WaitTimes:
      type: object
      required:
        - estimatedWaitToTreatmentDisplayDate
        - referredDate
        - plannedWaitTime
        - providerName
        - speciality
      properties:
        estimatedWaitToTreatmentDisplayDate:
          type: string
          format: date-time
          description: The 'MMMM yyyy' format date-time of the estimated wait to treatment.
        referredDate:
          type: string
          format: date-time
          description: The date-time of the referral.
        plannedWaitTime:
          type: integer
          description: State of the appointment. Initially only booked appointments will be returned.
        providerName:
          type: string
          description: Name of the provider.
        speciality:
          type: string
          description: Speciality.
