openapi: 3.0.2
info:
  version: 0.0.1
  title: NHS App Users-API
  description: NHS App Users-API - endpoints pertaining to Users, all require an Authorisation-Bearer Token to be included in the header.
paths:
  /users/me/devices:
    get:
      security:
        - nhsLoginBearerAuth: []
      tags:
        - user-devices
      summary: Retrieves the users device registration
      description: Using the accesstoken, will retrieve the user's current notifications registration on this device
      parameters:
        - in: header
          name: NHSO-Request-ID
          required: false
          description: A request identifier, should provide something unique on each separate request to allow NHS App to easily retrieve relevant log entries for debugging purposes.
          schema:
            type: string
        - in: query
          name: devicePns
          required: true
          description: The device PNS token
          schema:
            type: string
      responses:
        "204":
          description: Found registered device for notifications
        "400":
          $ref: '#/components/responses/BadRequest'
        "401":
          $ref: '#/components/responses/UnauthorizedError'
        "404":
          description: The device is not registered for notifications
        "500":
          $ref: '#/components/responses/UnexpectedError'
        "502":
          $ref: '#/components/responses/UnexpectedError'
    post:
      security:
        - nhsLoginBearerAuth: []
      tags:
        - user-devices
      summary: Registers the new device for notifications.
      description: Using the accesstoken, will register the user's wish to receive notifications on this device
      parameters:
        - in: header
          name: NHSO-Request-ID
          required: false
          description: A request identifier, should provide something unique on each separate request to allow NHS App to easily retrieve relevant log entries for debugging purposes.
          schema:
            type: string
      requestBody:
        x-name: AddDeviceRequest
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddDeviceRequest"
        description: Details of the device to be registered
        required: true
      responses:
        "201":
          description: Successfully registered device for notifications
        "400":
          $ref: '#/components/responses/BadRequest'
        "401":
          $ref: '#/components/responses/UnauthorizedError'
        "500":
          $ref: '#/components/responses/UnexpectedError'
        "502":
          $ref: '#/components/responses/UnexpectedError'
    delete:
      security:
        - nhsLoginBearerAuth: []
      tags:
        - user-devices
      summary: Deletes the users device registration
      description: Using the accesstoken, will delete the user's notifications registration on this device
      parameters:
        - in: header
          name: NHSO-Request-ID
          required: false
          description: A request identifier, should provide something unique on each separate request to allow NHS App to easily retrieve relevant log entries for debugging purposes.
          schema:
            type: string
        - in: query
          name: devicePns
          required: true
          description: The device PNS token
          schema:
            type: string
      responses:
        "204":
          description: Deleted the registered device for notifications
        "400":
          $ref: '#/components/responses/BadRequest'
        "401":
          $ref: '#/components/responses/UnauthorizedError'
        "404":
          description: The device is not registered for notifications
        "500":
          $ref: '#/components/responses/UnexpectedError'
        "502":
          $ref: '#/components/responses/UnexpectedError'
  /users/{nhsLoginId}/devices/notifications:
    post:
      tags:
        - notifications
      summary: Sends a notification
      description: Sends a notification to the specified user
      parameters:
        - in: path
          name: nhsLoginId
          required: true
          description: Unique identifier of a user
          schema:
            type: string
      requestBody:
        x-name: NotificationSendRequest
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NotificationSendRequest"
        description: Details of the notification to be sent
        required: true
      responses:
        "202":
          description: Successfully sent
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotificationSendResponse"
        "400":
          $ref: '#/components/responses/BadRequest'
        "409":
          $ref: '#/components/responses/Conflict'
        "500":
          $ref: '#/components/responses/UnexpectedError'
        "502":
          $ref: '#/components/responses/UnexpectedError'
  /users/devices/notifications/{notificationId}:
    get:
      tags:
        - notifications
      summary: Retrieves notification outcome details for given notification id
      description: Gets detailed notification outcome details
      parameters:
        - in: path
          name: notificationId
          required: true
          description: Unique identifier of a notification
          schema:
            type: string
        - in: query
          name: hubPath
          required: true
          description: The path of notification hub to query for outcome details
          schema:
              type: string
      responses:
        "200":
          description: Successfully retrieved notification outcome details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotificationOutcomeResponse"
        "400":
          $ref: '#/components/responses/BadRequest'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/UnexpectedError'
        "502":
          $ref: '#/components/responses/UnexpectedError'
  /users/me/devices/prompt/metrics:
    post:
      security:
        - nhsLoginBearerAuth: []
      tags:
        - notifications metric logging
      summary: logs metrics for the notifications prompt
      description: logs metrics for the notifications prompt
      requestBody:
        x-name: NotificationsPromptData
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NotificationsPromptData"
        description: Metrics to be logged for the notification prompt
        required: true
      responses:
        "200":
          description: Successfully logged
        "400":
          $ref: '#/components/responses/BadRequest'
  /users/me/devices/log/audit:
    post:
      security:
        - nhsLoginBearerAuth: []
      tags:
        - notifications audit logging
      summary: audit logs for notifications
      description: audit logs for notifications
      requestBody:
        x-name: NotificationsAuditData
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NotificationsAuditData"
        description: Audit details to be logged for the notification
        required: true
      responses:
        "200":
          description: Successfully logged
        "400":
          $ref: '#/components/responses/BadRequest'
  /users/me/silver-integration-blocked/metrics:
    post:
      security:
        - nhsLoginBearerAuth: []
      tags:
        - silver integration jumpoff blocked metric logging
      summary: logs metrics for the blocked silver integration jumpoff
      description: logs metrics for the blocked silver integration jumpoff
      requestBody:
        x-name: SilverIntegrationJumpOffBlockedData
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SilverIntegrationJumpOffBlockedData"
        description: Metrics to be logged for the blocked silver integration jumpoff
        required: true
      responses:
        "200":
          description: Successfully logged
        "400":
          $ref: '#/components/responses/BadRequest'
components:
  securitySchemes:
    nhsLoginBearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid.
    UnexpectedError:
      description: An unexpected error occurred processing the request.
    BadRequest:
      description: Bad request. Supplied request is invalid.
    NotFound:
        description: Not found. Requested resource is not found.
    Conflict:
      description: Conflict. Request could not be completed due to a conflict with the current state of the target resource.
  schemas:
    DeviceType:
      type: string
      enum:
          - ios
          - android
    AddDeviceRequest:
      type: object
      properties:
        devicePNS:
          type: string
        deviceType:
          $ref: '#/components/schemas/DeviceType'
      example:
        devicePNS: b1f99cf0-278d-49ca-a325-0a1504799488
        deviceType: android
    Device:
      type: object
      properties:
        deviceId:
          type: string
        deviceType:
          $ref: '#/components/schemas/DeviceType'
      example:
        deviceId: 2f2c28c8-3de9-4ffc-9d0b-23533363d7d3
        deviceType: android
    NotificationSendRequest:
      type: object
      required:
        - title
        - body
      properties:
        title:
          type: string
        subTitle:
          type: string
        body:
          type: string
        url:
          type: string
        scheduledTime:
          type: string
        senderContext:
          $ref: "#/components/schemas/PushNotificationSenderContext"
    NotificationSendResponse:
      type: object
      properties:
        notificationId:
          type: string
        scheduled:
          type: boolean
        hubPath:
          type: string
    NotificationOutcomeResponse:
      type: object
      properties:
        state:
          type: string
        enqueueTime:
          type: string
          format: date-time
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        pnsErrorDetailsUri:
          type: string
        platformOutcomes:
          type: array
          description: Array of Platform outcomes
          items:
            $ref: "#/components/schemas/PlatformOutcome"
    PlatformOutcome:
      type: object
      properties:
        platform:
          type: string
        outcome:
          type: string
        count:
          type: integer
    NotificationsPromptData:
      type: object
      required:
        - screenShown
        - notificationsRegistered
        - platform
        - didErrorAttemptingToUpdateStatus
      properties:
        screenShown:
          type: boolean
        notificationsRegistered:
          type: boolean
        platform:
          type: string
        didErrorAttemptingToUpdateStatus:
          type: boolean
    NotificationsAuditData:
      type: object
      required:
        - notificationsRegistered
        - notificationsDecisionSource
      properties: 
        notificationsRegistered: 
          type: boolean
        notificationsDecisionSource:                     
          type: string
          enum: 
            - Prompt
            - Toggle
            - Unknown
    PushNotificationSenderContext:
      type: object
      properties:
        supplierId:
          type: string
        senderId:
          type: string
        communicationId:
          type: string
        transmissionId:
          type: string
        communicationCreatedDateTime:
          type: string
          format: date-time
        requestReference:
          type: string
        campaignId:
          type: string
        odsCode:
          type: string
        nhsNumber:
          type: string
        nhsLoginId:
          type: string
    SilverIntegrationJumpOffBlockedData:
      type: object
      required:
        - providerId
        - providerName
        - jumpOffId
        - reason
      properties:
        providerId:
          type: string
        providerName:
          type: string
        jumpOffId:
          type: string
        reason:
          type: string