openapi: 3.0.2
info:
  version: 0.0.1
  title: NHS App Sub-API - Journey Configuration
  description: NHS App Sub-API - Endpoint to retreive patient Service Journey Rules Configuration
paths:
  /journey-configuration:
    get:
      tags:
        - service-journey-rules
      summary: Gets the service journey rules for a patients pratice
      description: This call returns the service journey rules for a patients pratice.
      responses:
        "200":
          description: Successful operation. Service Journey Rules returned
          content:
            application/json:
              schema:
                $ref: "servicejourneyrules.yaml#/components/schemas/ServiceJourneyRulesResponse"
        "404":
          description: Service Journey Rules Configuration not found.
        "500":
          description: An unexpected error occurred processing the request.
