swagger: "2.0"

info:
  version: 0.0.7
  title: NHS App Sub-API - GP Search
  description: NHS App Sub-API - Endpoint to facilitate searching for Gp Practices

paths:
  /gpsearch:
    post:
      tags:
        - gpsearch
      summary: Search for Gp Practices
      description: Returns Response object containing list of GP Practices
      consumes:
        - application/json
      parameters:
        - in: body
          name: GpSearchRequest
          required: true
          description: Search Term to be used when searching for GP Practices
          schema:
            $ref: "#/definitions/GpSearchRequest"
      responses:
        200:
          description: Search Executed Successfully
          schema:
            $ref: "#/definitions/GpSearchResponse"
        400:
          description: Bad request. Supplied request is incomplete or invalid.
        500:
          description: An unexpected error occurred processing the request.
        502:
          description: Bad response received from upstream system.
definitions:
  GpSearchRequest:
    type: object
    required:
      - searchTerm
    properties:
      searchTerm:
        type: string
        description: Search Term
        minLength: 1
  GpSearchResponse:
    type: object
    properties:
      organisations:
        type: array
        description: Array of organisations matched in search
        items:
          $ref: "#/definitions/Organisation"
      organisationQueryCount:
        type: integer
        description: Total count of Gp Practices in query
  Organisation:
    type: object
    properties:
      organisationName:
        type: string
        description: Name of practice
      address1:
        type: string
        description: Address line 1
      address2:
        type: string
        description: Address line 2
      address3:
        type: string
        description: Address line 3
      city:
        type: string
        description: City
      county:
        type: string
        description: County
      postcode:
        type: string
        description: Postcode
      nacsCode:
        type: string
        description: ODSCode
