openapi: 3.0.2
info:
  version: 0.0.5
  title: NHS App Sub-API - Document
  description: NHS App Sub-API - endpoints pertaining to documents. All require an
    NHSO-Session-Id cookie (obtained from Session endpoint).
paths:
  /documents/{documentIdentifier}:
    post:
      tags:
        - patient document
      summary: Gets a specific document from the user's documents for the logged on user.
      description: Returns only the specified document from the users document list for the
        logged in user. Requires NHSO-Session-Id cookie (obtained
        from session endpoint).
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetPatientDocumentRequest"
        required: true
        x-name: GetPatientDocumentRequest
      parameters:
        - in: path
          name: documentIdentifier
          required: true
          description: document Guid of specific document to return
          schema:
            type: string
      responses:
        "200":
          description: Returns specified document for the logged in user.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetPatientDocumentResult"
        "401":
          description: User session has expired.
        "500":
          description: An unexpected error occurred processing the request.
        "502":
          description: The GP system is currently unavailable.
        "504":
          description: The GP system did not respond in a timely fashion.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
  /documents/{documentIdentifier}/download:
    post:
      tags:
        - patient document
      summary: Gets a specific document and initiates a download of the document.
      description: Returns only the specified document from the users document list for the
        logged in user. Requires NHSO-Session-Id cookie (obtained
        from session endpoint).
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetPatientDocumentRequest"
        required: true
        x-name: GetPatientDocumentRequest
      parameters:
        - in: path
          name: documentIdentifier
          required: true
          description: document Guid of specific document to return
          schema:
            type: string
      responses:
        "200":
          description: Returns specified document for the logged in user.
          content:
            application/octect-stream:
              schema:
                type: string
                format: binary
components:
  schemas:
    GetPatientDocumentRequest:
      type: object
      properties:
        type:
          type: string
          description: The name of the document, used for img alt text on image document types
        name:
          type: string
          description: The type of the document, to determine whether or not to add the name as alt text
    GetPatientDocumentResult:
      type: object
      properties:
        hasErrored:
          type: boolean
          description: Shows if error occurred getting an individual document
        content:
          type: string
          description: base64 encoded string of document
        type:
          type: string
          description: type of document
        isViewable:
          type: boolean
          description: Indicates if the file is viewable
        isDownloadable:
          type: boolean
          description: Indicates if the file is downloadable
