swagger: "2.0"

info:
  version: 0.0.7
  title: NHS App Sub-API - Organ Donation
  description: NHS App Sub-API - endpoints pertaining to Organ Donation -  All require an NHSO-Session-Id cookie (obtained from Session endpoint).
paths:
  /organdonation:
    get:
      tags:
        - organDonation
      summary: Get the existing organ donation and user demographic information.
      description: Returns the user's organ donation record.
      consumes:
        - application/json
      responses:
        200:
          description: Successfully retrieved the user's organ donation record.
          schema:
            $ref: '#/definitions/organDonationRegistration'
        401:
          description: User session missing or expired.
        403:
          description: User forbidden access to GP System demographics.
        409:
          description: Conflicts on organ donation record.
        500:
          description: An unexpected error occurred processing the request.
        502:
          description: Bad response received from upstream system.
          schema:
            $ref: '#/definitions/apiErrorResponse'
        504:
          description: Timeout when calling upstream system.
    post:
      tags:
        - organDonation
      summary: Creates a user's organ donation record
      description: Creates the user's organ donation record and returns the record identifier.
      consumes:
        - application/json
      parameters:
        - in: body
          required: true
          name: 'organDonationRegistrationRequest'
          description: Details of the organ donation registration request.
          schema:
            $ref: '#/definitions/organDonationRegistrationRequest'
      responses:
        201:
          description: "Successfully created the organ donation record and returned the record identifier."
          schema:
            type: "object"
            properties:
              identifier:
                type: "string"
                description: "User's organ donation identifier."
              state:
                type: string
                enum: [NotFound, Ok, Conflicted]
                description: User's organ donation record state
        400:
          description: Bad request. Supplied request is incomplete or invalid.
        401:
          description: User session missing or expired.
        409:
          description: Conflicts on organ donation record.
        500:
          description: An unexpected error occurred processing the request.
        502:
          description: Bad response received from upstream system.
          schema:
            $ref: '#/definitions/apiErrorResponse'
        504:
          description: Timeout when calling upstream system.
    put:
        tags:
          - organDonation
        summary: Amends a user's organ donation record
        description: Amends the user's organ donation record and returns the record identifier.
        consumes:
          - application/json
        parameters:
          - in: body
            required: true
            name: 'organDonationRegistrationRequest'
            description: Details of the organ donation registration request.
            schema:
              $ref: '#/definitions/organDonationRegistrationRequest'
        responses:
          200:
            description: "Successfully amended the organ donation record and returned the record identifier."
            schema:
              type: "object"
              properties:
                identifier:
                  type: "string"
                  description: "User's organ donation identifier."
                state:
                  type: string
                  enum: [NotFound, Ok, Conflicted]
                  description: User's organ donation record state
          400:
            description: Bad request. Supplied request is incomplete or invalid.
          401:
            description: User session missing or expired.
          500:
            description: An unexpected error occurred processing the request.
          502:
            description: Bad response received from upstream system.
            schema:
              $ref: '#/definitions/apiErrorResponse'
          504:
            description: Timeout when calling upstream system.
  /organdonation/referencedata:
    get:
      tags:
        - organDonation
      summary: Get the reference data required for registering an organ donation decision.
      description: Returns the reference data for titles, genders, religions, ethnicities and withdrawal reasons.
      produces:
        - application/json
      responses:
        200:
          description: Successfully retrieved the organ donation reference data.
          schema:
            $ref: '#/definitions/organDonationReferenceData'
        401:
          description: User session missing or expired.
        500:
          description: An unexpected error occurred processing the request.
        502:
          description: Bad response received from upstream system.
          schema:
            $ref: '#/definitions/apiErrorResponse'
        504:
          description: Timeout when calling upstream system.
definitions:
  organDonationReferenceData:
    type: object
    properties:
      ethnicities:
        type: array
        items:
          $ref: '#/definitions/selectOption'
      genders:
        type: array
        items:
          $ref: '#/definitions/selectOption'
      titles:
        type: array
        items:
          $ref: '#/definitions/selectOption'
      religions:
        type: array
        items:
          $ref: '#/definitions/selectOption'
      withdrawReasons:
        type: array
        items:
          $ref: '#/definitions/selectOption'
  additionalDetails:
    type: object
    properties:
      religionId:
        type: string
        description: The identifier for the select religion.
      ethnicityId:
        type: string
        description: The identifier for the select ethnicity.
  organDonationRegistration:
    type: object
    properties:
      identifier:
        type: string
        description: User's organ donation identifier.
      nhsNumber:
        type: string
        description: User's nhs number from the GP System.
      nameFull:
        type: string
        description: User's full name.
      name:
        $ref: '#/definitions/usersName'
      gender:
        type: string
        description: User's gender from the GP System.
      dateOfBirth:
        type: string
        format: date
        description: User's date of birth from the GP System.
      addressFull:
        type: string
        description: User's full address.
      address:
        $ref: '#/definitions/usersAddress'
      emailAddress:
        type: string
        description: User's email address from nhs login.
      decision:
        type: string
        enum: [Unknown, OptIn, OptOut]
        description: User's organ donation decision.
      decisionDetails:
        $ref: '#/definitions/decisionDetails'
      faithDeclaration:
        type: string
        enum: [NotStated, Yes, No]
        description: User's faith decision.
      state:
        type: string
        enum: [NotFound, Ok, Conflicted]
        description: User's organ donation record state
  organDonationStoreRegistration:
    type: object
    properties:
      identifier:
        type: string
        description: User's organ donation identifier.
      nhsNumber:
        type: string
        description: User's nhs number from the GP System.
      name:
        $ref: '#/definitions/usersName'
      gender:
        type: string
        description: User's gender from the GP System.
      dateOfBirth:
        type: string
        format: date
        description: User's date of birth from the GP System.
      addressFull:
        type: string
        description: User's full address.
      address:
        $ref: '#/definitions/usersAddress'
      emailAddress:
        type: string
        description: User's email address from nhs login.
      decision:
        type: string
        enum: [OptIn, OptOut]
        description: User's organ donation decision.
      decisionDetails:
        $ref: '#/definitions/decisionDetails'
      faithDeclaration:
        type: string
        enum: [NotStated, Yes, No]
        description: User's faith decision.
  selectOption:
    type: object
    description: Contains data for a select box option
    properties:
      id:
        type: string
        description: The identifier for the select option.
      displayName:
        type: string
        description: The value to be displayed to the user.
  usersName:
    type: object
    description: User's name object.
    properties:
      title:
        type: string
        description: User's title from the GP System.
      givenName:
        type: string
        description: User's given name from the GP System.
      surname:
        type: string
        description: User's surname from the GP System.
  usersAddress:
    type: object
    description: User's address from the GP System.
    properties:
      text:
        type: string
        description: User's address from the GP System.
      postcode:
        type: string
        description: User's postcode from the GP System.
  decisionDetails:
    type: object
    description: User's organ donation decision.
    properties:
      all:
        type: boolean
        description: User's agreed to donate all organs.
      choices:
        description: User's individual organ donation choices.
        additionalProperties:
          type: string
          enum: [NotStated, Yes, No]
          description: Value of the choice.
        example:
          heart: Yes
          lungs: NotStated
          kidney: No
  organDonationRegistrationRequest:
    type: object
    description: Details of the organ donation registration request.
    properties:
      registration:
        $ref: '#/definitions/organDonationStoreRegistration'
      additionalDetails:
        $ref: '#/definitions/additionalDetails'
  apiErrorResponse:
    type: object
    description: error response from backend api.
    properties:
      ErrorCode:
        type: int
        description: error code.
      ErrorMessage:
        type: string
        description: error message.