swagger: "2.0"

info:
  version: 0.0.7
  title: NHS App Sub-API - Organ Donation
  description: NHS App Sub-API - endpoints pertaining to Organ Donation -  All require an NHSO-Session-Id cookie (obtained from Session endpoint).
paths:
  /organdonation:
    get:
        tags:
          - organDonation
        summary: Get the existing organ donation and user demographic information.
        description: Returns the users organ donation record.
        consumes:
          - application/json
        responses:
          200:
            description: Successfully retrieved the users organ donation record.
            schema:
              $ref: '#/definitions/organDonationRegistration'
          401:
            description: User session missing or expired.
          403:
            description: User forbidden access to gp system demographics.
          409:
            description: Conflicts on organ donation record.
          500:
            description: An unexpected error occurred processing the request.
          502:
            description: Bad response received from upstream system.
          504:
            description: Timeout when calling upstream system.
    post:
        tags:
          - organDonation
        summary: Creates a users organ donation record
        description: Creates the users organ donation record and returns the record identifier.
        consumes:
          - application/json
        parameters:
          - in: body
            required: true
            name: 'organDonationRegistrationRequest'
            description: Details of the organ donation registration request.
            schema:
              $ref: '#/definitions/organDonationRegistrationRequest'
        responses:
          201:
            description: "Successfully created the organ donation record and returned the record identifier."
            schema:
              type: "object"
              properties:
                identifier:
                  type: "string"
                  description: "Users organ donation identifier."
          400:
            description: Bad request. Supplied request is incomplete or invalid.
          401:
            description: User session missing or expired.
          409:
            description: Conflicts on organ donation record.
          500:
            description: An unexpected error occurred processing the request.
          502:
            description: Bad response received from upstream system.
          504:
            description: Timeout when calling upstream system.
  /organdonation/referencedata:
      get:
          tags:
            - organDonation
          summary: Get the reference data required for registering an organ donation decision.
          description: Returns the reference data for titles, genders, religions, ethnicities and withdrawal reasons.
          produces:
            - application/json
          responses:
            200:
              description: Successfully retrieved the organ donation reference data.
              schema:
                $ref: '#/definitions/organDonationReferenceData'
            401:
              description: User session missing or expired.
            500:
              description: An unexpected error occurred processing the request.
            502:
              description: Bad response received from upstream system.
            504:
              description: Timeout when calling upstream system.
definitions:
  organDonationReferenceData:
    type: object
    properties:
      ethnicities:
        type: array
        items:
          $ref: '#/definitions/selectOption'
      genders:
        type: array
        items:
          $ref: '#/definitions/selectOption'
      titles:
        type: array
        items:
          $ref: '#/definitions/selectOption'
      religions:
        type: array
        items:
          $ref: '#/definitions/selectOption'
      withdrawReasons:
        type: array
        items:
          $ref: '#/definitions/selectOption'
  additionalDetails:
    type: object
    properties:
      religionId:
        type: string
        description: The identifier for the select religion.
      ethnicityId:
        type: string
        description: The identifier for the select ethnicity.
  organDonationRegistration:
    type: object
    properties:
      identifier:
        type: string
        description: Users organ donation identifier.
      nhsNumber:
        type: string
        description: Users nhs number from the gp system.
      nameFull:
        type: string
        description: Users full name.
      name:
        $ref: '#/definitions/usersName'
      gender:
        type: string
        description: Users gender from the gp system.
      dateOfBirth:
        type: string
        format: date
        description: Users date of birth from the gp system.
      addressFull:
        type: string
        description: Users full address.
      address:
        $ref: '#/definitions/usersAddress'
      emailAddress:
        type: string
        description: Users email address from nhs login.
      decision:
        type: string
        description: Users organ donation decision - OptIn, OptOut or NotFound.
      decisionDetails:
        $ref: '#/definitions/decisionDetails'
      faithDeclaration:
        type: string
        description: Users faith decision - Yes, No, NotStated.
  selectOption:
    type: object
    description: Contains data for a select box option
    properties:
      id:
        type: string
        description: The identifier for the select option.
      displayName:
        type: string
        description: The value to be displayed to the user.
  usersName:
    type: object
    description: Users name object.
    properties:
      title:
        type: string
        description: Users title from the gp system.
      givenName:
        type: string
        description: Users given name from the gp system.
      surname:
        type: string
        description: Users surname from the gp system.
  usersAddress:
    type: object
    description: Users address from the gp system.
    properties:
      text:
        type: string
        description: Users address from the gp system.
      postcode:
        type: string
        description: Users postcode from the gp system.
  decisionDetails:
    type: object
    description: Users organ donation decision.
    properties:
      all:
        type: boolean
        description: Users agreed to donate all organs.
      choices:
        type: array
        items:
          $ref: '#/definitions/decisionChoice'
  decisionChoice:
    type: object
    description: Users individual organ donation choices.
    properties:
      name:
        type: string
        description: Name of the choice.
      value:
        type: string
        description: Value of the choice - Yes, No, NotStated.
  organDonationRegistrationRequest:
    type: object
    description: Details of the organ donation registration request.
    properties:
      registration:
          $ref: '#/definitions/organDonationRegistration'
      additionalDetails:
          $ref: '#/definitions/additionalDetails'
