openapi: 3.0.2
info:
  version: 0.0.1
  title: NHS App Practice to Patient Messages API
  description: NHS App Practice to Patient Messages API - endpoints pertaining to Practice to Patient Secure Messaging. All require an NHSO-Session-Id cookie (obtained from Session endpoint).
paths:
  /messages:
    get:
      tags:
        - patientMessages
      summary: Get a list of summaries for each conversation between the user and their practice
      description: Get a list of summaries for each conversation between the user and their practice
      responses:
        "200":
          description: Successfully retrieved a list of message summaries
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PatientMessagesResponse"
        "400":
          description: Upstream system returned BadRequest status.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
        "403":
          description: Upstream system returned Forbidden status.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
        "500":
          description: An unknown error occured when processing the request.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
        "502":
          description: Upstream system returned BadGateway status or an invalid response.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
    post:
      tags:
        - patientMessages
      summary: Sends a message from the user to their practice
      description: Sends a message from the user to their practice
      requestBody:
        x-name: CreateMessageRequest
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateMessageRequest"
        description: The message to be sent
        required: true
      responses:
        "200":
          description: Successfully sent a message to the users practice
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostMessageResponse"
        "400":
          description: Upstream system returned BadRequest status.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
        "403":
          description: Upstream system returned Forbidden status.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
        "500":
          description: An unknown error occured when processing the request.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
        "502":
          description: Upstream system returned BadGateway status or an invalid response.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
  /messages/recipients:
    get:
      tags:
        -patientMessages
      summary: Get a list of available recipients to which the user can send a message
      description: Get a list of available recipients to which the user can send a message
      responses:
        "200":
          description: Successfully retrieved a list of messaging recipients for the user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PatientMessageRecipientsResponse"
        "400":
          description: Upstream system returned BadRequest status.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
        "403":
          description: Upstream system returned Forbidden status.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
        "500":
          description: An unknown error occured when processing the request.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
        "502":
          description: Upstream system returned BadGateway status or an invalid response.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
  /messages/updateReadStatus:
    post:
      tags:
        - patientMessages
      summary: Update the read status of a message thread
      description: Update the read status of a message thread
      requestBody:
        x-name: UpdateMessageReadStatusRequestBody
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateMessageReadStatusRequestBody"
        description: Details of the message and the new read status.
        required: true
      responses:
        "200":
          description: Successfully updated the read status of the message
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PatientMessageReadStatusUpdatedResponse"
        "400":
          description: Upstream system returned BadRequest status.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
        "403":
          description: Upstream system returned Forbidden status.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
        "404":
          description: Upstream system returned Not found status.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
        "500":
          description: An unknown error occured when processing the request.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
        "502":
          description: Upstream system returned BadGateway status or an invalid response.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
  /messages/{id}:
    get:
      tags:
        - patientMessages
      parameters:
        - in: path
          name: id
          required: true
          description: The id of the message
          schema:
            type: string
      summary: Get details for a conversation between the user and their practice
      description: Get details for a conversation between the user and their practice
      responses:
        "200":
          description: Successfully retrieved message details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PatientMessageResponse"
        "400":
          description: Upstream system returned BadRequest status.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
        "403":
          description: Upstream system returned Forbidden status.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
        "500":
          description: An unknown error occured when processing the request.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
        "502":
          description: Upstream system returned BadGateway status or an invalid response.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
components:
  schemas:
    PatientMessagesResponse:
      type: object
      properties:
        messageSummaries:
          type: array
          description: A list of meta data about each available conversation between the patient and their practice
          items:
            $ref: "#/components/schemas/PatientMessageSummary"
    PatientMessageRecipientsResponse:
      type: object
      properties:
        messageRecipients:
          type: array
          description: A list of recipients to which the user can send a message
          items:
            $ref: "#/components/schemas/PatientMessageRecipient"
    PatientMessageResponse:
      type: object
      properties:
        messageDetails:
          type: array
          description: Details for a conversation between the patient and their practice
          items:
            $ref: "#/components/schemas/PatientMessageDetails"
    PatientMessageReadStatusUpdatedResponse:
      type: object
      properties:
        MessageReadStateUpdateStatus:
          type: string
          description: read status of the message
    PatientMessageRecipient:
      type: object
      properties:
        recipientGuid:
          type: string
          description: A unique identifier for this recipient
        name:
          type: string
          description: The name of the recipient
    PatientMessageSummary:
      type: object
      properties:
        id:
          type: integer
          description: A unique indentifier for this conversation
        subject:
          type: string
          description: A message summary provided by the patient when initiating the conversation
        lastMessageDateTime:
          type: string
          format: date-time
          description: The datetime the last message in the conversation was sent
        recipient:
          type: string
          description: The current owner of the conversation according to the GPSS
        replyCount:
          type: integer
          nullable: true
          description: The number of replies to the initial message sent by the patient  -  NHSO-6530 confirm this is not just unread messages
        hasUnreadReplies:
          type: boolean
          nullable: true
          description: Indicates whether there are messages the patient has not read
    PatientMessageDetails:
      type: object
      properties:
        MessageId:
          type: integer
          nullable: true
          description: A unique indentifier for this conversation
        subject:
          type: string
          description: A message summary provided by the patient when initiating the conversation
        content:
          type: string
          description: Content of the message sent by the user
        recipient:
          type: string
          description: recipient of the message sent by the user
        messageReplies:
          type: array
          description: array of message replies
          items:
            $ref: "#/components/schemas/MessageReplies"
    MessageReplies:
      type: object
      properties:
        sender:
          type: string
          description: Name of the sender
        sentDateTime:
          type: string
          format: date-time
          description: The datetime the reply was sent
        isUnread:
          type: boolean
          nullable: true
          description: Indicator to show if the message has already been read
        replyContent:
          type: string
          description: Content of the reply to the user
    UpdateMessageReadStatusRequestBody:
      type: object
      properties:
        messageId:
          type: integer
          description: id of the message to update the status
        messageReadState:
          type: string
          description: read state of the message
    CreateMessageRequest:
      type: object
      properties:
        messageBody:
          type: string
          description: The main text of the message
        subject:
          type: string
          description: The subject of the message
        recipient:
          type: string
          description: The guid of recipient of the message
    PostMessageResponse:
      type: object
      properties:
        messageSent:
          type: boolean
          nullable: true
          description: Indicates if the message has been successfully sent
