swagger: "2.0"

info:
  version: 0.0.5
  title: NHS App Sub-API - My Record
  description: NHS App Sub-API - endpoints pertaining to patient record. All require an NHSO-Session-Id cookie (obtained from Session endpoint).

paths:
  /my-record:
    get:
      tags:
        - myrecord
      summary: Gets the record for the logged on user.
      description: Returns the users medical record for the logged in user. Requires NHSO-Session-Id cookie (obtained from session endpoint).
      produces:
        - application/json
      responses:
        200:
          description: Returns myrecord data for the logged in user.
          schema:
            $ref: '#/definitions/MyRecordResponse'
        401:
          description: User session has expired.
        500:
          description: An unexpected error occurred processing the request.
        502:
          description: The GP system is currently unavailable.
        504:
          description: The GP system did not respond in a timely fashion.
  /test-result:
      get:
        tags:
          - test result
        summary: Returns a string which contains html from TPP for the selected test result.
        produces:
          - application/json
        parameters:
          - in: query
            name: testResultId
            type: string
            required: true
            description: id of selected test result
        responses:
          200:
            description: Returns html for selected test result from TPP
            schema:
              $ref: "#/definitions/TestResultResponse"
          400:
            description: Bad request. A querystring parameter is not in the expected format.
          401:
            description: User session has expired.
          500:
            description: An unexpected error occurred processing the request.
          502:
            description: The GP system is currently unavailable.
          504:
            description: The GP system did not respond in a timely fashion.
 
definitions:
  TestResultResponse:
    type: object
    properties:
      hasErrored:
        type: boolean
        description: Shows if error occurred getting test result from TPP
      testResult:
        type: string
        description: html represenation of test result data
        
  MyRecordResponse:
    type: object
    properties:
      hasSummaryRecordAccess:
        type: boolean
        description: Shows if the patient has access to their summary record.
      hasDetailedRecordAccess:
        type: boolean
        description: Shows if the patient has access to their detailed record.
      supplier:
        type: string
        description: supplier.
        enum:
          - UNKNOWN
          - EMIS
          - TPP
      allergies:
        type: object
        description: An object containing all allergy details.
        $ref: '#/definitions/Allergies'
      medications:
        type: object
        description:  An object containing all medication details.
        $ref: '#/definitions/Medications'
      immunisations:
        type: object
        description: An object containing all immunisation details.
        $ref: '#/definitions/Immunisations'
      testResults:
        type: object
        description: An object containing all test result details.
        $ref: '#/definitions/TestResults'
      problems:
        type: object
        description: An object containing all problems details.
        $ref: '#/definitions/Problems'
      tppDcrEvents:
        type: object
        description: An object containing all tpp dcr event details.
        $ref: '#/definitions/TppDcrEvents'
      consultations:
        type: object
        description: An object containing all consultation details.
        $ref: '#/definitions/Consultations'

  Allergies:
    type: object
    properties:
      hasAccess:
        type: boolean
        description: Does the patient have access to this data.
      hasErrored:
        type: boolean
        description: Some error occurred when attempting to retrieve this error.
      data:
        type: array
        description: An array of allergy information objects.
        items:
          $ref: '#/definitions/AllergyItem'

  AllergyItem:
    type: object
    properties:
      name:
        type: string
        description: The name of the allergy.
      date:
        $ref: '#/definitions/Date'

  Medications:
    type: object
    properties:
      hasAccess:
        type: boolean
        description: Does the patient have access to this data.
      hasErrored:
        type: boolean
        description: Some error occurred when attempting to retrieve this error.
      data:
        type: object
        properties:
          acuteMedications:
            type: array
            description: Array of acuteMedications
            items:
              $ref: '#/definitions/MedicationItem'
          currentRepeatMedications:
            type: array
            description: Array of acuteMedications
            items:
              $ref: '#/definitions/MedicationItem'
          discontinuedRepeatMedications:
            type: array
            description: Array of acuteMedications
            items:
              $ref: '#/definitions/MedicationItem'

  MedicationItem:
    type: object
    properties:
      date:
        type: string
        format: date-time
        description: The date/time of the item.
      lineItems:
        type: array
        description: An array of line items.
        items:
          $ref: '#/definitions/LineItem'

  LineItem:
    type: object
    properties:
      text:
        type: string
        description: When the record was entered.
      lineItems:
        type: array
        description: An array of line items
        items:
          type: string
          
  Immunisations:
    type: object
    properties:
      hasAccess:
        type: boolean
        description: Does the patient have access to this data.
      hasErrored:
        type: boolean
        description: Some error occurred when attempting to retrieve this error.
      data:
        type: object
        properties: 
          immunisations:
            type: array
            description: Array of immunisations.
            items:
              $ref: '#/definitions/ImmunisationItem'
        
  ImmunisationItem:
    type: object
    properties:
      effectiveDate:
        $ref: '#/definitions/Date'
      term:
        type: string
        description: The name of the immunisation.
            
  TestResults:
    type: object
    properties:
      hasAccess:
        type: boolean
        description: Does the patient have access to this data.
      hasErrored:
        type: boolean
        description: Some error occurred when attempting to retrieve this error.
      data:
        type: object
        properties: 
          testResults:
            type: array
            description: Array of test results
            items:
              $ref: '#/definitions/TestResultItem'
        
  TestResultItem:
    type: object
    properties:
      id:
        type: String
        description: Id of the test result
      date:
        $ref: '#/definitions/Date'
      description:
        type: string
        description: The name of the test result.
      associatedTexts:
        type: array
        description: Array of associated texts.
        items: string
      testResultChildItems:
        type: array
        description: Array of test result child line items.
        items:
          $ref: '#/definitions/TestResultChildLineItem'
  
  TestResultChildLineItem:
      type: object
      properties:
        description:
          type: string
          description: The name of the test result.
        associatedTexts:
          type: array
          description: Array of associated texts.
          items: string
                   
  Problems:
      type: object
      properties:
        hasAccess:
          type: boolean
          description: Does the patient have access to this data.
        hasErrored:
          type: boolean
          description: Some error occurred when attempting to retrieve this error.
        data:
          type: object
          properties: 
             problems:
              type: array
              description: Array of problems
              items:
                $ref: '#/definitions/ProblemItem'
          
  ProblemItem:
    type: object
    properties:
      effectiveDate:
        $ref: '#/definitions/Date'
      lineItems:
        type: array
        description: An array of line items.
        items:
          $ref: '#/definitions/LineItem'
  
  TppDcrEvents:
    type: object
    properties:
      hasAccess:
        type: boolean
        description: Does the patient have access to this data.
      hasErrored:
        type: boolean
        description: Some error occurred when attempting to retrieve this error.
      data:
        type: object
        properties: 
           problems:
            type: array
            description: Array of problems
            items:
              $ref: '#/definitions/TppDcrEvent'
    
  TppDcrEvent:
    type: object
    properties:
      effectiveDate:
        type: string
        format: date-time
        description: date/time value.
      eventLocationAndDoneBy:
        type: string
        description: Event location and done by
      eventItems:
        type: array
        description: Array of event items
        items:
          type: string 

  Consultations:
      type: object
      properties:
        hasAccess:
          type: boolean
          description: Does the patient have access to this data.
        hasErrored:
          type: boolean
          description: Some error occurred when attempting to retrieve this error.
        data:
          type: object
          properties: 
             problems:
              type: array
              description: Array of problems
              items:
                $ref: '#/definitions/ConsultationItem'
  
  ConsultationItem:
    type: object
    properties:
      effectiveDate:
        $ref: '#/definitions/Date'
      consultantLocation:
        type: string
        description: Consultant Location and Name
      consultationHeaders:
        type: array
        description: An array of consultationHeader.
        items:
          $ref: '#/definitions/ConsultationHeaderItem'
          
  ConsultationHeaderItem:
    type: object
    properties:
      header:
        type: string
        description: Consultation Header
      observations:
        type: array
        description: An array of observations.
        items:
          $ref: '#/definitions/ObservationItem'
  
  ObservationItem:
    type: object
    properties:
      term:
        type: string
        description: Observation Term
      associatedTexts:
        type: array
        description: An array of associated texts.
        items:
          type: string

  Date:
    type: object
    properties:
      value:
        type: string
        format: date-time
        description: date/time value.
      datePart:
        type: string
        description: date part to display.
        enum:
          - Unknown
          - Year
          - YearMonth
          - YearMonthDay
          - YearMonthDayTime
            