openapi: 3.0.2
info:
  version: 0.0.6
  title: NHS App Sub-API - Prescriptions
  description: NHS App Sub-API - endpoints pertaining to repeat prescriptions require
    NHSO-Session-Id cookie in header from session endpoint.
paths:
  /courses:
    get:
      tags:
        - courses
      summary: Gets a list of prescriptions courses for the given patient.
      description: Returns a list of prescriptions courses for the logged in user. Requires
        NHSO-Session-Id cookie in header from session endpoint.
      responses:
        "200":
          description: Returns list of courses and associated meta data. Returns empty
            collection of courses if GP system does not return a list of
            courses.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CourseListResponse"
        "401":
          description: User session missing or expired.
        "403":
          description: The patient does not have the necessary permissions within the GP
            system.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
        "500":
          description: An unexpected error occurred processing the request.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
        "502":
          description: Bad response received from upstream system.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
        "504":
          description: Timeout when calling upstream system.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
  /prescriptions:
    post:
      tags:
        - prescriptions
      summary: Creates a repeat prescription request for the logged in user
      description: For the given logged on user, will request a repeat prescription for a
        list of prescription courses. Requires NHSO-Session-Id cookie in header
        from session endpoint.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RepeatPrescriptionRequest"
        description: Repeat prescription request details to be created.
        required: true
        x-name: RepeatPrescriptionRequest
      responses:
        "201":
          description: Successful operation. Repeat Prescription Created.
        "202":
          description: Partial success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PrescriptionRequestPostPartialSuccessResponse"
        "400":
          description: Bad request. Supplied connection details or request data is
            incomplete or invalid.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"         
        "401":
          description: User session missing or expired.
        "403":
          description: The patient does not have the necessary permissions within the GP
            system.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
        "409":
          description: Conflict. A repeat prescription for the given course already exists
            preventing a new one to be created.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
        "466":
          description: The patient is trying to order medication which has already been
            ordered within the last 30 days.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
        "500":
          description: An unexpected error occurred processing the request.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
        "502":
          description: Bad response received from upstream system.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
        "504":
          description: Timeout when calling upstream system.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
    get:
      tags:
        - prescriptions
      summary: Gets a list of requested repeat prescriptions for the logged on user.
      description: For a given date range, returns a list of courses and repeat
        prescriptions for the logged in user. Requires NHSO-Session-Id cookie in
        header from session endpoint.
      parameters:
        - in: query
          name: fromDate
          required: false
          description: Repeat Prescription from date. Will default to 6 months ago if no
            value is supplied
          schema:
            type: string
            format: date-time
      responses:
        "200":
          description: Returns list of requested repeat prescriptions and associated meta
            data. Returns empty collection of repeat prescriptions if GP system
            does not return a list of prescriptions.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PrescriptionListResponse"
        "400":
          description: Bad request. All headers must be provided.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
        "401":
          description: User session has expired.
        "403":
          description: The patient does not have the necessary permissions within the GP
            system.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
        "500":
          description: An unexpected error occurred processing the request.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
        "502":
          description: Bad response received from upstream system.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
        "504":
          description: Timeout when calling upstream system.
          content:
            application/json:
              schema:
                $ref: "./nhsonline.shared.yaml#/components/schemas/PfsErrorResponse"
components:
  schemas:
    PrescriptionListResponse:
      type: object
      properties:
        prescriptions:
          type: array
          description: Array of repeat prescriptions.
          items:
            $ref: "#/components/schemas/PrescriptionItem"
        courses:
          type: array
          description: Array of prescription courses.
          items:
            $ref: "#/components/schemas/Course"
    CourseListResponse:
      type: object
      properties:
        courses:
          type: array
          description: An array of prescription courses
          items:
            $ref: "#/components/schemas/Course"
        specialRequestNecessity:
          $ref: "./nhsonline.shared.yaml#/components/schemas/Necessity"
          description: Indicates whether the patient can supply a special request when
            ordering a prescription.
        specialRequestCharacterLimit:
          type: integer
          description: The maximum number of characters permitted in the special request.
    RepeatPrescriptionRequest:
      type: object
      required:
        - courseIds
      properties:
        courseIds:
          type: array
          description: Array of course identifiers to create the prescription for.
          items:
            type: string
        specialRequest:
          type: string
          description: Optional free text that a user may supply in order to add a special
            request for the given prescription
    PrescriptionItem:
      type: object
      properties:
        courses:
          type: array
          description: Array of prescription courses.
          items:
            $ref: "#/components/schemas/CourseEntry"
        orderDate:
          type: string
          format: date-time
          description: The date on which the repeat prescription was ordered.
        status:
          type: string
          enum:
            - Unknown
            - Rejected
            - Requested
            - Approved
    CourseEntry:
      type: object
      properties:
        courseId:
          type: string
          description: Course identifier.
    Course:
      type: object
      properties:
        id:
          type: string
          description: Course identifier.
        name:
          type: string
          description: Course name.
        details:
          type: string
          description: Details of the course. Depending on the provider this may contain
            different information like dosage, quantity and status.
    PrescriptionRequestPostPartialSuccessResponse:
      type: object
      properties:
        successfulOrders:
          type: array
          description: successful orders array
          items:
            $ref: "#/components/schemas/Order"
        unsuccessfulOrders:
          type: array
          description: unsuccessful orders array
          items:
            $ref: "#/components/schemas/Order"
    Order:
      type: object
      properties:
        courseId:
          type: string
          description: course id
        name:
          type: string
          description: name of the drug
