openapi: 3.0.2
info:
  version: 0.0.1
  title: NHS Online Service Journey Rules API
  description: This is the API for NHS Online Service Journey Rules
paths:
  /api/servicejourneyrules:
    get:
      tags:
        - service-journey-rules
      summary: Gets the service journey rules for an ods code
      description: This call returns the service journey rules for an ods code.
      parameters:
        - in: query
          name: odsCode
          required: true
          description: ods code of patients practice
          schema:
            type: string
      responses:
        "200":
          description: Successful operation. Service Journey Rules returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServiceJourneyRulesResponse"
        "500":
          description: An unexpected error occurred processing the request.
components:
  schemas:
    ServiceJourneyRulesResponse:
      type: object
      properties:
        journeys:
          type: object
          properties:
            appointments:
              type: object
              oneOf:
                - $ref: "#/components/schemas/defaultProvider"
                - $ref: "#/components/schemas/informatica"
                - $ref: "#/components/schemas/linkedAccount"
                - $ref: "#/components/schemas/eConsult"
            cdssAdvice:
              type: object
              oneOf:
                - $ref: "#/components/schemas/cdssDisabled"
                - $ref: "#/components/schemas/cdssEnabled"
            cdssAdmin:
              type: object
              oneOf:
                - $ref: "#/components/schemas/cdssDisabled"
                - $ref: "#/components/schemas/cdssEnabled"
            medicalRecord:
              type: object
              oneOf:
                - $ref: "#/components/schemas/medicalRecord"
            prescriptions:
              type: object
              oneOf:
                - $ref: "#/components/schemas/defaultProvider"
            nominatedPharmacy:
              type: boolean
            notifications:
              type: boolean
            messaging:
              type: boolean
            userInfo:
              type: boolean
            documents:
              type: boolean
            im1Messaging:
              $ref: "#/components/schemas/im1Messaging"
    defaultProvider:
      type: object
      properties:
        provider:
          type: string
          description: The provider
          enum:
            - im1
            - gpAtHand
    linkedAccount:
      type: object
      properties:
        provider:
          type: string
          description: The provider
          enum:
            - linkedAccount
    eConsult:
      type: object
      properties:
        provider:
          type: string
          description: The provider
          enum:
            - eConsult
    informatica:
      type: object
      properties:
        provider:
          type: string
          description: The provider
          enum:
            - informatica
        informaticaUrl:
          type: string
          description: The informaticaUrl
    cdssDisabled:
      type: object
      properties:
        provider:
          type: string
          description: The provider
          enum:
            - none
    cdssEnabled:
      type: object
      properties:
        provider:
          type: string
          description: The cdss provider
          enum:
            - eConsult
            - stubs
        serviceDefinition:
          type: string
          description: The service definition
    medicalRecord:
      type: object
      properties:
        provider:
          type: string
          description: The provider
          enum:
          - im1
          - gpAtHand
        version:
          type: string
          description: The version of My Medical Records
          enum:
          - 1
          - 2
    im1Messaging: 
      type: object
      properties:
        isEnabled:
          type: boolean
        canDeleteMessages:
          type: boolean
    LinkedAccountsConfigResponse:
      type: object
      properties:
        id:
          type: string
          description: The guid of the current user
        hasLinkedAccounts:
          type: boolean