openapi: 3.0.2
info:
  version: 0.0.1
  title: NHS Online Service Journey Rules API
  description: This is the API for NHS Online Service Journey Rules
paths:
  /api/servicejourneyrules:
    get:
      tags:
        - service-journey-rules
      summary: Gets the service journey rules for an ods code
      description: This call returns the service journey rules for an ods code.
      parameters:
        - in: query
          name: odsCode
          required: true
          description: ods code of patients practice
          schema:
            type: string
      responses:
        200:
          description: Successful operation. Service Journey Rules returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServiceJourneyRulesResponse"
        500:
          description: An unexpected error occurred processing the request.
components:
  schemas:
    ServiceJourneyRulesResponse:
      type: object
      properties:
        appointments:
          type: object
          properties:
            provider:
              type: string
              description: The appointment provider
              enum:
                - im1
                - none