swagger: '2.0'

info:
  version: 0.0.3
  title: Emis PFS API - Citizen ID.
  description: This is the API for Emis PFS endpoints that are intended for consumption by Citizen ID.

schemes:
  - https

paths:
  /me/verifications:
    post:
      summary: "For a given nhs number and ods code, will find the user and add Citizen ID Verification"
      description: Will return a linkage key object for a given nhs number
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          name: X-API-EndUserSessionId
          required: true
          description: End user session token.
          type: string
        - in: header
          name: X-API-Version
          required: true
          description: Version of the API being used.
          type: string
        - in: header
          name: X-API-ApplicationId
          required: true
          description: The identity of the application making the call.
          type: string
        - in: body
          name: AddVerificationRequest
          required: true
          description: Patient account details who is Citizen ID Verified.
          schema:
            $ref: "#/definitions/AddVerificationRequest"
      responses:
        201:
          description: Successful operation. Citizen ID added Successfully.
          schema:
            $ref: "#/definitions/AddVerificationResponse"
        400:
          description: "The request was invalid. Further details are contained in the body and include<br><br>
          Error code - PracticeNotLive (-1401)<br/>
		      Error code - PatientMarkedAsArchived (-1552)<br/>
		      Error code - PatientNonCompetentOrUnder16 (-1553)<br/>
		      Error code - AccountStatusInvalid (-1107)"
        404:
          description: "NHS Number not found or online user not found. Further details are contained in the body.<br><br>
         	Error code - PatientNotRegisteredAtPractice (-1551)<br/>
		      Error code - NoRegisteredOnlineUserFound (-1104)"
        409:
          description: The user already exists with the citizen identity. The existing linkage key details will be returned.
        500:
          description: An unexpected error occurred processing the request.
        502:
          description: The GP system is currently unavailable.
        504:
          description: The GP system did not respond in a timely fashion.
  /users/nhs:
    post:
      summary: "Creates a restricted user account (OSU) that is associated with their own patient record"
      description: For a patient with the specified NHS number, a self associated restricted user account will be created.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          name: X-API-EndUserSessionId
          required: true
          description: End user session token.
          type: string
        - in: header
          name: X-API-Version
          required: true
          description: Version of the API being used.
          type: string
        - in: header
          name: X-API-ApplicationId
          required: true
          description: The identity of the application making the call.
          type: string
        - in: body
          name: AddNhsUserRequest
          required: true
          description: Patient account details used to create the online user.
          schema:
            $ref: "#/definitions/AddNhsUserRequest"
      responses:
        201:
          description: Successful operation. The online user was created and associated with the patient.
          schema:
            $ref: "#/definitions/AddNhsUserResponse"
        400:
          description: "The request was invalid. Further details are contained in the body. <br><br>
          Error code - PracticeNotLive (-1401)<br/>
		      Error code - PatientMarkedAsArchived (-1552)<br/>
		      Error code - PatientNonCompetentOrUnder16 (-1553)"
        404:
          description: No patient could be found matching the given NHS Number and ODS code.
        409:
          description: The patient already has an online account.
        500:
          description: An unexpected error occurred processing the request.
definitions:
  PatientNhsNumber:
    type: object
    properties:
        NHSNumber:
         type: string
         description: Patient's NHS number.
  AddNhsUserRequest:
    type: object
    required: [NationalPracticeCode, NHSNumber, EmailAddress]
    properties:
      NationalPracticeCode:
        type: string
        description: User's ODS Code
      NHSNumber:
        type: string
        description: NHS Number
      EmailAddress:
        type: string
        description: The email address used for the online user account
  AddNhsUserResponse:
    type: object
    properties:
      AccessIdentityGuid:
        type: string
        description: The access identity guid that represents the online user
  AddVerificationResponse:
    type: object
    properties:
      AccountId:
        type: string
        description: The user's ROSU Account id.
      IdentityId:
        type: number
        description:
      LinkageKey:
        type: string
        description: The user's linkage passphrase.
  AddVerificationRequest:
    type: object
    required: [NationalPracticeCode, NHSNumber, Token]
    properties:
      NationalPracticeCode:
        type: string
        description: User's ODS Code
      NHSNumber:
        type: string
        description: NHS Number
      Token:
        type: string
        description: Token of Citizen Identity
      AdditionalComment:
        type: string
        description: Any addition text