package features.linkage

enum class LinkageResult {
    NoneSpecified,
    SuccessfullyRetrievedFirstTime,
    SuccessfullyRetrieved,
    DetailsDoNotMatchInPDS,
    IncompletePFSRegistration,
    LastNameDoesNotMatch,
    DOBDoesNotMatch,
    PatientNotOldEnough,
    NoPatientWithNHSNumber,
    PatientNotRegisteredAtSpecifiedPractice,
    ErrorCreatingNewPFSAccountAndLinkageKeys,
    AccountStatusInvalid,
    PatientNonCompetentOrUnderMinimumAge,
    PatientMarkedAsArchived,
    NoRegisteredOnlineUserFound,
    PatientNotRegisteredAtPractice,
    PracticeNotLive,
    PatientAlreadyHasAnOnlineAccount,
    SuccessfullyCreated,
    InternalServerError,
    InvalidNhsNumber,
    PatientRecordNotFound,
    LinkageKeyRevoked,
    LinkageKeyAlreadyExists,
    MultipleRecordsFound,
    NoUserAssociatedWithNHSNumber,
    NoApiKeyAssociatedWithNHSNumber
}
