---
apiVersion: v1
kind: Service
metadata:
  name: default-api
  labels:
    role: default-api
    releaseVersion: {{ default "develop" .Values.api.version }}
spec:
  selector:
    role: {{ default "api" .Values.api.role }}
    version: {{ default "develop" .Values.api.version }}
  ports:
    - port: {{ .Values.defaultServicePort }}
      targetPort: {{ .Values.sidecar_proxy.containerPort }}
