---
apiVersion: v1
kind: Service
metadata:
  name: default-info
  labels:
    role: default-info
    releaseVersion: {{ default "develop" .Values.info.version }}
spec:
  selector:
    role: {{ default "info" .Values.info.role }}
    version: {{ default "develop" .Values.info.version }}
  ports:
    - port: {{ .Values.defaultServicePort }}
      targetPort: {{ .Values.sidecar_proxy.containerPort }}
