---
apiVersion: v1
kind: Service
metadata:
  name: default-messages
  labels:
    role: default-messages
    releaseVersion: {{ default "develop" .Values.messages.version }}
spec:
  selector:
    role: {{ default "messages" .Values.messages.role }}
    version: {{ default "develop" .Values.messages.version }}
  ports:
    - port: {{ .Values.defaultServicePort }}
      targetPort: {{ .Values.sidecar_proxy.containerPort }}
