---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'false'
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: default-messages
  labels:
    role: default-messages
    releaseVersion: {{ default "develop" .Values.messages.version }}
spec:
  rules:
    - host: api{{ .Values.environmentPublicHostSuffix }}
      http:
        paths:
          - path: /v[1,2]/api/users/me/messages
            pathType: ImplementationSpecific
            backend:
              service:
                name: default-messages
                port:
                  number: {{ .Values.defaultServicePort }}
          - path: /v[1,2]/api/users/([A-Za-z0-9-:]{36,37})/messages
            pathType: ImplementationSpecific
            backend:
              service:
                name: default-messages
                port:
                  number: {{ .Values.defaultServicePort }}
  tls:
    - hosts:
        - api{{ .Values.environmentPublicHostSuffix }}
      secretName: {{ .Values.tlsSecretName }}
