---
apiVersion: v1
kind: Service
metadata:
  name: default-users
  labels:
    role: default-users
    releaseVersion: {{ default "develop" .Values.users.version }}
spec:
  selector:
    role: {{ default "users" .Values.users.role }}
    version: {{ default "develop" .Values.users.version }}
  ports:
    - port: {{ .Values.defaultServicePort }}
      targetPort: {{ .Values.sidecar_proxy.containerPort }}
