---
apiVersion: v1
kind: Service
metadata:
  name: default-www
  labels:
    role: default-www
    releaseVersion: {{ default "develop" .Values.www.version }}
spec:
  selector:
    role: {{ default "www" $.Values.www.role }}
    version: {{ default "develop" $.Values.www.version }}
  ports:
    - port: {{ $.Values.defaultServicePort }}
      targetPort: {{ .Values.sidecar_proxy.containerPort }}
