// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.0.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace NHSOnline.Backend.Worker.IntegrationTests.Features.Emis.Im1Connection.Registration
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class EMISPatientRegistrationValidationFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
#line 1 "PatientRegistrationValidation.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "EMIS Patient Registration Validation", "    In order to allow users login to NHS online app\r\n    As a Citizen ID User\r\n  " +
                    "  I want to be able to register an EMIS user\'s IM1 credentials", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "EMIS Patient Registration Validation")))
            {
                global::NHSOnline.Backend.Worker.IntegrationTests.Features.Emis.Im1Connection.Registration.EMISPatientRegistrationValidationFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(TestContext);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Registering an EMIS user\'s IM1 credentials with an ODS Code not in the expected f" +
            "ormat returns a \"Bad Request\" error message")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EMIS Patient Registration Validation")]
        public virtual void RegisteringAnEMISUsersIM1CredentialsWithAnODSCodeNotInTheExpectedFormatReturnsABadRequestErrorMessage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Registering an EMIS user\'s IM1 credentials with an ODS Code not in the expected f" +
                    "ormat returns a \"Bad Request\" error message", ((string[])(null)));
#line 6
    this.ScenarioSetup(scenarioInfo);
#line 7
        testRunner.Given("I have an EMIS user\'s IM1 credentials with an ODS Code not in the expected format" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
        testRunner.When("I register an EMIS user\'s IM1 credentials", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
        testRunner.Then("I receive a \"Bad Request\" error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Registering an EMIS user\'s IM1 credentials with a Surname not in the expected for" +
            "mat returns a \"Bad Request\" error message")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EMIS Patient Registration Validation")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("bug")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("wip")]
        public virtual void RegisteringAnEMISUsersIM1CredentialsWithASurnameNotInTheExpectedFormatReturnsABadRequestErrorMessage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Registering an EMIS user\'s IM1 credentials with a Surname not in the expected for" +
                    "mat returns a \"Bad Request\" error message", new string[] {
                        "bug",
                        "wip"});
#line 13
    this.ScenarioSetup(scenarioInfo);
#line 14
        testRunner.Given("I have an EMIS user\'s IM1 credentials with a Surname not in the expected format", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 15
        testRunner.When("I register an EMIS user\'s IM1 credentials", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 16
        testRunner.Then("I receive a \"Bad Request\" error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Registering an EMIS user\'s IM1 credentials with an Account ID not in the expected" +
            " format returns a \"Bad Request\" error message")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EMIS Patient Registration Validation")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("bug")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("wip")]
        public virtual void RegisteringAnEMISUsersIM1CredentialsWithAnAccountIDNotInTheExpectedFormatReturnsABadRequestErrorMessage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Registering an EMIS user\'s IM1 credentials with an Account ID not in the expected" +
                    " format returns a \"Bad Request\" error message", new string[] {
                        "bug",
                        "wip"});
#line 20
    this.ScenarioSetup(scenarioInfo);
#line 21
        testRunner.Given("I have an EMIS user\'s IM1 credentials with an Account ID not in the expected form" +
                    "at", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 22
        testRunner.When("I register an EMIS user\'s IM1 credentials", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 23
        testRunner.Then("I receive a \"Bad Request\" error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Registering an EMIS user\'s IM1 credentials with a Linkage Key not in the expected" +
            " format returns a \"Bad Request\" error message")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EMIS Patient Registration Validation")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("bug")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("wip")]
        public virtual void RegisteringAnEMISUsersIM1CredentialsWithALinkageKeyNotInTheExpectedFormatReturnsABadRequestErrorMessage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Registering an EMIS user\'s IM1 credentials with a Linkage Key not in the expected" +
                    " format returns a \"Bad Request\" error message", new string[] {
                        "bug",
                        "wip"});
#line 27
    this.ScenarioSetup(scenarioInfo);
#line 28
        testRunner.Given("I have an EMIS user\'s IM1 credentials with a Linkage Key not in the expected form" +
                    "at", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 29
        testRunner.When("I register an EMIS user\'s IM1 credentials", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 30
        testRunner.Then("I receive a \"Bad Request\" error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Registering an EMIS user\'s IM1 credentials with a Date Of Birth not in the expect" +
            "ed format returns a \"Bad Request\" error message")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EMIS Patient Registration Validation")]
        public virtual void RegisteringAnEMISUsersIM1CredentialsWithADateOfBirthNotInTheExpectedFormatReturnsABadRequestErrorMessage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Registering an EMIS user\'s IM1 credentials with a Date Of Birth not in the expect" +
                    "ed format returns a \"Bad Request\" error message", ((string[])(null)));
#line 32
    this.ScenarioSetup(scenarioInfo);
#line 33
        testRunner.Given("I have an EMIS user\'s IM1 credentials with a Date Of Birth not in the expected fo" +
                    "rmat", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 34
        testRunner.When("I register an EMIS user\'s IM1 credentials", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 35
        testRunner.Then("I receive a \"Bad Request\" error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Registering an EMIS user\'s IM1 credentials with missing ODS Code returns a \"Bad R" +
            "equest\" error message")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EMIS Patient Registration Validation")]
        public virtual void RegisteringAnEMISUsersIM1CredentialsWithMissingODSCodeReturnsABadRequestErrorMessage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Registering an EMIS user\'s IM1 credentials with missing ODS Code returns a \"Bad R" +
                    "equest\" error message", ((string[])(null)));
#line 37
    this.ScenarioSetup(scenarioInfo);
#line 38
        testRunner.Given("I have an EMIS user\'s IM1 credentials with missing ODS Code", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 39
        testRunner.When("I register an EMIS user\'s IM1 credentials", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 40
        testRunner.Then("I receive a \"Bad Request\" error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Registering an EMIS user\'s IM1 credentials with missing Surname returns a \"Bad Re" +
            "quest\" error message")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EMIS Patient Registration Validation")]
        public virtual void RegisteringAnEMISUsersIM1CredentialsWithMissingSurnameReturnsABadRequestErrorMessage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Registering an EMIS user\'s IM1 credentials with missing Surname returns a \"Bad Re" +
                    "quest\" error message", ((string[])(null)));
#line 42
    this.ScenarioSetup(scenarioInfo);
#line 43
        testRunner.Given("I have an EMIS user\'s IM1 credentials with missing Surname", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 44
        testRunner.When("I register an EMIS user\'s IM1 credentials", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 45
        testRunner.Then("I receive a \"Bad Request\" error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Registering an EMIS user\'s IM1 credentials with missing Account ID returns a \"Bad" +
            " Request\" error message")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EMIS Patient Registration Validation")]
        public virtual void RegisteringAnEMISUsersIM1CredentialsWithMissingAccountIDReturnsABadRequestErrorMessage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Registering an EMIS user\'s IM1 credentials with missing Account ID returns a \"Bad" +
                    " Request\" error message", ((string[])(null)));
#line 47
    this.ScenarioSetup(scenarioInfo);
#line 48
        testRunner.Given("I have an EMIS user\'s IM1 credentials with missing Account ID", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 49
        testRunner.When("I register an EMIS user\'s IM1 credentials", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 50
        testRunner.Then("I receive a \"Bad Request\" error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Registering an EMIS user\'s IM1 credentials with missing Linkage Key returns a \"Ba" +
            "d Request\" error message")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EMIS Patient Registration Validation")]
        public virtual void RegisteringAnEMISUsersIM1CredentialsWithMissingLinkageKeyReturnsABadRequestErrorMessage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Registering an EMIS user\'s IM1 credentials with missing Linkage Key returns a \"Ba" +
                    "d Request\" error message", ((string[])(null)));
#line 52
    this.ScenarioSetup(scenarioInfo);
#line 53
        testRunner.Given("I have an EMIS user\'s IM1 credentials with missing Linkage Key", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 54
        testRunner.When("I register an EMIS user\'s IM1 credentials", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 55
        testRunner.Then("I receive a \"Bad Request\" error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
