swagger: '2.0'

info:
  version: 0.0.4
  title: NHS Online API
  description: This is the API for NHS online.

schemes:
  - https

paths:
  /v1/patient/appointment-slots:
    $ref: './nhsonline.appointments.yaml#/paths/~1appointment-slots'
  /v1/patient/appointments:
    $ref: './nhsonline.appointments.yaml#/paths/~1appointments'
  /v1/patient/prescriptions:
    $ref: './nhsonline.prescriptions.yaml#/paths/~1prescriptions'
  /v1/patient/courses:
    # Course endpoints are in the prescriptions file as they share the course definitions
    $ref: './nhsonline.prescriptions.yaml#/paths/~1courses'
  /v1/session:
    $ref: './nhsonline.usersession.yaml#/paths/~1session'
