swagger: '2.0'

info:
  version: 0.0.3
  title: NHS Online API
  description: This is the API for NHS online.

schemes:
  - https

paths:
  /v1/patient/appointmentslots:
    $ref: './nhsonline.appointments.yaml#/paths/~1appointmentslots'
  /v1/session:
    $ref: './nhsonline.usersession.yaml#/paths/~1session'
  