apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nhsonline-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nhsonline-web
    spec:
      containers:
      - name: nhsonline-web
        image: nhsonline.azurecr.io/nhsonline-web:latest
        ports:
        - containerPort: 3000
        env:
        - name: CID_REDIRECT_URI
          value: "https://www-preview.nonliveeuw.bitraft.io/auth-return"
        - name: API_HOST
          value: "https://api-preview.nonliveeuw.bitraft.io"
      imagePullSecrets:
       - name: azure-registry
