apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nhsonline-backendworker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nhsonline-backendworker
    spec:
      containers:
      - name: nhsonline-backendworker
        image: nhsonline.azurecr.io/nhsonline-backendworker:latest
        ports:
        - containerPort: 5123
        env:
        - name: STUBS_ENDPOINT_URL
          value: "http://nhsonline-stubs:5123"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
      imagePullSecrets:
       - name: azure-registry
