#!/usr/bin/env bash
function die () {
    echo >&2 "===]> Error: $@ "
    exit 1
}

function close () {
    echo >&2 "===]> Info: $@ "
    exit 0
}

function info () {
    echo >&2 "===]> Info: $@ ";
}
