#!/usr/bin/env bash
[ -z "$GIT_HOME_DIR" ]     && die "You need to set the GIT_HOME_DIR to the root directory of the git repo"

source ${GIT_HOME_DIR}/script_helpers/dependency_check
source ${GIT_HOME_DIR}/script_helpers/formatting

function unlock_repo () {
    info "Unlocking git repository"
    git-crypt unlock ~/.cicd.key || die "Problem decrypting secrets with git-crypt within repository"
}
