#!/bin/bash

DOCKER_IMAGE=${DOCKER_IMAGE_BROWSERSTACK}
DOCKER_TEST_RUN_IMAGES+=("$DOCKER_IMAGE_BROWSERSTACK")
DOCKER_COMPOSE_FILES_TRANCHE+=('../docker/bddtests/docker-compose.browserstack.yml')
BROWSERSTACK_USERNAME=${BROWSERSTACK_USERNAME:-ops20}
BROWSERSTACK_BUILD=${BROWSERSTACK_BUILD:-local}
BROWSERSTACK_LOCAL_IDENTIFIER=${BROWSERSTACK_LOCAL_IDENTIFIER:-$DOCKER_NETWORK}

EXCLUDE_TAGS+=("${TAGS_NEVER_RUN[@]}")
EXCLUDE_TAGS+=(nativepending nativebug)
EXCLUDE_TAGS_ARGS=$(join_by ' and not @' "${EXCLUDE_TAGS[@]}")
TAGS="@$TRANCHE_TAG and not @$EXCLUDE_TAGS_ARGS"

info "TAGS: $TAGS"

info "Uploading native app to BrowserStack: $NATIVE_APP_PATH"

BROWSERSTACK_APPPATH=$(curl \
  -u "$BROWSERSTACK_USERNAME:$BROWSERSTACK_ACCESS_KEY" \
  -X POST \
  -F "file=@$NATIVE_APP_PATH" \
  "https://api-cloud.browserstack.com/app-automate/upload" | sed -e 's/^.*"app_url":"\([^"]*\)".*$/\1/')

info "BROWSERSTACK_APPPATH: $BROWSERSTACK_APPPATH"

TRANCHE_RUN_ADDITIONAL_ARGS+=(--env "BROWSERSTACK_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY")
TRANCHE_RUN_ADDITIONAL_ARGS+=(--env "BROWSERSTACK_USERNAME=$BROWSERSTACK_USERNAME")
TRANCHE_RUN_ADDITIONAL_ARGS+=(--env "BROWSERSTACK_BUILD=$BROWSERSTACK_BUILD")
TRANCHE_RUN_ADDITIONAL_ARGS+=(--env "BROWSERSTACK_DEVICE_NAME=$BROWSERSTACK_DEVICE_NAME")
TRANCHE_RUN_ADDITIONAL_ARGS+=(--env "BROWSERSTACK_OS_VERSION=$BROWSERSTACK_OS_VERSION")
TRANCHE_RUN_ADDITIONAL_ARGS+=(--env "APP_PATH=$BROWSERSTACK_APPPATH")
TRANCHE_RUN_ADDITIONAL_ARGS+=(--env "BROWSERSTACK_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER")
TRANCHE_RUN_ADDITIONAL_ARGS+=(--env "APP_SCHEME=nhsapp")
TRANCHE_RUN_ADDITIONAL_ARGS+=(--env "AUTOLOGIN=true")
TRANCHE_RUN_ADDITIONAL_ARGS+=(--env "XPATH_PAGE_SOURCE=false")
TRANCHE_RUN_ADDITIONAL_ARGS+=(--env "SESSION_EXPIRY_MINUTES=5")
TRANCHE_RUN_ADDITIONAL_ARGS+=(--env "IS_NATIVE_APP_RUN=true")
TRANCHE_RUN_ADDITIONAL_ARGS+=(-v "$WORKING_DIR/logs://logs")

TRANCHE_RUN_SETUP="(BrowserStackLocal --key \"\$BROWSERSTACK_ACCESS_KEY\" --force-local --local-identifier \"$BROWSERSTACK_LOCAL_IDENTIFIER\" --log-file /logs/browserstack.log &) ;"

# shellcheck source=run_tests.sh
source "buildscripts/lib/run_tests.sh"
