#!/bin/bash

export DOCKER_COMPOSE_FILES_TRANCHE=()
export DOCKER_TEST_RUN_IMAGES=()
export TRANCHE_RUN_ADDITIONAL_ARGS=()
export TRANCHE_RUN_SETUP=
export TRANCHE_RUN_GRADLE_TASKS=(compileTestKotlin test aggregate)
export TRANCHE_RUN_GRADLE_ARGS=(--stacktrace "-Dwebdriver.base.url=http://web.local.bitraft.io:3000")

export APP_DOCKER_REGISTRY=${DOCKER_REGISTRY:-local}
export APP_DOCKER_TAG=${DOCKER_TAG:-latest}

export DOCKER_PROJECT_NAME="${DOCKER_PROJECT_NAME:-int_test}"
export DOCKER_NETWORK="${DOCKER_PROJECT_NAME}_default"

export DOCKER_REGISTRY=${DOCKER_REGISTRY:-nhsapp.azurecr.io}

# Should replace with an image that has just the required software
export DOCKER_IMAGE_GRADLE=${DOCKER_IMAGE_GRADLE:-$DOCKER_REGISTRY/chrome:latest}
export DOCKER_IMAGE_CHROME=${DOCKER_IMAGE_CHROME:-$DOCKER_REGISTRY/chrome:latest}
export DOCKER_IMAGE_BROWSERSTACK_LOCAL=${DOCKER_IMAGE_BROWSERSTACK_LOCAL:-$DOCKER_REGISTRY/nhsonline-browserstack-local:latest}

export DOCKER_IMAGE=${DOCKER_IMAGE_CHROME}

export BROWSER=${BROWSER:-chromeheadless}

if [[ $(uname -s) =~ ^MING.* ]]
then
  WORKING_DIR=$(pwd -W)
else
  WORKING_DIR=$(pwd)
fi

export NATIVE_APP_PATH_ANDROID=${NATIVE_APP_PATH_ANDROID:-../android/app/build/outputs/apk/browserstack/app-browserstack-unsigned.apk}

USER_ID=$(id -u)
GROUP_ID=$(id -g)

export WORKING_DIR
export USER_ID
export GROUP_ID

export WEB_DOCKER_TAG=${WEB_DOCKER_TAG:-$APP_DOCKER_TAG}
export WEB_DOCKER_REGISTRY=${WEB_DOCKER_REGISTRY:-$APP_DOCKER_REGISTRY}
export PFSAPI_DOCKER_TAG=${PFSAPI_DOCKER_TAG:-$APP_DOCKER_TAG}
export PFSAPI_DOCKER_REGISTRY=${PFSAPI_DOCKER_REGISTRY:-$APP_DOCKER_REGISTRY}
export CIDAPI_DOCKER_TAG=${CIDAPI_DOCKER_TAG:-$APP_DOCKER_TAG}
export CIDAPI_DOCKER_REGISTRY=${CIDAPI_DOCKER_REGISTRY:-$APP_DOCKER_REGISTRY}
export SJRCONFIG_DOCKER_TAG=${SJRCONFIG_DOCKER_TAG:-$APP_DOCKER_TAG}
export SJRCONFIG_DOCKER_REGISTRY=${SJRCONFIG_DOCKER_REGISTRY:-$APP_DOCKER_REGISTRY}
export SJRAPI_DOCKER_TAG=${SJRAPI_DOCKER_TAG:-$APP_DOCKER_TAG}
export SJRAPI_DOCKER_REGISTRY=${SJRAPI_DOCKER_REGISTRY:-$APP_DOCKER_REGISTRY}
export USERSAPI_DOCKER_TAG=${USERSAPI_DOCKER_TAG:-$APP_DOCKER_TAG}
export USERSAPI_DOCKER_REGISTRY=${USERSAPI_DOCKER_REGISTRY:-$APP_DOCKER_REGISTRY}
export USERINFOAPI_DOCKER_TAG=${USERINFOAPI_DOCKER_TAG:-$APP_DOCKER_TAG}
export USERINFOAPI_DOCKER_REGISTRY=${USERINFOAPI_DOCKER_REGISTRY:-$APP_DOCKER_REGISTRY}
export LOGAPI_DOCKER_TAG=${LOGAPI_DOCKER_TAG:-$APP_DOCKER_TAG}
export LOGAPI_DOCKER_REGISTRY=${LOGAPI_DOCKER_REGISTRY:-$APP_DOCKER_REGISTRY}
export MESSAGESAPI_DOCKER_TAG=${MESSAGESAPI_DOCKER_TAG:-$APP_DOCKER_TAG}
export MESSAGESAPI_DOCKER_REGISTRY=${MESSAGESAPI_DOCKER_REGISTRY:-$APP_DOCKER_REGISTRY}
