#!/bin/bash

DOCKER_COMPOSE_FILES_TRANCHE=()
DOCKER_TEST_RUN_IMAGES=()
TRANCHE_RUN_ADDITIONAL_ARGS=()
TRANCHE_RUN_SETUP=
TRANCHE_RUN_GRADLE_TASKS=(compileTestKotlin test aggregate)

export DOCKER_COMPOSE_FILES_TRANCHE
export DOCKER_TEST_RUN_IMAGES
export TRANCHE_RUN_ADDITIONAL_ARGS
export TRANCHE_RUN_SETUP
export TRANCHE_RUN_GRADLE_TASKS

APP_DOCKER_REGISTRY=${DOCKER_REGISTRY:-local}
APP_DOCKER_TAG=${DOCKER_TAG:-latest}

DOCKER_REGISTRY=${DOCKER_REGISTRY:-nhsapp.azurecr.io}

# Should replace with an image that has just the required software
DOCKER_IMAGE_GRADLE=${DOCKER_IMAGE_GRADLE:-$DOCKER_REGISTRY/chrome:latest}
DOCKER_IMAGE_CHROME=${DOCKER_IMAGE_CHROME:-$DOCKER_REGISTRY/chrome:latest}

if [[ $(uname -s) =~ ^MING.* ]]
then
  WORKING_DIR=$(pwd -W)
else
  WORKING_DIR=$(pwd)
fi

USER_ID=$(id -u)
GROUP_ID=$(id -g)

export DOCKER_REGISTRY
export DOCKER_IMAGE_GRADLE
export DOCKER_IMAGE_CHROME
export WORKING_DIR
export USER_ID
export GROUP_ID

export WEB_DOCKER_TAG=${WEB_DOCKER_TAG:-$APP_DOCKER_TAG}
export WEB_DOCKER_REGISTRY=${WEB_DOCKER_REGISTRY:-$APP_DOCKER_REGISTRY}
export PFSAPI_DOCKER_TAG=${PFSAPI_DOCKER_TAG:-$APP_DOCKER_TAG}
export PFSAPI_DOCKER_REGISTRY=${PFSAPI_DOCKER_REGISTRY:-$APP_DOCKER_REGISTRY}
export CIDAPI_DOCKER_TAG=${CIDAPI_DOCKER_TAG:-$APP_DOCKER_TAG}
export CIDAPI_DOCKER_REGISTRY=${CIDAPI_DOCKER_REGISTRY:-$APP_DOCKER_REGISTRY}
export SJRCONFIG_DOCKER_TAG=${SJRCONFIG_DOCKER_TAG:-$APP_DOCKER_TAG}
export SJRCONFIG_DOCKER_REGISTRY=${SJRCONFIG_DOCKER_REGISTRY:-$APP_DOCKER_REGISTRY}
export SJRAPI_DOCKER_TAG=${SJRAPI_DOCKER_TAG:-$APP_DOCKER_TAG}
export SJRAPI_DOCKER_REGISTRY=${SJRAPI_DOCKER_REGISTRY:-$APP_DOCKER_REGISTRY}
export USERSAPI_DOCKER_TAG=${USERSAPI_DOCKER_TAG:-$APP_DOCKER_TAG}
export USERSAPI_DOCKER_REGISTRY=${USERSAPI_DOCKER_REGISTRY:-$APP_DOCKER_REGISTRY}
export USERINFOAPI_DOCKER_TAG=${USERINFOAPI_DOCKER_TAG:-$APP_DOCKER_TAG}
export USERINFOAPI_DOCKER_REGISTRY=${USERINFOAPI_DOCKER_REGISTRY:-$APP_DOCKER_REGISTRY}
export LOGAPI_DOCKER_TAG=${LOGAPI_DOCKER_TAG:-$APP_DOCKER_TAG}
export LOGAPI_DOCKER_REGISTRY=${LOGAPI_DOCKER_REGISTRY:-$APP_DOCKER_REGISTRY}
export MESSAGESAPI_DOCKER_TAG=${MESSAGESAPI_DOCKER_TAG:-$APP_DOCKER_TAG}
export MESSAGESAPI_DOCKER_REGISTRY=${MESSAGESAPI_DOCKER_REGISTRY:-$APP_DOCKER_REGISTRY}
