#!/usr/bin/env bash
[ -z "$GIT_HOME_DIR" ]     && die "You need to set the GIT_HOME_DIR to the root directory of the git repo"

source ${GIT_HOME_DIR}/script_helpers/formatting

function helm_init () {
if  kubectl get secret helm-tls-key-pair --namespace=kube-system 2>&1 > /dev/null ; then
    info "Retreiving certs and configuring client side Helm to use TLS"
    helm init --client-only
	kubectl --namespace=kube-system get secret internal-ca-key-pair -o jsonpath --template '{.data.tls\.crt}' | base64 -d > $(helm home)/ca.pem
	kubectl --namespace=kube-system get secret helm-tls-key-pair -o jsonpath --template '{.data.tls\.crt}' | base64 -d > $(helm home)/cert.pem
	kubectl --namespace=kube-system get secret helm-tls-key-pair -o jsonpath --template '{.data.tls\.key}' | base64 -d > $(helm home)/key.pem
    helm init --upgrade --force-upgrade --client-only
    helm ls --tls
else
    info "No TLS certs exist for Helm. Starting client side Helm without TLS"
    helm init --upgrade --force-upgrade --client-only
fi
}
