---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "nhsapp.name" . }}-{{ $.Values.stubs.role }}-{{ .Chart.AppVersion | replace "." "-" }}
  namespace: {{ $.Values.global.environment }}
  labels:
    app: {{ template "nhsapp.name" . }}-{{ $.Values.stubs.role }}
    role: {{ $.Values.stubs.role }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  selector:
    role: {{ $.Values.stubs.role }}
    version: {{ .Chart.AppVersion | quote }}
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: https
    protocol: TCP
    port: {{ $.Values.sidecar_proxy.containerPort }}
    targetPort: {{ $.Values.sidecar_proxy.containerPort }}
