apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nhsonline-backendworker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nhsonline-backendworker
    spec:
      containers:
      - name: nhsonline-backendworker
        image: nhsapp.azurecr.io/nhsonline-backendworker:latest
        ports:
        - containerPort: 8082
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: REDIS_ODSLOOKUP_CONFIG
          value: "redis:6379"
        - name: REDIS_SESSION_CONFIG
          value: "redis2:6379"
        - name: EMIS_BASE_URL
          value: "http://185.13.72.81/PFS/"
        - name: EMIS_APPLICATION_ID
          value: "D66BA979-60D2-49AA-BE82-AEC06356E41F"
        - name: EMIS_VERSION
          value: "2.1.0.0"
        - name: NHS_WEB_APP_BASE_URL
          value: "https://www-preview.nonliveeuw.bitraft.io/"
        - name: CORS_AUTHORITY
          value: "https://www-preview.nonliveeuw.bitraft.io"
      imagePullSecrets:
       - name: azure-registry
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nhsonline-wiremock
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nhsonline-wiremock
    spec:
      containers:
      - name: nhsonline-wiremock
        image: nhsapp.azurecr.io/wiremock:2.17.0-alpine
        ports:
        - containerPort: 8080
        env:
        - name: WIREMOCK_AUTHORITY
          value: "nhsonline-wiremock:8080"
        - name: WAIT_FOR_TIMEOUT
          value: "60"
      imagePullSecrets:
       - name: azure-registry
