import { INDEX_CRUMB } from '@/breadcrumbs/general';
import {
  APPOINTMENTS_NAME,
  GP_APPOINTMENTS_NAME,
  HOSPITAL_APPOINTMENTS_NAME,
} from '@/router/names';

const UPLIFT_APPOINTMENTS_CRUMB = {
  defaultCrumb: [INDEX_CRUMB],
  nativeDisabled: true,
};

export const APPOINTMENTS_CRUMB = {
  defaultCrumb: [INDEX_CRUMB],
  i18nKey: 'appointments',
  name: APPOINTMENTS_NAME,
  nativeDisabled: true,
};

export const GP_APPOINTMENTS_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, APPOINTMENTS_CRUMB],
  i18nKey: 'gpAppointments',
  name: GP_APPOINTMENTS_NAME,
};

const HOSPITAL_APPOINTMENTS_CRUMB = {
  name: HOSPITAL_APPOINTMENTS_NAME,
  defaultCrumb: [INDEX_CRUMB, APPOINTMENTS_CRUMB],
};

const GP_AT_HAND_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, APPOINTMENTS_CRUMB],
};

const INFORMATICA_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, APPOINTMENTS_CRUMB],
};

const BOOKING_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, APPOINTMENTS_CRUMB, GP_APPOINTMENTS_CRUMB],
};

const CONFIRMATION_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, APPOINTMENTS_CRUMB, GP_APPOINTMENTS_CRUMB],
};

const BOOKING_SUCCESS_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, APPOINTMENTS_CRUMB, GP_APPOINTMENTS_CRUMB],
  nativeDisabled: true,
};

const ADD_TO_CALENDAR_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, APPOINTMENTS_CRUMB],
};

const CANCELLING_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, APPOINTMENTS_CRUMB, GP_APPOINTMENTS_CRUMB],
};

const CANCELLING_SUCCESS_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, APPOINTMENTS_CRUMB, GP_APPOINTMENTS_CRUMB],
  nativeDisabled: true,
};

const ADMIN_HELP_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, APPOINTMENTS_CRUMB, GP_APPOINTMENTS_CRUMB],
  moreCrumb: [INDEX_CRUMB],
};

const GP_ADVICE_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, APPOINTMENTS_CRUMB, GP_APPOINTMENTS_CRUMB],
  adviceCrumb: [INDEX_CRUMB],
};

export default {
  UPLIFT_APPOINTMENTS_CRUMB,
  APPOINTMENTS_CRUMB,
  GP_APPOINTMENTS_CRUMB,
  HOSPITAL_APPOINTMENTS_CRUMB,
  GP_AT_HAND_CRUMB,
  INFORMATICA_CRUMB,
  BOOKING_CRUMB,
  CONFIRMATION_CRUMB,
  BOOKING_SUCCESS_CRUMB,
  ADD_TO_CALENDAR_CRUMB,
  CANCELLING_CRUMB,
  CANCELLING_SUCCESS_CRUMB,
  ADMIN_HELP_CRUMB,
  GP_ADVICE_CRUMB,
};
