import { INDEX_CRUMB } from '@/breadcrumbs/general';
import { MORE_NAME, MORE_ACCOUNTANDSETTINGS_NAME, MORE_ACCOUNTANDSETTINGS_LEGALANDCOOKIES_NAME } from '@/router/names';

export const MORE_CRUMB = {
  defaultCrumb: [INDEX_CRUMB],
  i18nKey: 'more',
  name: MORE_NAME,
  nativeDisabled: true,
};

export const ACCOUNT_AND_SETTINGS_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, MORE_CRUMB],
  i18nKey: 'accountAndSettings',
  name: MORE_ACCOUNTANDSETTINGS_NAME,
  nativeDisabled: true,
};

export const LEGAL_AND_COOKIES_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, MORE_CRUMB, ACCOUNT_AND_SETTINGS_CRUMB],
  i18nKey: 'legalAndCookies',
  name: MORE_ACCOUNTANDSETTINGS_LEGALANDCOOKIES_NAME,
  nativeDisabled: true,
};

const MORE_COOKIES_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, MORE_CRUMB],
};

const MORE_NOTIFICATIONS_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, MORE_CRUMB],
};

const MORE_LOGIN_SETTINGS_INDEX_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, MORE_CRUMB],
};

const MORE_LOGIN_SETTINGS_ERROR_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, MORE_CRUMB],
};

const MORE_ACCOUNT_AND_SETTINGS_INDEX_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, MORE_CRUMB],
};

const MORE_ACCOUNT_AND_SETTINGS_LEGAL_AND_COOKIES_INDEX_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, MORE_CRUMB, ACCOUNT_AND_SETTINGS_CRUMB],
};

const MORE_ACCOUNT_AND_SETTINGS_LEGAL_AND_COOKIES_MANAGE_COOKIES_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, MORE_CRUMB, ACCOUNT_AND_SETTINGS_CRUMB, LEGAL_AND_COOKIES_CRUMB],
};

export default {
  MORE_CRUMB,
  MORE_COOKIES_CRUMB,
  MORE_NOTIFICATIONS_CRUMB,
  MORE_LOGIN_SETTINGS_INDEX_CRUMB,
  MORE_LOGIN_SETTINGS_ERROR_CRUMB,
  MORE_ACCOUNT_AND_SETTINGS_INDEX_CRUMB,
  MORE_ACCOUNT_AND_SETTINGS_LEGAL_AND_COOKIES_INDEX_CRUMB,
  MORE_ACCOUNT_AND_SETTINGS_LEGAL_AND_COOKIES_MANAGE_COOKIES_CRUMB,
};
