import { INDEX_CRUMB } from '@/breadcrumbs/general';
import { PRESCRIPTIONS_CRUMB } from '@/breadcrumbs/prescriptions';
import {
  NOMINATED_PHARMACY_NAME,
  NOMINATED_PHARMACY_SEARCH_NAME,
  NOMINATED_PHARMACY_CONFIRM_NAME,
  NOMINATED_PHARMACY_CHANGE_SUCCESS_NAME,
  NOMINATED_PHARMACY_INTERRUPT_NAME,
  NOMINATED_PHARMACY_DSP_INTERRUPT_NAME,
  NOMINATED_PHARMACY_SEARCH_RESULTS_NAME,
  NOMINATED_PHARMACY_CHECK_NAME,
  NOMINATED_PHARMACY_CHOOSE_TYPE_NAME,
  NOMINATED_PHARMACY_ONLINE_ONLY_CHOICES_NAME,
  NOMINATED_PHARMACY_ONLINE_ONLY_SEARCH_NAME,
} from '@/router/names';

const NOMINATED_PHARMACY_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, PRESCRIPTIONS_CRUMB],
  name: NOMINATED_PHARMACY_NAME,
};

const NOMINATED_PHARMACY_SEARCH_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, PRESCRIPTIONS_CRUMB],
  name: NOMINATED_PHARMACY_SEARCH_NAME,
};

const NOMINATED_PHARMACY_CONFIRM_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, PRESCRIPTIONS_CRUMB],
  name: NOMINATED_PHARMACY_CONFIRM_NAME,
};

const NOMINATED_PHARMACY_CHANGE_SUCCESS_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, PRESCRIPTIONS_CRUMB],
  name: NOMINATED_PHARMACY_CHANGE_SUCCESS_NAME,
};

const NOMINATED_PHARMACY_INTERRUPT_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, PRESCRIPTIONS_CRUMB],
  name: NOMINATED_PHARMACY_INTERRUPT_NAME,
};

const NOMINATED_PHARMACY_DSP_INTERRUPT_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, PRESCRIPTIONS_CRUMB],
  name: NOMINATED_PHARMACY_DSP_INTERRUPT_NAME,
};

const NOMINATED_PHARMACY_SEARCH_RESULTS_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, PRESCRIPTIONS_CRUMB],
  name: NOMINATED_PHARMACY_SEARCH_RESULTS_NAME,
};

const NOMINATED_PHARMACY_CHECK_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, PRESCRIPTIONS_CRUMB],
  name: NOMINATED_PHARMACY_CHECK_NAME,
};

const NOMINATED_PHARMACY_CHOOSE_TYPE_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, PRESCRIPTIONS_CRUMB],
  name: NOMINATED_PHARMACY_CHOOSE_TYPE_NAME,
};

const NOMINATED_PHARMACY_ONLINE_ONLY_CHOICES_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, PRESCRIPTIONS_CRUMB],
  name: NOMINATED_PHARMACY_ONLINE_ONLY_CHOICES_NAME,
};

const NOMINATED_PHARMACY_ONLINE_ONLY_SEARCH_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, PRESCRIPTIONS_CRUMB],
  name: NOMINATED_PHARMACY_ONLINE_ONLY_SEARCH_NAME,
};

export default {
  NOMINATED_PHARMACY_CRUMB,
  NOMINATED_PHARMACY_SEARCH_CRUMB,
  NOMINATED_PHARMACY_CONFIRM_CRUMB,
  NOMINATED_PHARMACY_CHANGE_SUCCESS_CRUMB,
  NOMINATED_PHARMACY_INTERRUPT_CRUMB,
  NOMINATED_PHARMACY_DSP_INTERRUPT_CRUMB,
  NOMINATED_PHARMACY_SEARCH_RESULTS_CRUMB,
  NOMINATED_PHARMACY_CHECK_CRUMB,
  NOMINATED_PHARMACY_CHOOSE_TYPE_CRUMB,
  NOMINATED_PHARMACY_ONLINE_ONLY_CHOICES_CRUMB,
  NOMINATED_PHARMACY_ONLINE_ONLY_SEARCH_CRUMB,
};
