import { INDEX_CRUMB } from '@/breadcrumbs/general';
import { PRESCRIPTIONS_NAME } from '@/router/names';

export const PRESCRIPTIONS_CRUMB = {
  defaultCrumb: [INDEX_CRUMB],
  i18nKey: 'prescriptions',
  name: PRESCRIPTIONS_NAME,
  nativeDisabled: true,
};

export const PRESCRIPTIONS_VIEW_ORDERS_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, PRESCRIPTIONS_CRUMB],
};

export const PRESCRIPTION_REPEAT_COURSES_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, PRESCRIPTIONS_CRUMB],
};

export const PRESCRIPTION_CONFIRM_COURSES_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, PRESCRIPTIONS_CRUMB],
};

export const PRESCRIPTION_ORDER_SUCCESS_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, PRESCRIPTIONS_CRUMB],
};

export const PRESCRIPTION_REPEAT_PARTIAL_SUCCESS_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, PRESCRIPTIONS_CRUMB],
};

export const PRESCRIPTIONS_GP_AT_HAND_CRUMB = {
  defaultCrumb: [INDEX_CRUMB],
};

export const UPLIFT_PRESCRIPTIONS_CRUMB = {
  defaultCrumb: [INDEX_CRUMB],
  nativeDisabled: true,
};

export default {
  PRESCRIPTIONS_CRUMB,
  PRESCRIPTIONS_VIEW_ORDERS_CRUMB,
  PRESCRIPTION_REPEAT_COURSES_CRUMB,
  PRESCRIPTION_CONFIRM_COURSES_CRUMB,
  PRESCRIPTION_ORDER_SUCCESS_CRUMB,
  PRESCRIPTION_REPEAT_PARTIAL_SUCCESS_CRUMB,
  PRESCRIPTIONS_GP_AT_HAND_CRUMB,
  UPLIFT_PRESCRIPTIONS_CRUMB,
};
