import { INDEX_CRUMB } from '@/breadcrumbs/general';
import {
  PRESCRIPTIONS_NAME,
  PRESCRIPTIONS_VIEW_ORDERS_NAME,
  PRESCRIPTION_REPEAT_COURSES_NAME,
  PRESCRIPTION_CONFIRM_COURSES_NAME,
  PRESCRIPTIONS_ORDER_SUCCESS_NAME,
  PRESCRIPTIONS_REPEAT_PARTIAL_SUCCESS_NAME,
  PRESCRIPTIONS_GP_AT_HAND_NAME,
  UPLIFT_PRESCRIPTIONS_NAME,
} from '@/router/names';

export const PRESCRIPTIONS_CRUMB = {
  i18nKey: 'prescriptions',
  defaultCrumb: [INDEX_CRUMB],
  name: PRESCRIPTIONS_NAME,
  nativeDisabled: true,
};

export const PRESCRIPTIONS_VIEW_ORDERS_CRUMB = {
  i18nKey: 'prescriptions',
  defaultCrumb: [INDEX_CRUMB, PRESCRIPTIONS_CRUMB],
  name: PRESCRIPTIONS_VIEW_ORDERS_NAME,
};

export const PRESCRIPTION_REPEAT_COURSES_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, PRESCRIPTIONS_CRUMB],
  name: PRESCRIPTION_REPEAT_COURSES_NAME,
};

export const PRESCRIPTION_CONFIRM_COURSES_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, PRESCRIPTIONS_CRUMB],
  name: PRESCRIPTION_CONFIRM_COURSES_NAME,
};

export const PRESCRIPTION_ORDER_SUCCESS_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, PRESCRIPTIONS_CRUMB],
  name: PRESCRIPTIONS_ORDER_SUCCESS_NAME,
};

export const PRESCRIPTION_REPEAT_PARTIAL_SUCCESS_CRUMB = {
  defaultCrumb: [INDEX_CRUMB, PRESCRIPTIONS_CRUMB],
  name: PRESCRIPTIONS_REPEAT_PARTIAL_SUCCESS_NAME,
};

export const PRESCRIPTIONS_GP_AT_HAND_CRUMB = {
  defaultCrumb: [INDEX_CRUMB],
  name: PRESCRIPTIONS_GP_AT_HAND_NAME,
};

export const UPLIFT_PRESCRIPTIONS_CRUMB = {
  defaultCrumb: [INDEX_CRUMB],
  name: UPLIFT_PRESCRIPTIONS_NAME,
};

export default {
  PRESCRIPTIONS_CRUMB,
  PRESCRIPTIONS_VIEW_ORDERS_CRUMB,
  PRESCRIPTION_REPEAT_COURSES_CRUMB,
  PRESCRIPTION_CONFIRM_COURSES_CRUMB,
  PRESCRIPTION_ORDER_SUCCESS_CRUMB,
  PRESCRIPTION_REPEAT_PARTIAL_SUCCESS_CRUMB,
  PRESCRIPTIONS_GP_AT_HAND_CRUMB,
  UPLIFT_PRESCRIPTIONS_CRUMB,
};
