import { INDEX_CRUMB } from '@/breadcrumbs/general';
import { WAYFINDER_HELP_NAME, WAYFINDER_NAME, WAYFINDER_WAITING_LISTS_NAME } from '@/router/names';
import { APPOINTMENTS_CRUMB } from '@/breadcrumbs/appointments';

const APPOINTMENTS_WAYFINDER_CRUMB = {
  name: WAYFINDER_NAME,
  i18nKey: 'wayfinderReferralsAndAppointments',
  defaultCrumb: [INDEX_CRUMB, APPOINTMENTS_CRUMB],
};

const WAYFINDER_HELP_CRUMB = {
  name: WAYFINDER_HELP_NAME,
  defaultCrumb: [INDEX_CRUMB, APPOINTMENTS_CRUMB, APPOINTMENTS_WAYFINDER_CRUMB],
};

const WAYFINDER_WAIT_TIMES_CRUMB = {
  name: WAYFINDER_WAITING_LISTS_NAME,
  defaultCrumb: [INDEX_CRUMB, APPOINTMENTS_CRUMB, APPOINTMENTS_WAYFINDER_CRUMB],
};

export default {
  WAYFINDER_HELP_CRUMB,
  APPOINTMENTS_WAYFINDER_CRUMB,
  WAYFINDER_WAIT_TIMES_CRUMB,
};
