package mocking.onlineConsultations.configurations.evaluate

import mocking.onlineConsultations.configurations.IQuestionConfiguration

class ConditionsConfigurations: IQuestionConfiguration {

    override val request = """{
   "resourceType":"Parameters",
   "parameter":[
      {
         "name":"organization",
         "resource":{
            "resourceType":"Organization",
            "identifier":[
               {
                  "value":"{{odsCode}}"
               }
            ]
         }
      },
      {
         "name":"inputData",
         "resource":{
            "resourceType":"QuestionnaireResponse",
            "questionnaire":{
               "reference":"Questionnaire/GLO_PRE_DISCLAIMERS_NHS_2"
            },
            "status":"completed",
            "item":[
               {
                  "linkId":"GLO_PRE_DISCLAIMERS_NHS_2",
                  "answer":[
                     {
                        "valueCoding":{
                           "code":"GLO_PRE_DISCLAIMERS_1"
                        }
                     }
                  ]
               }
            ]
         }
      },
      {
         "name":"patient",
         "resource":{
            "resourceType":"Patient",
            "identifier":[
               {
                  "system":"https://fhir.nhs.uk/Id/nhs-number",
                  "value":"{{nhsNumber}}"
               }
            ],
            "name":[
               {
                  "family":"{{familyName}}",
                  "given":[
                     "{{name}}"
                  ]
               }
            ],
            "birthDate":"{{dob}}",
            "address":[
               {
                  "text":"{{address}}"
               }
            ]
         }
      }
   ]
}"""

    override val response: String = """{
       "resourceType":"GuidanceResponse",
       "contained":[
          {
             "resourceType":"Questionnaire",
             "id":"CONDITION_LIST",
             "status":"active",
             "item":[
                {
                   "linkId":"BRP",
                   "text":"Breathing problems",
                   "type":"group",
                   "required":false,
                   "item":[
                      {
                         "linkId":"BRP_BRP",
                         "text":"Breathing problems",
                         "type":"boolean",
                         "required":false
                      },
                   ]
                },
                {
                   "linkId":"EYE",
                   "text":"Eye problems",
                   "type":"group",
                   "required":false,
                   "item":[
                      {
                         "linkId":"EYE_CNJ",
                         "text":"Conjunctivitis",
                         "type":"boolean",
                         "required":false
                      },
                   ]
                },
                {
                   "linkId":"GBS",
                   "text":"Gut, bowel & stomach",
                   "type":"group",
                   "required":false,
                   "item":[
                      {
                         "linkId":"GBS_DAV",
                         "text":"Gastroenteritis",
                         "type":"boolean",
                         "required":false
                      },
                   ]
                },
                {
                   "linkId":"JTP",
                   "text":"Joint pain",
                   "type":"group",
                   "required":false,
                   "item":[
                      {
                         "linkId":"JTP_SPN",
                         "text":"Shoulder pain",
                         "type":"boolean",
                         "required":false
                      },
                   ]
                },
                {
                   "linkId":"LTC",
                   "text":"Long term conditions",
                   "type":"group",
                   "required":false,
                   "item":[
                      {
                         "linkId":"LTC_HYT",
                         "text":"Hypertension review",
                         "type":"boolean",
                         "required":false
                      }
                   ]
                },
                {
                   "linkId":"MHL",
                   "text":"Men's health",
                   "type":"group",
                   "required":false,
                   "item":[
                      {
                         "linkId":"MHL_CYS",
                         "text":"Bladder infection in men",
                         "type":"boolean",
                         "required":false
                      },
                   ]
                },
                {
                   "linkId":"MLL",
                   "text":"Mental health",
                   "type":"group",
                   "required":false,
                   "item":[
                      {
                         "linkId":"MLL_ANX",
                         "text":"Anxiety",
                         "type":"boolean",
                         "required":false
                      },
                   ]
                },
                {
                   "linkId":"WHL",
                   "text":"Women's health",
                   "type":"group",
                   "required":false,
                   "item":[
                      {
                         "linkId":"WHL_BVG",
                         "text":"Bacterial vaginosis",
                         "type":"boolean",
                         "required":false
                      },
                      {
                         "linkId":"WHL_VAD",
                         "text":"Vaginal discharge",
                         "type":"boolean",
                         "required":false
                      }
                   ]
                }
             ]
          }
       ],
       "module":{
          "reference":"https://test/fhir/ServiceDefinition/CONDITION_LIST"
       },
       "status":"data-required",
       "dataRequirement":[
          {
             "id":"PATIENT",
             "type":"Patient",
             "profile":[
                "https://fhir.hl7.org.uk/STU3/StructureDefinition/CareConnect-Patient-1"
             ]
          },
          {
             "id":"ORG",
             "type":"Organization",
             "profile":[
                "https://fhir.hl7.org.uk/STU3/StructureDefinition/CareConnect-Organization-1"
             ],
             "codeFilter":[
                {
                   "path":"identifier",
                   "valueSetString":"odsOrganizationCode"
                }
             ]
          },
          {
             "id":"CONDITION_LIST",
             "extension":[
                {
                   "url":"https://www.hl7.org/fhir/questionnaire.html",
                   "valueReference":{
                      "reference":"#CONDITION_LIST"
                   }
                }
             ],
             "type":"QuestionnaireResponse",
             "profile":[
                "https://www.hl7.org/fhir/questionnaireresponse.html"
             ]
          }
       ]
    }"""
}