package mocking.onlineConsultations.configurations.evaluate

import mocking.onlineConsultations.configurations.IQuestionConfiguration

class GenderQuestionConfiguration: IQuestionConfiguration {
    override val request = """{
       "resourceType":"Parameters",
       "parameter":[
          {
             "name":"organization",
             "resource":{
                "resourceType":"Organization",
                "identifier":[
                   {
                      "value":"A29928"
                   }
                ]
             }
          },
          {
             "name":"inputData",
             "resource":{
                "resourceType":"QuestionnaireResponse",
                "questionnaire":{
                   "reference":"Questionnaire/GLO_PRE_DISCLAIMERS"
                },
                "status":"completed",
                "item":[
                   {
                      "linkId":"GLO_PRE_DISCLAIMERS",
                      "answer":[
                         {
                            "valueCoding":{
                               "code":"GLO_PRE_DISCLAIMERS_1"
                            }
                         }
                      ]
                   }
                ]
             }
          },
          {
             "name":"patient",
             "resource":{
                "resourceType":"Patient",
                "identifier":[
                   {
                      "system":"https://fhir.nhs.uk/Id/nhs-number",
                      "value":"{{nhsNumber}}"
                   }
                ],
                "name":[
                   {
                        "text" : "{{name}} {{familyName}}"
                   }
                ],
                "birthDate":"{{dob}}",
                "address":[
                   {
                      "text":"{{address}}"
                   }
                ]
             }
          }
       ]
    }"""

    override val response = """{
       "resourceType":"GuidanceResponse",
       "contained":[
          {
             "resourceType":"Parameters",
             "id":"outputParams",
             "parameter":[
                {
                   "name":"sessionId",
                   "valueString":"1"
                }
             ]
          },
          {
             "resourceType":"Questionnaire",
             "id":"PRE_STD_AD_SEX",
             "status":"active",
             "item":[
                {
                   "linkId":"PRE_STD_AD_SEX_GROUP",
                   "type":"group",
                   "item":[
                      {
                         "extension":[
                            {
                               "url":"http://hl7.org/fhir/StructureDefinition/questionnaire-itemControl",
                               "valueCodeableConcept":{
                                  "id":"codeableConcept",
                                  "coding":[
                                     {
                                        "system":"http://hl7.org/fhir/ValueSet/questionnaire-item-control",
                                        "code":"button",
                                        "display":"back"
                                     }
                                  ],
                                  "text":"back"
                               }
                            }
                         ],
                         "linkId":"PRE_STD_AD_SEX_PREV",
                         "type":"choice",
                         "required":false
                      },
                      {
                         "linkId":"PRE_STD_AD_SEX",
                         "text":"Tell us your sex",
                         "type":"choice",
                         "required":true,
                         "repeats":false,
                         "option":[
                            {
                               "valueCoding":{
                                  "code":"PRE_STD_AD_SEX_F",
                                  "display":"Female"
                               }
                            },
                            {
                               "valueCoding":{
                                  "code":"PRE_STD_AD_SEX_M",
                                  "display":"Male"
                               }
                            }
                         ]
                      }
                   ]
                }
             ]
          }
       ],
       "requestId":"1",
       "module":{
          "reference":"https://stubs.onlineconsultations/fhir/ServiceDefinition/BRP_BRP"
       },
       "status":"data-required",
       "occurrenceDateTime":"2019-05-23T11:06:54.969",
       "outputParameters":{
          "reference":"#outputParams"
       },
       "dataRequirement":[
          {
             "id":"PRE_STD_AD_SEX",
             "extension":[
                {
                   "url":"https://www.hl7.org/fhir/questionnaire.html",
                   "valueReference":{
                      "reference":"#PRE_STD_AD_SEX"
                   }
                }
             ],
             "type":"QuestionnaireResponse",
             "profile":[
                "https://www.hl7.org/fhir/questionnaireresponse.html"
             ]
          }
       ]
    }"""
}