package mocking.onlineConsultations.configurations.evaluate.childJourney

import mocking.onlineConsultations.configurations.IQuestionConfiguration

class HowWeCanHelpQuestionChildConfiguration: IQuestionConfiguration {
    override val request  = """{
       "resourceType":"Parameters",
       "parameter":[
          {
             "name":"sessionId",
             "valueString":"1"
          },
          {
             "name":"inputData",
             "resource":{
                "resourceType":"QuestionnaireResponse",
                "questionnaire":{
                   "reference":"Questionnaire/PRE_STD_AD_SEX"
                },
                "status":"completed",
                "item":[
                   {
                      "linkId":"PRE_STD_AD_SEX",
                      "answer":[
                         {
                            "valueCoding":{
                               "code":"PRE_STD_AD_SEX_M"
                            }
                         }
                      ]
                   }
                ]
             }
          }
       ]
    }"""


    override val response: String = """{
       "resourceType":"GuidanceResponse",
       "contained":[
          {
             "resourceType":"Parameters",
             "id":"outputParams",
             "parameter":[
                {
                   "name":"sessionId",
                   "valueString":"f8f2c2a2-acd9-425a-b93e-cf9c21bbd512"
                }
             ]
          },
          {
             "resourceType":"Questionnaire",
             "id":"Q_BRP_BRP_AD_1",
             "status":"active",
             "item":[
                {
                   "linkId":"Q_BRP_BRP_AD_1_GROUP",
                   "text":"",
                   "type":"group",
                   "item":[
                      {
                         "extension":[
                            {
                               "url":"http://hl7.org/fhir/StructureDefinition/questionnaire-itemControl",
                               "valueCodeableConcept":{
                                  "id":"backButton",
                                  "coding":[
                                     {
                                        "system":"http://hl7.org/fhir/ValueSet/questionnaire-item-control",
                                        "code":"button",
                                        "display":"back"
                                     }
                                  ],
                                  "text":"back"
                               }
                            }
                         ],
                         "linkId":"Q_BRP_BRP_AD_1_PREV",
                         "text":"",
                         "type":"boolean",
                         "required":false
                      },
                      {
                         "extension":[
                            {
                               "url":"http://hl7.org/fhir/StructureDefinition/maxLength",
                               "valueInteger":500
                            }
                         ],
                         "linkId":"Q_BRP_BRP_AD_1",
                         "text":"Please tell us what symptoms your child is showing.",
                         "type":"text",
                         "required":true
                      }
                   ]
                }
             ]
          }
       ],
       "module":{
          "reference":"https://stubs.onlineconsultations/fhir/ServiceDefinition/BRP_BRP"
       },
       "status":"data-required",
       "occurrenceDateTime":"2020-02-25T11:32:01.729",
       "outputParameters":{
          "reference":"#outputParams"
       },
       "dataRequirement":[
          {
             "id":"Q_BRP_BRP_AD_1",
             "extension":[
                {
                   "url":"https://www.hl7.org/fhir/questionnaire.html",
                   "valueReference":{
                      "reference":"#Q_BRP_BRP_AD_1"
                   }
                }
             ],
             "type":"QuestionnaireResponse",
             "profile":[
                "https://www.hl7.org/fhir/questionnaireresponse.html"
             ]
          }
       ]
    }"""
}
