//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHSOnline.Backend.Worker {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NHSOnline.Backend.Worker.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration value &apos;{0}&apos; not found.
        /// </summary>
        internal static string ConfigurationValueNotFound {
            get {
                return ResourceManager.GetString("ConfigurationValueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionMultiplexer &apos;{0}&apos; could not be found..
        /// </summary>
        internal static string ConnectionMultiplexerFactoryUnknownMultiplexerName {
            get {
                return ResourceManager.GetString("ConnectionMultiplexerFactoryUnknownMultiplexerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HttpClient &apos;{0}&apos; could not be found..
        /// </summary>
        internal static string HttpClientFactoryUnknownClientName {
            get {
                return ResourceManager.GetString("HttpClientFactoryUnknownClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured log level of &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string InvalidLogLevel {
            get {
                return ResourceManager.GetString("InvalidLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHS number not available, please set up audit scope..
        /// </summary>
        internal static string NoNhsNumberAvailable {
            get {
                return ResourceManager.GetString("NoNhsNumberAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ODS Code &apos;{0}&apos; could not be found..
        /// </summary>
        internal static string OdsCodeLookupUnknownOdsCode {
            get {
                return ResourceManager.GetString("OdsCodeLookupUnknownOdsCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ODS Code &apos;{0}&apos; is associated with unexpected supplier &apos;{1}&apos;..
        /// </summary>
        internal static string OdsCodeLookupUnknownSupplierCode {
            get {
                return ResourceManager.GetString("OdsCodeLookupUnknownSupplierCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier not specified, please set up audit scope..
        /// </summary>
        internal static string SupplierNotSpecified {
            get {
                return ResourceManager.GetString("SupplierNotSpecified", resourceCulture);
            }
        }
    }
}
