const NOMINATED_PHARMACY_SUMMARY = 'nominatedPharmacy';
const NOMINATED_PHARMACY_CHECK = 'check';
const PRESCRIPTIONS = 'prescriptions';

export default {
  NOMINATED_PHARMACY_SUMMARY,
  NOMINATED_PHARMACY_CHECK,
  PRESCRIPTIONS,
};
