version: "3.2"
services:
  web.local.bitraft.io:
    image: nhsonline.web
    ports:
      - "3000:3000"
    environment:
      - API_PORT=8082
      - API_PORT_SERVER=8082
      - CID_AUTH_ENDPOINT=http://stubs.local.bitraft.io:8080/citizenid/authorize
      - CID_REGISTER_ENDPOINT=http://stubs.local.bitraft.io:8080/citizenid/register
  api.local.bitraft.io:
    image: nhsonline.backend.worker
    environment:
      - BACKENDWORKER_RUNMODE=pfs
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8082
      - PORT=8082
      - CORS_AUTHORITY=*
      - CITIZEN_ID_BASE_URL=http://stubs.local.bitraft.io:8080/citizenid/
      - ConfigurationSettings__DefaultSessionExpiryMinutes=1
      - EMIS_BASE_URL=http://stubs.local.bitraft.io:8080/emis/
      - TPP_BASE_URL=http://stubs.local.bitraft.io:8080/tpp/
      - VISION_URI=http://stubs.local.bitraft.io:8080/vision
      - VISION_CERT_PASSPHRASE
      - GP_PROVIDER_ENABLED_EMIS=true
      - GP_PROVIDER_ENABLED_TPP=true
      - GP_PROVIDER_ENABLED_VISION=true
      - GP_PROVIDER_ENABLED_MICROTEST=true
      - STUB_TERMS_AND_CONDITIONS=true
      - ConfigurationSettings__CookieDomain=.bitraft.io
    depends_on:
      - nhsonline.redis.sds
    ports:
      - "8082:8082"
  cid.local.bitraft.io:
    image: nhsonline.backend.worker
    environment:
      - BACKENDWORKER_RUNMODE=cid
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8084
      - PORT=8084
      - CORS_AUTHORITY=*
      - CITIZEN_ID_BASE_URL=http://stubs.local.bitraft.io:8080/citizenid/
      - ConfigurationSettings__DefaultSessionExpiryMinutes=1
      - EMIS_BASE_URL=http://stubs.local.bitraft.io:8080/emis/
      - TPP_BASE_URL=http://stubs.local.bitraft.io:8080/tpp/
      - VISION_URI=http://stubs.local.bitraft.io:8080/vision
      - VISION_CERT_PASSPHRASE
      - GP_PROVIDER_ENABLED_EMIS=true
      - GP_PROVIDER_ENABLED_TPP=true
      - GP_PROVIDER_ENABLED_VISION=true
      - GP_PROVIDER_ENABLED_MICROTEST=true
      - STUB_TERMS_AND_CONDITIONS=true
    depends_on:
      - nhsonline.redis.sds
    ports:
      - "8084:8084"
  stubs.local.bitraft.io:
    image: nhsapp.azurecr.io/wiremock:2.17.0-alpine
    command: --local-response-templating
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
    tty: true
  data.stubs.local.bitraft.io:
    image: nhsonline.stubs.data
    build:
      context: .
      dockerfile: Dockerfile.mock
    environment:
      - wiremockUrl=http://stubs.local.bitraft.io:8080
    depends_on:
      - nhsonline.stubs
  redis-data.nhsonline.redis-data.sds:
    image: nhsapp.azurecr.io/nhsonline-redis-data:latest
    environment:
      - REDIS_HOST=nhsonline.redis.sds
    depends_on:
      - nhsonline.redis.sds
  nhsonline.redis.sds:
    image: nhsapp.azurecr.io/redis:4.0.8-r7
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
    volumes:
      - 'redis_data:/bitnami/redis'
  nhsonline.redis.session:
    image: nhsapp.azurecr.io/redis:4.0.8-r7
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6380:6379"
volumes:
  redis_data:
    driver: local
