version: "3.2"
services:
  nhsonline.web:
    image: nhsonline.web
    ports:
      - "3000:3000"
    environment:
      - API_HOST=http://localhost:8082
      - API_HOST_SERVER=http://nhsonline.backend.worker:8082
      - CID_REDIRECT_URI=http://localhost:3000/auth-return
      - ANDROID_CID_REDIRECT_URI=nhsapp://10.0.2.2:3000/auth-return
      - CID_AUTH_ENDPOINT=http://localhost:8080/citizenid/authorize
      - CID_REGISTER_ENDPOINT=http://localhost:8080/citizenid/register
      - DATA_PREFERENCES_URL=http://localhost:8080/ndop/ndopapp-build1.thunderbird.service.nhs.uk/createsession
  nhsonline.backend.worker:
    image: nhsonline.backend.worker
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CORS_AUTHORITY=*
      - CITIZEN_ID_BASE_URL=http://nhsonline.stubs:8080/citizenid/
      - ConfigurationSettings__DefaultSessionExpiryMinutes=20
      - VISION_CERT_PASSPHRASE
      - GP_PROVIDER_ENABLED_EMIS=true
      - GP_PROVIDER_ENABLED_TPP=false
      - GP_PROVIDER_ENABLED_VISION=false
      - GP_PROVIDER_ENABLED_MICROTEST=false
      - NDOP_CERTIFICATE_PASSWORD=GnewUt4z3y
      - NDOP_CERTIFICATE_PATH=/app/bddcerts/ndopJwtTest.pfx
      - NDOP_CLAIM_AUDIENCE=https://ndopapp-int1.thunderbird.service.nhs.uk
      - NDOP_CLAIM_ISSUER=https://www-preview.devuks1.nonlive.nhsapp.service.nhs.uk
      - EMIS_LINKAGE_USE_STUBBED_DATA=false
      - STUB_TERMS_AND_CONDITIONS=true
    depends_on:
      - nhsonline.redis.sds
    ports:
      - "8082:8082"
    volumes:
      - ./src/main/kotlin/mocking/ndop:/app/bddcerts
  nhsonline.stubs:
    image: nhsapp.azurecr.io/wiremock:2.17.0-alpine
    command: --local-response-templating
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
    tty: true
  nhsonline.redis-data.sds:
    image: nhsapp.azurecr.io/nhsonline-redis-data:latest
    environment:
      - REDIS_HOST=nhsonline.redis.sds
    depends_on:
      - nhsonline.redis.sds
  nhsonline.redis.sds:
    image: nhsapp.azurecr.io/redis:4.0.8-r7
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
    volumes:
      - 'redis_data:/bitnami/redis'
  nhsonline.redis.session:
    image: nhsapp.azurecr.io/redis:4.0.8-r7
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6380:6379"
volumes:
  redis_data:
    driver: local