version: "3.2"
services:
  nhsonline.mongodb.session:
    image: mongo:latest
    ports:
    - "27017:27017"
  web.local.bitraft.io:
    image: nhsonline.web
    ports:
      - "3000:3000"
    environment:
      - URI_FORMAT_API_CLIENT=http://api{host}:8082
      - API_HOST_SERVER=http://api.local.bitraft.io:8082
      - URI_FORMAT_CID_REDIRECT_WEB=http://web{host}:3000/auth-return
      - URI_FORMAT_CID_REDIRECT_NATIVE=http://web{host}:3000/auth-return
      - CID_AUTH_ENDPOINT=http://stubs.local.bitraft.io:8080/citizenid/authorize
      - CID_REGISTER_ENDPOINT=http://stubs.local.bitraft.io:8080/citizenid/register
      - DATA_PREFERENCES_URL=http://stubs.local.bitraft.io:8080/ndop/createsession
      - GP_LOOKUP_API_RESULTS_LIMIT=20
      - COOKIE_DOMAIN=.bitraft.io
      - VERSION_TAG=dev_bdd_docker_main
      - BIOMETRICS_ENABLED=true
      - THROTTLING_ENABLED=false
      - ORGAN_DONATION_INTEGRATION_ENABLED=true
  api.local.bitraft.io:
    image: nhsonline.backend.pfsapi
    environment:
      - BACKENDWORKER_RUNMODE=pfs
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8082
      - PORT=8082
      - CORS_AUTHORITY=*
      - CITIZEN_ID_BASE_URL=http://stubs.local.bitraft.io:8080/citizenid/
      - ConfigurationSettings__DefaultSessionExpiryMinutes=3
      - EMIS_BASE_URL=http://stubs.local.bitraft.io:8080/emis/
      - TPP_BASE_URL=http://stubs.local.bitraft.io:8080/tpp/
      - VISION_BASE_URI=http://stubs.local.bitraft.io:8080/vision/
      - ConfigurationSettings__EmisExtendedHttpTimeoutSeconds=10
      - VISION_PFS_PATH=pfs/
      - VISION_LINKAGE_PATH=linkage/
      - VISION_CERT_PATH=/app/bddcerts/TestCert.pfx
      - VISION_CERT_PASSPHRASE=GnewUt4z3y
      - VISION_SENDER_USERNAME=Username123123asdas
      - VISION_SENDER_USERFULLNAME=Name
      - VISION_SENDER_USERIDENTITY=65489761321654
      - VISION_SENDER_USERROLE=ROSU
      - GP_PROVIDER_ENABLED_EMIS=true
      - GP_PROVIDER_ENABLED_TPP=true
      - GP_PROVIDER_ENABLED_VISION=true
      - GP_PROVIDER_ENABLED_MICROTEST=true
      - NDOP_CERTIFICATE_PASSWORD=GnewUt4z3y
      - NDOP_CERTIFICATE_PATH=/app/bddcerts/TestCert.pfx
      - NDOP_CLAIM_AUDIENCE=https://ndopapp-int1.thunderbird.service.nhs.uk
      - NDOP_CLAIM_ISSUER=https://www-preview.devuks1.nonlive.nhsapp.service.nhs.uk
      - EMIS_LINKAGE_USE_STUBBED_DATA=false
      - STUB_TERMS_AND_CONDITIONS=true
      - ConfigurationSettings__CookieDomain=.bitraft.io
      - SESSION_MONGO_DATABASE_HOST=nhsonline.mongodb.session
      - SESSION_MONGO_DATABASE_PORT=27017
      - SESSION_MONGO_DATABASE_USERNAME=
      - SESSION_MONGO_DATABASE_PASSWORD=
      - ORGAN_DONATION_BASE_URL=http://stubs.local.bitraft.io:8080/organdonation/
      - ORGAN_DONATION_CLIENT_ID=ODR-26-NHSAP
      - ORGAN_DONATION_OCP_APIM_SUBSCRIPTION_KEY=781859de3cce4bc48a715dfc8f36dc6f
      - ORGAN_DONATION_INTEGRATION_ENABLED=true
      - TERMS_CONDITIONS_COSMOS_ENDPOINT_URI=https://nhsapp-local-test.documents.azure.com:443/
      - TERMS_CONDITIONS_COLLECTION_LINK=dbs/local/colls/consent/
      - TERMS_CONDITIONS_COSMOS_DATABASE_ID=local
      - TERMS_CONDITIONS_COSMOS_COLLECTION_NAME=consent
      - TERMS_CONDITIONS_COSMOS_AUTH_KEY=
      - ConfigurationSettings__CurrentTermsConditionsEffectiveDate=2018-12-12T00:00:00+00:00
      - NHS_SEARCH_BASE_URL=http://stubs.local.bitraft.io:8080/nhs-search-indexes/
      - GP_LOOKUP_API_KEY=testnhssearchservicekey
      - GP_LOOKUP_API_RESULTS_LIMIT=20
      - POSTCODE_LOOKUP_SEARCH_RADIUS_KM=10
      - BROTHER_MAILER_URL=http://stubs.local.bitraft.io:8080/brothermailer/
      - BROTHER_MAILER_ADDRESSBOOK_ID=brothermaileraddressid
      - BROTHER_MAILER_SIG=brothermailersig
      - BROTHER_MAILER_USER_ID=brothermaileruserid
    depends_on:
      - nhsonline.redis.sds
    ports:
      - "8082:8082"
    volumes:
      - ./src/main/kotlin/mocking/dummycerts:/app/bddcerts
  cid.local.bitraft.io:
    image: nhsonline.backend.cidapi
    depends_on:
      - nhsonline.redis.sds
      - nhsonline.redis.session
    environment:
      - BACKENDWORKER_RUNMODE=cid
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8084
      - ConfigurationSettings__EmisExtendedHttpTimeoutSeconds=15
      - PORT=8084
      - CORS_AUTHORITY=*
      - CITIZEN_ID_BASE_URL=http://stubs.local.bitraft.io:8080/citizenid/
      - EMIS_BASE_URL=http://stubs.local.bitraft.io:8080/emis/
      - TPP_BASE_URL=http://stubs.local.bitraft.io:8080/tpp/
      - VISION_BASE_URI=http://stubs.local.bitraft.io:8080/vision/
      - VISION_PFS_PATH=pfs/
      - VISION_LINKAGE_PATH=linkage/
      - TPP_CERTIFICATE_PASSWORD
      - TPP_CERTIFICATE_PATH=./certs/TppNhsTest.pfx
      - VISION_CERT_PATH=/app/bddcerts/TestCert.pfx
      - VISION_CERT_PASSPHRASE=GnewUt4z3y
      - GP_PROVIDER_ENABLED_EMIS=true
      - GP_PROVIDER_ENABLED_TPP=true
      - GP_PROVIDER_ENABLED_VISION=true
      - GP_PROVIDER_ENABLED_MICROTEST=true
      - NDOP_CERTIFICATE_PASSWORD
      - NDOP_CERTIFICATE_PATH=/app/bddcerts/TestCert.pfx
      - NDOP_CLAIM_AUDIENCE=https://ndopapp-int1.thunderbird.service.nhs.uk
      - NDOP_CLAIM_ISSUER=https://www-preview.devuks1.nonlive.nhsapp.service.nhs.uk
      - STUB_TERMS_AND_CONDITIONS=true
      - SESSION_MONGO_DATABASE_HOST=nhsonline.mongodb.session
      - SESSION_MONGO_DATABASE_PORT=27017
      - SESSION_MONGO_DATABASE_USERNAME=
      - SESSION_MONGO_DATABASE_PASSWORD=
      - TERMS_CONDITIONS_COSMOS_ENDPOINT_URI=https://nhsapp-local-test.documents.azure.com:443/
      - TERMS_CONDITIONS_COLLECTION_LINK=dbs/local/colls/consent/
      - TERMS_CONDITIONS_COSMOS_DATABASE_ID=local
      - TERMS_CONDITIONS_COSMOS_COLLECTION_NAME=consent
      - TERMS_CONDITIONS_COSMOS_AUTH_KEY=
    ports:
      - "8084:8084"
    volumes:
      - ./src/main/kotlin/mocking/dummycerts:/app/bddcerts
  stubs.local.bitraft.io:
    image: nhsapp.azurecr.io/wiremock:2.17.0-alpine
    command: --local-response-templating
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
    tty: true
  nhsonline.redis-data.sds:
    image: nhsapp.azurecr.io/nhsonline-redis-data:latest
    environment:
      - MODE=development
      - REDIS_HOST=nhsonline.redis.sds
    depends_on:
      - nhsonline.redis.sds
  nhsonline.redis.sds:
    image: nhsapp.azurecr.io/redis:4.0.8-r7
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
    volumes:
      - 'redis_data:/bitnami/redis'
  nhsonline.redis.session:
    image: nhsapp.azurecr.io/redis:4.0.8-r7
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6380:6379"
  mongo_seed:
    image: mongo:latest
    links:
      - nhsonline.mongodb.session
    command: /bin/bash -c "sleep 5; mongo --host nhsonline.mongodb.session --eval 'db.session.createIndex({_ts:1},{expireAfterSeconds:60})' development"
    depends_on:
      - nhsonline.mongodb.session
volumes:
  redis_data:
    driver: local
