version: "3.2"
services:
  web.local.bitraft.io:
    image: nhsonline.web
    environment:
      - URI_FORMAT_API_CLIENT=http://api{host}:8082
      - API_HOST_SERVER=http://api.local.bitraft.io:8082
      - URI_FORMAT_CID_REDIRECT_WEB=http://web{host}:3000/auth-return
      - URI_FORMAT_CID_REDIRECT_NATIVE=nhsapp://10.0.2.2:3000/auth-return
      - CID_AUTH_ENDPOINT=http://10.0.2.2:8080/citizenid/cicauth/realms/NHS/protocol/openid-connect/auth
      - VERSION_TAG=dev_bdd_docker_appium
  api.local.bitraft.io:
    image: nhsonline.backend.pfsapi
    environment:
      - STUB_TERMS_AND_CONDITIONS=true
  servicejourneyrulesapi.local.bitraft.io:
    image: nhsonline.backend.servicejourneyrulesapi
    ports:
      - "8086:8086"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8086
      - PORT=8086
      - CORS_AUTHORITY=*
      - VERSION_TAG=servicejourneyrules_docker_main
      - SESSION_MONGO_DATABASE_HOST=nhsonline.mongodb.session
      - SESSION_MONGO_DATABASE_PORT=27017
      - SESSION_MONGO_DATABASE_USERNAME=
      - SESSION_MONGO_DATABASE_PASSWORD=
  clinicaldecisionsupportapi.local.bitraft.io:
    image: nhsonline.backend.clinicaldecisionsupportapi
    ports:
      - "8087:8087"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8087
      - PORT=8087
      - CORS_AUTHORITY=*
      - VERSION_TAG=clinicaldecisionsupport_docker_main
      - SESSION_MONGO_DATABASE_HOST=nhsonline.mongodb.session
      - SESSION_MONGO_DATABASE_PORT=27017
      - SESSION_MONGO_DATABASE_USERNAME=
      - SESSION_MONGO_DATABASE_PASSWORD=
      - EMS_CDSS_STUB_URL=http://ems.cdss.stubs.local.bitraft.io:8088
