version: "3.2"
services:
  web.local.bitraft.io:
    image: nhsonline.web
    environment:
      - CID_AUTH_ENDPOINT=http://stubs.local.bitraft.io:8080/citizenid/authorize
      - CID_REGISTER_ENDPOINT=http://stubs.local.bitraft.io:8080/citizenid/register
      - URI_FORMAT_API_CLIENT=http://api{host}:8082
      - API_HOST_SERVER=http://api.local.bitraft.io:8082
      - URI_FORMAT_CID_REDIRECT_WEB=http://web{host}:3000/auth-return
      - URI_FORMAT_CID_REDIRECT_NATIVE=nhsapp://web{host}:3000/auth-return
      - VERSION_TAG=dev_bdd_docker_browserstack
  api.local.bitraft.io:
    image: nhsonline.backend.worker
    environment:
      - BACKENDWORKER_RUNMODE=pfs
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8082
      - PORT=8082
      - NHS_WEB_APP_BASE_URL=http://web.local.bitraft.io:3000
      - STUB_TERMS_AND_CONDITIONS=true
      - ConfigurationSettings__CookieDomain=.bitraft.io
      - ConfigurationSettings__DefaultSessionExpiryMinutes=5
