FROM nhsapp.azurecr.io/nhsonline-stubs-data:latest

ENV wiremockUrl http://nhsonline.stubs:8080
ENV WAIT_FOR_TIMEOUT 60

CMD wait-for -t ${WAIT_FOR_TIMEOUT} ${wiremockUrl#*//} -- ./gradlew mock -DmockArgs="['mockenvironment']"
