serenity.project.name= NHSOnline Tests

webdriver.driver = provided
webdriver.provided.type = chrome

webdriver.provided.chrome = webdrivers.ChromeDriver
webdriver.provided.chromeheadless = webdrivers.ChromeHeadlessDriver
webdriver.provided.chromenongpu = webdrivers.ChromeNonGPUDriver
webdriver.provided.firefox = webdrivers.FirefoxDriver
webdriver.provided.firefoxheadless = webdrivers.FirefoxHeadlessDriver
webdriver.provided.android = webdrivers.AndroidDriver
webdriver.provided.browserstack_chrome = webdrivers.BrowserstackChromeDriver

webdriver.base.url = http://localhost:3000/

serenity.take.screenshots=AFTER_EACH_STEP
serenity.browser.maximized=true
webdriver.wait.for.timeout=15000

junit.retry.tests=true
max.retries=3
serenity.restart.browser.frequency=10
serenity.use.unique.browser=true