serenity.project.name= NHSOnline Tests

webdriver.driver = provided
webdriver.provided.type = chrome

webdriver.provided.chrome = webdrivers.ChromeDriver
webdriver.provided.chromeheadless = webdrivers.ChromeHeadlessDriver
webdriver.provided.chromeheadlessowasp = webdrivers.ChromeHeadlessOWASPDriver
webdriver.provided.chromenongpu = webdrivers.ChromeNonGPUDriver
webdriver.provided.firefox = webdrivers.FirefoxDriver
webdriver.provided.firefoxheadless = webdrivers.FirefoxHeadlessDriver
webdriver.provided.android = webdrivers.Pixel2LocalDriver
webdriver.provided.browserstack_chrome = webdrivers.BrowserstackChromeDriver
webdriver.provided.pixel_2 = webdrivers.Pixel2Driver
webdriver.provided.iphoneX = webdrivers.IPhoneXDriver

webdriver.base.url = http://localhost:3000/

serenity.take.screenshots=FOR_FAILURES
serenity.browser.maximized=true
webdriver.wait.for.timeout=15000

webdriver.timeouts.implicitlywait=5000