---
apiVersion: v1
data:
  .dockercfg: {{ .Values.dockerRegistrySecret }}
kind: Secret
metadata:
  name: azure-registry-sjr-{{ .Chart.AppVersion }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
type: kubernetes.io/dockercfg
