{{- if $.Values.networkPolicyEnabled -}}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-sjr-ingress-from-api-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.sjr.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          role: api
    ports:
    - protocol: TCP
      port: {{ $.Values.sidecar_proxy.containerPort }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-sjr-ingress-from-cid-{{ .Chart.AppVersion }}
  namespace: {{ $.Values.global.environment }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
spec:
  podSelector:
    matchLabels:
      role: {{ $.Values.sjr.role }}
      version: {{ .Chart.AppVersion | quote }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          role: cid
    ports:
    - protocol: TCP
      port: {{ $.Values.sidecar_proxy.containerPort }}
{{- end }}