version: "3.4"

services:

  stubs.local.bitraft.io:
    image: ${MINIMOCK_DOCKER_REGISTRY:-nhsapp.azurecr.io}/nhsonline-minimock:${MINIMOCK_DOCKER_TAG:-latest}
    env_file:
      - ./docker/stubbed/env/minimock.env