export const IS_LOADING = 'IS_LOADING';
export const LOADING_COMPLETE = 'LOADING_COMPLETE';
export const SET_API_ERROR_RESPONSE = 'SET_API_ERROR_RESPONSE';
export const CLEAR_API_ERROR_RESPONSE = 'CLEAR_API_ERROR_RESPONSE';
export const INIT_HTTP = 'INIT_HTTP';
