/* This file is generated by swagger-node-codegen and should not be altered manually.
 */

/* eslint-disable */

/*jshint esversion: 6 */
/*global fetch, btoa */
import $q from 'q';
import axios from 'axios'
import isEmpty from 'lodash/fp/isEmpty'
import get from 'lodash/fp/get'
import {
    resolveApiClient
} from '../middleware/urlResolution'

const getWebVersion = get('store.state.appVersion.webVersion');
const getNativeVersion = get('store.state.appVersion.nativeVersion');
const getPlatform = get('store.state.device.source');

/**
 * This is the API for the NHS App.
 * @class NhsAppApi
 * @param {(string|object)} [domainOrOptions] - The project domain or options object.
 *                                              If object, see the object's optional properties.
 * @param {string} [domainOrOptions.domain] - The project domain
 * @param {object} [domainOrOptions.token] - auth token - object with value property and optional
 *                                                        headerOrQueryName and isQuery properties
 */
class NHSOnlineApi {
  constructor(options) {
    this.store = options.store;
    this.res = options.res;
    this.req = options.req;
    this.cookies = options.cookies;
    this.__domain = options.domain;

  }

  get domain() {
      const {
          app: {
              $env
          }
      } = this.store;
      const domain = this.req ?
          $env.API_HOST_SERVER :
          resolveApiClient({
              host: this.req,
              env: $env
          });

      return domain;
  }

  serializeQueryParams(parameters) {
    let str = [];
    for (let p in parameters) {
      if (parameters.hasOwnProperty(p)) {
        str.push(encodeURIComponent(p) + '=' + encodeURIComponent(parameters[p]));
      }
    }
    return str.join('&');
  }

  mergeQueryParams(parameters, queryParameters) {
    if (parameters.$queryParameters) {
      Object.keys(parameters.$queryParameters)
        .forEach(function(parameterName) {
          let parameter = parameters.$queryParameters[parameterName];
          queryParameters[parameterName] = parameter;
      });
    }
    return queryParameters;
  }

    /**
     * HTTP Request
     * @method
     * @name NhsAppApi#request
     * @param {string} method - http method
     * @param {string} url - url to do request
     * @param {object} parameters
     * @param {object} body - body parameters / object
     * @param {object} headers - header parameters
     * @param {object} queryParameters - querystring parameters
     * @param {object} form - form data object
     * @param {object} deferred - promise object   
     * @param {object} ignoreError - boolean to control dispatching ApiError message
     */
    request({
        method,
        url,
        parameters,
        body,
        headers,
        queryParameters,
        form,
        deferred,
        ignoreError,
      }) {
        const queryParams = queryParameters && Object.keys(queryParameters).length ? this.serializeQueryParams(queryParameters) : null;
        const urlWithParams = url + (queryParams ? '?' + queryParams : '');

        if (body && !Object.keys(body).length) {
          body = undefined;
        }

        const CancelToken = axios.CancelToken;
        let cancel;

        this.store.dispatch('http/isLoading');

        const csrfToken = get('csrfToken')(parameters) || get('store.state.session.csrfToken')(this);
        if (csrfToken) {
          headers['X-CSRF-TOKEN'] = csrfToken;
        }

        const cookie = get('cookie')(parameters) || this.cookie;
        if (cookie) {
          headers['Cookie'] = cookie;
        }

        const webVersion = getWebVersion(this);
        const nativeVersion = getNativeVersion(this);
        const platform = getPlatform(this);

        if (webVersion) {
          headers['NHSO-Web-Version-Tag'] = webVersion + ' (commit:' + this.store.app.$env.COMMIT_ID + ')';
        }
        if (nativeVersion) {
          if (platform !== 'web') {
            let fullNativeVersion = platform;
            fullNativeVersion += ' ';
            fullNativeVersion += nativeVersion;

            headers['NHSO-Native-Version-Tag'] = fullNativeVersion;
          } else {
            headers['NHSO-Native-Version-Tag'] = nativeVersion;
          }
        }

        const resolve = ({
            store,
            deferred,
            result,
            cancel
        }) => {
            deferred.resolve(result)
            if (store && store.dispatch) store.dispatch('http/addCancelRequestHandler', cancel);
        };

        const reject = ({
            store,
            deferred,
            error,
            cancel
        }) => {
            deferred.reject(error)
            if (store && store.dispatch) store.dispatch('http/addCancelRequestHandler', cancel);
        };

        const requestStartTime = new Date();

        let consola = {};

        if (process.server) {
          consola = require('consola');
          consola.info(`Begin request: ${method} ${urlWithParams}`);
        }

        axios({
          cancelToken: new CancelToken(function executor(c) {
            // An executor function receives a cancel function as a parameter
            cancel = c;
          }),
          url: urlWithParams,
          method,
          headers,
          withCredentials: true,
          crossDomain: true,
          data: JSON.stringify(body)
        }).then((response) => {
          if (process.server) {
            this.res.setHeader('Cache-Control', `${response.headers['cache-control']}`);
            this.res.setHeader('Pragma', `${response.headers['pragma']}`);
    
            if (response) {
              const requestDurationMilliseconds = new Date().getTime() - requestStartTime.getTime();
              consola.info(`End request: ${method} ${urlWithParams}, response: ${response.status}, duration: ${requestDurationMilliseconds}ms`);
            }
            if (response.headers['set-cookie']) {
              this.res.setHeader('Set-Cookie', `${response.headers['set-cookie']}; SameSite=Lax`);
            }
          }

          return response.data
        }).then((body) => {
          this.store.dispatch('http/loadingCompleted');
            resolve({
              deferred,
              result: body,
              store: this.store
          });
        }).catch((error) => {
          if (process.server) {
            const requestDurationMilliseconds = new Date().getTime() - requestStartTime.getTime();

            if (error.response) {
              consola.error(new Error(`Error response for request: ${method} ${urlWithParams}, response: ${error.response.status}, duration: ${requestDurationMilliseconds}ms}`));
            } else if (error.request) {
              consola.error(new Error(`Error sending request: ${method} ${urlWithParams}, duration: ${requestDurationMilliseconds}ms`));
            } else {
              consola.error(new Error(`Error setting up the request: ${method} ${urlWithParams}, error: ${error.message}, duration: ${requestDurationMilliseconds}ms`));
            }
          }
          this.store.dispatch('http/loadingCompleted');
          if (!axios.isCancel(error)) {
            if (error.response !== undefined && 401 === error.response.status) {
              this.store.dispatch('auth/unauthorised');
              resolve({
                  deferred,
                  store: this.store
              });
            }

            if (!ignoreError) {
              this.store.dispatch('errors/addApiError', error);
            }

            if (process.server && !isEmpty(this.store.state.errors.apiErrors)) {
                resolve({
                    deferred,
                    store: this.store
                });
            } else {
                reject({
                    deferred,
                    error,
                    store: this.store
                });
            }
          }
        
          reject({
              deferred,
              error
          });
        });
    }

  /**
   * Gets a collection of configuration values.
   * @method
   * @name NHSOnlineApi#getV1Configuration
   * @param {object} parameters - method options and parameters
   * @param { string } parameters.deviceName - name of the device (android or ios)
   * @param { string } parameters.nativeAppVersion - version number of the NHS App installed on the device
   */
  getV1Configuration(parameters) {
    if (parameters === undefined) {
      parameters = {};
    }
    let ignoreError = parameters.ignoreError || false;
    let deferred = $q.defer();
    let domain = this.domain;
    let path = '/v1/configuration';
    let body = {};
    let headers = {};
    let form = {};

    let queryParameters = {};

    headers['Accept'] = ['application/json'];    
  
        if (parameters['deviceName'] !== undefined) {
          queryParameters['deviceName'] = parameters['deviceName'];
        }

        if (parameters['deviceName'] === undefined) {
          deferred.reject(new Error('Missing required  parameter: deviceName'));
          return deferred.promise;
        }

        if (parameters['nativeAppVersion'] !== undefined) {
          queryParameters['nativeAppVersion'] = parameters['nativeAppVersion'];
        }

        if (parameters['nativeAppVersion'] === undefined) {
          deferred.reject(new Error('Missing required  parameter: nativeAppVersion'));
          return deferred.promise;
        }

      queryParameters = this.mergeQueryParams(parameters, queryParameters);

      this.request({
        method: 'GET',
        url: domain + path,
        parameters,
        body,
        headers,
        queryParameters,
        form,
        deferred,
        ignoreError
      });

      return deferred.promise;
  }
      /**
   * Gets a boolean value to indicate if gp practice is participating in public beta
   * @method
   * @name NHSOnlineApi#getV1Odscodelookup
   * @param {object} parameters - method options and parameters
   * @param { string } parameters.odsCode - ods code of gp practice
   */
  getV1Odscodelookup(parameters) {
    if (parameters === undefined) {
      parameters = {};
    }
    let ignoreError = parameters.ignoreError || false;
    let deferred = $q.defer();
    let domain = this.domain;
    let path = '/v1/odscodelookup';
    let body = {};
    let headers = {};
    let form = {};

    let queryParameters = {};

    headers['Accept'] = ['application/json'];    
  
        if (parameters['odsCode'] !== undefined) {
          queryParameters['odsCode'] = parameters['odsCode'];
        }

        if (parameters['odsCode'] === undefined) {
          deferred.reject(new Error('Missing required  parameter: odsCode'));
          return deferred.promise;
        }

      queryParameters = this.mergeQueryParams(parameters, queryParameters);

      this.request({
        method: 'GET',
        url: domain + path,
        parameters,
        body,
        headers,
        queryParameters,
        form,
        deferred,
        ignoreError
      });

      return deferred.promise;
  }
      /**
   * Cancels a specified appointment for the logged on user. Requires NHSO-Session-Id cookie (obtained from session endpoint).
   * @method
   * @name NHSOnlineApi#deleteV1PatientAppointments
   * @param {object} parameters - method options and parameters
   */
  deleteV1PatientAppointments(parameters) {
    if (parameters === undefined) {
      parameters = {};
    }
    let ignoreError = parameters.ignoreError || false;
    let deferred = $q.defer();
    let domain = this.domain;
    let path = '/v1/patient/appointments';
    let body = {};
    let headers = {};
    let form = {};

    let queryParameters = {};

    headers['Content-Type'] = ['application/json'];
  
        
        if (parameters['appointmentCancelRequest'] !== undefined) {
          body = parameters['appointmentCancelRequest'];
        }

        if (parameters['appointmentCancelRequest'] === undefined) {
          deferred.reject(new Error('Missing required  parameter: appointmentCancelRequest'));
          return deferred.promise;
        }
      queryParameters = this.mergeQueryParams(parameters, queryParameters);

      this.request({
        method: 'DELETE',
        url: domain + path,
        parameters,
        body,
        headers,
        queryParameters,
        form,
        deferred,
        ignoreError
      });

      return deferred.promise;
  }
      /**
   * Returns list of booked appointments for the logged on user, and associated metadata including list of cancellation reasons that can be used to cancel upcoming appointments. Requires NHSO-Session-Id cookie (obtained from session endpoint).
   * @method
   * @name NHSOnlineApi#getV1PatientAppointments
   * @param {object} parameters - method options and parameters
   */
  getV1PatientAppointments(parameters) {
    if (parameters === undefined) {
      parameters = {};
    }
    let ignoreError = parameters.ignoreError || false;
    let deferred = $q.defer();
    let domain = this.domain;
    let path = '/v1/patient/appointments';
    let body = {};
    let headers = {};
    let form = {};

    let queryParameters = {};

    headers['Accept'] = ['application/json'];    
  
      queryParameters = this.mergeQueryParams(parameters, queryParameters);

      this.request({
        method: 'GET',
        url: domain + path,
        parameters,
        body,
        headers,
        queryParameters,
        form,
        deferred,
        ignoreError
      });

      return deferred.promise;
  }
      /**
   * Books an appointment slot for the logged on user, given a slot identifier. Identifiers of available slots can be obtained using the appointment-slots endpoint. Requires NHSO-Session-Id cookie (obtained from session endpoint).
   * @method
   * @name NHSOnlineApi#postV1PatientAppointments
   * @param {object} parameters - method options and parameters
   */
  postV1PatientAppointments(parameters) {
    if (parameters === undefined) {
      parameters = {};
    }
    let ignoreError = parameters.ignoreError || false;
    let deferred = $q.defer();
    let domain = this.domain;
    let path = '/v1/patient/appointments';
    let body = {};
    let headers = {};
    let form = {};

    let queryParameters = {};

    headers['Content-Type'] = ['application/json'];
  
        
        if (parameters['appointmentBookRequest'] !== undefined) {
          body = parameters['appointmentBookRequest'];
        }

        if (parameters['appointmentBookRequest'] === undefined) {
          deferred.reject(new Error('Missing required  parameter: appointmentBookRequest'));
          return deferred.promise;
        }
      queryParameters = this.mergeQueryParams(parameters, queryParameters);

      this.request({
        method: 'POST',
        url: domain + path,
        parameters,
        body,
        headers,
        queryParameters,
        form,
        deferred,
        ignoreError
      });

      return deferred.promise;
  }
      /**
   * Returns lists of clinicians, appointment sessions, locations and available appointment slots for the logged in user. Requires NHSO-Session-Id cookie (obtained from session endpoint).
   * @method
   * @name NHSOnlineApi#getV1PatientAppointmentSlots
   * @param {object} parameters - method options and parameters
   */
  getV1PatientAppointmentSlots(parameters) {
    if (parameters === undefined) {
      parameters = {};
    }
    let ignoreError = parameters.ignoreError || false;
    let deferred = $q.defer();
    let domain = this.domain;
    let path = '/v1/patient/appointment-slots';
    let body = {};
    let headers = {};
    let form = {};

    let queryParameters = {};

    headers['Accept'] = ['application/json'];    
  
      queryParameters = this.mergeQueryParams(parameters, queryParameters);

      this.request({
        method: 'GET',
        url: domain + path,
        parameters,
        body,
        headers,
        queryParameters,
        form,
        deferred,
        ignoreError
      });

      return deferred.promise;
  }
      /**
   * Returns a list of prescriptions courses for the logged in user. Requires NHSO-Session-Id cookie in header from session endpoint.
   * @method
   * @name NHSOnlineApi#getV1PatientCourses
   * @param {object} parameters - method options and parameters
   */
  getV1PatientCourses(parameters) {
    if (parameters === undefined) {
      parameters = {};
    }
    let ignoreError = parameters.ignoreError || false;
    let deferred = $q.defer();
    let domain = this.domain;
    let path = '/v1/patient/courses';
    let body = {};
    let headers = {};
    let form = {};

    let queryParameters = {};

    headers['Accept'] = ['application/json'];    
  
      queryParameters = this.mergeQueryParams(parameters, queryParameters);

      this.request({
        method: 'GET',
        url: domain + path,
        parameters,
        body,
        headers,
        queryParameters,
        form,
        deferred,
        ignoreError
      });

      return deferred.promise;
  }
      /**
   * Returns personal details and address details for the logged-in user. Requires NHSO-Session-Id cookie (obtained from session endpoint).
   * @method
   * @name NHSOnlineApi#getV1PatientDemographics
   * @param {object} parameters - method options and parameters
   */
  getV1PatientDemographics(parameters) {
    if (parameters === undefined) {
      parameters = {};
    }
    let ignoreError = parameters.ignoreError || false;
    let deferred = $q.defer();
    let domain = this.domain;
    let path = '/v1/patient/demographics';
    let body = {};
    let headers = {};
    let form = {};

    let queryParameters = {};

    headers['Accept'] = ['application/json'];    
  
      queryParameters = this.mergeQueryParams(parameters, queryParameters);

      this.request({
        method: 'GET',
        url: domain + path,
        parameters,
        body,
        headers,
        queryParameters,
        form,
        deferred,
        ignoreError
      });

      return deferred.promise;
  }
      /**
   * Returns the users medical record for the logged in user. Requires NHSO-Session-Id cookie (obtained from session endpoint).
   * @method
   * @name NHSOnlineApi#getV1PatientMyRecord
   * @param {object} parameters - method options and parameters
   */
  getV1PatientMyRecord(parameters) {
    if (parameters === undefined) {
      parameters = {};
    }
    let ignoreError = parameters.ignoreError || false;
    let deferred = $q.defer();
    let domain = this.domain;
    let path = '/v1/patient/my-record';
    let body = {};
    let headers = {};
    let form = {};

    let queryParameters = {};

    headers['Accept'] = ['application/json'];    
  
      queryParameters = this.mergeQueryParams(parameters, queryParameters);

      this.request({
        method: 'GET',
        url: domain + path,
        parameters,
        body,
        headers,
        queryParameters,
        form,
        deferred,
        ignoreError
      });

      return deferred.promise;
  }
      /**
   * Returns only the specified section from the users medical record for the logged in user (Vision only). Requires NHSO-Session-Id cookie (obtained from session endpoint).
   * @method
   * @name NHSOnlineApi#getV1PatientMyRecordSection
   * @param {object} parameters - method options and parameters
   * @param { string } parameters.section - specific section to return
   */
  getV1PatientMyRecordSection(parameters) {
    if (parameters === undefined) {
      parameters = {};
    }
    let ignoreError = parameters.ignoreError || false;
    let deferred = $q.defer();
    let domain = this.domain;
    let path = '/v1/patient/my-record/section';
    let body = {};
    let headers = {};
    let form = {};

    let queryParameters = {};

    headers['Accept'] = ['application/json'];    
  
        if (parameters['section'] !== undefined) {
          queryParameters['section'] = parameters['section'];
        }

        if (parameters['section'] === undefined) {
          deferred.reject(new Error('Missing required  parameter: section'));
          return deferred.promise;
        }

      queryParameters = this.mergeQueryParams(parameters, queryParameters);

      this.request({
        method: 'GET',
        url: domain + path,
        parameters,
        body,
        headers,
        queryParameters,
        form,
        deferred,
        ignoreError
      });

      return deferred.promise;
  }
      /**
   * Returns a signed Jwt token to be passed to Ndop Web Page
   * @method
   * @name NHSOnlineApi#getV1PatientNdop
   * @param {object} parameters - method options and parameters
   */
  getV1PatientNdop(parameters) {
    if (parameters === undefined) {
      parameters = {};
    }
    let ignoreError = parameters.ignoreError || false;
    let deferred = $q.defer();
    let domain = this.domain;
    let path = '/v1/patient/ndop';
    let body = {};
    let headers = {};
    let form = {};

    let queryParameters = {};

    headers['Content-Type'] = ['application/json'];
  
      queryParameters = this.mergeQueryParams(parameters, queryParameters);

      this.request({
        method: 'GET',
        url: domain + path,
        parameters,
        body,
        headers,
        queryParameters,
        form,
        deferred,
        ignoreError
      });

      return deferred.promise;
  }
      /**
   * Returns the user&#x27;s organ donation record.
   * @method
   * @name NHSOnlineApi#getV1PatientOrgandonation
   * @param {object} parameters - method options and parameters
   */
  getV1PatientOrgandonation(parameters) {
    if (parameters === undefined) {
      parameters = {};
    }
    let ignoreError = parameters.ignoreError || false;
    let deferred = $q.defer();
    let domain = this.domain;
    let path = '/v1/patient/organdonation';
    let body = {};
    let headers = {};
    let form = {};

    let queryParameters = {};

    headers['Accept'] = ['application/json'];    
  
      queryParameters = this.mergeQueryParams(parameters, queryParameters);

      this.request({
        method: 'GET',
        url: domain + path,
        parameters,
        body,
        headers,
        queryParameters,
        form,
        deferred,
        ignoreError
      });

      return deferred.promise;
  }
      /**
   * Creates the user&#x27;s organ donation record and returns the record identifier.
   * @method
   * @name NHSOnlineApi#postV1PatientOrgandonation
   * @param {object} parameters - method options and parameters
   */
  postV1PatientOrgandonation(parameters) {
    if (parameters === undefined) {
      parameters = {};
    }
    let ignoreError = parameters.ignoreError || false;
    let deferred = $q.defer();
    let domain = this.domain;
    let path = '/v1/patient/organdonation';
    let body = {};
    let headers = {};
    let form = {};

    let queryParameters = {};

    headers['Content-Type'] = ['application/json'];
  
        
        if (parameters['organDonationRegistrationRequest'] !== undefined) {
          body = parameters['organDonationRegistrationRequest'];
        }

        if (parameters['organDonationRegistrationRequest'] === undefined) {
          deferred.reject(new Error('Missing required  parameter: organDonationRegistrationRequest'));
          return deferred.promise;
        }
      queryParameters = this.mergeQueryParams(parameters, queryParameters);

      this.request({
        method: 'POST',
        url: domain + path,
        parameters,
        body,
        headers,
        queryParameters,
        form,
        deferred,
        ignoreError
      });

      return deferred.promise;
  }
      /**
   * Amends the user&#x27;s organ donation record and returns the record identifier.
   * @method
   * @name NHSOnlineApi#putV1PatientOrgandonation
   * @param {object} parameters - method options and parameters
   */
  putV1PatientOrgandonation(parameters) {
    if (parameters === undefined) {
      parameters = {};
    }
    let ignoreError = parameters.ignoreError || false;
    let deferred = $q.defer();
    let domain = this.domain;
    let path = '/v1/patient/organdonation';
    let body = {};
    let headers = {};
    let form = {};

    let queryParameters = {};

    headers['Content-Type'] = ['application/json'];
  
        
        if (parameters['organDonationRegistrationRequest'] !== undefined) {
          body = parameters['organDonationRegistrationRequest'];
        }

        if (parameters['organDonationRegistrationRequest'] === undefined) {
          deferred.reject(new Error('Missing required  parameter: organDonationRegistrationRequest'));
          return deferred.promise;
        }
      queryParameters = this.mergeQueryParams(parameters, queryParameters);

      this.request({
        method: 'PUT',
        url: domain + path,
        parameters,
        body,
        headers,
        queryParameters,
        form,
        deferred,
        ignoreError
      });

      return deferred.promise;
  }
      /**
   * Delete the user&#x27;s organ donation record.
   * @method
   * @name NHSOnlineApi#deleteV1PatientOrgandonation
   * @param {object} parameters - method options and parameters
   */
  deleteV1PatientOrgandonation(parameters) {
    if (parameters === undefined) {
      parameters = {};
    }
    let ignoreError = parameters.ignoreError || false;
    let deferred = $q.defer();
    let domain = this.domain;
    let path = '/v1/patient/organdonation';
    let body = {};
    let headers = {};
    let form = {};

    let queryParameters = {};

    headers['Content-Type'] = ['application/json'];
  
        
        if (parameters['organDonationWithdrawRequest'] !== undefined) {
          body = parameters['organDonationWithdrawRequest'];
        }

        if (parameters['organDonationWithdrawRequest'] === undefined) {
          deferred.reject(new Error('Missing required  parameter: organDonationWithdrawRequest'));
          return deferred.promise;
        }
      queryParameters = this.mergeQueryParams(parameters, queryParameters);

      this.request({
        method: 'DELETE',
        url: domain + path,
        parameters,
        body,
        headers,
        queryParameters,
        form,
        deferred,
        ignoreError
      });

      return deferred.promise;
  }
      /**
   * Returns the reference data for titles, genders, religions, ethnicities and withdraw reasons.
   * @method
   * @name NHSOnlineApi#getV1PatientOrgandonationReferencedata
   * @param {object} parameters - method options and parameters
   */
  getV1PatientOrgandonationReferencedata(parameters) {
    if (parameters === undefined) {
      parameters = {};
    }
    let ignoreError = parameters.ignoreError || false;
    let deferred = $q.defer();
    let domain = this.domain;
    let path = '/v1/patient/organdonation/referencedata';
    let body = {};
    let headers = {};
    let form = {};

    let queryParameters = {};

    headers['Accept'] = ['application/json'];    
  
      queryParameters = this.mergeQueryParams(parameters, queryParameters);

      this.request({
        method: 'GET',
        url: domain + path,
        parameters,
        body,
        headers,
        queryParameters,
        form,
        deferred,
        ignoreError
      });

      return deferred.promise;
  }
      /**
   * For the given logged on user, will request a repeat prescription for a list of prescription courses. Requires NHSO-Session-Id cookie in header from session endpoint.
   * @method
   * @name NHSOnlineApi#postV1PatientPrescriptions
   * @param {object} parameters - method options and parameters
   */
  postV1PatientPrescriptions(parameters) {
    if (parameters === undefined) {
      parameters = {};
    }
    let ignoreError = parameters.ignoreError || false;
    let deferred = $q.defer();
    let domain = this.domain;
    let path = '/v1/patient/prescriptions';
    let body = {};
    let headers = {};
    let form = {};

    let queryParameters = {};

    headers['Content-Type'] = ['application/json'];
  
        
        if (parameters['repeatPrescriptionRequest'] !== undefined) {
          body = parameters['repeatPrescriptionRequest'];
        }

        if (parameters['repeatPrescriptionRequest'] === undefined) {
          deferred.reject(new Error('Missing required  parameter: repeatPrescriptionRequest'));
          return deferred.promise;
        }
      queryParameters = this.mergeQueryParams(parameters, queryParameters);

      this.request({
        method: 'POST',
        url: domain + path,
        parameters,
        body,
        headers,
        queryParameters,
        form,
        deferred,
        ignoreError
      });

      return deferred.promise;
  }
      /**
   * For a given date range, returns a list of courses and repeat prescriptions for the logged in user. Requires NHSO-Session-Id cookie in header from session endpoint.
   * @method
   * @name NHSOnlineApi#getV1PatientPrescriptions
   * @param {object} parameters - method options and parameters
   * @param { string } parameters.fromDate - Repeat Prescription from date. Will default to 6 months ago if no value is supplied
   */
  getV1PatientPrescriptions(parameters) {
    if (parameters === undefined) {
      parameters = {};
    }
    let ignoreError = parameters.ignoreError || false;
    let deferred = $q.defer();
    let domain = this.domain;
    let path = '/v1/patient/prescriptions';
    let body = {};
    let headers = {};
    let form = {};

    let queryParameters = {};

    headers['Accept'] = ['application/json'];    
  
        if (parameters['fromDate'] !== undefined) {
          queryParameters['fromDate'] = parameters['fromDate'];
        }

      queryParameters = this.mergeQueryParams(parameters, queryParameters);

      this.request({
        method: 'GET',
        url: domain + path,
        parameters,
        body,
        headers,
        queryParameters,
        form,
        deferred,
        ignoreError
      });

      return deferred.promise;
  }
      /**
   * Returns the most recent patient consent for the logged in user. Requires NHSO-Session-Id cookie (obtained from session endpoint).
   * @method
   * @name NHSOnlineApi#getV1PatientTermsAndConditionsConsent
   * @param {object} parameters - method options and parameters
   */
  getV1PatientTermsAndConditionsConsent(parameters) {
    if (parameters === undefined) {
      parameters = {};
    }
    let ignoreError = parameters.ignoreError || false;
    let deferred = $q.defer();
    let domain = this.domain;
    let path = '/v1/patient/terms-and-conditions/consent';
    let body = {};
    let headers = {};
    let form = {};

    let queryParameters = {};

    headers['Accept'] = ['application/json'];    
  
      queryParameters = this.mergeQueryParams(parameters, queryParameters);

      this.request({
        method: 'GET',
        url: domain + path,
        parameters,
        body,
        headers,
        queryParameters,
        form,
        deferred,
        ignoreError
      });

      return deferred.promise;
  }
      /**
   * Records whether the logged in user has given their consent to use the app and date and time of consent
   * @method
   * @name NHSOnlineApi#postV1PatientTermsAndConditionsConsent
   * @param {object} parameters - method options and parameters
   */
  postV1PatientTermsAndConditionsConsent(parameters) {
    if (parameters === undefined) {
      parameters = {};
    }
    let ignoreError = parameters.ignoreError || false;
    let deferred = $q.defer();
    let domain = this.domain;
    let path = '/v1/patient/terms-and-conditions/consent';
    let body = {};
    let headers = {};
    let form = {};

    let queryParameters = {};

    headers['Content-Type'] = ['application/json'];
  
        
        if (parameters['consentRequest'] !== undefined) {
          body = parameters['consentRequest'];
        }

        if (parameters['consentRequest'] === undefined) {
          deferred.reject(new Error('Missing required  parameter: consentRequest'));
          return deferred.promise;
        }
      queryParameters = this.mergeQueryParams(parameters, queryParameters);

      this.request({
        method: 'POST',
        url: domain + path,
        parameters,
        body,
        headers,
        queryParameters,
        form,
        deferred,
        ignoreError
      });

      return deferred.promise;
  }
      /**
   * 
   * @method
   * @name NHSOnlineApi#getV1PatientTestResult
   * @param {object} parameters - method options and parameters
   * @param { string } parameters.testResultId - id of selected test result
   */
  getV1PatientTestResult(parameters) {
    if (parameters === undefined) {
      parameters = {};
    }
    let ignoreError = parameters.ignoreError || false;
    let deferred = $q.defer();
    let domain = this.domain;
    let path = '/v1/patient/test-result';
    let body = {};
    let headers = {};
    let form = {};

    let queryParameters = {};

    headers['Accept'] = ['application/json'];    
  
        if (parameters['testResultId'] !== undefined) {
          queryParameters['testResultId'] = parameters['testResultId'];
        }

        if (parameters['testResultId'] === undefined) {
          deferred.reject(new Error('Missing required  parameter: testResultId'));
          return deferred.promise;
        }

      queryParameters = this.mergeQueryParams(parameters, queryParameters);

      this.request({
        method: 'GET',
        url: domain + path,
        parameters,
        body,
        headers,
        queryParameters,
        form,
        deferred,
        ignoreError
      });

      return deferred.promise;
  }
      /**
   * Returns Response object containing list of GP Practices
   * @method
   * @name NHSOnlineApi#postV1Gpsearch
   * @param {object} parameters - method options and parameters
   */
  postV1Gpsearch(parameters) {
    if (parameters === undefined) {
      parameters = {};
    }
    let ignoreError = parameters.ignoreError || false;
    let deferred = $q.defer();
    let domain = this.domain;
    let path = '/v1/gpsearch';
    let body = {};
    let headers = {};
    let form = {};

    let queryParameters = {};

    headers['Content-Type'] = ['application/json'];
  
        
        if (parameters['gpSearchRequest'] !== undefined) {
          body = parameters['gpSearchRequest'];
        }

        if (parameters['gpSearchRequest'] === undefined) {
          deferred.reject(new Error('Missing required  parameter: gpSearchRequest'));
          return deferred.promise;
        }
      queryParameters = this.mergeQueryParams(parameters, queryParameters);

      this.request({
        method: 'POST',
        url: domain + path,
        parameters,
        body,
        headers,
        queryParameters,
        form,
        deferred,
        ignoreError
      });

      return deferred.promise;
  }
      /**
   * Returns status code indicating if signup to brothermailer was successful
   * @method
   * @name NHSOnlineApi#postV1Brothermailer
   * @param {object} parameters - method options and parameters
   */
  postV1Brothermailer(parameters) {
    if (parameters === undefined) {
      parameters = {};
    }
    let ignoreError = parameters.ignoreError || false;
    let deferred = $q.defer();
    let domain = this.domain;
    let path = '/v1/brothermailer';
    let body = {};
    let headers = {};
    let form = {};

    let queryParameters = {};

    headers['Content-Type'] = ['application/json'];
  
        
        if (parameters['brothermailerRequest'] !== undefined) {
          body = parameters['brothermailerRequest'];
        }

        if (parameters['brothermailerRequest'] === undefined) {
          deferred.reject(new Error('Missing required  parameter: brothermailerRequest'));
          return deferred.promise;
        }
      queryParameters = this.mergeQueryParams(parameters, queryParameters);

      this.request({
        method: 'POST',
        url: domain + path,
        parameters,
        body,
        headers,
        queryParameters,
        form,
        deferred,
        ignoreError
      });

      return deferred.promise;
  }
      /**
   * Given an OAuth authorisation code and PKCE code verifier, creates and returns a user session.
   * @method
   * @name NHSOnlineApi#postV1Session
   * @param {object} parameters - method options and parameters
   */
  postV1Session(parameters) {
    if (parameters === undefined) {
      parameters = {};
    }
    let ignoreError = parameters.ignoreError || false;
    let deferred = $q.defer();
    let domain = this.domain;
    let path = '/v1/session';
    let body = {};
    let headers = {};
    let form = {};

    let queryParameters = {};

    headers['Content-Type'] = ['application/json'];
  
        
        if (parameters['userSession'] !== undefined) {
          body = parameters['userSession'];
        }

        if (parameters['userSession'] === undefined) {
          deferred.reject(new Error('Missing required  parameter: userSession'));
          return deferred.promise;
        }
      queryParameters = this.mergeQueryParams(parameters, queryParameters);

      this.request({
        method: 'POST',
        url: domain + path,
        parameters,
        body,
        headers,
        queryParameters,
        form,
        deferred,
        ignoreError
      });

      return deferred.promise;
  }
      /**
   * Given a valid session cookie deletes the users session and signs the user out. Requires NHSO-Session-Id cookie obtained from post session endpoint.
   * @method
   * @name NHSOnlineApi#deleteV1Session
   * @param {object} parameters - method options and parameters
   */
  deleteV1Session(parameters) {
    if (parameters === undefined) {
      parameters = {};
    }
    let ignoreError = parameters.ignoreError || false;
    let deferred = $q.defer();
    let domain = this.domain;
    let path = '/v1/session';
    let body = {};
    let headers = {};
    let form = {};

    let queryParameters = {};

    headers['Content-Type'] = ['application/json'];
  
      queryParameters = this.mergeQueryParams(parameters, queryParameters);

      this.request({
        method: 'DELETE',
        url: domain + path,
        parameters,
        body,
        headers,
        queryParameters,
        form,
        deferred,
        ignoreError
      });

      return deferred.promise;
  }
      /**
   * Extends a user session for an authenticated user, by calling an upstream endpoint. Requires NHSO-Session-Id cookie obtained from post session endpoint.
   * @method
   * @name NHSOnlineApi#postV1SessionExtend
   * @param {object} parameters - method options and parameters
   */
  postV1SessionExtend(parameters) {
    if (parameters === undefined) {
      parameters = {};
    }
    let ignoreError = parameters.ignoreError || false;
    let deferred = $q.defer();
    let domain = this.domain;
    let path = '/v1/session/extend';
    let body = {};
    let headers = {};
    let form = {};

    let queryParameters = {};

    headers['Content-Type'] = ['application/json'];
  
      queryParameters = this.mergeQueryParams(parameters, queryParameters);

      this.request({
        method: 'POST',
        url: domain + path,
        parameters,
        body,
        headers,
        queryParameters,
        form,
        deferred,
        ignoreError
      });

      return deferred.promise;
  }
      /**
   * Returns Response object containing list of pharmacies matched in search.
   * @method
   * @name NHSOnlineApi#getV1PatientPharmacies
   * @param {object} parameters - method options and parameters
   * @param { string } parameters.searchTerm - Search term to search for pharmacies by postcode, town or pharmacy name.
   */
  getV1PatientPharmacies(parameters) {
    if (parameters === undefined) {
      parameters = {};
    }
    let ignoreError = parameters.ignoreError || false;
    let deferred = $q.defer();
    let domain = this.domain;
    let path = '/v1/patient/pharmacies';
    let body = {};
    let headers = {};
    let form = {};

    let queryParameters = {};

    headers['Accept'] = ['application/json'];    
  
        if (parameters['searchTerm'] !== undefined) {
          queryParameters['searchTerm'] = parameters['searchTerm'];
        }

        if (parameters['searchTerm'] === undefined) {
          deferred.reject(new Error('Missing required  parameter: searchTerm'));
          return deferred.promise;
        }

      queryParameters = this.mergeQueryParams(parameters, queryParameters);

      this.request({
        method: 'GET',
        url: domain + path,
        parameters,
        body,
        headers,
        queryParameters,
        form,
        deferred,
        ignoreError
      });

      return deferred.promise;
  }
      /**
   * Returns the nominated pharmacy detail for the logged in user. Requires NHSO-Session-Id cookie in header from session endpoint.
   * @method
   * @name NHSOnlineApi#getV1PatientNominatedPharmacy
   * @param {object} parameters - method options and parameters
   */
  getV1PatientNominatedPharmacy(parameters) {
    if (parameters === undefined) {
      parameters = {};
    }
    let ignoreError = parameters.ignoreError || false;
    let deferred = $q.defer();
    let domain = this.domain;
    let path = '/v1/patient/nominated-pharmacy';
    let body = {};
    let headers = {};
    let form = {};

    let queryParameters = {};

    headers['Accept'] = ['application/json'];    
  
      queryParameters = this.mergeQueryParams(parameters, queryParameters);

      this.request({
        method: 'GET',
        url: domain + path,
        parameters,
        body,
        headers,
        queryParameters,
        form,
        deferred,
        ignoreError
      });

      return deferred.promise;
  }
      /**
   * Returns http response.
   * @method
   * @name NHSOnlineApi#postV1PatientNominatedPharmacy
   * @param {object} parameters - method options and parameters
   */
  postV1PatientNominatedPharmacy(parameters) {
    if (parameters === undefined) {
      parameters = {};
    }
    let ignoreError = parameters.ignoreError || false;
    let deferred = $q.defer();
    let domain = this.domain;
    let path = '/v1/patient/nominated-pharmacy';
    let body = {};
    let headers = {};
    let form = {};

    let queryParameters = {};

    headers['Content-Type'] = ['application/json'];
  
        
        if (parameters['updateNominatedPharmacyRequest'] !== undefined) {
          body = parameters['updateNominatedPharmacyRequest'];
        }

        if (parameters['updateNominatedPharmacyRequest'] === undefined) {
          deferred.reject(new Error('Missing required  parameter: updateNominatedPharmacyRequest'));
          return deferred.promise;
        }
      queryParameters = this.mergeQueryParams(parameters, queryParameters);

      this.request({
        method: 'POST',
        url: domain + path,
        parameters,
        body,
        headers,
        queryParameters,
        form,
        deferred,
        ignoreError
      });

      return deferred.promise;
  }
    
}

export default NHSOnlineApi;