server {
  listen      8089;
  server_name 0.0.0.0;

  location / {
      proxy_pass http://pfs.local.bitraft.io:8082/;
      proxy_redirect      off;
    }

  location /v1/api/users {
      proxy_pass http://users.local.bitraft.io:8083/v1/api/users;
      proxy_redirect      off;
    }
    
  location /v1/api/log {
    proxy_pass http://log.local.bitraft.io:8090/v1/api/log;
    proxy_redirect off;
  }
}
