package utils

enum class GlobalSerenityHelpers : ISerenityHelperEnums{
    CITIZEN_ID_SESSION_CREATED,
    TEAR_DOWN_ACTIONS,
    GP_SYSTEM,
    FUNCTIONS_TO_ADD_TO_WINDOW_NATIVE_APP_OBJECT,
    USER_SESSION_CREATED,
    SWITCHED_LINKED_ACCOUNT,
    USER_AGENT
}
