version: "3.2"
services:
  nhsonline.web:
    image: nhsonline.web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_HOST=http://localhost:8082
      - API_HOST_SERVER=http://nhsonline.backend.worker:8082
      - CID_REDIRECT_URI=http://localhost:3000/auth-return
      - NATIVE_CID_REDIRECT_URI=nhsapp://10.0.2.2:3000/auth-return
  nhsonline.backend.worker:
    image: nhsonline.backend.worker
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CORS_AUTHORITY=*
      - TPP_CERTIFICATE_PATH=./certs/TppNhsTest.pfx
      - TPP_CERTIFICATE_PASSWORD
      - VISION_CERT_PATH=./certs/vps_nhson001.pfx
      - VISION_CERT_PASSPHRASE
      - STUB_TERMS_AND_CONDITIONS=true
    depends_on:
      - nhsonline.redis.sds
    ports:
      - "8082:8082"
  nhsonline.stubs:
    image: rodolpheche/wiremock
    command: --local-response-templating
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
    tty: true
  nhsonline.stubs.data:
    image: nhsonline.stubs.data
    environment:
      - wiremockUrl=http://nhsonline.stubs:8080
    depends_on:
      - nhsonline.stubs
  nhsonline.redis-data.sds:
    image: nhsapp.azurecr.io/nhsonline-redis-data:latest
    environment:
      - REDIS_HOST=nhsonline.redis.sds
    depends_on:
      - nhsonline.redis.sds
  nhsonline.redis.sds:
    image: bitnami/redis:4.0.8-r7
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
    volumes:
      - 'redis_data:/bitnami/redis'
  nhsonline.redis.session:
    image: bitnami/redis:4.0.8-r7
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6380:6379"
volumes:
  redis_data:
    driver: local
