version: "3.2"
services:
  api.local.bitraft.io:
    image: nginx:alpine
    volumes:
      - ./nginx/https:/etc/nginx/conf.d
      - ~/.nhsonline/local-development-certificate:/etc/ssl
    ports:
      - "443:443"
      - "444:444"
    depends_on:
      - web.local.bitraft.io
      - pfs.local.bitraft.io
  web.local.bitraft.io:
    image: nhsonline.web
    environment:
      - URI_FORMAT_API_CLIENT=https://api.local.bitraft.io:444
      - API_HOST_SERVER=http://api.local.bitraft.io:444
      - URI_FORMAT_CID_REDIRECT_WEB=https://local.bitraft.io/auth-return
      - URI_FORMAT_CID_REDIRECT_NATIVE=nhsapp://local.bitraft.io/auth-return
      - SECURE_COOKIES=true
      - GP_LOOKUP_API_KEY=
      - GP_LOOKUP_API_URL=https://nhsuk-apim-int-uks.azure-api.net/service-search/search?api-version=1
      - GP_LOOKUP_API_RESULTS_LIMIT=20
      - POSTCODE_LOOKUP_API_URL=https://nhsuk-apim-int-uks.azure-api.net/service-search/postcodesandplaces/search?api-version=1
      - POSTCODE_LOOKUP_SEARCH_RADIUS_KM=10
      - THROTTLING_ENABLED=
      - VERSION_TAG=dev_web_docker_https
  pfs.local.bitraft.io:
    image: nhsonline.backend.pfsapi
    environment:
      - STUB_TERMS_AND_CONDITIONS=true
      - ConfigurationSettings__CookieDomain=.bitraft.io
