version: "3.2"
services:
  nhsonline.reverse-https-proxy:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ~/.nhsonline/local-development-certificate:/etc/ssl
    ports:
      - "443:443"
      - "444:444"
    depends_on:
      - web.local.bitraft.io
      - api.local.bitraft.io
  web.local.bitraft.io:
    image: nhsonline.web
    environment:
      - API_PORT=444,
      - API_PORT_SERVER=444
      - API_HOST_SERVER=http://web.local.bitraft.io:8082
      - CID_REDIRECT_URI=https://android.local.bitraft.io/auth-return
      - NATIVE_CID_REDIRECT_URI=nhsapp://android.local.bitraft.io/auth-return
  api.local.bitraft.io:
    image: nhsonline.backend.worker
    environment:
      - NHS_WEB_APP_BASE_URL=http://10.0.2.2:3000/
      - ConfigurationSettings__CookieDomain=.bitraft.io
