version: "3.4"

services:

  pfs.local.bitraft.io:
    environment:
      DATA_PREFERENCES_URL: http://ndopapp-int1.thunderbird.service.nhs.uk/createsession
      NDOP_CERTIFICATE_PASSWORD:
      NDOP_CERTIFICATE_PATH: ./certs/ndopJwtTest.pfx
      NDOP_CLAIM_AUDIENCE: https://ndopapp-int1.thunderbird.service.nhs.uk
      NDOP_CLAIM_ISSUER: https://www-preview.devuks1.nonlive.nhsapp.service.nhs.uk
      ORGAN_DONATION_CERT_PATH: ./certs/OrganDonation.pfx

  messages.local.bitraft.io:
    environment:
      CORS_AUTHORITY: '*'
