version: "3.2"
services:
  nhsonline.reverse-https-proxy:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ~/.nhsonline/local-development-certificate:/etc/ssl
    ports:
      - "443:443"
      - "444:444"
    depends_on:
      - web.local.bitraft.io
      - api.local.bitraft.io
  web.local.bitraft.io:
    image: nhsonline.web
    environment:
      - URI_FORMAT_API_CLIENT=https://{host}:444
      - URI_FORMAT_API_SERVER=http://api.{host}:8082
      - URI_FORMAT_CID_REDIRECT_WEB=https://{host}/auth-return
      - URI_FORMAT_CID_REDIRECT_NATIVE=nhsapp://{host}/auth-return
      - VERSION_TAG=dev_web_docker_https
  api.local.bitraft.io:
    image: nhsonline.backend.worker
    environment:
      - STUB_TERMS_AND_CONDITIONS=true
      - ConfigurationSettings__CookieDomain=.bitraft.io
